### ISSUE TITLE
Feature-Request: Nutzung von G27/G29 gear shifters für Shuttle Control bei Getriebe off und IVT

### ISSUE THREAD

**Issue by breadcan** [Mogli12/VehicleControlAddon#137]
Ich nutze den Gear shifter in verschiedenen Fahrzeugen in den Modi mit Gängen/Gruppen.
In anderen Fahrzeugen würde ich aber gerne IVT mit Shuttle Control nutzen.
Vor den Getriebefunktionen habe ich immer Gang 3 und 4 für das Shuttle Control genutzt.
Aktuell kann ich die Funktion nicht parallel nutzen und muss das Shuttle Control auf Side Panel legen

Wäre es möglich und sinnvoll hier eine Doppelbelegung zu erlauben die bei IVT und off die Shuttle Control z.B. auf Gang 3 und 4 legen lässt und gleichzeitig in den anderen Modi aber die Gänge schaltet?

Die angedachte Input Zuordnung:
![image](https://user-images.githubusercontent.com/416166/51404092-a91c8e80-1b52-11e9-9662-fad481f65d12.png)

Aktuell sieht es bei obiger Konfiguration dann bei Einlegen von Gang 3 und Getriebe off oder IVT so aus und man kann nicht fahren.

![image](https://user-images.githubusercontent.com/416166/51404207-0284bd80-1b53-11e9-9c4c-ec8bd709c9c2.png)

**Comment by Shreklich** [comment]
Hallo Mogli,
gibt es eine Möglichkeit zu dem oben genannten Problem da ich diese Funktion zuvor genauso genutzt habe.

**Comment by Mogli12** [comment]
Hallo,
ich denke, dass man das nicht über die Tastenbelegung erreichen kann. Man könnte aber pro Fahrzeug die Bedeutung der einzelnen Tasten ändern. Ich denke mal drüber nach.
Viele Grüße

**Comment by Mogli12** [comment]
Hallo,
bitte prüfe die aktuelle Version (ab 0.0.8.1).
Viele Grüße

**Comment by breadcan** [comment]
Läuft. Danke.
