### ISSUE TITLE
The host changes the client settings

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/VehicleControlAddon#143]
I played with a friend in MP and found 2 errors:
1) When the host is on the menu, the vehicle stops at the client.
2) When host changing any settings in the mod menu, the host settings have a higher priority than the client (but at the client nothing changes in the mod menu).

**Comment by Mogli12** [comment]
Please try of version 0.0.1.2. I was not able to test it in MP. I am not sure if it breaks loading or saving games.

**Comment by KITT3000** [comment]
Sory for such a late reply, everything is ok now.

**Comment by KITT3000** [comment]
Sory for misleading, but I have incorrectly tested the problem.Problem 1 still exists, but it only appears when you want to control the vehicle via the W/S keys, when the cruise control is activated, the vehicle goes without a problem.

**Comment by KITT3000** [comment]
Ok, now it's definitely all ok.

**Comment by roadtrain59** [comment]
My keyboardsteermod (ksm) of the compass bearing/heading is frozen like on screen  270*/ 90*  is  stuck (first numbers froze before /  second number moves) and any other  vehicle or machinery all frozen  bearing/heading  and doesn't resets after turned off  stays in the same last locked position  and a error in log of ..warning: missing l10n 'input_ksmSHUTTLE' and  inputDIRECTION'  I have version 0.0.0.5 {single player)

**Comment by Mogli12** [comment]
Just press LAlt+W to reset the snap angle.

**Comment by roadtrain59** [comment]
Thankyou for the information all good sweet awesome yay fs19 woo hoo

Sent from Mail for Windows 10
