### ISSUE TITLE
not an issue....complete lua-doc?

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#146]
hi...kann das sein, dass diese nun komplett ? Lua-doc 1.3:

https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=69&class=8917

**Comment by Mogli12** [comment]
Ja, das sieht vollständig aus. Das hätte man ja mal ankündigen können. Das ist das erste Mal überhaupt, dass Giants eine halbwegs vollständige Doku veröffentlicht.

Aber es ändert nichts daran, dass ich zwar noch gelegentlich FS19 spiele und daher weiter an FS19_VehicleControllAddon bastel. Aber mit Giants und auch mit etlichen Moddern (z.B. vertexdezign) will nicht nichts mehr zu tun haben.

Ich hatte in den letzen 2 Jahren keine Zeit um an einer FarmCon teilzunehmen. Das ist ganz offensichtlich mittlerweile ein Problem, da ich dadurch keinen Kontakt zu Giants habe. Und jetzt ist einfach zu viel Porzellan zerschlagen.
