### ISSUE TITLE
Frontloader with implement not working

### ISSUE THREAD

**Issue by Laurindra** [Mogli12/VehicleControlAddon#148]
I have an issue when a frontloader with attachment is used.
But as soon as you attach an implement/tool on the frontloader the primary controls for the frontloader do nothing anymore. (lift/lower frontloader and lift/lower frontloader implement. SpecifixThese are the ogirinal controls you operate with mouse1 held down and moving the mouse)
Same issue happens with the bag'n'lifter (addon). Bag'n'lifter without bigbag attached does work
Reassigning one of these axis' to another mousebinding doesn't work around the issue.
Assigning keys or gamepad controls to these axis' dont work around the issue.

**Comment by Mogli12** [comment]
I think there is something wrong with your inputBinding.xml. I propose to delete it.

**Comment by Laurindra** [comment]
Agreed. One of my mods seems to have permanently botched-up inputbindings. Had to reset controls to get it to work again. Sorry for the inconvenoence.

**Comment by Mogli12** [comment]
No problem. If you adjusted the input bindings then resetting them is not easy.
