### ISSUE TITLE
Player model pressing brake pedal when brake light is showing

### ISSUE THREAD

**Issue by knuuud** [Mogli12/VehicleControlAddon#149]
Sorry for reviving this, but it would be nice if this was working :)

When the machines in the game are standing still , pressing the brake key only lights the brake lights. Is it possible to make the player model press the brake pedal as well like when the machine is braking from speed?

This is now working on shuttle backwards, should it not also work on shuttle forwards than? :)

**Comment by Mogli12** [comment]
Now the script docu looks complete I can try to find out how to do it. But it does not have top priority for me at the moment. Ok?

**Comment by knuuud** [comment]
Sure ;) I just wanted to mention it so it wasn't forgotten 👍  BTW superhappy to see you back! :)

**Comment by Mogli12** [comment]
Please check version 0.0.7.8
