### ISSUE TITLE
New Course setting not possible in Multiplayer

### ISSUE THREAD

**Issue by game455** [Mogli12/VehicleControlAddon#151]
After first course is set on a vehicle (i tried it with every tractor, truck, combine, etc.) it is not possible, to set a new course with different direction. Even a restart of the game will not restore the setting.

**Comment by Mogli12** [comment]
Please press LAlt+W.

**Comment by game455** [comment]
That easy? thanks

**Comment by game455** [comment]
Thanks again. Working well on SP, but on MP...
after pressing LAlt+W... 
- new course is indicated and steering wheels immediately begins to flicker
- vehicle turn back to old course
- steering Wheels are flickering, also on (still active) old course
Second player see same effects

**Comment by game455** [comment]
Log-entry on dedi server upon each login of player:

2019-02-10 15:24 Gerhard joined the game 
2019-02-10 15:25 Error: mogliBase30Request received invalid NodeObject

No other entries in log

Hope, this will help

**Comment by Mogli12** [comment]
Please check version 0.0.5.8.

**Comment by Mogli12** [comment]
I closed this issues after 5 month w/o feedback.
