### ISSUE TITLE
Kupplung/Clutch

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#153]
Hallo,
ich nutze die Version 0.0.1.5 und versuche gerade mit der manuellen Kupplung zu fahren nur leider trennt die nicht zu 100%. Benutze das G27 von Logitech wenn also die Kupplung im Spiel betätigt wird, dann geht die Prozentzahl nicht über 60-70% je nachdem wie schnell diese betätigt wird. Die Prozentzahl geht auch nicht auf 0% zurück sondern bleibt bei etwa 36%. Leider knirscht es nur im Getriebe (übrigens ein Top features gefällt mir) und bekomme die Gänge nicht geschaltet.  Belege ich die Kupplung über eine Taste funktioniert es.  Häng dies mit der analogen Eingabe vom Pedal zusammen oder mache ich vielleicht etwas falsch?

**Comment by Mogli12** [comment]
Ich habe noch nicht herausgefunden, wie ich eine Achse abfrage.

**Comment by Shreklich** [comment]
Ich weiß nicht ob es legitim ist aber könnte dir vielleicht das Skript von modelleicher helfen? Er arbeitet ebenfalls an einem Getriebe und hat wohl laut seinem Video auch eine analoge Kupplung verbaut.

**Comment by Shreklich** [comment]
Also mit Version 0.0.1.6 klappt es vielen lieben Dank dafür. Macht richtig Laune dein Skript.

**Comment by Mogli12** [comment]
Danke fürs schnelle Testen.
