### ISSUE TITLE
Leerlaufsound im MP

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#155]
Hallo,
ich habe mal versucht deine neuste Version auf dem Server zu laden nachdem es im SP so gut klappt nur irgendwie hab ich damit ein Problem. Im Schlepper wird keine Drehzahl mehr angezeigt sobald ich das Getriebe versuche auf manuell zu stellen und der Sound ist stets nur der Leerlaufsound.  Irgendwie ist da ganz schön der Wurm drin. Im SP läuft er ja echt spitze und auf dem Dedi dann sowas. Ich denke das ich dann nochmal zurück zur Version 0.0.1.3 gehen muss da diese auf dem Server vorher lief, leider dann ohne Kupplung. 

PS: Habe im Savegame unter Vehicle auch die Einträge gelöscht die vom VehicleControlAddon erstellt worden sind da sonst durch das ersetzen von Version 0.0.1.8 zu 0.0.1.3 das Soundproblem nicht weg ging. Ich würde ja sehr gerne helfen aber habe leider null Ahnung vom skripten. Könnte es höchstens jedoch für dich auf dem Server testen. 
Gruß Thorsten

Mir fällt gerade noch etwas ein was vielleicht noch zusätzlich als Information helfen kann. Bei der Version 0.0.1.3 die ich vorher auf dem Server hab laufen lassen ist der Sound in den Gängen vor dem letzten Gang auch bei erreichen der jeweiligen Endgeschwindigkeit (zb 1Gang 8kmh) auch auf die Leerlsufdrehzahl gesprungen. Damit konnte ich ohne Probleme leben nur ist es jetzt so das der Sound permanent auf Leerlauf bleibt.

**Comment by Mogli12** [comment]
Hallo,
VCA verändert im Wesentlichen die Übersetzung. Die Drehzahl ist das Ergebnis der geänderten Übersetzung und wird im Host/Dedi-Server berechnet. Das ist aber bereits Standard-Skript. Mit der Verteilung auf die Clients hat VCA dann nichts zu tun.
Viele Grüße,
Stefan

**Comment by Shreklich** [comment]
Ich werde heute Abend deine neue Datei auf dem Server testen. Danke schon mal dafür. Wenn Interesse besteht würde ich dir auch gerne für einen Monat einen Dedi für evtl test zur Verfügung stellen würde diesen dann mieten. MfG

**Comment by Shreklich** [comment]
Top getestet habe ich nun die Version 0.0.2.0 und Sound geht wieder sogar bleibt er bei Vollgas wenn die Endgeschwindigkeit in den Gängen erreicht wurde. Der neue Anfahrsound gefällt mir wenn man zu wenig Gas gibt beim Einkuppeln kann man den Wert irgendwo einstellen wieviel Gas man geben muss da ich schon Vollgas geben muss damit die Drehzahl nicht völlig runterrauscht. Das einzige was mir aufgefallen ist das man den Traktor nicht mehr abwürgen kann aber damit kann ich leben von daher vielen vielen Dank.

**Comment by Mogli12** [comment]
Die extrem niedrige Drehzahl hatte ich nur, wenn man die Wendeschaltung betätigt ohne auf der Bremse zu stehen. Das ist mit 0.0.2.2 korrigiert.

**Comment by Shreklich** [comment]
Ja hab es gestern noch ausprobiert und funktioniert sehr gut. Hab nur noch nicht die Zeit gehabt mich hier zu melden. Danke sehr fürs Update.

**Comment by Mogli12** [comment]
Ich denke, dass ich das Issue zu machen kann. Vielen Dank fürs Testen!
