### ISSUE TITLE
User setting not save correctly

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#157]
Hallo Mogli,
ich nutze dein Skript auf einem Dedi und mir ist aufgefallen das die Einstellungen je Spieler nicht korrekt geladen werden. Ich habe zb zu beginn ein manuelles Getriebe eingestellt 6 gears with splitter und dazu noch autoclutch auf AUS. Verlasse ich nun den Server und betrete ihn wieder wird mir rechts unten der Fahrtrichtungspfeil angezeigt mit einem roten Ausrufezeichen (Handbremse?) in den Settings steht zwar noch 6 gears with splitter aber die automatische Kupplung ist jetzt aktiv. Um nun wieder manuell schalten zu können muss ich die Kupplung umschalten und zusätzlich einmal das Getriebe switchen. Es ist nicht all zu tragisch aber kann mich erinnern das die Einstellungen mal gespeichert wurden. 
LG

**Comment by Mogli12** [comment]
Welche Version?

**Comment by Shreklich** [comment]
Oh sorry bei der Version 0.0.2.3 und war auch bei der davor schon so also 0.0.2.2 .
Kann nicht mehr genau sagen bei welcher Version es noch gespeichert wurde. Bei 0.0.1.3 funktionierte es, danach die Versionen bin ich mir nicht sicher.
LG

**Comment by Mogli12** [comment]
Mit Version 0.0.5.8 sollte das Speicher verschiedener Einstellungen pro User funktionieren. Ich habe es selber getestet.
