### ISSUE TITLE
"Fahrzeugcamara zuruecksetzen" 

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#158]
Hi, irgendwie funktioniert bei mir seit einigen Versionen die FS-Option "Fahrzeugcam zuruecksetzen" im ingame Menue nicht mehr...ich hatte diese immer auf "aus", aber nun schwenkt die cam immer wieder in Ausgangsposition...eigentlich sollte die sich ja eigentlich die letzte Position, innen und aussen,merken....

**Comment by cabmac** [comment]
Hi...vielleicht kann man das im Vid leichter ersehen, was ich meine....im VCA die Ïnnen-und Aussencamarabewegung ausgestellt und die Position der Cam wird nicht mehr gespeichert beim wechseln der Innen zur Aussencam...Stellt man die Bewegung jedoch an, wird die Position gespeichert...:

https://vimeo.com/317667761

**Comment by Mogli12** [comment]
Was passiert denn, wenn Du VCA gar nicht verwendest? Klappt es dann?

**Comment by cabmac** [comment]
,ja, wenn ichs ganz rausnehme, ist es wie vorgesehen..

**Comment by cabmac** [comment]
Moin...ich bin mal weiter zurueckgegangen...die Version vom 23. Januar (b0130b8) funktioniert noch, also "speichert" die Blickrichtung noch:

https://vimeo.com/317785999

**Comment by Mogli12** [comment]
Bitte teste die Version 0.0.2.6.

**Comment by cabmac** [comment]
perfekt jetzt...
