### ISSUE TITLE
stop and go brake

### ISSUE THREAD

**Issue by sehmuscan** [Mogli12/VehicleControlAddon#159]
hello first thanks for this wonderful mod.i have problem with stop and go brake option.Is there a way to activate

**Comment by Mogli12** [comment]
What exactly do you mean?

**Comment by sehmuscan** [comment]
hi
sorry for my bad engilish,    and this video for my problem.
for example, when I go forward, the brake does not stop and starts to move backwards.
back and forth unstoppable 😊
> https://youtu.be/fC14OAaeXp8

my idea how to fix 
if you are not going to go forward or back =continuous braking and open brake lights

**Comment by sehmuscan** [comment]
Thanks very much my problem is solved (v0.0.2.4)
