### ISSUE TITLE
Font Color when snapped

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#160]
Hi, have the idea to colour the direction/compass font e.g. in green when angle is snapped. Would be helpful after switching between vehicles
And btw, superb work, I love it!

**Comment by Mogli12** [comment]
I currently thinking about how to visualize snap angle. If a direction is defined but inactive then lines would be useful to find the next lane.

**Comment by iljarogoff** [comment]
I saw you implemented the visualization of the snap angle with lines. If I may, I would tell my opinion to it. The lines look like floating above ground making them very strange when changing viewing perspective. This is confusing me. I would suggest to draw the lines on the surface.
Additionally I have another suggestion to it: it would be fine, if you could shift the lines/snap. For me, its easy to find and snap to the next lane, but its hard to adjust the lane with the working width to, e.g. the field edge.
btw, again many thanks to that great mod!

**Comment by Mogli12** [comment]
The lines are 0.1 meter above the ground. This is the same height that Giant uses for markers. The old command drawDebugLine does not work anymore.

**Comment by iljarogoff** [comment]
Ah, ok. Thanks for explanation 👍

**Comment by Mogli12** [comment]
Did you test version 0.0.3.4? Can we close this issue?

**Comment by iljarogoff** [comment]
Yes, and thank a lot for those new features. Working like a charm 👍
