### ISSUE TITLE
Anhalten mit FullPowershift

### ISSUE THREAD

**Issue by BLACKOUT-Z0ck3R** [Mogli12/VehicleControlAddon#161]
Hallo und erstmal danke für deine Mühe und den klasse Mod.
Ich habe das Problem, wenn ich (z.b. mit meinem 8r mit dem FPS) mit Autoclutch spiele, dass man nicht anhalten kann.... die Kupplung bleibt bei 99% und er rollt weiter.... dies tritt nur bei FPS auf und egal bei welchem Trecker.
Wenn man die Fahrtrichtung 2 mal wechselt bleibt er stehen.
Video: https://youtu.be/iET4TmhT3s8
Hoffe du kannst den Fehler finden.... in älteren Versionen (vom 08.02.19) passiert dieses noch nicht

**Comment by Mogli12** [comment]
Du musst einen größeren Startgang wählen. Es ist momentan ein bekannter Bug, dass der Startgang nicht richtig gewählt wird.

**Comment by BLACKOUT-Z0ck3R** [comment]
Problem ist immernoch vorhanden, wenn man die Shuttle funktion von EnhancedVehicle benutzt, wenn man die von VCA benutz macht es nach dem Anhalten nur noch nen kleinen "ruck"
trotzdem danke

**Comment by Mogli12** [comment]
Ich denke, dass die Verwendung von Shuttle von EnhancedVehicle in Kombination mit dem Getriebe von VCA eine schlechte Idee ist. Dazu hängen Shuttle und Getriebe einfach zu sehr voneinander ab.
