### ISSUE TITLE
Traktor bleibt nicht stehen

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#163]
Ich habe als Tastaturspieler das Problem, dass der Traktor nicht stehen bleibt, er wird zwar allmählich langsamer, aber er bleibt nie wirklich stehen. Um ihn wirklich zum Stillstand zu bringen, ist es ein ziemliches Gepfriemel vor/zurück bis man dann mal steht. Er rollt immer mit so 2-3 km/h weiter.
Das war in früheren Versionen so nicht der Fall.

**Comment by Shreklich** [comment]
Hallo hast du die neue Version 0.0.2.5 schon getestet damit sollte es jetzt gehen.

**Comment by Mogli12** [comment]
Wenn es schon nicht klappt die verwendete Version in ein Issue zu schreiben, dann lade doch bitte wenigstens die log.txt in Gist hoch. Danke

**Comment by iljarogoff** [comment]
Sorry, Schande über mich wg. der fehlenden Informationen. Ich verwende die 0.0.2.5
Wie das mit Gist funktioniert habe ich noch nicht herausgefunden, evtl. hilft das Attachment

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/2872824/log.txt)

**Comment by Mogli12** [comment]
Ok, danke für die Informationen. Kannst Du genau beschreiben, was Du machst und was Du eingestellt hast? Welches Getriebe verwendest Du und ist Shuttle Control an? Verwendest Du die Tastatur, einen analogen Joystick oder ein Lenkrad?

Was macht FS19_zzzSpeedControl?

Bei mir bleibt das Fahrzeug ohne Probleme stehen.

**Comment by iljarogoff** [comment]
IVT Getriebe, ich spiele mit Tastatur, Joystick ist angesteckt, benutze ich aber nicht. ShuttleControl ist aus.
Im Traktor kurz "W" antippen, damit er 2-3 kmh fährt, dann rollt er immer weiter.
FS19_zzzSpeedControl ist ein Mod, welcher den Tempomat auf feste Werte einstellt. Habs testweise mal deaktiviert, ohne diesen Mod rollt er dennoch weiter. Erst wenn ich VCA ausschalte, dann bleibt der Trecker stehn so wie er soll.

![fsscreen_2019_02_17_11_50_21](https://user-images.githubusercontent.com/21023840/52911892-4c73d700-32aa-11e9-9df6-3675426cc005.png)

**Comment by Mogli12** [comment]
Aber wenn Du bremst, dann bleibt er stehen, oder?

**Comment by iljarogoff** [comment]
Ja, bleibt man dann nur ein bisschen zu lange auf der "Bremse" dann fährt man rückwärts. Aber bei einem Tempo von 2-3 kmh rollt er halt unendlich weiter. Egal ob man vorwärts oder rückwärts rollt.

**Comment by Toidi2k** [comment]
ist bei uns auch. Man bremst und das Fahrzeug rollt dann immer noch weiter, um wirklich zum stehen zu kommen muss man kurz vor und zurück drücken bis er steht.

**Comment by Thornie03** [comment]
Kann ich auch bestätigen spiele mit Lenkrad und Pedale bis Version 0.0.19 funktionierte Alles jetzt tippt man das Gas kurz an und der Traktor fährt mit 3 km/h und bremsen ist nicht möglich erst nach dem richtungswechsel. Gibt man richtig Gas kann man auch normal bremsen dann bleibt der Traktor auch stehen. alles davor geht garnicht mehr. Leider.

Frage: Kann man eine vorerige Version bekommen? Aber wahrscheinlich geht das nicht mehr weil das ganze Zeug nun im Savgame gespeichert wird.... :(

**Comment by Thornie03** [comment]
Nachtrag:
Die oben von mir angegebene Version stimmt nicht. Das Problem tritt mit der Version 0.0.1.0 das erste mal auf also quasi mit dem einbinden der Kupplung. Was mir im Zuge dessen noch aufgefallen ist das sich die Kompassanzeige nach dem benutzen nicht wieder zurück setzt.

**Comment by Mogli12** [comment]
Giants hat in https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=69&class=8930#updateWheelsPhysics142887 in den Zeilen

**Comment by H8DCarnifeX** [comment]
Ich möchte das ausstellen, was muss ich dafür tun?
ShuttleControl nutze ich gar nicht, aber das Getriebe möchte ich definitiv nutzen.

Es stört mich pers. sehr, dass die Fahrzeuge beim Bremsen nicht ordnungsgemäß halten.
Dieses Hin und Her, bis man dann zum stehen gekommen ist, nervt dann auch leider permanent.

**Comment by Mogli12** [comment]
Ich möchte das ausstellen, was muss ich dafür tun? => FS19_VehicleControlAddon nicht verwenden!

**Comment by H8DCarnifeX** [comment]
> Ich möchte das ausstellen, was muss ich dafür tun? => FS19_VehicleControlAddon nicht verwenden!

Ich habe höflich gefragt, sehe da kein Grund, dass mir direkt so patzig geantwortet wird?
Das Addon gefällt mir ansonsten sehr gut und meinen Dank hatte ich an anderer Stelle auch schon ausgesprochen, dementsprechend möchte ich es nicht im LS19 missen und werde selbst nach einer Lösung suchen. *rollyeyes*

Ein passendes Zitat aber noch:
"Fast alle Menschen, die etwas taugen, haben schlechte Manieren."

MfG

**Comment by Ralleran** [comment]
Low Brake Force auf mindestens auf 5 % stellen dann gehts .. danke für das update mit dem allrad und so :)
