### ISSUE TITLE
Blickrichtung vertauscht beim kurzen rechts/links schauen wenn man nach hinten schaut

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/VehicleControlAddon#164]
Ist die Kamera auf Blickrichtung nach hinten eingestellt und man wählt die Funktion zum "kurz nach rechts schauen" aus schaut man nach links hinten, bei "kurz nach links schauen" entsprechend nach rechts hinten. Tritt sowohl in der Innen- als auch in der Aussenperspektive auf.

Getestet mit FS19_VehicleControlAddon (Version: 0.0.2.5) ohne andere Mods auf der macOS Version von FS19 v1.2.0.1.

**Comment by fdanapfel** [comment]
Gerade nochmal mit version 1.0.0 auf der aktuellen Version des Spiels (1.5.2.0) getestet, aber leider ist die Blickrichtung für "kurz nach links" und "kurz nach rechts" beim Rückwärtsschauen immer noch verkehrt.

**Comment by Mogli12** [comment]
Es wird jeweils auf die linke bzw. rechte Fahrzeugseite geschaut. Beim Blick nach hinten ist der Wert einfach nur größer, also 0.7*math.pi anstelle von 0.3*math.pi bzw. -0.7*math.pi anstelle von -0.5*math.pi.
