### ISSUE TITLE
Ausrichten am Raster funktioniert nicht richtig 0.0.2.7

### ISSUE THREAD

**Issue by Toidi2k** [Mogli12/VehicleControlAddon#170]
Wir benutzen das VCA um halt die Felder mit dem Raster abzuarbeiten. Leider geht das in den neueren Versionen nicht mehr so gut wie noch mit dem alten Keybordsteer. Drückt man STRG W will sich das Fahrzeug ausrichten, schlackert dann aber hin und her. Auch wenn man im Optionsmenü ist, während das Fahrzeug mit Rasterfunktion fährt, fährt es plötzlich mitten durchs Feld. Oder liegt hier ein Problem mit dem TSX_EnhancedVehicle zusammen?

**Comment by Mogli12** [comment]
Bei mir funktioniert es noch ohne Probleme. Die einzige Änderung war, dass LAlt+W die Rastersteuerung jetzt komplett aus schaltet. Man kann sie also nur noch mit LCtrl+W einschalten.

**Comment by Toidi2k** [comment]
also offline gibts dieses "Schlangenlinien" fahren nicht, kommt nur auf dem Dedi vor. Je schneller man damit fährt, desto größer wird es. Auch ist es sehr stark, wenn man nicht im 90° Raster fährt. Sonst Top Mod  überholt GPS noch:-)

**Comment by Mogli12** [comment]
Hast Du Version 0.0.3.0 probiert?

**Comment by Toidi2k** [comment]
ja auch mit version 0.0.3.0 schlackert er immer so 5-10° hin und her. haben verschiedene Karten, mit und ohne Mods getestet, immer das gleiche. Funktionierte in älteren Versionen sehr gut, leider hab ich keine Ahnung wann das angefangen hat. Soll ich mal ein Video davon machen?

**Comment by Mogli12** [comment]
Nein, das ist nicht notwendig. Tritt das Pendeln meistens nur im MP auf?

**Comment by Toidi2k** [comment]
ja im SP ist alles normal

**Comment by Mogli12** [comment]
Probier bitte mal die neueste Version. Die Lenkung wird jetzt komplett auf dem Server berechnet. Eventuell bewegt sich daher das Lenkrad aber nicht mehr im MP.

**Comment by Toidi2k** [comment]
Ok ich hab nun die 0.0.3.3 auf unseren Test DEDI installiert, aber erstmal offline getestet. Offline rastet er wirklich gut ein und auch die Linienführung ist super. Auf den Server allerdings werden keine Linien angezeigt und Einrasten tut das Fahrzeug auch nicht. Die °Anzeige wird auch nicht mehr bei ALT + W auf dem Raster angezeigt, was aber offline noch geht.

**Comment by Mogli12** [comment]
Ich spiele und teste FS19 nur im SinglePlayer. Mit Version 0.0.3.4 sollte es nun hoffentlich wieder funktionieren.

**Comment by Toidi2k** [comment]
Super Arbeit, läuft richtig gut bisher:-) Weiter so. Automatische breite noch rein und mehr brauch ich nicht*G*

**Comment by Mogli12** [comment]
Danke fürs Testen. Schön, dass es jetzt auch in MP klappt. Das mit der automatischen Breite überlege ich mir noch.
