### ISSUE TITLE
vehicle`s losing RPM and speed when reaching max speed using IVT transmission

### ISSUE THREAD

**Issue by mikeboy203** [Mogli12/VehicleControlAddon#171]
when using the fendt 700 series, Krone big M mower and a little more machines like that will lose speed and RPM when reaching the max speed and return to 35km/h. when applying the throttle again it will pickup speed again.
(v0.0.2.8)

**Comment by Mogli12** [comment]
Hallo,
ich kann das nicht reproduzieren. Kannst Du mal die log.txt in [Gist](https://gist.github.com/) hochladen? Ich vermute, dass hier ein Mod-Konflikt vorliegt.
Viele Grüße

**Comment by mikeboy203** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/2891236/log.txt)

**Comment by Mogli12** [comment]
I think your input bindings are corrupt. Please reset them.
