### ISSUE TITLE
Idea: offset

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#172]
Hi,
is it possible to add an option to set an offset for the snap, e.g. when using a plow or mower that works not in the middle behind the tractor?

**Comment by Mogli12** [comment]
Hi,
I think for a standard turn plow the offset is just a visual thing. But it would be rather complicated. So I am not sure if it is worth the effort.
Regards,
Stefan

**Comment by iljarogoff** [comment]
Yes, I guess it not just an easy thing to implement. It was just an idea in case you need a challenge :)

**Comment by Mogli12** [comment]
We need some many settings. Firstly, we need an input field for the offset, And then we need a setting what happens to the offset in reverse direction.

**Comment by Vanquish081** [comment]
How does this feature continue?

**Comment by Mogli12** [comment]
Please try version 0.1.2.0. If you enter 0 for distance, then VCA will calculate it automatically. This is very implicit, but right now it is the easiest way to add this feature.
