### ISSUE TITLE
working widths

### ISSUE THREAD

**Issue by Willi-77** [Mogli12/VehicleControlAddon#174]
Hallo, ich hab mal eine Frage, ist es möglich für das von dir verbaute GPS die Arbeitsbreiten noch ein bißchen feiner einstellen? ist teilweise nur in 0,5 Meter Schritten oder 1 bis 2 Meter Schritten. Wäre super wenn man es manuell eingeben könnte. Da es bei einigen Mods auch Breiten wie 5,7 Meter oder 7,60m gibt.
Ansonsten ist der Mod absolut Top!!
Ach ja währe es möglich das man die GPS linien noch verschieben könnte nachdem man die Richtung erstellt hat??

mfg Willi_77

Ansonsten läuft alles Super keine Fehler ferstgestellt V0.0.3.4

**Comment by iljarogoff** [comment]
Eine manuelle Einstellmöglichkeit wäre super. Ich hab zwar rausgefunden, wo ich neue Arbeitsbreiten hinzufügen kann, aber dazu muss ich leider immer die Originaldatei ändern.

**Comment by Willi-77** [comment]
ok vielleicht gibt es ja doch noch eine Möglichkeit da was zu machen.

**Comment by iljarogoff** [comment]
Schau mal in die Datei "vehicleControlAddon.lua"
In den Zeilen 2984-2987 stehen die Arbeitsbreiten. Dort kannst du neue hinzufügen.

**Comment by Willi-77** [comment]
ok danke das werd ich glaub ich auch als nichtmodder hinbekommen!

besten dank!

**Comment by Willi-77** [comment]
grad mal nachgesehen glaub das bekomm ich hin

**Comment by Mogli12** [comment]
Bei 5,7m oder 7,6m muss man leider 5,5m oder 7,5m wählen.
