### ISSUE TITLE
speichern der Einstellungen

### ISSUE THREAD

**Issue by taylorfx** [Mogli12/VehicleControlAddon#175]
Hallo Stefan,

wie früher schon, deine Addon's sind das Salz in der LS-Suppe. ich kann mir kaum verstellen mit dem Ding ohne Gearbox oder VehiclecControlAddon längere Zeit Spaß zu haben. Danke dafür. Und mich quält auch nur eine Lapalie :-). Die Einstellung "Automatik auf Ein" wird bei mir nicht gespeichert. Bei jeder neuen Session muß ich die Automatik wieder einschalten. Einstellungen betreffend der Schaltart, bei mir immer Powershift bleiben aber schön erhalten. Mach ich was verkehrt? Ist das so gewollt? Liegt es an den Traktoren? oder vielleicht doch am Script. Ich nutze den sagenhaften MB-Trac, den es auf Modhoster gibt oder einen Fendt 800 Favorit, ebenfalls von Modhoster.

Gruß

Frank

**Comment by Mogli12** [comment]
Hallo Frank,

mit Version 0.0.5.1 müsste es korrigiert sein.

Viele Grüße,
Stefan

**Comment by Evilman2517** [comment]
Hallo, leider kann ich das Verhalten mit der aktuellsten Version bestätigen. Habe einem Fahrzeug das 2x6 Getriebe verpasst und muss nach jedem Login auf dem Server das Getriebe einmal wechseln und wieder auf das richtige stellen. Falls Logs benötigt werden, kann ich gerne meine lokalen und die Dedi-Logs Zur Verfügung stellen

**Comment by Mogli12** [comment]
Ich würde gerne die Log-Datei vom Server und die vehicle.xml sehen.

**Comment by Evilman2517** [comment]
Bekommst du heute Abend

**Comment by Evilman2517** [comment]
Hallo, anbei der Link zu den geforderten Files.
Beim MB Trac (Zeile 1925 in der vehicles.xml) habe ich das Problem festgestellt.
[https://gist.github.com/Evilman2517/d9e0a1dc6e3174c6aa89e94d80cfe453](url)

**Comment by Mogli12** [comment]
Der Link ist kaputt?

**Comment by Evilman2517** [comment]
Hmm, keine Ahnung warum der nicht geht, copy und paste funktioniert

**Comment by Mogli12** [comment]
Das Log ist recht groß und unübersichtlich. Kannst Du es nochmal mit Version 0.0.5.5 probieren? Welcher Spieler bist Du und was hast Du konkret gemacht?

**Comment by Evilman2517** [comment]
Stimmt, sorry. Ist halt ein echter Spielstand mit 4-5 Spielern.
Ich bin der Spieler Chris und habe mir einen MB Trac gekauft, diesem habe ich im VCA Menü das 2x6 Getriebe konfiguriert und gespeichert. Wenn ich das Spiel speichere, den Server verlasse und wieder betrete, wird mir im VCA Menü weiterhin das 2x6 Getriebe angezeigt, das Fahrzeug hat aber das Standard Automatik-Getriebe, ich kann auch nicht schalten oder sonstiges, ich muss erst wieder ins VCA Menü, das Getriebe einmal auf etwas anderes stellen und speichern, dann wieder ins VCA Menü und wieder das 2x6 Getriebe auswählen, dann läuft alles wieder, zumindest bis zum nächsten Verlassen und Betreten des Servers.

Werde heute Abend die neue Version nutzen und dir die Logs zukommen lassen (versuche auch sie kleiner zu halten ;-))

**Comment by DoubleUJ** [comment]
Wir haben das gleiche Problem.
Ich werde auch heute Abend die neue Version nutzen und sehen, ob wir brauchbare Log-data generieren können. Wir haben ein Setup mit zwei Spielern.

**Comment by Mogli12** [comment]
Ok, das bedeutet also, dass zwar das richtige Getriebe angezeigt wird, aber es funktioniert nicht, richtig?

**Comment by Mogli12** [comment]
Ok, probiert mal 0.0.5.6

**Comment by Evilman2517** [comment]
Leider brachte die neue Version keine Besserung, eher im Gegenteil, ich kann nun gar kein Getriebe auswählen (es steht immer nil im Display)

**Comment by Mogli12** [comment]
Ok, mit Version 0.0.5.8 hat es bei mir nun funktioniert. Jeder Benutzer hat damit seine eigenen VCA Einstellungen, die auch pro User gespeichert werden.

**Comment by taylorfx** [comment]
Hallo,

Vielen Dank für die Anpassung, das Speicherproblem ist wohl schon mit Buil 5.3 oder 5.4 beseitigt worden. Ich dachte zuerst, ich dachte zuert, bei mir spukt es, als ich die AI-Console der Trecker öffnete und die gespeicherten Werte vorfand und habe es erts hier mit dem Lesen kapiert as du wohl Hand angelegt hast, Danke nochmals dafür

**Comment by Evilman2517** [comment]
Klasse, vielen Dank für das letzte Update, Einstellungen werden gespeichert und auch wieder geladen. Vielen Dank für die Arbeit und fürs fixen.

Grüße
