### ISSUE TITLE
Linienanzeige im MP funktioniert nicht immer in allen Fahrzeugen

### ISSUE THREAD

**Issue by Toidi2k** [Mogli12/VehicleControlAddon#176]
Hallo Mogli. Nach ausgiebigen testen der 0.0.3.4 ist mir jetzt noch ein Fehler aufgefallen und zwar zeigt es mir nicht immer die Linien an, wenn ich STRG-W Drücke zum festlegen der Gradzahl. Es ertönt zwar das Signal nach Aktivierung, aber es kommt kein Kurs. Wechsel ich dann in ein anderes Fahrzeug, läuft das dann dort wieder, aber nicht im Ausgangsfahrzeug. Tritt ehr sporadisch bei einzelnen Fahrzeugen auf, leider habe ich noch keine Lösung gefunden. Es sind auch nicht immer die gleichen Fahrzeuge.

**Comment by Toidi2k** [comment]
Die Führung ist aber immer in Hintergrund aktiv nur nich einstell- und sichtbar.

**Comment by Willi-77** [comment]
kann ich bestätigen das Problem hab ich auch im MP!

**Comment by Toidi2k** [comment]
Das Problem scheint random aufzutreten. ab und an gehts in fast allen Fahrzeugen und dann wieder in keinem, dann bleibt nur der "unsichtbare" 90° Modus übrig ohne Linien.

**Comment by Mogli12** [comment]
Welche Version?

**Comment by Toidi2k** [comment]
Wir haben jetzt Version 0.0.4 drauf. das gleiche passiert auch bei den anderen Versionen. wenn du ne log brauchst kann ich die auch gerne posten.

**Comment by Mogli12** [comment]
Ich spiele selber nicht in MP und ich habe keine Ahnung, warum es nicht funktioniert. Das Problem wird also wohl nicht gelöst werden. Sorry.

P.S.: Meine Mods baue ich eigentlich nur noch für mich selber und teile sie dann so wie sie sind.

**Comment by Toidi2k** [comment]
echt schade, weil wir finden deine Mod echt gut nur halt doof das die linien nicht immer da sind:-) aber sonst super arbeit. wenn du aber lust hat kannst gerne unseren Testserver nutzen:-)

**Comment by Willi-77** [comment]
Hallöchen hab festgestellt wenn dann ein anderer spieler in das Fahrzeug rein geht und dann einmal ALT+W drück und ich dann wieder rein gehen geht das mit den GPS linien wieder einwandfrei. Auch wenn wann vor dem Spiel speichern und beenden das GPS ALT+W deaktiviert funktionirts beim neustart im MP dann eigentlich. Vielleicht hilfft es dir ja "Toidi2k" ach ja ist eigentlich immer in dem Fahrzeug wo man zuletzt drin gesessen hat vor dem Speichern und beenden.
Das "Problem" tritt eigentlich bis jetzt in allen Versionen auf, hab immer die neuste drauf aus dem Github.
Nur in der 0.0.4.9 noch nicht getestet.
Ansonsten großes DAnkeschön an dich "Mogli12" ich feiere dein Script. Ohne das würde ich den LS vielleicht schon nicht mehr spielen.
Danke Danke Danke

**Comment by Toidi2k** [comment]
Hmm cool wenn das funktioniert wäre das echt super. @ Mogli geiler Mod wenn der gar nicht mehr gehen würde. würde mir in LS was fehlen. Allein das Getriebe ist richtig geil!

**Comment by Mogli12** [comment]
Kann mal jemand einen Screenshot von den Settings machen, sobald das Problem im MP aufgetreten ist?

**Comment by Toidi2k** [comment]
![20190408224025_1](https://user-images.githubusercontent.com/47612817/55755763-413e5b80-5a50-11e9-9f15-37068268726f.jpg)
![20190408224031_1](https://user-images.githubusercontent.com/47612817/55755764-413e5b80-5a50-11e9-93d3-248e9379d6c0.jpg)
![20190408223946_1](https://user-images.githubusercontent.com/47612817/55755793-52876800-5a50-11e9-9db1-f3ade4065515.jpg)
![20190408223948_1](https://user-images.githubusercontent.com/47612817/55755794-52876800-5a50-11e9-8dfb-f4c06c6a79d8.jpg)
![20190408223918_1](https://user-images.githubusercontent.com/47612817/55755805-5a470c80-5a50-11e9-8bd0-a6b19a4cf814.jpg)
![20190408223925_1](https://user-images.githubusercontent.com/47612817/55755806-5a470c80-5a50-11e9-9eee-fd02c5ec8976.jpg)
![20190408223809_1](https://user-images.githubusercontent.com/47612817/55755829-69c65580-5a50-11e9-869e-3754d1ecc212.jpg)
![20190408223832_1](https://user-images.githubusercontent.com/47612817/55755830-69c65580-5a50-11e9-8515-b99ba9c2caee.jpg)

**Comment by Toidi2k** [comment]
ok hab die neue version probiert, bei einigen gehts bei anderen nicht. Kauft man im MP allerdings die Fahrzeuge neu, scheint es auf den ersten Blick zu funktionieren, wo es bei bestehenden nicht Funktioniert. Beim MB Trac zb gehts bei dem einen, aber bei dem anderen nicht.

**Comment by Mogli12** [comment]
Und die Rastersteuerung hört einfach auf zu funktionieren? Was haben die Spieler gemacht?

**Comment by Toidi2k** [comment]
Nein die Rastersteurerung fällt nicht aus, sie ist dann einfach nicht mehr aktiv, egal was man macht. Das einzige was ich bisher herausgefunden habe ist, das wenn man die Fahrzeuge neu kauft, es auf jedenfall immer funktioniert. Wir testen mal die neue Version und laden dann mal die Logs hoch

**Comment by Mogli12** [comment]
Neu an 0.0.5.1 ist nur, dass beim Ausschalten zusätzliche Ausgaben ins Log geschrieben werden.

**Comment by Toidi2k** [comment]
Ach so wir haben jetzt erstmal alle Fahrzeuge getauscht und neu gekauft, damit funktionierts erstmal. Die Steuerung ist wirklich echt gut gelungen. Wenn es wieder weg ist bei bestimmtem Fahrzeugen, werd ich die Logs posten. Vielen dank das dir doch die Mühe machst vielen vielen dank....

**Comment by Toidi2k** [comment]
[log1.txt](https://github.com/Mogli12/VehicleControlAddon/files/3074792/log1.txt)
[serverlog.txt](https://github.com/Mogli12/VehicleControlAddon/files/3074793/serverlog.txt)
[gamelog.txt](https://github.com/Mogli12/VehicleControlAddon/files/3074795/gamelog.txt)

**Comment by Toidi2k** [comment]
ich hoffe hier kann man was sehen. Hatte nun das Problem, das bei unserem Claas Lexion 780 die Lienenführung bis heute ging und dann nicht mehr. Habe dann das Fahrzeug verkauft und ein neues gekauft, wo es dann wieder einwandfrei funktionierte.

**Comment by Mogli12** [comment]
Hi,
es treten immer noch die komischen MP-Fehler auf, die mich dazu bewogen haben, keine Mods mehr für FS19 zu veröffentlichen.

Probiert bitte mal Version 0.0.5.2 und schickt mir nochmals beide Log-Dateien zu.
Danke

**Comment by Raven868** [comment]
Moin Leute.
Mir ist zur der Sache aufgefallen, das die Linien nur verschwinden wenn das Fahrzeug mit eingeschalten GPS abgestellt wurde und keine mehr auf dem Server ist. Wenn man das GPS dann wieder ganz ausschaltet, gibt es keine Probleme.

**Comment by Toidi2k** [comment]
Wie denn ganz ausschalten?

**Comment by Mogli12** [comment]
LAlt+W

**Comment by Toidi2k** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/3076747/log.txt)
[gamelog.txt](https://github.com/Mogli12/VehicleControlAddon/files/3076748/gamelog.txt)

**Comment by Mogli12** [comment]
So, mit Version 0.0.5.3 sollte es funktionieren.

**Comment by Mogli12** [comment]
Falls es immer noch nicht klappt: 0.0.5.8!

**Comment by Toidi2k** [comment]
Läuft alles super
