### ISSUE TITLE
How can I add new gearboxes?

### ISSUE THREAD

**Issue by V3XING** [Mogli12/VehicleControlAddon#177]
Hello, first of all, thank you very much for your work. I am a layman in programming but would like to know if it is possible to add new gearboxes?

**Comment by Mogli12** [comment]
Please make a proposal. Is is sufficient to add a new gearbox globally for all vehicles via modSettings?

**Comment by V3XING** [comment]
I'm trying to 2x4 for harvesters and old trucks, and 5 gears for cars.
But I can not get them to full speed, I think it's because there are 12 gears.

**Comment by Mogli12** [comment]
Yes, currently, everything is based on 12 gears.

**Comment by Mogli12** [comment]
Please check #181 and https://github.com/Mogli12/VehicleControlAddon/blob/master/modSettings/FS19_VehicleControlAddon/transmissions.xml.
