### ISSUE TITLE
shuttle control by tabbing vehicle

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#178]
Hi, seit 0.0.3.9 (kann auch seit 0.0.3.7 sein, die hab ich jetzt nciht probiert), geht, wenn man in das Fzg "reintabbt", shuttle control und Gangwechsel nicht mehr, man muss also mit E ein- und wieder aussteigen...dann gehts...also tabben geht nicht, mit E geht...bei 0.0.3.6 gehts auf jeden Fall noch..

schoene Gruesse

**Comment by Mogli12** [comment]
Ich weiß und verstehe es leider nicht.

**Comment by Mogli12** [comment]
Es ist mit 0.0.0.4 gelöst.
