### ISSUE TITLE
0.0.3.9 Am Raster ausrichten deaktiviert sich selbstständig(MP)

### ISSUE THREAD

**Issue by Toidi2k** [Mogli12/VehicleControlAddon#179]
In den Fahrzeugen wo ich VCA nutzen kann, deaktiviert sich am Raster ausrichten ständig von alleine.

**Comment by Mogli12** [comment]
Die Linien werden ausgeblendet, wenn der Traktor automatisch lenkt. Aber das kann man in den Settings einstellen.

**Comment by Toidi2k** [comment]
Ne das meine ist nicht, die linien bleibne sichtbar, schalten aber von grün auf rot und man hört auch diesen Ton, genau wie wenn man ALT W drückt. Passiert aber nach dem Aussteigen nicht immer.
