### ISSUE TITLE
Automatic shifting gears with manual range selection 

### ISSUE THREAD

**Issue by kananesgi** [Mogli12/VehicleControlAddon#181]
Would it be possible to add an option to allow selection of automatic gears without automatically shifting ranges as well? I'm having some difficulty using the 4x4 transmission on a low-powered tractor while trying to climb a hill. Movement stalls between shifts in M or H range, but LL and L work fine. Problem is that I start in one of the lower ranges, the tractor gets a few feet and then shifts into M and next thing you know, it's stuck again. The only solution I've found is to switch to manual shifting, but to me, shifting gears with KB is cumbersome at best.

I've run into this problem in fieldwork as well. When trying to work a field that's pretty vertical (steep hills), the tractor's movement often stalls because it tries to shift into too high a range.

**Comment by Mogli12** [comment]
Please check version 0.0.4.7. I added two transmissions
- "6x4 AutoPowerShift" has 6 ranges and 4 automatic gears with power shift
- "Car with low range" has 6 automatic gears and 2 ranges, which are shifted manually.

Additionally, you can add your own transmissions. Please check https://github.com/Mogli12/VehicleControlAddon/blob/master/modSettings/FS19_VehicleControlAddon/transmissions.xml for details.
