### ISSUE TITLE
Feature Request: Arbeitsbreite (work width)

### ISSUE THREAD

**Issue by Aceone1** [Mogli12/VehicleControlAddon#183]
Hallo Mogli

Erstmal vielen Dank für die unerwarteten GPS Funktionen im VCA. Seit deren Implementierung spiele ich den LS wieder viel häufiger.
Request: 
Es wäre schön wenn die einstellbare Mindestarbeitsbreite bei 1,8 m anstatt bei 2 m liegen würde um zb. die gezogenen Kartoffel- bzw. Zuckerrübenernter mit abzudecken.
Das wars schon.

english: request for a smaller work width in the VCA options (from 2,0 m to 1,8 m)

**Comment by Messy71** [comment]
@Aceone1 for further adjustments , you can manually add new values in vehicleControlAddon.lua at the bottom you have the line ‘’ for i,v in pairs({ 0, 1.5, 1.6 ,   ...}) i don’t know if there is a limit for the width or the number of values you can add in there but when you put a value in it should end with a comma and if it not an rounded number you should use period , for example  one hundred and a half meters should be  —  100.5, — ( 100.4, 100.5, 100.6, ,, )

**Comment by Mogli12** [comment]
It is fixed with version 0.0.4.7
