### ISSUE TITLE
Draw marker function

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/VehicleControlAddon#187]
Hi Stephan, I got in my inputBinding file like you know:

```
<actionBinding action="vcaSNAP">
        <binding device="KB_MOUSE_DEFAULT" input="KEY_lctrl KEY_w" axisComponent="+" neutralInput="0" index="1"/>
```

but the real action in my french game is input="KEY_lctrl KEY_z" !! the mod is S19_Ford40er_Serie.zip. Is this is a issue of tractor configuration mod ? cause other vehicle don't do that thing below, the 3 lines are always on every time on
![1](https://user-images.githubusercontent.com/25174503/56991829-f61ff000-6b98-11e9-9756-18c77acd1fd1.png)
all tried function in Draw marker (my bad english), and unable too to translate "Draw Marker" and all options it show... it's the 1st time I see that things lines in my gameplayed.
![2](https://user-images.githubusercontent.com/25174503/56991891-1a7bcc80-6b99-11e9-8d71-739d993c9bd4.png)
So how I can disable these options ? ans so what that do ? when I input="KEY_lctrl KEY_z" the tractor turn random it seem ? on the 3 green lines...
Also we are in multiplayer dedicated server but it does not be linked I think.
These weird functions for me "‎panic brain" many questions sorry.
Br

**Comment by Mogli12** [comment]
I propose to check your inputBinding.xml.

**Comment by Anonymous-any** [comment]
Thank, It made already because I show you what is inside they are default input like you know, my real issue is I'm unable to disable lines showed in this mod tractor with every function are purposed, so it look to be an issue with this mod or is this in VCA ? also what these are made to do ?

**Comment by Anonymous-any** [comment]
I close because I already don't know what these are supposed to do.
Regard
