### ISSUE TITLE
Man kann keine Holzstücke in die hand nehmen 

### ISSUE THREAD

**Issue by SaveSpace93** [Mogli12/VehicleControlAddon#188]
Ich habe die erfahrung gemacht das man keine kleinen Holzstücke in die Hand nehmen kann, wenn Gearbox als mod aktiv ist, somit ist auch die beliebte Tajfun Seilwinde ohne Funktion,

ich habe auch versucht nur gearbox und besagte seilwinde zu aktivieren, und hab alle anderen Mods entfern, Problem blieb weiterhin, Log zeigte mir aber keinerlei Fehler

**Comment by denut** [comment]
no problem by us maybe you have a control conflict left click fom mouse assigned to the gearbox ?

**Comment by Mogli12** [comment]
Hast Du mal Deine inputBinding.xml gelöscht. Aber bitte mach vorher eine Sicherungskopie.
