### ISSUE TITLE
little issues for a very good mod

### ISSUE THREAD

**Issue by denut** [Mogli12/VehicleControlAddon#189]
first your mod is very good you have published the link for the real manual transmission .... i don't like the only raison is your mod is workin with all vehicle the other not, you implement a very good gps, and you help the keyboard players with steering !!!!

for me playing with g27 i use the 2 x 6 gearbox it's awesome

the only little problems are :
1: shuttle control have little problem if the terrain have vertical drop you need to brake before you can reaccelerate
2: shuttle control have the possibility to use 2 bouton 1 for forward and 1 for backward i'm all time using this function but with tractor with reverse driving forward stay the front from tractor ...
3: select the tool width need a lots of clicks (is it possible to use the mouse scroll only in this selection?)

the fonction to implement if you want a gearbox 4x4 where we can assign the the 4 left to bouton and the 4 right to other bouton ?

my other problem i du to the community with my team we make live video regularly and a lot of people asking the mod we are using for gearbox and gps and i don't give your git adress because i don't want you have problematic people 

my solution is to publish your mod with my own link but is not a good solution for me the best way is you publish a sharemod link that y can share ? (dont use the mogli name for this upload to have a little privacy, user more experimented will find you in the mod files)

if you want to see us there is the youtube link https://www.youtube.com/channel/UCrUOoja__myTnRy24A854aw 
we are french .....

big thanks for your job

**Comment by fdanapfel** [comment]
@Mogli12: I think the second issue described above is similar to what I've already reported here: https://github.com/Mogli12/VehicleControlAddon/issues/147

**Comment by denut** [comment]
yes it's the same

**Comment by denut** [comment]
hello
my question about 1 bouton 1 fonction is because i plan to buy this adapter https://www.ricmotech.com/Leo_Bodnar_USB_Adapter_for_Logitech_Shifter_p/bod-lgshftusb.htm

i have a second g27 shifter as spare (no more spare with adapter) and using 4 gears on one and 6 on the other can be verry fun

**Comment by denut** [comment]
a other way is this adapter https://www.ebay.ca/itm/Replacement-Sequential-Adapter-Pad-for-Logitech-G27-G29-G920-G25-Gear-Shifter/401667268005?hash=item5d853c1da5:g:6ngAAOSwUTZcpdpd working good for you 6x4 gearbox 
but when i use the 6 gear and the A B C D as sequencial every time i change the 1 2 3 4 5 6 gear the sequencial jump to C and don't stay in the initial A B or D gear 

the best is maybe at changing the 1 2 3 4 5 6 the sequencial jump to B because the A is slower than the before gear and C is to fast

not sure my explication is understandable

**Comment by denut** [comment]
or and other option when shifting from 1 ABCD to 2 B     form 2ABCD to 3 B
from 3 ABCD to 2D  from 2 ABCD to 1 D

**Comment by denut** [comment]
6.1 working perfect on hoffbergmann :)

**Comment by denut** [comment]
1: shuttle control have little problem if the terrain have vertical drop you need to brake before you can reaccelerate


no more problems now !!!!!!!!!!!!

**Comment by denut** [comment]
2: shuttle control have the possibility to use 2 bouton 1 for forward and 1 for backward i'm all time using this function but with tractor with reverse driving forward stay the front from tractor ... 

same problem but not a big problem

**Comment by Mogli12** [comment]
You can already assign the two actions vcaFORWARD and vcaREVERSE.

**Comment by denut** [comment]
have assigned no problem with normal tractors but with a valtra in reverse cab driving mod (turn the seat inside the cab) the vca forward stay the front of the tractor but it must be the back of the tractor

**Comment by denut** [comment]
reverse cab driving ok !!!

**Comment by Mogli12** [comment]
I think this can be closed, right?
