### ISSUE TITLE
Vehicle direction

### ISSUE THREAD

**Issue by Bandesss** [Mogli12/VehicleControlAddon#190]
Hello in the MP we have the problem that we benutezn your Mod and de VCA. I'm the only one with a keyboard .... In the single player I can switch with the space bar. But not in the MP ... it changes the arrow from forward to reverse but still I drive backwards only with S.
In Singel Player I drove backwards after switching with the space bar also backward with W ....
What can that be, thank you Bandes

**Comment by Mogli12** [comment]
Do you use the latest version?

**Comment by Bandesss** [comment]
Yes the file Upload yesterday from github

**Comment by Mogli12** [comment]
Can you please post the log.txt of the server?

**Comment by Bandesss** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/3217152/log.txt)
[TestLOG.txt](https://github.com/Mogli12/VehicleControlAddon/files/3217184/TestLOG.txt)
There are no log errors. But a video where you can see what I mean: I just upload the video on Youtube
https://youtu.be/fFE6CqDdesg

**Comment by Mogli12** [comment]
Hi,
you are using the shuttle control of enhanced vehicle. 
Regrads,
Stefan
