### ISSUE TITLE
[Solved] Issues in machines Hof Bergmann Map

### ISSUE THREAD

**Issue by Vanquish081** [Mogli12/VehicleControlAddon#194]
`2019-06-13 23:05 Warning (script): 'setMotorProperties': Argument 1 has wrong type. Expected: Int. Actual: Nil 2019-06-13 23:05 ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (791): expectedType == Value::VoidType || expectedType == Value::ClassType 2019-06-13 23:05 LUA call stack: 2019-06-13 23:05 dataS/scripts/vehicles/specializations/Motorized.lua (1610) : setMotorProperties 2019-06-13 23:05 =[C] (4294967295) 2019-06-13 23:05 =d:/servers/service12212/home/games/FarmingSimulator19/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua (2928) : pcall 2019-06-13 23:05 =d:/servers/service12212/home/games/FarmingSimulator19/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua (884) : updateMotorProperties 2019-06-13 23:05 dataS/scripts/vehicles/SpecializationUtil.lua (30) 2019-06-13 23:05 dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent 2019-06-13 23:05 dataS/scripts/network/NetworkNode.lua (98) : update 2019-06-13 23:05 dataS/scripts/network/Server.lua (58) : updateActiveObjects 2019-06-13 23:05 dataS/scripts/BaseMission.lua (1500) : update 2019-06-13 23:05 dataS/scripts/FSBaseMission.lua (1971) : update 2019-06-13 23:05 dataS/scripts/missions/mission00.lua (469) : update 2019-06-13 23:05 dataS/scripts/main.lua (1863) : update 2019-06-13 23:06 Warning (script): 'setMotorProperties': Argument 1 has wrong type. Expected: Int. Actual: Nil 2019-06-13 23:06 ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (791): expectedType == Value::VoidType || expectedType == Value::ClassType 2019-06-13 23:06 LUA call stack: 2019-06-13 23:06 dataS/scripts/vehicles/specializations/Motorized.lua (1610) : setMotorProperties 2019-06-13 23:06 =d:/servers/service12212/home/games/FarmingSimulator19/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua (2938) : superFunc 2019-06-13 23:06 =d:/servers/service12212/home/games/FarmingSimulator19/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua (884) : updateMotorProperties 2019-06-13 23:06 dataS/scripts/vehicles/SpecializationUtil.lua (30) 2019-06-13 23:06 dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent 2019-06-13 23:06 dataS/scripts/network/NetworkNode.lua (98) : update 2019-06-13 23:06 dataS/scripts/network/Server.lua (58) : updateActiveObjects 2019-06-13 23:06 dataS/scripts/BaseMission.lua (1500) : update 2019-06-13 23:06 dataS/scripts/FSBaseMission.lua (1971) : update 2019-06-13 23:06 dataS/scripts/missions/mission00.lua (469) : update 2019-06-13 23:06 dataS/scripts/main.lua (1863) : update`

This erros show when in to seedMaster or similar for production of products and start engine.

**Comment by D9005** [comment]
Hello, 

Maybe it could be an option, to ask the "vehicle" if it is wearable or not. The function of wearability is disabled in the productions of this map, so it could be the solution for these errors.

Hallo,
Vielleicht könnte es helfen, wenn man im VCA eine Abfrage auf "Abnutzung" mit einbindet. Bei der Hof Bergmann ist diese nämlich bei den Produktionen, die diese Errors verursachen, raus genommen worden. 

MfG D9005

**Comment by Mogli12** [comment]
Hallo,

Probier mal Version 0.0.6.0

Viele Grüeß,
Stefan

**Comment by Vanquish081** [comment]
Hi! no show error now with 0.0.6.1, great :)
