### ISSUE TITLE
Vehicle sound change whilst leaving

### ISSUE THREAD

**Issue by Szmiti** [Mogli12/VehicleControlAddon#195]
Hello,

Thanks for the great mod, and appreciate all you have done to improve the LS series !  Seems to be a small issue since patch 1.4 (tested by removing all other mods - in single player - from mod folder) ...

When leaving vehicle with engine running but not completely stationary - ie. if still moving only very very slightly and slowly, then vehicle sound is changed to a dull / muffled sound until re-entering the vehicle.  If ensure the vehicle is absolutely stationary and exit, then no issue.  OK, not big issue but vehicles do not always stop 100% if braking then quickly exiting to say, attach something ...

Szmiti

**Comment by KeyboardFarmer** [comment]
Hi, I've seen this as well in patch 1.3 - Like you say it's a small issue :)

**Comment by Mogli12** [comment]
Can you test it with version 0.0.6.3?

**Comment by Szmiti** [comment]
The issue with the sound was solved with v0.0.6.2 and now no sound issues.  Thanks !

Sound continues to be no issue in v0.0.6.3.  However, there is a new issue with v0.0.6.3 whereby vehicles with working reversing lights (ie. New Holland T7 (vanilla)) have these white reversing lights flashing when either braking (after stopping) or just allowing vehicle to come to rest (in either direction).  In addition, vehicle then rolls slowly and does not remain stationary - effect (issue) stops with either exit vehicle or engine off.

**Comment by Mogli12** [comment]
You have to press the brake for 1 second to remain stationary.

**Comment by Szmiti** [comment]
Yes, and that (1sec braking) works perfectly in v0.0.6.2 but with v0.0.6.3 I cannot stop the vehicle rolling and the issue is with the reversing lights flashing - I have reloaded the game several times with both versions and only happens with v0.0.6.3.  I need to try with all other mods removed - and sorry I also mixed two issues here - the original issue (with the sound) has been resolved in both v0.0.6.2 and v0.0.6.3

**Comment by Mogli12** [comment]
Did you try the latest version?
