### ISSUE TITLE
Transmission gets disabled while using Wopsters Guidance Steering

### ISSUE THREAD

**Issue by KeyboardFarmer** [Mogli12/VehicleControlAddon#196]
Hi, when I activate the guidance steering from Wopsters GPS mod it seems VCA is disabled completely, only to be reactivated on the headland where the GPS is deactivated.
This is a bit of a shame since I really like the IVT simulation where the engine can rev up/down as needed.
Is this a conflict between the mods, or is it VCA disabling itself in the presence of the GPS mod, or is it the GPS mod disabling VCA?

All the best,
KeyboardFarmer

**Comment by denut** [comment]
why not use the gps inside VCA ?

**Comment by KeyboardFarmer** [comment]
Because it draws multiple lines: https://github.com/Mogli12/VehicleControlAddon/issues/191
Besides, Wopsters GPS has some cool features with offset & automatic offset reversal etc.
That being said VCA is my favourite mod, I wouldn't be a proper KeyboardFarmer without it. I'm just hoping to get them to work together.

Regards,
KeyboardFarmer

**Comment by ThisPf** [comment]
Hallo Stefan
Das Thema ist mir auch schon auf Wobsters Github aufgefallen. Zwar im Zusammenhang mit Enhanced Vehicle, aber könnte dasselbe Problem sein.
https://github.com/stijnwop/guidanceSteering/issues/143
Wopsters Guidance Steering stellt das Fahrzeug auf "not controlled by player mode" was auch VCA zu deaktivieren scheint. Hoffe das hilft.
Vielen Dank für deine tolle Arbeit! Grüsse.

**Comment by Mogli12** [comment]
Hallo,
mir ist das schon bewusst. Nur kann ich nichts dagegen machen. Wenn getIsControlled() nicht true zurück gibt, dann ist das Getriebe aus, bzw. im Helfermodus.
Viele Grüße,
Stefan

**Comment by Evilman2517** [comment]
Perfekt, vielen Dank

**Comment by KeyboardFarmer** [comment]
Working Fine now thanks for the update, I haven't been able to play for a while :+ :)
Thanks for all your hard work and have a good 2020.
