### ISSUE TITLE
Tastenbelegung ausblenden

### ISSUE THREAD

**Issue by Shepperd1337** [Mogli12/VehicleControlAddon#198]
Moin,
es ist nicht wirklich ein Fehler jedoch werden mir die Gänge nicht im Tastaturmodus im HUD angezeigt, wenn ich auf den Lenkradmodus wechsel dann werden mir alle Belegungen angezeigt. Gibt es da ne Option oder ne Lösung wie ich das ausblenden kann?

MfG, danke für den tollen Mod :)

**Comment by Mogli12** [comment]
Hallo,

ich denke, dass das vom Spiel automatisch gemacht wird. Ich kann dem Hilfe-Text nur eine Priorität geben.

Viele Grüße
