### ISSUE TITLE
Doppelbelegung Beim Shifter möglich?

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#199]
Hallo Mogli,
ich wollte mal fragen ob es zu diesem Problem #137 eine Lösung gibt?
Benutze die Version 0.0.6.2 in Moment ist es nur möglich Shuttle Control an zu lassen egal welche Getriebeart man benutzt da sonst der Rückwärtsgang nicht funktioniert. Belegt sind die Gänge 1-6 +der Rückwärtsgang nutze ich nun ein Automatik Getriebe zB IVT dann kann ich zwar Shuttle nutzen muss aber dann umständlich den Rückwärtsgang einlegen und würde es gerne wie in dem anderen Beitrag beschrieben auf die Gänge 3 und 4 belegen, für vorwärts und rückwärts. Werden die Tasten also doppelt belegt dann funktioniert das Getriebe nicht mehr oder aber der Rückwärtsgang auf den Gang 4 wird ignoriert. Hoffe ich konnte es so einigermaßen erklären. Es müsste also irgendwie funktionieren das mit eingeschaltetem Shuttle Control die Gangbelegung 1-6 ignoriert werden. Dazu müsste aber dann auch der Rückwärtsgang ohne Shuttle Control im Handschaltmodus funktionieren. 
Schon mal vielen Dank für deine Mod auch wenn dieses hier vielleicht nicht umgesetzt werden kann, den ohne dein Skript zu zocken ist keine Option für mich.

**Comment by Mogli12** [comment]
Hallo,
Probier mal Version 0.0.8.1. Man kann hier beim jedem Fahrzeug individuell zwischen verschiedenen Schalt-Schemata wählen.
Viele Grüße

**Comment by Shreklich** [comment]
Werd ich morgen erst ausprobieren können. Vielen lieben dank aber trotzdem schon mal.

**Comment by Shreklich** [comment]
Hallo,
So nach meiner ersten Testphase muss ich sagen absolute Spitzenklasse was du da gezaubert hast. Klappt echt super musste halt nur erstmal herausfinden das man für die Shuttle Option in der Tastenbelegung auch die Fahrtrichtung vorwärts und rückwärts belegen muss. Mit der neuen Einstellung in den Optionen ist es ohne Probleme möglich die Fahrzeuge individuell anzupassen einfach Top. Des Weiteren ist es absolut mega das nun auch die Range gespeichert wird war vorher auch nicht so. Bin absolut begeistert und vielen vielen herzlichen Dank für deine Mühe. Ist echt schön das du damals doch nicht alles hingeschmissen hast. Ohne solche Skripte wäre das ganze nicht einmal halb so schön wie mit. Nochmals Danke dafür.

Viele Grüße

Eine kurze Frage hätte ich aber noch was bedeutet das Schalt-Schemata LH  zB bei 6G, Shuttle, LH ?

**Comment by Mogli12** [comment]
Hallo,
vielen Dank fürs positive Feedback. 

LH steht für Low/High. Da wird mit einer Taste zwischen den höheren und tieferen Gängen umgeschaltet. Bei den meisten Getrieben gibt es 12 verschiedene Übersetzungen (z.b. beim 4x4). Mit LH wird dann zwischen den geraden und den ungeraden Gängen umgeschaltet. So hat man mit den 6 festen Gängen einen relative großen Bereich abgedeckt.

Viele Grüße

**Comment by Shreklich** [comment]
Achso also genau das was jetzt sehr gut funktioniert beim Schalten. Vielen Dank für die Erklärung.
