### ISSUE TITLE
Increase/Decrease PTO RPM via keyboard

### ISSUE THREAD

**Issue by SameLaser130** [Mogli12/VehicleControlAddon#200]
Is there a way to increase or decrease handthrottle RPM via keyboard or it's possible to do it only via the ctrl+c menu? Because i can't find any input to assign the key in the keyboard config menu.  Thanks in advance for the reply.

**Comment by Mogli12** [comment]
Currently, this is only possible via the settings menu. I will check if I could add a key combination.

**Comment by Mogli12** [comment]
PTO RPM is not really working well. I will have to look over it.

**Comment by Mogli12** [comment]
Hi,
Please check version 0.0.7.9. There are new action bindings (KEY_minus / KEY_equals) to change hand throttle RPM and (KEY_lctrl KEY_equals) to toggle hand throttle RPM with and without PTO
Best regards

**Comment by SameLaser130** [comment]
Thanks a lot for taking in consideration my wish. Now this mod is simply PERFECT!
Thank you so much. 
Regards.
