### ISSUE TITLE
Vehicle Camera 3rd person

### ISSUE THREAD

**Issue by Snottus** [Mogli12/VehicleControlAddon#203]
Hey Stafan,

First of all thanks a lot for all the great mods you've created over the years, been a permanent part of my modlist since '17.

Anyway, is there any chance you could add a "free camera" mode to this mod?
IE freeing up the camera rotation from the movement of the vehicle when in 3rd person.

There was a mod for it in FS17 (on [ModHub](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=51805&title=fs2017)), but seems no one has converted it to FS19, and my own experience with coding is too low to figure out how to.

**Comment by KCHARRO** [comment]
Any news about this improvement?

**Comment by Mogli12** [comment]
Hi,

There is a new key vcaKEEPROT (insert key). If you press it then the rotation of the camera is fixed to the global rotation.

Regards,
Stefan

**Comment by Caamo** [comment]
Now THIS is AWESOME!
Thank you very, very much, Mogli12.
But... Would it be possible to make it toggleable? I just can't hold the key all the time, and I really, really, really need this.
-Marco

**Comment by KCHARRO** [comment]
AWESOME, thanks, toggleable will be better....

THANKS...

**Comment by Mogli12** [comment]
Hi,
it is toggle-able with version 0.1.2.2. Just press KEY_lctrl KEY_insert

**Comment by Snottus** [comment]
Hey again Stafan,

Just started playing the game again, thank you so very much for your fantastic work!

Is there any chance you could make the free-cam exterior only?
Or add an option to set it exterior-only, and make it a global option?

**Comment by Mogli12** [comment]
Hi,

Sorry, but I think that would be too complex.

Sorry

**Comment by Snottus** [comment]
Aight, well thank you anyway - I wouldn't play the game if not for your mod!
