### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by doc3d** [Mogli12/VehicleControlAddon#205]
If the tractor for some reason stalls, like too low gear up a hill, or trying to pull something heavy in the wrong gear, if it stalls and kills the engine, I cant get it to move again. It is like the handbrake is on and there is no revving of the engine, it just stalls again. This happens until I reboot the game, or if I customize the tractor. After this is works again until I stall it again. 
Im trying to figure out why this happens, but cant seem to figure it out. Have you heard of similar problems before? There does not seem to be any errors thrown in the Log when this happens. 
Edit: I am using version 1.3.0.4

Thank you for a most excellent mod! 

Google Translate:
Wenn der Traktor aus irgendeinem Grund stehen bleibt, z. B. einen Berg hinauf zu niedrig geschaltet ist oder versucht wird, etwas Schweres in den falschen Gang zu schalten, kann ich ihn nicht wieder zum Laufen bringen, wenn er abwürgt und den Motor tötet. Es ist, als ob die Handbremse angezogen ist und der Motor nicht läuft, sondern nur wieder blockiert. Dies geschieht, bis ich das Spiel neu starte oder wenn ich den Traktor anpasse. Danach klappt es wieder, bis ich es wieder hinlege.
Ich versuche herauszufinden, warum dies passiert, aber ich kann es nicht herausfinden. Haben Sie schon von ähnlichen Problemen gehört?

Vielen Dank für einen hervorragenden Mod!

**Comment by Mogli12** [comment]
Hi,

Do you use automatic motor start?

Regards

**Comment by doc3d** [comment]
No automatic start. The engine is running, but it does not react to accellerator or clutch pedal. (I have not tried the keys, I am using pedals). 
I have shifted to neutral and tried to accellerate or clutch -none of them show any signs of working although the display will say "clutch 100%" when I press it. The accellerator gives no feedback at all, no sound change, no rpm change.The RPM is steady at idle. If I select the absolute lowest gears, I can get the tractor to move very slowly and jittery and most times it stalls. From where I sit, it looks like the wheels are not wanting to move, they sort of jitter around, like the parkingbrake is on while trying to move. It doesnt seem to happen with ALL tractors, but the ones I have been using lately all exibit this issue when first stalled. Tested mods are the classic IHC 544-644, the IHC 956-1056 XL, the Ford Pack(not tried ALL, but the ones I have tested have failed) and NH 8670. 
If I bring a toolkit and customize the tractor, it works again, otherwise I have to shut the game down and restart for it to start working again. 
I first thought it might be a conflict with enhanced vehicle mod or simplified controls or ome other mod that alters the behaviour. I tested without these and the issue remains.

**Comment by Mogli12** [comment]
Sorry, but I am not able to reproduce it.

**Comment by pulimatrix** [comment]
Hey moglie, I have the problem Also newest, If I run off the engine or then it is as if a handbrake is put on, resetet Solves the problem configment solves this also, for example, I drive a no gas engine switches off I start, engine but does not go black as if being held: / Can it help Maybe?lg

**Comment by Mogli12** [comment]
Yes, you are in neutral after stalling the engine. So you need to press vcaNeutral (default is KEY_semicolon)
