### ISSUE TITLE
Handbrake after Helper

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#207]
Hi Stefan, when I use the helper and stop the vehicle the handbrake is locked.

**Comment by caplink811** [comment]
I like to admit, this seems to happen only with V0.0.6.3, with V0.0.6.2 myself has no problems. Another point, I don't know if this is realy the handbrake,which locked the tractor. At least there is no optical sign for that. (the other tools I've used are Autodrive 1.0.5.1, and CPV6.01.00294). Also nothing comes up in the logfile.

Beside of this, thanks for this tool/mod.

**Comment by Williwillswisse** [comment]
Hi Stefan, it was a mod conflict with AutoDrive . With the latest version of AD everything is ok.
And thanks a lot for your amazing mods.
