### ISSUE TITLE
Handbremssymbol nach Helfer

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#209]
Hallo Stefan, ich habe heute noch mal rumprobiert. Das Handbremssymbol wird nur angezeigt, wenn Shuttle Control auf EIN steht. Fahre ich ohne Shuttle Control bekomme ich also keinen Hinweis warum ich nicht fahren kann,
Ich habe mal in dein Script vehicleControlAddon.lua reingeschaut, und eine Änderung getestet (siehe Screenshot). Ich weiß nicht ob es die richtige Stelle ist, aber bei mir zieht er jetzt bei dem Giant Getriebe die Handbremse nicht mehr an, Ich fände es praktisch wenn die Handbremse nur bei deinen Getrieben kommen würde, oder vielleicht ein Eintrag in den Settings ob mit oder ohne Handbremse.
![vehicleControlAddon lua](https://user-images.githubusercontent.com/47098121/64814387-a2d89800-d5a3-11e9-9513-c3f6503c4e8f.png)

**Comment by Bandesss** [comment]
Ja diesen Fehler habe ich auch ....

**Comment by Mogli12** [comment]
Entschuldigung, dass ich bei Fehler etwas gereizt reagiere. Aber ein Fehler wäre für mich, wenn massenhaft die log.txt voll geschrieben wird, oder etwas gar nicht funktioniert.

**Comment by Williwillswisse** [comment]
Hallo Stefan, ich habe nicht von einem Fehler gesprochen. Ich finde deine Mods einfach genial und möchte mit meinen bescheidenen Kentnissen nur zur Entwicklung beitragen. Ich habe vollen Respekt vor deinen Arbeiten.

**Comment by Mogli12** [comment]
Ich habe mir folgendes überlegt: Nach dem Ende des Helfers geht das Getriebe in AutoHold. Es soll einfach sicher gestellt werden, dass das Fahrzeug nicht einfach wegrollt. AutoHold es schon länger eingebaut, aber es wurde bislang nicht angezeigt.

**Comment by Bandesss** [comment]
Kein Ding, hätte vergessen das Handbremse Problem erst mit der neuen Version passiert.
Danke für den geilen Mod:)

**Comment by Williwillswisse** [comment]
Perfekt !!! Danke Stefan, das hast du perfekt gelöst. Das AutoHold ist ja noch viel besser als die Handbremse.

**Comment by Mogli12** [comment]
Ich denke, dass wir das Problem schließen können, oder?

**Comment by Williwillswisse** [comment]
Ja, das können wir. Deine Lösung gefällt mir super. Vielen Dank Stefan.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Stefan Biedenstein <notifications@github.com>
Gesendet: Wednesday, September 25, 2019 5:08:22 PM
An: Mogli12/VehicleControlAddon <VehicleControlAddon@noreply.github.com>
Cc: Williwillswisse <c.willen@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [Mogli12/VehicleControlAddon] Handbremssymbol nach Helfer (#209)


Ich denke, dass wir das Problem schließen können, oder?
