### ISSUE TITLE
no more menu access with mod hub tow bar

### ISSUE THREAD

**Issue by denut** [Mogli12/VehicleControlAddon#210]
hello

i have tested the towbar https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=138175&title=fs2019

and with this mod actif left ctrl + c don't open the vca menu

not a big problem i prefer the vca working and no towbar

just to give you the information

**Comment by Mogli12** [comment]
Hi,

Is there a log.txt? Or is there a conflict in input binding?

Regards

**Comment by denut** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/3612614/log.txt)

[inputBinding - Copie (16).txt](https://github.com/Mogli12/VehicleControlAddon/files/3612615/inputBinding.-.Copie.16.txt)

**Comment by denut** [comment]
see no conflict in input binding log towbar mod desactived :
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/3612619/log.txt)

**Comment by Mogli12** [comment]
Hi,
There are several warnings about the CTRL key. I do not fully understand them.
Regards

**Comment by denut** [comment]
me too ...

**Comment by denut** [comment]
but this warning is mot the probelm in this case i think without the tow bar the warning is in the log but no problem to open the vca menu

**Comment by Mogli12** [comment]
Hi,

I think that the problem is inside tow bar. There are multiple forum threads around this mod and it was deleted from Modhub.

Regards
