### ISSUE TITLE
VCA 0.0.6.8 - display of track guides

### ISSUE THREAD

**Issue by caplink811** [Mogli12/VehicleControlAddon#213]
Morning,

with the version VCA 0,0.6.8 myself expirienced a, maybe, strange behaviour of the guiding lines for the track. They show "vehicleControlAddon" instead of the dots, like in the versions before. Indicates this problems, or is this only an advertisment? 

Like to know for clarification.

tia
 JrB

![VCA_1068](https://user-images.githubusercontent.com/49813958/65695897-a4f92700-e078-11e9-8dc2-91b33a9ccf17.png)

**Comment by Mogli12** [comment]
I might change the text in future. But right now it replaces the dots. And the performance should be much better.

**Comment by caplink811** [comment]
thanks for that information, as well as thanks for your mods...

ciao
 JrB

**Comment by Mogli12** [comment]
Did you like the dots more?

**Comment by caplink811** [comment]
hm, that do not depend on dots, when it comes to performance, maybe  dashes, or "x" s are also ok, cause they are symetrical. When you "go" around a vehicle with guides switch on, it looks a little bit odd...

thanks and have a nice weekend
 bye
  JrB
