### ISSUE TITLE
Danke für den Mod und Frage

### ISSUE THREAD

**Issue by TobiAs1995** [Mogli12/VehicleControlAddon#214]
Guten Tag
Wollte mich bedanken für den mod und Den Geabox im 17er.
Eine Frage hätte ich aber. Ich nutze VCA mit einem Controller und würde gerne mit dem KEIN ZURÜCK LENKEN nutzen dies aber ja nur für Keyboard nutzbar ist. Gibt es da eine einstellung oder ist es nicht möglich. Habe schon im 17er Drive Control das Free Steering genutzt und im 19er gibt es nichts vergleichbares als VCA aktuell

**Comment by Mogli12** [comment]
Probier mal Version 0.0.7.1. Man kann das über CTRL+C auch permanent schalten.

**Comment by TobiAs1995** [comment]
Vielen vielen dank^^

**Comment by Mogli12** [comment]
In Version 0.0.7.2 ist es nun so, dass die Mouse nicht mehr automatisch zurück rotiert. Man kann das nur über modSettings/FS19_VehicleControlAddon/config.xml mit dem `<mouseAutoRotateBack type="bool" value="false"/>` ändern.
