### ISSUE TITLE
config.xml 

### ISSUE THREAD

**Issue by evybart** [Mogli12/VehicleControlAddon#215]
the config.xml file is not appering in the modsetting map thanks for the greats mods in the years version 0.6.7

**Comment by Mogli12** [comment]
Modsettings do not appear in the savegame. This is a separate folder in the same directory as the mods folder.

**Comment by evybart** [comment]
yes i know its not in the savegame bud in the map modsettings there is no map config.xml when you load the game with the mod en save the game and look in the map modssettings no config.xml file

**Comment by Mogli12** [comment]
Yes, you can create the config.xml by hand. But it is never created automatically.
