### ISSUE TITLE
Feature um Front-/Heckhydraulik getrennt heben und senken zu können

### ISSUE THREAD

**Issue by oschuhm** [Mogli12/VehicleControlAddon#216]
Hi,
wäre es möglich ein Feature einzubauen mit dem man per Button
- Fronthydraulik
- Heckhydraulik
getrennt voneinander heben/senken kann?
Am einfachten per Tastenbelegung am Joystick.

Ebenso wäre es toll wenn man die Geräte an Front- und Heckhydraulik über eine Tastenbelegung (auch am Joystick) getrennt voneinander aktivieren / deaktivieren kann.

Würde mich freuen wenn man soetwas noch einbauen könnte.

VG
Oliver

**Comment by Mogli12** [comment]
Hallo Oliver,

da gibt es doch schon https://www.modhoster.de/mods/vereinfachte-steuerung.

Viele Grüße,
Stefan

**Comment by oschuhm** [comment]
Danke für den Hinweis. Das hatte ich noch gar nicht gesehen.
