### ISSUE TITLE
VCA V0.0.77 freies lenken on/off

### ISSUE THREAD

**Issue by caplink811** [Mogli12/VehicleControlAddon#218]
within the version 0.0.7.7 the switch "freies lenken" on or off show no different behaviour (the steering never comes back to neutral). This isn't the same as in at least V0.0.7.1 (there the steering comes back to neutral).

This is intentional behavior, or an error? 

thx
JrB

**Comment by Mogli12** [comment]
Mouse, keyboard, gamepad or steering wheel?

**Comment by caplink811** [comment]
Oops, sry.... Only using a keyboard.
--
Ciao JrB

**Comment by Mogli12** [comment]
At what speed are you driving? Below 4 km/h the auto rotate back is disabled. It might be that I increased this limit a little. Above 4 km/h auto rotate back is delayed by up to one second after steering. I felt that this makes it easier to drive a curvy road. I tested it with keyboard and the MAN truck in Felsbrunn.

**Comment by caplink811** [comment]
Admittedly, I'd tried only on the farm yard, so I assume, with speeds < 10, when I felt the different behaviour on low speed. The 2nd you admit sounds like an advantage, but the 1st isn't one (in my opinion). When it works as designed, then it isn't a bug. 

Any chance for a config switch between old and new behaviour (for low speed)?

thx and ciao
JrB

**Comment by Mogli12** [comment]
Hi JrB.

Auto rotate back was always off if the vehicle did not move. 

BR

**Comment by caplink811** [comment]
of course...

Adaptive steering set to off is nearly on the old behaviour, which meet my needs. Assuming I lost some other benefits, but I'll find out.

thanks agai for this mod, I'll go ahead, and close this issue

bye JrB

**Comment by jhomer** [comment]
I also recently noticed this.
I'm using a gamepad (xbox 360).
I notice the delay when traveling at higher speeds which makes it pretty easy to lose control from one side to the other. Feels kind of like you're overcompensating steering back and fourth. Steering with a controller I'm usually more or less just flicking the joystick side to side.
I never steer with keyboard so I have no idea how that goes.
But like @caplink811 said, turning adaptive steering off solves the issue.

**Comment by Mogli12** [comment]
Is the controller analog?

**Comment by jhomer** [comment]
I'm not 100% sure what analog is but from what I look up it is. 
The stick has 360 degree rotation (y-,y+,x-,x+) and the further you push the stick to left or right the further the steering angle.

**Comment by Mogli12** [comment]
This is an analog controller. The main purpose of enhanced steering is to make steering with keyboard or digital controllers easier.
