### ISSUE TITLE
Erweiterung: Vereinfachtes Vario Getriebe

### ISSUE THREAD

**Issue by Mantikor83** [Mogli12/VehicleControlAddon#219]
Hi Mogli, 
zu aller erst möchte ich mich bei dir bedanken! Deine Arbeit im besonderen mit dem GBA ist wirklich beeindruckend. Ich kann aber auch vollends verstehen, dass du mit dem LS19 einen neuen Weg eingeschlagen hast und ich muss nach anfänglicher Skepsis sagen, du hast recht gehabt. Ich war ein großer Fan des GBA und konnte mir zuerst nicht vorstellen ohne zu spielen. Nach nun vielen vielen Spielstunden mit VCA muss ich aber sagen, dass dir ein wirklich sehr sehr guter Kompromiss gelungen ist!

Zu meinem Anliegen, ich setze im Spiel primär Fendt Schlepper ein, die bekannter Weise auf Vario Getriebe setzen. Für die 1000er Serie habe ich da mit dem VCA keine Schwierigkeiten, da das IVT Getriebe mir "nah genug dran ist" am neuen Vario Getriebe. Für die alten 700er und 900er Schlepper fehlt allerdings ein IVT Getriebe mit zwei Ranges, oder eben das PKW Getriebe ohne Unterbrechung beim schalten. Da ich mit Sicherheit nicht der einzige Fendt Fahrer im LS19 bin wollte ich anregen, ob du uns nicht auf die eine oder andere der genannten Arten mit relativ geringem Aufwand mit einem Vario Getriebe beglücken könntest? Vielleicht ist das ja möglich!

Vielen Dank und Grüße,

Manti

PS: KeyBindings für das durchschalten der Handgasstufen wäre wirklich mega! Das ist keine verschwendete Entwicklungszeit ;)

**Comment by Mogli12** [comment]
Hallo,

Probier mal Version 0.0.8.1. Dort gibt es beim IVT Getriebe auch einen Low-Range

Viele Grüße

**Comment by Mantikor83** [comment]
Hallo Mogli,
vielen Dank für das Update, ich hatte jetzt nur eine halbe Stunde Zeit zu testen, deswegen ist der Testfallkatalog noch nicht vollständig. Da ich aber erst am Sonntag dazu kommen werde weiter zu machen schon mal ein Feedback für dich.

Generell tun die low und high Range des IVT was sie sollen. Ich habe mit den 900er Varios und den JD 6R aus dem vanilla Spiel getestet. In beiden Fällen ermittelt das Getriebe korrekt die Geschwindigkeit für das High und das Low Setting. Auch der Wechsel der Getriebestufe funktioniert reibungslos (auch während der Fahrt, aber das der Realität anzupassen für nur im Stillstand war ja auch kein Teil der User-Story). Ebenfalls in Ordnung ist die Anpassung des Drehmoments/der RPM zum jeweiligen Geschwindigkeitsband. Beim Vario liegt bei ca. 2100 RPM das volle Drehmoment an, er zieht die maximale Last. Geht man z.B. mit dem Handgas auf 2200 RPM hoch sackt die Leistung weg. Soweit Daumen hoch, passt (sprach der Typ der nie im Leben nen echten Vario gefahren ist^^).

Was mir aber aufgefallen ist, es gibt einen merkbaren RPM Sprung, der eigentlich nicht erklärbar ist, wenn man folgendes tut (tritt bei allen Schleppern mit IVT auf, bei FullPowerAutoshift z.B. konnte ich es nicht reproduzieren): Fahre den Schlepper bei mehr als 1200 rpm, bremse den Schlepper, bis die Haltestellung (A) anspringt und die RPM Nadel bei ca. 1000 RPM das erste mal zur Ruhe kommt, nicht warten bis sie auf 800 RPM runter geht, dass tut sie ein paar Sekundne später. Beschleunige den Schlepper dann wieder. Die Nadel springt dann unmittelbar von ca. 1000 RPM rauf auf ca. 1200 RPM, sackt kurz ab und dann entwickeln sich die RPM wieder normal. Das gleiche Phänomen tritt auf, wenn man relativ hochtourig aus dem Rückwärtsgang direkt in den Vorwärtsgang wechselt, auch dann sacken die RPM kurz weg, springen hoch und entwickeln sich dann wieder normal. Maybe its a bug, maybe a feature. 

Ich werde Sonntag nochmal ausführlicher mit den Mods Courseplay und GPS testen. Sollte mir da noch etwas auffallen vom Verhalten her poste ich es. 

Ach ja, in der Log sind weder Warnings noch Errors bei mir aufgetaucht ;) aber ich denke das hast du vorher auch getestet.

Nochmal vielen Dank und Grüße,

Manti

**Comment by Mantikor83** [comment]
Hallo Mogli,
hier mein versprochenes finales Feedback:

- Veränderung läuft auch mit CP und GS ohne Probleme
- Wenn Auto-Clutch abgeschaltet wird lässt sich die Range des IVT nicht mehr ändern, ich bin mir nicht sicher, ob Bug oder Feature
- Speed-Limiter Wert Gear-Speed-To wird derzeit im LOW Band genau halbiert, scheinbar rechnet das Script da mit der gleichen Routine, die dann zweimal aufgerufen wird, einmal für das Low-Range-Band und einmal wenn man den Speed-Limiter setzt. Eine einfache if Abfrage sollte Abhilfe schaffen.
- Dann hatte ich noch einmal einen Bug, den ich bisher leider nicht reproduzieren konnte. In Verbindung mit einem laufenden Motor habe ich die Getriebe Arten durchgeschaltet über das Menü. Am Ende hat der Schlepper im IVT nicht mehr über 5Km/h hinaus beschleunigt (die RPM gingen auch nicht hoch), erst Spielstand Neustarten hat Abhilfe geschafft. Aber wie gesagt, ich kann den Bug nicht reproduzieren. Ich melde mich nochmal, wenn ich es schaffen sollte. 

Bis hier hin aber erstmal vielen Dank! Tolle Erweiterung!

**Comment by Mogli12** [comment]
Danke fürs Feedback. ich werde es mit der nächsten Version wahrscheinlich korrigieren.

**Comment by Mogli12** [comment]
Hallo,

die Punkte 2 und 3 sollten mit Version 0.0.8.2 behoben sein.

Viele Grüße

**Comment by Mantikor83** [comment]
Alles klar, ich teste erneut. Falls du noch andere Sachen hast, die du getestet haben möchtest kannst du mir gerne eine Nachricht schicken. Wenn es dir hilft investiere ich die Zeit gerne, quasi als kleine Unterstützung.

**Comment by Mantikor83** [comment]
Hallo Mogli,
Test ist abgeschlossen. Die beiden oben genannten Punkte funktionieren nun. 

Dafür habe ich etwas neues gefunden:

- 90% PTO scheint keinen Effekt mehr zu haben, bei keinem Getriebesetting (IVT, FullPower, etc. das war meine ich in der letzten Version noch in Ordnung)
- Wenn der SpeedLimiterTo gesetzt wird, dann werden die RPM nicht mehr korrekt ermittelt, braucht ein schlepper z.B. mit IVT Getriebe ca. 1400 RPM um eine Geschwindigkeit von 8Km/h zu halten braucht er mit gesetztem SpeedLimiter nahezu immer volle RPM. 
- Richtig witzig wird es wenn dann noch das Handgas dazu kommt. Sagen wir ein Schlepper fährt ohne Handgas bei 1400 RPM 8Km/h, wir setzen dann das Handgas auf 1200 RPM, dann geht er auch auf 1200 RPM runter und hält die Geschwindigkeit (ab einem bestimmten kritischen Wert bei der RPM im Handgas fällt die Geschwindigkeit natürlich), kommt nun noch der Speedlimiter dazu jagt er sofort wieder hoch auf Max. RPM. Was ich sagen möchte, wenn es einem Fahrzeug möglich ist mit einer MinRPM eine Geschwindigkeit X zu fahren, dann sollte diese Geschwindigkeit doch im selben Verhältnis zur RPM stehen, wie wenn die RPM über das Handgas gesteuer ist oder irre ich da? Wie dem auch sei, es scheint jedenfalls einen Unterschied bei der Berechnung des IVT zwischen Handgas und Gaspedal zu geben :D ich kanns sonst auch gerne mal als Video aufnehmen und hochladen.

Grüße,

Manti

**Comment by Mantikor83** [comment]
Nachtrag: Handgas 90% hat nur keinen Effekt, wenn der Neutralmodus A anliegt, ist der Schlepper in Bewegung funktioniert Handgas 90%. Handgas 100% und ECO funktionieren auch, wenn A anliegt.
