### ISSUE TITLE
Fahrzeug rollt wieder von alleine los, sobald man von der Bremse geht

### ISSUE THREAD

**Issue by geo-luchs** [Mogli12/VehicleControlAddon#220]
Hallo

ich habe die Version 0.0.7.9 , und vorher auch 0.0.6.9.
Wenn ich mit einem Fahrzeug fahre, dann bremse und anhalte, rollt das Fahrzeug von allein wieder los (ganz langsam).

Nur, wenn ich etwas länger auf der Bremse stehenbleibe, bleibt dsa Fahrzeug auch danach stehen.
Es reicht nicht, das Fahreug einmal zum Stillstand zu bringne. Gefühlt würde ich sagen, muss ich 2-3 Sekunden auf der Bremse stehenbleiben.

geringere Bremskraft steht auf 100%, also er bremst wirklich schnell und direkt.

Aber das langsame Losrollen kann damit nicht verhindert werden.

**Comment by Mogli12** [comment]
Hallo,

das ist Absicht. Man muss 1-2 Sekunden auf der Bremse bleiben. Dann ändert sich auch des Symbol über dem Tacho. Man kann auch die Neutral-Taste betätigen.

Viele Grüße

**Comment by geo-luchs** [comment]
Hallo

Danke für die Info.
OK, wenn ich manuell fahre, muss ich halt etwas drauf bleiben.

Allerdings spiele ich auch mit AD- Autodrive.
Da sieht es dann wohl so aus, dass AD den Zielpunkt erreicht, und abbremst, aber das Fahrzeug danach leicht weiterrollt.

Hast Du Kontakt zu dem Stephan, der Autodrive programmiert?
Gibt es eine Möglichkeit, dass er am Ende über LUA aktiv eine Bremsung von 2 Sekunden macht?
Bzw. könnte dein Mod erkennen, wenn das Fahrzeug über Autodrive gesteuert und abgebremst wird?

**Comment by plexten** [comment]
Hallo Stefan,
danke für die schöne Mod es bereichert das Spiel ungemein und ist nicht mehr wegzudenken.
Wo im Script kann ich denn die 1-2 Sekunden die ich auf der Bremse bleiben muß verkürzen?
Grüßle plexten

**Comment by Mogli12** [comment]
@geo-luchs Sitzt Du im Fahrzeug, wenn sich AutoDrive beendet? Welches Getriebe hast Du gewählt? IVT? AutoDrive sollte doch auch über den Helfer funktionieren, oder. Dann sollte eigentlich onAIEnd gerufen werden und automatisch AutoStop einschalten

**Comment by Mogli12** [comment]
@plexten: Wenn Du nur das stufenlose Getriebe verwendest, dann kannst Du ja alternativ Getriebe "off" verwenden. Das ist auch stufenlos. Die AutoStop-Zeit ist momentan nicht konfigurierbar.

**Comment by plexten** [comment]
> 
> 
> @plexten: Wenn Du nur das stufenlose Getriebe verwendest, dann kannst Du ja alternativ Getriebe "off" verwenden. Das ist auch stufenlos. Die AutoStop-Zeit ist momentan nicht konfigurierbar.

Danke Stefan, habe jetzt das Getriebe auf "off" gestellt.

**Comment by geo-luchs** [comment]
> 
> 
> @geo-luchs Sitzt Du im Fahrzeug, wenn sich AutoDrive beendet? Welches Getriebe hast Du gewählt? IVT? AutoDrive sollte doch auch über den Helfer funktionieren, oder. Dann sollte eigentlich onAIEnd gerufen werden und automatisch AutoStop einschalten

Hi

habe das Getriebe IVT.
Wenn ich im Fahrzeug sitze, bremst er am Zielpunkt ab, und rollt dann langsam weiter.
Stehe ich daneben, hält der Traktor ordnungsgemäß am Zielpunkt an.

Auf was kann das hindeuten? Wo könnte der Unterschied sein zwischen im Fahrzeug sein und außerhalb?

**Comment by geo-luchs** [comment]
mit Getriebe Off stoppt er auch, wenn ich IM Fahrzeug bin.

Was ist die Auswirkung, ob ich mit IVT oder Getriebe Off fahre?

**Comment by Mogli12** [comment]
Ist es mit Version 0.0.8.0 besser? 

Der Unterscheid zw. Getriebe "off" und "IVT" ist nur, dass die Drehzahl anders moduliert wird. So geht der Motor bei hoher Last auf Nenndrezahl, um dann erst bei voller Last runter auf die Drehzahl mit Maximalleistung geht (->Drückung).

**Comment by geo-luchs** [comment]
Hallo Stefan

deine 0.0.8.0 war gar nicht nötig.
Ich hatte Stephan vom Autodrive deinen Hinweis mit dem onAIEnd genannt. Hat er eingebaut, und nun klappt es auch mit Autodrive  und deinem IVT.

Somit kann ich nicht sagen, ob deine letzte Änderung zwingend notwendig ist, oder ob Du sie wieder rausnehmen kannst? ;-)

Hab jetzt auch deine 0.0.8.0 hinzugenommen. Zumindest ist mir in dieser Kombination mit der Autodrive-Änderung nichts Negatives aufgefallen.

Danke für deinen guten und schnellen  Support

Viele Grüße
Carsten
