### ISSUE TITLE
Grundeinstellung der Linienanzeige

### ISSUE THREAD

**Issue by CupGTI** [Mogli12/VehicleControlAddon#221]
Hi, ist es möglich die Grundeinstellung der Linienanzeige zu verändern? Sprich von "nur anzeigen wenn inaktiv" auf "aus". Wenn einmal "GPS" genutzt wurde, werden die Linien nach jedem Neustart des Spiels dann eingeblendet, weil die Einstellung auf "nur anzeigen wenn inaktiv" springt. Generell "aus" und dann erst auf dem Acker umstellen wär denk ich etwas schöner nach dem Neustart.

**Comment by Mogli12** [comment]
Hallo, mit Alt-W sind die Linien und die Einstellung weg. Im Menu kann man die Linien auch ganz ausschalten.

**Comment by Powerbrille77** [comment]
Hallo Mogli12 

Ist es machbar die beiden äusseren Linien in einer anderen Farbe zu machen so das man immer die Mitte leichter findet.

**Comment by Mogli12** [comment]
Aktuell wird im laufenden Betrieb nur die Mittellinie angezeigt.
