### ISSUE TITLE
Lenkungsgeschwindigkeit

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#222]
Moin, das erste mal seit 3 Monaten Fs mal. wieder angeschmissen und auch VC aktualisiert.
Ich muss sagen, ich komme mit der schnelleren Lenkung bei langsamer Geschwindigkeit, die Lenkung sich erst ab 4 km/g zurueckstellt und der Sekunde Verzögerung bei schnellerer Fahrt gar. Nicht zurecht, sei es bei Rangier-oder FL-Arbeiten oder bei langsamer Feldarbeit.... deshalb die Frage, ob man das in def config irgendwo wieder zurueckstellen kann, so wie es "immer" war?

Schoene Gruesse 
Claudio

**Comment by Mogli12** [comment]
Du kannst die adaptive Lenkung im Menü (Strg+C) ausschalten.

**Comment by cabmac** [comment]
Jo.. ist mir. klar... ich wuerde die aber gerne vor der Modifikation, so wie das in den letzten Versionen war, haben.. also weniger schnell bei kleiner Geschwindigkeit, und ohne die "Gedenksekunde".., wird aber wohl nicht mehr gehen...

**Comment by Mogli12** [comment]
Hallo Claudio,

was ist denn Dein größtes Problem derzeit. Das Zurücklenken habe ich absichtlich verlangsamt, damit die Fahrzeuge in den Kurven nicht so sehr wackeln. Du brauchst aber nur einmal kurz in die andere Richtung zu Lenken und dann geht Zurücklenken sofort und mit voller Geschwindigkeit.

Die Lenkgeschwindigkeit bei niedriger Geschwindigkeit benötigt eventuell noch etwas Feinschliff. ich wollte aber bei Wendemanövern möglichst flott von Anschlag zu Anschlag Lenken, auch wenn das nicht sehr realistisch ist.

Zur Erklärung: Beim Fahren auf der Straße drücken ich die Tasten A und W immer nur kurz und dafür mehrfach hintereinander. Daher wird die Lenkung schneller, je länger man auf die Taste drückt.

Viele Grüße,
Stefan

**Comment by cabmac** [comment]
Hallo,
also generell gesagt ist die Lenkung bei hoher Geschwindigkeit sehr gewöhnungsbedürftig, diese "Sekunde", die die Lenkung braucht um wieder langsam zurueckzugehen reicht gerade, um mich in den nächsten Zaun zu befördern.. 😆.. wie gesagt, evtl gewöhnungsbedürftig und bekommt man wohl in den Griff...k. A. 
An die Lenkung bei niedriger Geschwindigkeit kann ich mich allerdings garnicht gewöhnen, bei Rangier-oder FL-Arbeiten ist die Angelegenheit mir persönlich einfach zu schnell bzw. zu nervös und macht das Arbeiten unpräzise. Nun in Verbindung  das Lenkung garnicht mehr "zurueckgeht" bis 4km/h,dann komme ich z. B. beim Paletten oder Ballen verladen auf einen Hänger garnicht mehr zurecht.
Vielleicht hängt das auch an mir, aber als Tastaturfahrer hat mir das "alte" System wesentlich bessere gefallen. 

Schoene Gruesse, 
Claudio

**Comment by Mogli12** [comment]
Hallo Claudio,

es wird sofort bei hoher Geschwindigkeit zurückgelenkt, wenn man nur kurz die Taste für die andere Richtung antippt. Wenn man also mit A nach links gelenkt hat, dann muss man nur im richtigen Moment die Taste D drücken und es wird sofort zurückgelenkt. Ich kann so mit der Tastatur auch langgezogenen Kurven flüssig fahren.

Viele Grüße,
Stefan

**Comment by cabmac** [comment]
Hallo....hmm, irgendwie laeuft das jetzt bei weitem besser, aber keine A. warum...die 4km/h Sache hast du abgestellt, richtig?

**Comment by Mogli12** [comment]
Ich habe die Geschwindigkeit, ab der automatisch zurück rotiert wird, von 4 km/h auf 1 km/h reduziert

**Comment by cabmac** [comment]
ich werds heute Nachmittag nochmal ausführlich testen, aber so scheint das gut zu gehen....

**Comment by cabmac** [comment]
So, heute mal ein bisschen rumprobiert...so denke ich kann man sich daran gewoehnen wenn mann das mal raushat mit dem zurueckrotieren....dass du das auf 1km/reduziert hast ist auch sehr viel besser, bei FL-hatte mich das enorm gestoert....

schoene Gruesse,

Claudio
