### ISSUE TITLE
Duchdrehende Räder / Reifen 

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/VehicleControlAddon#224]
Hallo,

mir ist aufgefallen. wenn man die Automatik deaktiviert, ein Getriebe wählt (z.B. 4x4) und dann an langsam fährt, also die Bremse immer wieder betätigt und löst (um z.B. Ballen zu laden), dass dann öfters die Reifen im Stand eine komplette oder halbe Drehung machen. Meistens ist es ein Rad an der Vorderachse, sehr selten ein Hinterrad. Ist kein funktionelles Problem, eher visuell, fällt besonders bei Traktoren ohne Kotflügel auf.
Problem habe ich im SP bemerkt, es tritt auch ohne weitere Mods auf.

**Comment by Mogli12** [comment]
Hallo,

ja, das habe ich auch gesehen. Ich denke nur nicht, dass ich das ändern kann. Die Kupplung wird ja nur simuliert. Eigentlich ist es weiterhin das stufenlose Getriebe, nur das nicht mehr als x Nm Drehmoment übertragen werden können. Daher kann das Durchdrehen eigentlich nicht kommen.

Viele Grüße

**Comment by Evilman2517** [comment]
Liegt es eventuell an dem selbst anfahren, wenn die Kupplung noch nicht getrennt ist? Wirkt immer so, als würde das Rad gerne los fahren, es das aber noch nicht darf / kann

**Comment by Mogli12** [comment]
Vielleicht gibt die Leerlaufanreicherung am Anfang zu viel Gas.

**Comment by Evilman2517** [comment]
Vielen Dank, dass du da nochmal nachschaust.

**Comment by Evilman2517** [comment]
Vielen Dank, es ist jetzt schon deutlich besser geworden, einzig, bei Steigungen oder großem Lenkeinschlag ist es noch zu beobachten. Vielen Dank nochmal , dass du dich dem angenommen hast.

**Comment by Mogli12** [comment]
Viele Dank fürs Feedback!
