### ISSUE TITLE
Fehler übersetzung

### ISSUE THREAD

**Issue by Bandesss** [Mogli12/VehicleControlAddon#225]
Hallo ich bekomme die Warnung mit der neuesten Version 
Warning: Missing l10n 'input_vcaHandRpm_1'
  Warning: Missing l10n 'input_vcaHandRpm_2'

Wie kann ich die Beheben ?
[log.zip](https://github.com/Mogli12/VehicleControlAddon/files/3775594/log.zip)

**Comment by Mogli12** [comment]
Hallo,
das ist bereits mit Version 0.0.8.1 behoben.
Viele Grüße
