### ISSUE TITLE
PowerShift Getriebe defekt

### ISSUE THREAD

**Issue by Mantikor83** [Mogli12/VehicleControlAddon#227]
Guten Morgen,
heute habe ich aus versehen mal ein nicht IVT Getriebe gefahren, es scheint als wenn alle PowerShift Getriebe derzeit ein Problem haben. Nicht betroffen sind scheinbar alle IVT und manuellen Schaltgetriebe.

Wechselt man per Shifter die Fahrtrichtung setzt sich das Getriebe fest und es läuft danach nur noch in die zuletzt gefahrene Richtung. Die jeweils andere Richtung verursacht dann ein Ruckeln der Reifen, Hinterachse dreht Rückwärts, Vorderachse dreht vorwärts. Getestet wurde das ganze auf Vanilla Schleppern auf Vanilla Maps ohne weitere Mods. Vielleicht aber hilfreich, wenn ich das TSX Script dazu nehme lässt sich durch schalten des Alradantriebs das Getriebe kurzzeitig wieder gangbar machen, allerdings nur bis man wieder wenden möchte/muss.

Das Problem habe ich bei Versionen <8.0 nie gehabt, irgendwas muss also danach geschehen sein, allerdings ist in der Zeit auch der neue Patch erschienen.

Grüße,

Manti

**Comment by Shreklich** [comment]
Hallo schau mal bitte nach ob du auch die Gänge vorwärts und rückwärts belegt hast. Du musst die Gänge 8 und 9/rückwärtsgang nicht belegen. Hatte das selbe Problem gehabt. Danach sollte alles gehen.

**Comment by Mantikor83** [comment]
Das funktioniert tatsächlich! :D Wo ist denn bitte da die Logik? xD

**Comment by Shreklich** [comment]
Dein Stifter hat doch nur 6Gänge plus Rückwärtsgang. Das Skript ist aber für viele verschiedene Shiftmodis ausgelegt. Denke mal hier liegt die Logik. Aber schön das es jetzt funktioniert.

**Comment by Mantikor83** [comment]
Ich habe nur gar keinen Shifter angeschlossen :D hatte die Gänge lediglich auf der Tastatur (KeyPad) belegt, falls ich sie doch mal brauche. Eigentlich bin ich immer mit automatischen Getrieben unterwegs. Aber ja, gut das es nun funktioniert. Dank dir!

**Comment by Shreklich** [comment]
Kein Problem dann mal ein frohes Ackern weiterhin.
