### ISSUE TITLE
Low/High Range wechselt automatisch

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#230]
Hallo Mogli,
ich habe beim letzten mal davon berichtet das die Range nun auch beim Schalten bestehen bleibt funktioniert aber irgendwie doch nicht so richtig, gemeint ist also das ich die Gänge von 1-6 schalten kann und dann die Gänge in L bleiben aber es wechselt ständig automatisch zu H wenn ich hoch oder runterschalte. Ich hatte damals noch die Version 8.1 gehabt wo es meiner Meinung nach funktioniert hatte bin jetzt zur Version 8.4 gewechselt und dabei ist mir das aufgefallen. Ich habe dann nochmals zur Version 8.1 gewechselt aber auch da funktioniert es nicht mehr oder hat auch vorher nicht funktioniert bin mir da jetzt echt nicht mehr sicher. Meine Frage ist nun ob das so gewollt ist das automatisch beim Schalten von Low zu High gewechselt wird? Und wenn nicht ob du dir das vllt nochmal ansehen magst ob man daran etwas ändern kann. Eigentlich ist es nur beim Rangieren interessant da man so ständig die Range wechseln muss nur weil man mal in den Rückwärtsgang geschaltet hat. Es geht sich bei mir persönlich um das 2x6 Getriebe Schaltmodus 6G, 1R, LH. Nutze das G27 mit 6Gang Shifter.
MfG Thorsten

**Comment by Mogli12** [comment]
Hallo Thorsten,
tritt das Problem in der aktuellen Version 0.0.9.1 immer noch auf?
Viele Grüße

**Comment by Shreklich** [comment]
Ja ist leider immer noch so. Aber vllt habe ich auch irgendwas falsch eingestellt. 
Shuttle Control : An
Getriebe : 2x6
Automatik : Aus
AutoClutch : Aus 
Gear Shifter Mode : 6G, 1R, LH
Hoffe es hilft dir weiter. Und vielen Dank schon mal für deine Mühe.

**Comment by Mogli12** [comment]
Hallo,
ich kann das leider nicht nachvollziehen. Mit den Tasten für die Gänge 1 bis 6 wird ganz normal von 1+ (H 1) bis 6+ (H 6) bzw. 1- (L 1) bis 6- (L 6) durchgeschaltet.
Viele Grüße

**Comment by Shreklich** [comment]
Also in der Gruppe H funktioniert es auch schalte ich jetzt G1 in der Gruppe L danach in G2 schaltet er automatisch in G2 H und nicht in G2 L. Also die Gruppe Low geht beim Hochschalten also Gangwechsel immer in High über und muss dann wieder die Gruppe separat Wechsel auf low wenn ich diese Gruppe nutzen will.

**Comment by Mogli12** [comment]
Wie genau schaltest Du denn? Ziffernblock? G27? Was ist mit der Kupplung?

**Comment by Shreklich** [comment]
Kupplung ist über das Pedal also als axis ausgelegt. Und schalten über den Shifter vom G27 hat 6 Gänge plus einen Rückwärtsgang. Eigentlich nutze ich zum normalen fahren die Gruppe H. Beim rangieren würde ich aber gern die Gruppe L nutzen und muss dann beim Wechseln von G1 L in den Rückwärtsgang wieder die Gruppe zurück schalten weil er mir beim Rückwärtsgang einlegen die Gruppe in H einstellt.

**Comment by Shreklich** [comment]
Ich hoffe mal ich erkläre es nicht zu kompliziert. Ganz einfach gesagt ich kann die Gänge in der Gruppe H von Gang 1 bis 6 schalten ohne Probleme. Ich kann aber nicht in der Gruppe L die Gänge 1-6 Hochschalten muss dann immer wieder die Gruppe von H in L zurückwechseln.

**Comment by Mogli12** [comment]
Und wie hast Du die Gruppe gewechselt? Mit der Taste "VCA: G27/G29 Gang Splitter" oder mit "VCA: Gruppe runter"?

Die Idee war, dass der Ganghebel mit allen Getrieben funktioniert? Es werden immer die obersten 12 Gänge geschaltet. Von den oberen zu den unteren 6 Gängen kommt mit mit "VCA: G27/G29 Gang Splitter".

Die "normalen" Tasten für Gang- und Gruppenwechsel schalten dann wieder vom G27-Modus in den normalen Modus.

**Comment by Shreklich** [comment]
Ich habe die Gruppe hoch und Gruppe runter über zwei Tasten belegt vllt ist das mein Problem. Ich muss das mal testen nur bin ich noch unterwegs.

**Comment by Mogli12** [comment]
Ja, man schaltet entweder über Gang hoch/runter und Gruppe hoch/runter oder mit Gang 1-6 plus Splitter. Beides zusammen funktioniert leider nicht.

**Comment by Shreklich** [comment]
So also ich habe es nun nochmal getestet mit dem Splitter bleibt und wie du geschrieben hast bleibt er in der jeweiligen Gruppe. Damit komme ich zurecht. Beim 4x4 Getriebe kann man so natürlich nicht die 4 Gruppen schalten aber alles gut das 4x4 nutze ich auch nur extrem selten. Vielen Dank dir schon mal für deine Mühe und Geduld.

**Comment by Mogli12** [comment]
Hallo,

Du kannst auch die "4G, R+/-, Shuttle" oder "6G, R+/-, Shuttle" verwenden. Bei "4G, R+/-, Shuttle" hast Du 4 Gänge, die Positionen 5 und 6 schalten Gruppe hoch bzw. runter und die 7. Position kehr die Fahrrichtung um. Bei "6G, R+/-, Shuttle" ist halt alles um 2 verschoben.

Nur das mischen der klassischen Tasten mit den G27/G29 Tasten klappt nicht.

Viele Grüße
