### ISSUE TITLE
Einfach mal danke sagen!

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#232]
Hallo @Moglie12, 

ich bin leider erst sehr spät auf den Gearbox aufmerksam geworden und muss sagen das es auf dem LS17 nen bleibenden Eindruck hinterlassen. Und hier im LS19 als VCA schon richtig gut läuft. Für deine Arbeit deine Mühen und fürs teilen möchte ich mich bei dir bedanken. 

Das war auch der einzige Grund für mich hier im Github angemeldet zu sein und hoffe das du weiterhin am Ball bleibst. 

Kleine Zwischenfrage wo in der XML finde ich die Codezeilen für den Kompass, würde es gerne abschalten wollen. Da ich nen kein überladenen HUD brauche. 

Ausserdem lässt der VCA den gräßlichen Sound der Traktoren etwas humaner wirken und hoffe echt die bringen die Soundengine aus dem LS17er hier rein.

**Comment by Mogli12** [comment]
Hallo,

Du kannst das HUD über die Settings (Ctrl+C) ausschalten. Der Schalter ist in der linken Spalte unten. Den Standard kannst Du auch zentral umstellen. Dazu musst Du im modSettings Order einen Unterordner FS19_VehicleControlAddon anlegen. Eine Vorlage findest Du hier im Github [](https://github.com/Mogli12/VehicleControlAddon/tree/master/modSettings/FS19_VehicleControlAddon).

In dieser config.xml in den modSettings kannst Du den Schalter drawHud auf "false" stellen.

Viele Grüße und vielen Dank fürs Feedback

**Comment by Bomberman82** [comment]
Super danke für den Tipp. Und viel Erfolg weiterhin.

**Comment by Bomberman82** [comment]
Danke nochmals, fürs updaten, das Addon wird immer besser und besser. Ohne dein Addon läuft es nicht mehr. 

Zwischenfrage @Mogli12, du hast nicht mit Balu aus dem Modhoster zu tun oder?
