### ISSUE TITLE
HUD to show km/h or mph?

### ISSUE THREAD

**Issue by jhomer** [Mogli12/VehicleControlAddon#237]
Hello Mogli,
This is not a big deal but for the few non metric folks.
When I download an update of your mod I usually replace line 1923 of vehicleControlAddon.lua:
text = text .." "..string.format(" %3.0f km/h",maxSpeed )
with:
local maxSpeed2 
maxSpeed2 = maxSpeed*0.621371
text = text .." "..string.format(" %3.0f mph",maxSpeed2 )

Just wondering if it could be implemented somehow?
I would try and do a pull request but I don't have much knowledge with this.
Not sure how it could check for language in the script or maybe something it could check for in the config.xml in mod settings?
No big deal if you want to implement it, just thought I'd mention it.
Thanks either way!

**Comment by Mogli12** [comment]
Hi, 
Please check the latest version.
Best regards

**Comment by jhomer** [comment]
All good! I noticed the VCA menu is also changed!
Thank you!!
