### ISSUE TITLE
Drezahl geht im Stand nicht mehr. 

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#238]
Hallo Mogli12, 

dein letztes Update hat bewirkt das es keinen Beschleunigungssound mehr gibt wenn man im Leerlauf ist in den vorigen Updates ging das noch also Leerlauf schalten und den Motor aufheulen lassen.

gruß 
Bomberman82

**Comment by Mogli12** [comment]
Hallo,

Ah, vielen Dank. Ich habe mich so sehr auf ein besser klingendes Anfahren mit der Tastatur konzentriert, dass ich das nicht mehr getestet habe.

Viele Grüße

**Comment by Bomberman82** [comment]
Kein Problem, der VCA ist noch der einzige Grund warum ich LS19 noch spiele. Schade das Giants zum Thema Sound absolut schweigt. 
Nicht das ich jetzt alles vom LS19 schlecht Reden will aber beim alten Soundguru im LS17 (@Sevorane) hat man noch die gewisse Leidenschaft an der Arbeit gespürt. Und das sah man auch in seinen Interviews. 

Eine Frage: Gibt es hier im Github so etwas wie eine "Changelog" wo man die Verbesserung/Änderungen/Update so erklärt. Mir sagen leider XML-Codes nicht besonders viel???. 

Ich wünsche dir auf jedenfall weiterhin viel Erfolg mit dem VCA und auch anderen Arbeiten und freue mich immer wieder etwas neues von dir zu hören :)

**Comment by Mogli12** [comment]
Warum der Sound so schlecht ist, kann man am besten am Deutz 6.61 beobachten. Der Sound ohne Last und unter Volllast haben eine andere Tonhöhe. Das klingt mit VCA schon etwas komisch, wenn man vom Gas geht. 

Im LS17 hatte derselbe Traktor dagegen einen recht kernigen Klang. Das war einer der Fahrzeuge, die ich am liebsten mit Getriebe gespielt habe.

ich denke, wenn Giants mit globalen Sound Templates zum Abmischen der verschiedenen Klänge arbeitet, dann müssen die Tonhöhen der einzelnen Klänge viel genauer auf einander abgestimmt werden.

**Comment by Patar95** [comment]
Hey Mogli,

du hast doch diese Funktion "Tonhöhe bei Maximaler Drehzahl". Ehrlich gesagt bin ich mir garnicht sicher, was die aktuell genau bewirkt. Aber wie wäre es denn, wenn man damit nur den Sound OHNE Last beeinflusst? Dann könnte man damit ingame die Sounds etwas anpassen und hätte diese bescheuerte Pitchdifferenz nicht mehr drinnen.

**Comment by Mogli12** [comment]
Ja, das könnte man machen. Aber dazu müsste ich zunächst mal die eine Dialogseite auf viele Seite mit Tabs umstellen. Dann könnte man auch einen extra Tab fürs Sound-Tuning anbieten. Mal schauen.

**Comment by Bomberman82** [comment]
Der Deutz 6.61Agrostar ist auch mein absoluter Favorit der ist so genial mit dem Gearbox Addon (LS17), weil da die komplette Schalteranimation eingefügt wurde. Wo ich echt gestaunt habe in wie weit das Gearbox Addon ins Spielgeschehen eingreift, selbst kaputte Mod´s wurden damit aufgewertet und die Fahrzeuge fuhren sich besser als sie es hätten tun sollen, Wow. 

Den Deutz nutze ich auch auf dem LS19er. Und hier fehlt mir so einiges an Immersion am Sound. 

Ich würde ja selber and den Quellcode am Sound was ändern man müsste die Datein kompelieren, die Skripte müssten erst dekompeliert, geändert und wieder kompeliert werden, bin leider kein Modder und mit Giants Editor schaffe ich mal etwas Copy&Paste zu machen mehr auch net. 

Umso dankbarer das es Modder wie auch gibt @Mogli12

**Comment by Mogli12** [comment]
Die Probleme der unpassenden Tonhöhe sollte behoben sein. Ansonsten mach dieses Issue bitte wieder auf.
