### ISSUE TITLE
Einfach mal bedanken und eine Kurze Frage.

### ISSUE THREAD

**Issue by Skorm89** [Mogli12/VehicleControlAddon#241]
Wollte mich mal für das VCA bedanken sehr gut gelungen im Großen ganzen!! Danke für Zeit und Aufwand!
Problem beim IVT Getriebe funktioniert leider kein Tempomat. Oder habe ich da was übersehen?
Mit Geschwindigkeit Permanent halten ist super kommt dem Realen fahren wie z.b Vario mit Handhebel sehr nahe. Nur müsste es wie im Realen sein das wenn du zurück ziehst der Traktor stehen bleibt oder wenn man die Bremse Tritt. Momentan fährt er dann direkt Rückwärts bzw Vorwärts.

**Comment by Mogli12** [comment]
Gern geschehen!

Wie fährt man mit dem Fahrhebel im Fendt Vario eigentlich rückwärts. Zieht man den Hebel nach hinten? Oder drückt man ihn nach vorne?

Ist bei Dir Stop&Go an oder aus?

**Comment by Skorm89** [comment]
Servus Mogli
Beim Vario wie bei allen anderen Stufenlosen ist als Würdest Joystick mit dem Gas Pedal Tauschen.
Drückst du ihn nach Vorne Fährt er Vorwärts ( So wie Jetzt mit VCA) Lässt den Jostick los behält er die Geschwindigkeit. Ziehst ihn zurück stellst du nur die Geschwindigkeit zurück ( Bis auf 0 ) Bremsen kannst du auch mit der Bremse. 
Zum Rückwärts fahren musst aber den den Wahlhebel bzw die Richtung wieder ändern (Quasi wie beim Shuttle Contr.) Bei dir geht er ja direkt mit der Geschwindigkeit Rückwärts. Im Realen würde er stehen Bleiben weil du von V auf R umschalten musst. Zum Rückwärts fahren Drückst dann wieder den Hebel nach Vorne.
Du müsstest das so um Programmieren das du zurück ziehst bis null und dann steht er. Shuttle für Richtung ändern und dann Joystick wieder vor für Vorwärts oder entsprechend Rückwärts. 
Stop and Go ist bei mir aus. Fahre ja IVT heist anhalten und dann Fahrtrichtung wechseln.

Bei fragen helfe ich dir gerne. Bin den Vario 936 S4, Vario 936 BB S4 und den Vario 716 BB S2 gefahren.

**Comment by Skorm89** [comment]
Sooo lieber Mogli hab eben die neue Version Geladen und ganz genau so Funktioniert das.
Absolut Perfekt das Ganze.
Freue mich gerade wie Bolle da ich jetzt mit dem Side Panel Fahren kann und die Füße überflüssig sind XD XD.
Respekt und Riesen Lob, so ist es absolut an der Realität.
Wie gesagt bei so Fragen kann ich helfen

**Comment by Skorm89** [comment]
Okay Wenn du GPS aktiviert hast dann kannst du nicht mehr Bremsen oder Gas geben. Musst Spur halten ausschalten und dann kannst du erst wieder Geschw. Einstellen

**Comment by Mogli12** [comment]
Hallo,
das Problem ist, dass GuidedSteering das Fahrzeug in den Zustand "gesteuert durch Helfer" versetzt. Dass es auch anders geht, sieht man ja an VCA. Leider kann ich da nichts machen, sonst gehen der normale Helfer und Courseplay kaputt.
Viele Grüße,
Stefan

**Comment by Skorm89** [comment]
Hallo Stefan ich mal wieder.
Hatte die Änderung mal ausgiebig getestet muss sagen es Klappt sehr gut eigentlich.
Das Einzige das ich noch als Verbesserung sehen würde wäre das man z.b bei dem Thema Geschw.Halten 2 Seperate InputBindings macht. Da man ja alles mit Gas und Bremse einstellt. Es geht halt viel Bremsweg und Wirkung verloren da man ja nicht mehr Verzögert sondern nur die Geschw. herunter nimmt.
Mir fehlt das Man trotz allem Normal Bremsen kann und die Bremswirkung hat.
Ansonsten absolut Top Mod und Respekt!

**Comment by Mogli12** [comment]
Hallo,
mit der Entf-Taste (KEY_delete) schaltet man zwischen Geschwindigkeit halten an/aus um. Wenn Du es also permanent eingeschaltet hast, dann schaltest Du es mit Entf aus. So kannst Du besser bremsen und mit Vollgas beschleunigen.
Viele Grüße

**Comment by Skorm89** [comment]
Ja habe ich auch auf der Konsole schon drauf ist eine Lösung so fahre ich die ganze Zeit. Ich habe leider kein Plan von dem Ganzen sonst hätte ich versucht das ganze Quasi auf eine Eigene Achse gelegt
z.b Seitenkonsole vor und zurück.

**Comment by Skorm89** [comment]
Bzw einfachste Variante wäre wenn es an und ausschaltbar wäre per Taste. So musst du ja die Taste gedrückt halten zum Aktivieren oder Deaktivieren. Wenn man es per Knopf Druck völlig an und aus schalten könnte wie im Menü. Wäre die einfachste Variante.

**Comment by Mogli12** [comment]
Ich hatte früher mal im GearboxAddon eine Taste zum Ein-/Ausschalten, aber damit bin ich gar nicht klar gekommen. Wenn ich das per Taste machen, dann muss ich die Taste nur los lassen, und Alles ist wieder normal.

**Comment by Skorm89** [comment]
Okay ja ich glaube man könnte das in 10 Verschiedenen Version machen und jeder würde es trotzdem anders wollen XD. Finde die RPM Anpassung bei Geschw. halten hast du sehr gut hin bekommen.
Nja mein größtes Problem ist das ich nicht weiß welche map ich Spielen soll XD

**Comment by Mogli12** [comment]
Hinterkaifeck?

**Comment by Skorm89** [comment]
Die ist schon nicht Schlecht sehr gut gemacht und absolut eine der Besten Maps. Nur das alles vorplatziert ist stört mich. Spiele Maximal mit Kühe und Pferden aber wenn du den Hof immer Zwangsweise Voll mit den anderen Tieren hast Stört das etwas. Spiele seit Glaub ich ca 30+ Std. die MW Felsbrunn Edit aber da hat der etwas mehr Platz und Luft.
Müsste mal Schauen ob ich vlt doch um ziehe. Ist wieder ein Haufen Arbeit die Maschinen und co mit zu nehmen

**Comment by Mogli12** [comment]
Ja, das stimmt. Es dauert immer erst lange, bis man eine Map im richtigen Zustand hat. Eventuell hilft [Easy Development Controls](hier https://www.farming-simulator.com/mod.php?mod_id=138864&title=fs2019). Es ist halt blöd, wenn man erst im Frühling anfängt, Wintergetreide aber im Herbst gesät wird.
Ich spiele ansonsten die originale Felsbrunn und baue mir dann inGame die Landschaft um.

**Comment by Skorm89** [comment]
Also Spielt du mit Seasons? Ja ich die ganze Zeit noch ohne. 
Ja bin immer nur im SP unterwegs und auch nur am WE am PC da war mir bis jetzt Seasons zu langwierig da ich den Winter immer überspringen muss gerade am Anfang.
Ja die Felsbrunn ist eigentlich sehr solide zum Spielen. Konnte die CP course und alles mit übernehmen.

**Comment by Mogli12** [comment]
Ok, in Version 0.1.0.0 habe ich noch eine weitere Taste (Strg+Entf) eingebaut, so dass Du Geschwindigkeit permanent umschalten kann.

**Comment by Skorm89** [comment]
Sehr Gut du bist absolut klasse und Reagierst auch direkt auf Feedback und Co.

**Comment by Shreklich** [comment]
Hallo zusammen,
ich habe da mal eine Frage zum Vario Getriebe das ganze wird ja langsam kompliziert für einen Laie wenn ich jetzt ein Fahrzeug mit dem Variogetriebe fahren möchte und ich dabei Shuttle Control nutze dann werden bei mir die Gänge 3 im Hud angezeigt und kann nur mit halber Geschwindigkeit fahren. Kurze Erklärung dazu ich nutze sehr häufig die H Schaltung vom G27 für die manuellen Getriebe und Shuttle also vor und zurück liegen auch auf der H Schaltung also Gang 3 für Vorwärts und Gang 4 für Rückwärts kann es damit zusammenhängen das er mir dann immer nur die Geschwindigkeit bis Gang 3 freigibt bzw Gang 4 beim Rückwärtsfahren? Beim IVT Getriebe ist das nicht so hier werden keine Gänge angezeigt und es funktioniert ohne Probleme. 

@Skorm89 welche Tastenbelegung hast du eingestellt und was hast du im VCA Einstellfenster (Strg-C) konfiguriert? Hoffe das es mir weiterhelfen kann. 

MfG Thorsten

**Comment by Mogli12** [comment]
@Shreklich Hast Du die Gänge 3 und 4 in den inputBindings auf Vorwärts bzw. Rückwärts belegt? Oder nutzt Du die Einstellungen von VCA?

Mein Vorschlag ist, dass man alle Gänge vom G27 ganz normal belegt, also 1 bis 7 auf VCA 1 bis 7. Dann kann man sich in den Einstellungen von VCA pro Fahrzeug auswählen, welche Bedeutung die Gänge 1 bis 7 im jeweiligen Fahrzeug haben sollen. Wenn Du "D/R , G+/-, R+/-" auswählst, dann schaltest Du mit Gang 1 nach vorne, Gang 2 auf rückwärts, Gang 3 einen Gang hoch, Gang 4 einen Gang herunter, Gang 5 eine Gruppe hoch und mit Gang 6 eine Gruppe runter. Das sollte eigentlich auch beim stufenlosen Getriebe passen. 

In der neuesten Version gibt es zwei stufenlose Getriebe. Beim IVT gibt es keine Gänge mehr. Beim Vario gibt es 2 Gruppen (low/high).

Ich hoffe, dass das etwas hilft.

**Comment by Shreklich** [comment]
Hallo Mogli 
ja ich habe alle Gänge belegt diese nutze ich auch für den Gangmodus 6G, 1R, LH bei der Getriebeart 2x6 das funktioniert ja mittlerweile hervorragend. Ich habe auch die Vorwärts und Rückwärts belegt auf Gang 3 und 4. Ich werde es mal ein wenig durchprobieren mit deiner Einstellung sprich D/G, G+/-, R+/- 
Danke schon mal dafür werde mich melden wie es geklappt hat.

**Comment by Shreklich** [comment]
Soweit so gut das geht schon mal einziges Handicap ist dann aber, dass man nicht während der Fahrt die Gruppe wechseln kann den sobald ich den Gang 1 für nach vorne rausnehme direkt Autohold aktiv ist und die Kiste auf 0 abbremst. 
Vllt sollte ich hier einfach mal die Fahrtrichtung Per Taste belegen und nicht auf den Shifter, genauso wie die Gruppe die ich schon bereits als Taste belegt habe. 
Ist halt alles nicht so einfach. Ich fahre die älteren Traktoren eben mit manueller Schaltung also Gänge 1-6 plus die Gruppe und hin und wieder die modernen mit IVT bzw jetzt noch das Variogetriebe bei zB den Fendt Traktoren.  Wenn man dann alle unter einem Dach habe möchte muss man eben etwas tüffteln. 

Auf VCA will und kann man eben nicht mehr verzichten. Deshalb nochmals vielen Dank für deine Mühe.

**Comment by Bomberman82** [comment]
> 
> 
> @Shreklich Hast Du die Gänge 3 und 4 in den inputBindings auf Vorwärts bzw. Rückwärts belegt? Oder nutzt Du die Einstellungen von VCA?
> 
> Mein Vorschlag ist, dass man alle Gänge vom G27 ganz normal belegt, also 1 bis 7 auf VCA 1 bis 7. Dann kann man sich in den Einstellungen von VCA pro Fahrzeug auswählen, welche Bedeutung die Gänge 1 bis 7 im jeweiligen Fahrzeug haben sollen. Wenn Du "D/R , G+/-, R+/-" auswählst, dann schaltest Du mit Gang 1 nach vorne, Gang 2 auf rückwärts, Gang 3 einen Gang hoch, Gang 4 einen Gang herunter, Gang 5 eine Gruppe hoch und mit Gang 6 eine Gruppe runter. Das sollte eigentlich auch beim stufenlosen Getriebe passen.
> 
> In der neuesten Version gibt es zwei stufenlose Getriebe. Beim IVT gibt es keine Gänge mehr. Beim Vario gibt es 2 Gruppen (low/high).
> 
> Ich hoffe, dass das etwas hilft.

Ich danke dir tausendmal für diese kleine Erklärung jetzt wird mir so einiges klar!. Kenne mich mit der Art der Getriebeeinstellung ja garnicht aus nun weiß ich es. Und danke nochmals das du am Ball bleibst. Ich habe nochmals den 17er mit Gearbox angeschmissen nun gefällt mir dein VCA nen tucken besser als das klassische Gearbox vom 17er.

**Comment by Mogli12** [comment]
> Soweit so gut das geht schon mal einziges Handicap ist dann aber, dass man nicht während der Fahrt die Gruppe wechseln kann den sobald ich den Gang 1 für nach vorne rausnehme direkt Autohold aktiv ist und die Kiste auf 0 abbremst.

Wenn der Shifter in keiner Position ist, dann soll Neutral nicht die Handbremse betätigen. Das werde ich korrigieren. Allerdings ist es beim Vario wohl so, dass man die zw. low/high nur im Stand wechseln kann. Aber wie gesagt, das ist mir eigentlich zu viel Realismus und war keine Absicht. ;-)

**Comment by Shreklich** [comment]
Also das hast du mal wieder super gelöst und vor allem wie schnell du das immer wieder hinbekommst  vielen dank dafür. Einfach nur Top. Wo bleibt nur der Spendenbutton?

**Comment by Bomberman82** [comment]
Genau wo ist dein Spendenbutton? Es ist mir auch schon langsam peinlich so gute Mods von Modder entgegenzunehmen ohne die dafür zu huldigen. Ich bin gerne bereit auch nen vernünftigen Obulus zu geben. Andere Entwickler scheißen ihre DLC heraus ohne vernünftigen Support oder gar Verbesserungen und hier wird am laufenden Band etwas geändert und verbessert. Auf jedenfall Daumen hoch und Hut ab.

**Comment by geo-luchs** [comment]
> 
> 
> Ok, in Version 0.1.0.0 habe ich noch eine weitere Taste (Strg+Entf) eingebaut, so dass Du Geschwindigkeit permanent umschalten kann.

Hi Mogli

ich habe heute herausgefunden, dass mit deiner VCA Version 0.1.0.0  Probleme beim Drescher Abtanken mit Autodrive auftreten.

VCA 0.0.9.9 ist noch OK. mit 0.1.0.0 habe ich das Problem aber reproduzieren können.

Hab ich jetzt erst gemerkt, da ich nach ewigen Zeiten mal ein neues VCA genommen hatte.
Es gibt dort auch ein Issue dazu.
https://github.com/Stephan-S/FS19_AutoDrive/issues/1412
Meinst Du, du könntest dort etwas zur Lösungsfindung beitragen?

**Comment by Mogli12** [comment]
@geo-luchs Das ist doch das bereits bekannt Problem, dass AutoDrive nicht auf Helfer umstellt, oder? Das kollidiert dann mit allen Mods, die ShullteControl anbieten.

**Comment by geo-luchs** [comment]
Hallo Stefan

ich war längere Zeit nicht aktiv im Github und in den Issues ;-)
Hatte das nicht auf dem Schirm.

Danke für den schnellen Hinweis.
Mal sehn, ob die AD-Modder was mit deinem Vorschlag anfangen können.

Gruß
Carsten
