### ISSUE TITLE
Tempomat seit 0.0.9.3 nicht mehr korrekt nutzbar

### ISSUE THREAD

**Issue by Mike-Juli** [Mogli12/VehicleControlAddon#242]
Hi,
Mein Kumpel und ich sind die unendlich dankbar, dass du dich dazu durchgerungen hast doch noch eine Gangschalt-Mod zu erstellen....Danke!!

Aber leider haben wir ein Problem seit der V 0.0.9.3, dass der Tempomat bei Manuell-schaltbaren Getreiben nicht mehr ordnungsgemäß funtionieren will. Z.B Getreibe= 2x6 .... man stellt beim ersten Gang 10km/h ein und er fährt zuerst mit vollgas bis auf den Begrenzeranschlag, dann geht er langsam runter bis auf die 10km/h (dauert ca. 10sec), weiters beginnt es von neuem sobald man mit den Rädern einlenkt.

HILFE....?!

**Comment by Mogli12** [comment]
Hallo,

es scheint, als ob Giants beim Tempomaten etwas in 1.5,1 geändert hat, was in der Skriptdoku noch fehlt. Jetzt sollte das Problem aber gelöst sein.

Viele Grüße
