### ISSUE TITLE
Wendeschaltung (vorwärts/rückwärts) bei einigen Knicklenkern

### ISSUE THREAD

**Issue by Fracking** [Mogli12/VehicleControlAddon#243]
Hi,

einige Knicklenker (Radlader, Teleskoplader, Rübenernter) haben Probleme mit der Wendeschaltung.
Problem: Schaltet man vom Vor- in den Rückwärtsgang (und andersrum auch) bremst der Knicklenker nicht ab, sondern rollt aus. Dies tritt nur auf, wenn der Knicklenker "geknickt" ist (also man nach links oder rechts dreht). Steht der Knicklenker gerade besteht das Problem nicht.

Beispiel: Mit dem Radlader W190D eine Kurve fahren und in der Kurve in den Rückwärtsgang schalten.

Grüße

Andreas

**Comment by Mogli12** [comment]
Wenn das Fahrzeug noch in die falsche Richtung fährt, dann wird nicht vorwärts/rückwärts gewechselt, sondern mit der Handbremse gebremst. Aber nun gibt es eine Sonderlogik für Knicklenker, dass die Handbremse gelöst wird, wenn man lenkt.

Ich muss mal schauen, wie man das lösen kann.

**Comment by Fracking** [comment]
Stimmt. Das mit dem "Bremsen" beim Richtungswechsel wusste ich. Ich hatte vergessen das zu präzisieren. Mit v0.0.9.7 funktioniert es.

Danke
