### ISSUE TITLE
Anfrage: Standardwerte ändern

### ISSUE THREAD

**Issue by Aceone1** [Mogli12/VehicleControlAddon#245]
Hallo Stefan

Wo kann ich die Werte so verändern, dass einige Optionen standardmäßig beim laden eines Spielstandes, bzw. Kauf eines neuen Fahrzeuges aktiv / inaktiv sind?

Beispiel:
Wenn ich die camInsideRotation immer ausschalten möchte, reicht es in der vehicleControlAddonConfig.xml "true" durch "false" zu ersetzen, oder hat diese xml eine andere Aufgabe?
Wenn ja, wie ist es bei der Getriebeeinstellung? Dort ist IVT Standard. Schalte ich es für ein Fahrzeug aus (off) und speichere den Spielstand, ist nach dem erneuten Laden des Spielstandes IVT wieder eingeschaltet, so dass hier eine Änderung vermutlich nichts bringen wüde.

**Comment by Shreklich** [comment]
Beim Getriebe musst du einfach Zahlen eintragen zb 0 ist das Standartgetriebe von Giants in der XML Datei 1 IVT Getreibe und so weiter. Aber eigentlich sollten die Getriebe nach dem Speichern für die einzelnen Fahrzeuge bestehen bleiben. 
Solltest du nicht genau wissen wo du es ändern musst schick ich dir gerne einen Auszug aus der XML wenn ich wieder daheim bin.
MfG

**Comment by Mogli12** [comment]
Du kannst einfach den Inhalt von [modSettings](https://github.com/Mogli12/VehicleControlAddon/tree/master/modSettings) in deinen modSettings Order kopieren und dann die Datei config.xml editieren. Ich empfehle dazu notepad++.

**Comment by Aceone1** [comment]
Ich wusste jetzt nicht wie ich den Inhalt kopiert bekomme, aber habe die Ordnerstruktur einfach selbst erstellt und den Code in die entsprechenden Dateien eingefügt.
Bei testhalber neu gekauften Fahrzeugen hat es gleich funktioniert. Bei denen welche schon in meinem Besitz waren musste ich die Einstellungen noch einmal manuell vornehmen, aber nach speichern und neu laden des Spielstandes war alles so wie gewünscht.
Danke für die schnelle Hilfe, auch an Shreklich.
