### ISSUE TITLE
Low RPM beim Gang einlegen

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#246]
Hallo Mogli, 
ich habe folgendes Problem hin und wieder, aber doch sehr häufig kommt es vor das beim Gang einlegen mit getretener Kupplung ( 100% ) das Fahrzeug trotzdem losrollt und dann die Anzeige Low RPM *** <850 RPM  aufploppt. Wäre es irgendwie möglich das losrollen zu verhindern? Oder aber besteht die Möglichkeit diese Anzeige zu deaktivieren, da ich deine Mod auf einem MP Server nutze und es dann bei allen Mitspielern angezeigt wird? Schön wäre natürlich wenn das Fahrzeug nicht mehr einfach so losrollen würde aber weiß leider nicht mit wieviel Aufwand das zusammenhängt. Deswegen wäre mir auch schon mit der Deaktivierung der Anzeige sehr geholfen. 
Aktuelle Version im Spiel ist die 0.0.9.7 

Danke schon mal und wünsche noch einen angenehmen Tag. 

MfG Thorsten

**Comment by Patar95** [comment]
Wegen dem Problem mit den Anzeigetexten wollte ich gerade einen Issue aufmachen. Ich denke, es lässt sich relativ einfach verhindern, dass die Texte bei jedem, nicht nur beim betroffenen auftauchen. Wenn ich das gerade richtig im Kopf habe, geht es um die oben genannte "low-RPM"-Warnung und um die Handgasanzeige (bei Handgasveränderung auf den beiden Tasten).

**Comment by Shreklich** [comment]
Hallo Mogli
also das Anfahren läuft gefühlt um einiges besser weiß zwar nicht genau was du geändert hast aber das ist schon mal gut so. Danke schon mal dafür. Nun ist aber leider ein weiteres Problem aufgetaucht das bei Version 0.0.9.7 nicht so war wenn ich jetzt die Kupplung trete und gleichzeitig auf die Bremse dann ist diese inaktiv das Fahrzeug rollt also einfach weiter ohne die Geschwindigkeit zu verzögern. 
MfG Thorsten

**Comment by Shreklich** [comment]
Absolut Top also nochmals vielen lieben Dank für deinen Support. Es ist einfach großartig wie schnell du solche Dinge löst. 
Danke sehr.

**Comment by Mogli12** [comment]
Danke fürs Feedback
