### ISSUE TITLE
Fahrzeug bremst aktiv bei Richtungswechsel trotz getretener Kupplung

### ISSUE THREAD

**Issue by Patar95** [Mogli12/VehicleControlAddon#248]
Beim Rangieren passiert das ja öfter. Wenn ich Rückwärts rolle und bei getretener Kupplung auf Vorwärts wechsle, müsste das Fahrzeug eigentlich weiter rückwärts rollen.

**Comment by Mogli12** [comment]
Das kann die Engine leider so nicht.

**Comment by Patar95** [comment]
Einspruch euer Ehren! Ich erwarte ja nicht, dass die Kupplung dann realistisch und ruckelfrei in die andere Richtung beschleunigt. Schön wäre jedoch, wenn er eben bei 100% nicht bremst, bei 90% dann aber schon, denn dann will ich ja sowieso in die andere Richtung beschleunigen.

Bis vor kurzem ist das ja bei den Knicklenkern ungewollt passiert, dass diese trotz Richtungswechsel weiter rollen. Übrigens Funktioniert der Richtungswechsel bei den Knicklenkern während dem Lenken trotz fix noch nicht. Merkt man bei 900° Lenkrad dann doch besser. ;-)

Wünsche dir einen schönen Abend!

**Comment by Mogli12** [comment]
Auf solche Kommentare habe ich keine Lust.
