### ISSUE TITLE
Shuttle Control fehlerhaft

### ISSUE THREAD

**Issue by Powerbrille77** [Mogli12/VehicleControlAddon#249]
Hallo Mogli12

Bei der Version 0.1.0.0 funktioniert der Shuttle Control nicht wenn auch kein Getriebe ausgewählt ist.
Es wird auch die Fahrtrichtung nicht angezeigt (Pfeile). 
Bei den verschiedenen Getrieben funktioniert Shuttle Control tadellos.

**Comment by Shreklich** [comment]
Hallo
ergänzend möchte ich noch sagen das auch die Bremskrafteinstellung keinen Einfluss auf das Fahrzeug hat, sprich ob es jetzt auf 15% oder auf 100% gestellt ist macht bei der Getriebeeinstellung OFF keinen Unterschied mehr. Auch die Autoholdfunktion schein nicht mehr zu funktionieren das Fahrzeug roll von alleine los. Dieses kann man zwar per Handbremse Taste (ö) verhindern es sollte aber dafür eine anzeige im HUD geben. 
Lieben Gruß Thorsten

**Comment by Mogli12** [comment]
Hallo,
AutoHold gibt es nicht bei Getriebe Off, weil es Teil des Getriebes ist.
Viele Grüße

**Comment by Shreklich** [comment]
Wäre es den möglich das man hier die Bremskraft wieder variieren könnte? Also das sie Fahrzeuge schneller zum halten kommen wenn man vom Gas geht. Es geht sich aber allein um die Funktion wenn das Getriebe abgeschaltet ist. Da ich deine Mod im Multiplayer nutze kann so jeder entscheiden wie er es am liebsten mag.

**Comment by Shreklich** [comment]
Sehr schön Mogli vielen lieben danke fürs Update. Macht echt mega Spaß mit deiner Mod. Einfach nur top für die schnelle Hilfe.

**Comment by Powerbrille77** [comment]
Danke Mogli12 jetzt funktioniert es

**Comment by Mogli12** [comment]
Danke fürs Feedback!

**Comment by FSDynasty** [comment]
Danke für das AddOn. Schade ist nur, dass die Einstellungen die man vornimmt, und das bei jedem einzelnen Fahrzeug nicht gespeichert werden. Bei Spielneustartz ist z.B bei Getriebe statt ->off<-
wieder ->IVT<- drin. Wenn man mit Kontroller spielt, muss die Getriebeeinstellung zwingend ->off<- sein und auch bleiben, sonst verliert man den Spass am AddOn.

**Comment by Shreklich** [comment]
@FSDynasty  du kannst die config XML so ändern das immer das Getriebe auf Off ist.Dazu schaust du bei Transmission und wechselst die 1 in 0 somit ist das Getriebe immer auf Off. Aber du hast recht mit dem speichern, dass das Skript die Daten nicht korrekt von der letzten Einstellung übernimmt bei mir ist zb die automatische Kupplung immer wieder aktiv obwohl ich die auf Off stelle. Ich selber komm damit aber zurecht ist vllt nur ein kleiner Schönheitsfehler.
MfG Thorsten

**Comment by FSDynasty** [comment]
@Shreklich, danke für die info
