### ISSUE TITLE
Einstellungen client gebunden?

### ISSUE THREAD

**Issue by blutfahne** [Mogli12/VehicleControlAddon#250]
Hallo, erstmal großes lob für deinen Mod, wir würden den mod gern auf dem server nutzen, leider hat natürlich jeder spieler seine eigenen vorstellungen im bezug wie er gern die schaltung eingestellt hat, wäre es möglich die einstellungen für jeden spieler seperat zu speichern für jedes fahrzeug? Und nicht das spieler A einstellungen vornimmt an traktor a, und spieler b nicht mit den einstellungen für traktor A klar kommt, ich hoffe es ist verständlich ausgedrückt?

**Comment by Mogli12** [comment]
Ja, das ist bereits so.

**Comment by blutfahne** [comment]
hm, in welcher version denn? hatten die version von vorgestern auf dem server

**Comment by Mogli12** [comment]
Das ist schon seit einigen Monaten so.

**Comment by Shreklich** [comment]
Hallo könnte es sein das einige Einstellung nach erneuten beitreten nicht übernommen werden also diese nicht gespeichert werden? Bei mir in der aktuellen Version 0.0.1.4 werden das Anzeigen des Getriebehuds auf 'Aus' gestellt obwohl es eingestellt war und die Autoclutch stellt sich immer wieder ein. Sonst ist mir bis jetzt noch nichts weiter aufgefallen. 
MfG Thorsten 

Wünsche noch ein schönes besinnliches Weihnachtsfest.

**Comment by Mogli12** [comment]
Tritt das Problem immer noch auf?
