### ISSUE TITLE
vehicleControlAddonMenu.lua:43: attempt to index field 'dialogBackground' (a nil value)

### ISSUE THREAD

**Issue by Vanquish081** [Mogli12/VehicleControlAddon#253]
> .....2019-12-22 01:58 C:/Program Files (x86)/Steam/steamapps/common/Farming Simulator 19/pdlc/claasPack/shared/connectionHoses/connectors.i3d (181.83 ms)
> 2019-12-22 01:58 Load mod: 'Real Dirt Color: Independent Mode' v1.1.0.2 by: ViperGTS96
> 2019-12-22 01:58 --- loading Tardis V0.9.1.3 | ModName FS19_Tardis ---
> 2019-12-22 01:58 Disabled withering
> 2019-12-22 01:58 --- loading Vehicle Control Addon 0.1.0.3 by mogli ---
> 2019-12-22 01:58 **Error calling vehicleControlAddonRegister.postLoadMission :F:/Mis Documentos/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/gui/vehicleControlAddonMenu.lua:43: attempt to index field 'dialogBackground' (a nil value)**
> 2019-12-22 01:58 C:/Program Files (x86)/Steam/steamapps/common/Farming Simulator 19/pdlc/johnDeereCottonPack/particleSystems/particle_materialHolder.i3d (0.91 ms)
> 2019-12-22 01:58 C:/Program Files (x86)/Steam/steamapps/common/Farming Simulator 19/pdlc/claasPack/particleSystems/effect_materialHolder.i3d (1.87 ms)
> 2019-12-22 01:58 F:/Mis Documentos/My Games/FarmingSimulator2019/mods/FS19_SiloDisplays/materialHolders/siloDisplayIcon_materialHolder.i3d (22.05 ms)
> 2019-12-22 01:58 C:/Program Files (x86)/Steam/steamapps/common/Farming Simulator 19/pdlc/andersonPack/particleSystems/particle_materialHolder.i3d (2.35 ms)
> 2019-12-22 01:58 C:/Program Files (x86)/Steam/steamapps/common/Farming Simulator 19/pdlc/claasPack/vehicles/claas/corio875FC/corio875FC.i3d (77.91 ms)
> 2019-12-22 01:58 data/store/ui/shop.i3d (26.64 ms)
> 2019-12-22 01:58 data/shared/materialHolders/glowEffectMaterialHolder.i3d (0.18 ms)
> 2019-12-22 01:58 data/store/ui/cube.i3d (0.25 ms)
> .....

I can use GPS, but no work the UI, no show nothing with Left Ctrl + C

**Comment by Mogli12** [comment]
Strange that this happens only on your machine. Do you use the latest patch (1.5.1)? Can you post the complete log in Gist?

**Comment by Vanquish081** [comment]
Log

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/3992311/log.txt)

The "Warning: Tried assigning the binding..." is by VCA also?

**Comment by Mogli12** [comment]
Please try version 0.1.0.4. Can you please post a screen shot of the VCA settings UI if it comes up?

**Comment by Vanquish081** [comment]
![HUD](https://i.imgur.com/OsMdtFp.jpg)

Is more cool xD

**Comment by Mogli12** [comment]
Thanks!

The texts are placeholder only. The current commits are only intermediate steps to a tabbed settings screen. I can see now the problems of wide screens. The buttons Q and E are too far to the side.

**Comment by Vanquish081** [comment]
Yes... I play to 2560x1080
