### ISSUE TITLE
Inkompatible mit der Abschleppstange aus dem Modhub

### ISSUE THREAD

**Issue by jonaslinhose** [Mogli12/VehicleControlAddon#258]
Hallo,

erst mal vielen Dank für den tollen Mod, eines der Scripte ohne den der LS einfach keinen Spaß machen würde.
Allerdings funktionierte er plötzlich nicht mehr bzw. ich kam nicht mehr in das Menü. Ich habe also meine Mods sukzessive deaktiviert und als Verursacher die Abschleppstange aus dem Modhub ausfindig gemacht ("https://www.farming-simulator.com/mod.php?mod_id=141991").
Fehler in der Log habe ich leider nicht gefundne, falls du da was machen kannst / willst dies nur als Hinweis, auf die Stange kann ich verzichten, auf das Script nicht.
Ich würde auch gerne den Modder aus dem Modhub informieren, finde aber keine Kontakdaten dort.. schade.

**Comment by Mogli12** [comment]
So, mit der neuesten Version sollte es behoben sein. Das Problem war, eine normales Fahrzeug mit Abschleppstange vom Jens Holzhacker mit Motor zu unterscheiden.

**Comment by jonaslinhose** [comment]
great.. thank you
