### ISSUE TITLE
don't read the file config.xml

### ISSUE THREAD

**Issue by Vanquish081** [Mogli12/VehicleControlAddon#259]
Don't read the file config.xml, every time you enter you have to change the options.

![config](https://i.imgur.com/YuB2nYM.png)

**Comment by fdanapfel** [comment]
Based on your screenshot it looks like there is an error in the name of the folder where the settings files are stored.

As you can see at https://github.com/Mogli12/VehicleControlAddon/blob/05edc797454735b0c8fa6ce178a1940c5370c55e/FS19_VehicleControlAddon/vehicleControlAddon.lua#L150 the mod looks for the config.xml in a folder named 'modsSettings', but in your screenshot you are using a folder named 'modSettings' (there is an 's' missing after the 'd').

**Comment by Mogli12** [comment]
I corrected the folder name here in github. It is modsSettings.
