### ISSUE TITLE
Free steering vs. AutoRotateBackSpeed

### ISSUE THREAD

**Issue by AgroMeester** [Mogli12/VehicleControlAddon#260]
Hi Stefan,

Something changed in the behaviour of the AutoRotateBack function.

I think it has to do with the introduction of the new Free Steering setting in the VCA menu. Before that you implemented a hotkey option to temporarily disable the AutoRotateBack function and thus enabling free steering on the fly (at my request at that time I believe).

Since the new Free Steering option (which is on or off without a key mapping option) the AutoRotateBack function kind of instantly resets (snaps) the steering to straight ahead (or maybe it is a very fast AutoRotateBackSpeed?) instead of gently steering back (simulating the friction of the tires on the ground).

Could you please have a look at that? I hope I made myself clear.

Thanking you in advance and wishing you all the best for 2020!

Greetings from Holland,

AgroMeester.

**Comment by Mogli12** [comment]
Hi, 

Is this issue still open?

Regards
