### ISSUE TITLE
Issues after engine dies

### ISSUE THREAD

**Issue by jdoyle26** [Mogli12/VehicleControlAddon#261]
Hello, I have noticed that if the engine stops for any other reason than being turned off (stalls, runs out of fuel) the transmission no longer works.  If auto clutch is on the engine will rev up and hold that rpm even after releasing the accelerator and it shows the clutch at 100%.  Turning auto clutch off will bring the rpms down to almost nothing and the vehicle will barely move and not respond to throttle, IVT just revs up and down as if stuck in neutral. Attempting to turn the transmission off results in no response what so ever from the accelerator (engine doesn't even rev). The only way to fix this is to reset the equipment or restart the game.  I am using the latest version of your mod 1.0.0.5 that was released 3 days ago.

**Comment by Mogli12** [comment]
Can please add some screen shots. I do not really understand what is not working.

**Comment by KCHARRO** [comment]
The same thing happened to me, but instead of restarting, or resetting the vehicle, I stop it and start courseplay or autodrive and with the AI somehow it works again (only once did I have to restart the game)

**Comment by Mogli12** [comment]
I think that you are in neutral. But if no one adds a screenshot, then I cannot help.

**Comment by jdoyle26** [comment]
Sorry been super busy at work, I'm reloading windows since I bought a new graphics card and it was time anyways.  I'll see if I can get a screenshot or video of the issue when everything is done here soon.

**Comment by Mogli12** [comment]
Did already try to press ";" (semicolon on US keyboard, vcaNeutral)?

**Comment by FloSch02** [comment]
DE:
Hallo! Ich habe das selbe Problem, es tritt bei mir aber nur an einem Traktor auf, soviel ich weiss... In der log.txt scheint mir nichts aussergewöhnlich. Fahre ich den Schlepper gegen eine Wand, würgt es den Motor ab. Soweit alles wie sein es soll. Ich starte den Traktor wieder. Gebe ich nun Gas, wandert die Anzeige der Kupplung von 100% bis so ca. 87% manchmal sogar bis 13%, doch der Traktor bewegt sich kaum und geht anschliessend aus. 
Der Effekt tritt aber auch auf, wenn ich aussteige ein Gerät oder Anhänger anhänge, wieder einsteige und Gas gebe.

Ich verwendete diesen Traktor,
[https://ls-modcompany.com/filebase/file/692-fiat-1300dt-modelleicher-edit/](url)
ManualAttaching aus dem Modhub und sonst nur Standard-Objekte.

Kanns mir nicht erklären...

**Comment by Mogli12** [comment]
@FloSch02 Welche Versoin? log.txt?

**Comment by FloSch02** [comment]
@Mogli12 Werde ich noch nachreichen, einen Moment Geduld bitte.

**Comment by FloSch02** [comment]
https://gist.github.com/FloSch02/fcb1652adcf83e1687caa51f1eb77228#file-log-txt

Die aktuellste Version (0.1.3.0) des VCA ist installiert.
Und auch sonst ist alles auf dem neusten Stand.

Keine Ahnung, was die Warnings im unteren Teil da zu suchen haben...
