### ISSUE TITLE
Request: Engine onload sound rectification

### ISSUE THREAD

**Issue by Laurindra** [Mogli12/VehicleControlAddon#262]
A small request. I've noticed that the engine sound offload and onload have different pitch. This is due to Giants altering their carefully recorded engine sounds by 15% for hardworking engines. As seen in ../data/sounds/soundTemplates.xml
```
<template name="DEFAULT_MOTOR_ONLOAD_RUN" parent="DEFAULT_MOTOR_RUN" >
        <pitch indoor="1.15" outdoor="1.15" />
    </template>
```
When operating a vehicle at constant speed and in a specific gear, it doesnt raise the pitch of an engine if the load (ie uphill vs downhill) changes. Ít only It only changes the 'roarines' of the sound. 
This is something that irritates me. It just doesnt sound realistic.
Therefore I have altered the game base files. A very crude solution to this poor decision from Giants IMO.

My request is: Can you add this XML setting in your mod, so others can have more realistic accurate pitched engine sounds as well.?

Cheers and thanks again for an already wonderful mod,

Gerrit 'Laurindra' Bosch

p.S. 'Silently' wishing for fleeting turbos and/or growling open-exhausts.

**Comment by Mogli12** [comment]
Hi Gerrit,

overall pitch is a static setting. It does not change with motor load. I find it difficult to change.

At the end I think this is an error in the soundTemplates.xml. But it can be fixed in the soundTemplates.xml itself or while loading it. 

In the motorSamples table it is not clear, if the pitch came from a sound template or not.

Regards,
Stefan

**Comment by Mogli12** [comment]
P.S.: I was not able to overwrite the default sound templates via mod. I propose to change the pitch of offload sound to 1.15 as well:
```xml
    <template name="DEFAULT_MOTOR_OFFLOAD_RUN" parent="DEFAULT_MOTOR_RUN" >
        <volume indoor="0.55" outdoor="0.85" >
            <modifier type="MOTOR_LOAD" value="0.0" modifiedValue="1.00" />
            <modifier type="MOTOR_LOAD" value="0.7" modifiedValue="0.50" />
            <modifier type="MOTOR_LOAD" value="1.0" modifiedValue="0.00" />
        </volume>
        <pitch indoor="1.15" outdoor="1.15" />New entry, same pitch as DEFAULT_MOTOR_ONLOAD_RUN
    </template>
```
