### ISSUE TITLE
Config.xml and transmission.xml not showing up in modsSettings folder

### ISSUE THREAD

**Issue by mikeboy203** [Mogli12/VehicleControlAddon#264]
Dear Mogli

i have an issue where the config files dont show up in my modsSettings file (version 0.1.0.6). is there any way to fix this ?

<img width="961" alt="issue" src="https://user-images.githubusercontent.com/47869434/72641566-c739ec00-396a-11ea-8b69-43456db20dd7.png">

**Comment by Mogli12** [comment]
Hi,
They are not created automatically.
Regards

**Comment by mikeboy203** [comment]
How can i add them manually ? I’d like to fiddle around with adding my own transmission

**Comment by Mogli12** [comment]
You can use this as template: [modsSettings](https://github.com/Mogli12/VehicleControlAddon/tree/master/modsSettings/)

**Comment by ZhoraPoroh** [comment]
> How can i add them manually ? I’d like to fiddle around with adding my own transmission

Hi. You can upload your transmission here.

**Comment by RamonaTigier** [comment]
> 
> 
> You can use this as template: [modsSettings](https://github.com/Mogli12/VehicleControlAddon/tree/master/modsSettings/)

Einstellung "Anzeihe der Rasterbahn" wird (trotzdem) nicht gespeichert.
