### ISSUE TITLE
VCA does not remember gear type

### ISSUE THREAD

**Issue by DerBauer2** [Mogli12/VehicleControlAddon#268]
If I drive the tractor with CP or AD, he then switches the transmission to either OFF or IVT. Is this a bug or does something have to be set?

**Comment by DerBauer2** [comment]
apparently no interest to improve a mod ....
Incidentally, the mod with AI can not drive well, you could fix that

**Comment by Mogli12** [comment]
Hey, there is no need to get angry just because I do not pick up an issue within few days. 

VCA 0.1.0.6 uses the transmission with CP or AD but without gear shift times. Just the IVT and the Vario will be turned off as the vanilla transmission is very similar.

**Comment by DerBauer2** [comment]
CP & AD only run under Vario or IVT because other modes switch off the AI ​​because the RPM are too low

**Comment by Mogli12** [comment]
Can you describe your problem in more details? Can you add screen shots? Looking at your ID it seems that you speak German. I speak German as well.

**Comment by Mogli12** [comment]
Just on tip: Stop the vehicle until the red "auto hold" sign shows up above the speedmeter. Now choose the right gear to start. The vehicle will remember it.

**Comment by DerBauer2** [comment]
das macht es leichter :D Also mir ist es nur bei AD aufgefallen denn CP fähr bei mir nur auf dem Feld. 
Das komische ist bei denn Schaltgetreieben ist das es ne weile funktioniert bis dann dein Mod im ersten gang nicht mehr hoch schaltet bzw die warung kommt RPM zu niedrieg das bleibt dann kurz so das er halt sehr langsam fährt. normal würde der User ja weiter fahren und dann kommten die RPM´s aber AD schaltet sich dann ab da der nicht voran kommt bzw meldet denn fehler er steckt fest ect. 

Ich weis nicht wie du es Pogramiert hast aber normal dürften die RPM nicht so weit fallen das der Motor fast aus geht beim anfahren. Vlt könnte man da noch was machen das der Mod nie unter die Min drechzahl kommt das solte das mit AD auch keine Probleme machen.

Das gleiche mit Schalten der KI nach einer gewissen zeit schaltet das Getriebe nicht mehr und AD fährt in denn niedregsten Gängen.

**Comment by Mogli12** [comment]
Du kannst in der aktuellsten Version das Getriebe für den Helfer ausschalten.
