### ISSUE TITLE
Arbeitsbreite nicht mehr einstellbar

### ISSUE THREAD

**Issue by Aceone1** [Mogli12/VehicleControlAddon#269]
Verhalten: (Menüpunkt Distance)
1. Die erste bereits enthaltene Zahl lässt sich nur löschen, wenn man dahinter eine andere Zahl eingibt und dann z.b. mittels Pfeiltasten zur ersten Zahl springt.
2. Zusätzlich ist keine Eingabe von Punkt oder Komma mehr möglich, so dass nur noch Arbeitsbreiten im Meterabstand möglich sind.

Trat erstmals mit der derzeit aktuellsten Version auf: 0.1.0.6

Nachtrag: tritt auch bei einem neuen Spielstand ohne andere aktive Mods auf

**Comment by Mogli12** [comment]
Das Problem is mit Version 0.1.0.8 gelöst.

**Comment by Aceone1** [comment]
Vielen Dank für deine Mühe und ein schönes Wochenende.
