### ISSUE TITLE
FS17_GearBoxAddon Transmissions

### ISSUE THREAD

**Issue by KCHARRO** [Mogli12/VehicleControlAddon#270]
It is a question

Can the xml transmissions of GearBoxAddon be used? and if not ... How can I make them work in VCA?

Because I want to use the ones CLAAS uses in their tractors, C-MATIC, HEXASHIFT, Eccom 4.5, Eccom 5.0, their configurations are found in the GearBoxAddon XML.

**Comment by Mogli12** [comment]
Hi,

Sorry, but VCA's transmission is very simple. You cannot use the "old" XML.

I propose to use the "6x4 AutoPowerShift" transmission. It has 4 groups and 6 gears with powershift. It does not shift the groups automatically.

Regards,
Stefan

**Comment by KCHARRO** [comment]
OK. Thanks for answering.

Do you think it will eventually work, with VCA development in later versions?

**Comment by Mogli12** [comment]
No, FS17_GearboxAddon tried to create a realistic gearbox simulation. 

My idea about transmissions in VCA is to have them configurable in the game.

**Comment by KCHARRO** [comment]
I agree, and that idea seems good to me ...

Is there any way that I can make them at least similar?

I've tried but it's complicated for me ...

**Comment by Mogli12** [comment]
I added the hexashift transmission in version 0.1.0.8.

**Comment by KCHARRO** [comment]
Thanks very much
