### ISSUE TITLE
Multiplayer Problem

### ISSUE THREAD

**Issue by Dinratte** [Mogli12/VehicleControlAddon#272]
Hallo,
das Problem ist ziemlich schwer zu beschreiben aber ich versuche es mal .
Wir haben auf dem Server EV und VCA und haben alle die Änderung in der XML gemacht, nun habe wir das Problem , dass ich mit shuttle Control auf an fahre da ich das mit shifter fahre.
Wenn dann jetzt ein Kollege vom Server in den Traktor einsteigt kann er nicht los fahren er kann auch nicht den Shuttle Contorl auf an oder aus verstellen. Das heisst ich muss rein und den Shuttle Control auf aus stellen dann kann der Kollege wieder rein und fahren. Ich weiss ziemlich komisches Problem eventuell kannst du ja helfen.
Danke im vorraus

**Comment by Mogli12** [comment]
Nutzt ihr Shuttle Control von EV  oder VCA? Wird das eventuell beim Fahrerwechsel geändert?

**Comment by Dinratte** [comment]
Wir nutzen Shuttle Control von VCA. Und vom Server haben alle den Shuttle Control vom EV über die XML deaktiviert.

**Comment by Mogli12** [comment]
Könnt ihr einen Screen Shot machen, wie es in der Situation am Client aussieht?

**Comment by Dinratte** [comment]
Ja kann ich heute Abend machen

**Comment by Dinratte** [comment]
Schaffe das heute abend nicht mit dem Screen Shot . Was möchtest du denn sehen auf dem Screen shot? Gruß
Stefan

**Comment by Dinratte** [comment]
Also wir haben jetzt mal was rausgefunden und zwar kann er bzw die anderen nicht fahren wenn ich das Fahrzeug verlasse mit Gang drin. Stell ich das Fahrzeug ab im " Leerlauf" können die anderen normal fahren. 
Ausserdem haben wir rausgefunden das wenn der Kollege das Fahrzeug abstellt wenn er rückwärts gefahren ist (er hat im VCA den Blick nach hinten wenn man Rückwärts fährt an), Kann ich mein Headtracking nur noch nach hinten schauend zentrieren.
Hoffe ich konnte das gut erklären sonst mal TS oder Discord ;D 
Danke schon mal im vorraus.
Gruß Stefan

**Comment by Dinratte** [comment]
Es liegt wohl an zürückblickend innen, wie gesagt ich headtracking und habe das aus der kollege fährt normal und hat das an . Alles sehr komisch

**Comment by Dinratte** [comment]
ok also ich muss wohl einen Button belegen für leerlauf was ja über den shifter nicht belegbar ist. dann können die kollegen fahren. Das mit dem Headtracking und dem Rückwärts fahren besteht immer noch.

**Comment by Dinratte** [comment]
Wir werden es am Wochenende teste.
Vielen Danke für deine Mühe. Top Arbeit.
Gruß
Stefan

**Comment by Dinratte** [comment]
Hallo Stefan,
das Problem mit der Rückfahrkamera ist erledigt danke dafür. ;D
Das andere Problem besteht allerdings noch. Und zwar muss ich wenn ich den Schlepper verlasse auf neutral stellen (extra ein Button dafür belegt) . Mit dem Shift in Neutral reicht nicht aus komischerweise. Heisst verlasse ich den Schlepper mit Gang drin (über den shifter), können die kollegen den Schlepper nicht benutzen sie bekommen quasi kein Gang rein so hört es sich an .
Geh ich rein stell auf neutral können sie fahren.
also wenn ich es nicht vergesse geht alles . Vergesse ich aber auf neutral zu schalten sind die schlepper nicht fahrbar für andere Mitspieler.
Wenn du es lösen könntest dieses Problem wäre es genial, wenn es aber zu viel arbeit wäre dann stress dich damit nicht.
Vielen Dank nochmal 
Gruss
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,
wie ist die Kupplung eingestellt?
Viele Grüße,
Stefan

**Comment by Dinratte** [comment]
Die Kupplung vom G29 ganz normal würde ich sagen Kupplungsachse linkes Pedal.
Hätte TS anzubieten einen Server zum Testen usw sag bescheid wie ich dir helfen kann ;D
Gruß
Stefan

**Comment by Mogli12** [comment]
Hast Du die automatische Kupplung (AutoClutch) ausgeschaltet?

**Comment by Dinratte** [comment]
Nein die ist angeschaltet.

**Comment by Mogli12** [comment]
Vielleicht liegt es trotzdem daran, dass Du beim Aussteigen das analoge Kupplungspedal getreten hast. Probier es mal mit Version 0.1.1.2

**Comment by Dinratte** [comment]
Werde ich versuchen, bekommst dann Meldung.
Danke nochmal für deinen Einsatz.

**Comment by Dinratte** [comment]
Das geht soweit wohl. Nur leider im MP nicht aber gut solo läuft das. Vielen dank nomma.

**Comment by Dinratte** [comment]
Läuft alles so wie es aussieht mit der 0.1.2.2
Danke für deine Bemühung!
