### ISSUE TITLE
Soundprobleme, Lösungen

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#273]
Hallo @Mogli12, 

tja, wie soll ich es beschreiben, es ist kein Problem im eigentlichen Sinne sondern, bei einigen Modtraktoren passiert folgendes, wenn man Getriebe auf on geht und eins der verschiedenen Getriebetypen aussucht, dann ändert sich der Motorsound in ein Piepgeräusch (hört sich lustig an) z.B. der Amazon Profihopper (Rasenmäher), wenn man aber wieder das Getriebe ausschaltet dann läufts wie es soll, vieleicht weiß du ja Rat wie man das in das VCA implentieren kann. Andernfalls versuche ich etwas Copy&Paste bei den XML´s zu machen. Und dann gibt es noch das diverse Fahrzeuge ne extrem lange Übersetzung haben im 1.Gang trotz Schaltgetriebe braucht es ziemlich lange um in die Pötte zu kommen, naja ist jetzt nichts schlimmes. 

Danke im Voraus 

Und tausend, tausend, tausend, Dank für deine Mod´s.

**Comment by Mogli12** [comment]
Hallo,

Sobald ein VCA Getriebe aktiv ist, wird auch die Tonhöhe modifiziert. Das scheint mit einigen Mods nicht zu funktionieren.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo,

in Version 0.1.0.9 kannst Du im 2. Tab die Änderungen am Klang ausschalten.

Viele Grüße

**Comment by Bomberman82** [comment]
Alter @Mogli12,

ich könnte dich küssen!!! Das ist super!!!! richtig richtig geil, ich liebe den VCA. 

Danke für das Update und deinen tollen Mod´s! Es scheint auch im Allgemeinen etwas runder zu laufen jetzt. Top so macht LS19 richtig richtig spaß. 

Danke 

Viele Grüße
