### ISSUE TITLE
transmission

### ISSUE THREAD

**Issue by nbhubbard96** [Mogli12/VehicleControlAddon#274]
is there a way to save the selection for transmission type so i dont have to change it every time i load the save game up? and can you make it where you can make the selections a global change instead of for each vehicle

**Comment by KCHARRO** [comment]
Download the modsSettings folder:
Then, place it in the saved folder C: \ Users \ XXXX \ Documents \ My Games \ FarmingSimulator2019 \

and modify: config.xml

What you set here will be global for all vehicles, even new ones you buy in the store

**Comment by Mogli12** [comment]
Simple transmissions can be configured ingame if you choose "own transmission".
