### ISSUE TITLE
Modklau???

### ISSUE THREAD

**Issue by MarcusModding** [Mogli12/VehicleControlAddon#275]
Hey Stefan,

bei Modhoster hat jemand deinen Mod als Direktdownload veröffentlicht. Ich gehe mal davon aus, dass du davon nichts weißt.

Hier hast du den Link:
https://www.modhoster.de/mods/vehicle-control-addon--2#description

Gruß
Marcus

**Comment by Mogli12** [comment]
Der Mod ist ja bei mir kostenlos und ohne uploaded erhältlich. Da kann man nichts klauen.
