### ISSUE TITLE
Abrupter Stopp unter 2Km/h

### ISSUE THREAD

**Issue by A3Ambition** [Mogli12/VehicleControlAddon#276]
Hallo Stefan,

erst einmal vielen Dank für das zur Verfügung stellen des tollen Mods, der das Grundspiel doch erheblich zum positiven Aufwertet.

Du hattest bis zur Version 0.1.0.0 eine Funktion eingebaut die die Giants Engine umgeht und das abrupte Anhalten unter 2Km/h verhindert. Es scheint als das seit Version 0.1.0.2 diese nicht mehr funktioniert - dies lässt sich am besten mit dem IVT Getriebe testen da die Schlepper eben nun unter 2 Km/h sofort zum Stillstand kommen und eben nicht weiter ausrollen. Getestet habe ich diesen Effekt mit der Version 0.1.0.0 bei der es noch funktioniert hat, und alle darauf folgenden Versionen haben leider wieder den abrupten Stopp. Vielleicht kannst du Dir das ja mal ansehen und ggf. in einer zukünftigen Version wieder mit einbauen ;-)

**Comment by Mogli12** [comment]
Hallo,

kannst Du das Problem noch etwas genauer beschreiben? Welchen Traktor hast Du probiert (wg. Leistung)? Du hast das IVT Getriebe verwendet? Spielst Du mit der Tastatur oder mit analogem Gaspedal und Bremse?

Die log.txt wäre auch hilfreich, z.B. um zu sehen, welche anderen Mods auch noch installiert sind. Auch ein Screen Shot hilft.

Vielen Dank

**Comment by Mogli12** [comment]
Probier mal Version 0.1.1.1

**Comment by A3Ambition** [comment]
Hallo Stefan,

Sorry für die verzögerte Rückmeldung. Gespielt wurde mit der Tastatur und mit einem Gamepad in beiden Fällen mit IVT. Die neue Version hat das Problem behoben! 

Vielen vielen Dank für die schnelle Rückmeldung! Übrigens ein Klasse Mod der mit jeder Version immer besser wird!
