### ISSUE TITLE
Seltsame Lags

### ISSUE THREAD

**Issue by sehannss** [Mogli12/VehicleControlAddon#278]
Hallo Mogli,

Wir spielen auf einem Dedi-Server.
Seit v0.1.1.2 wird immer wieder der Error in line 1530 geworfen. An sich passiert erstmal nichts. Sobald dies aber teilw. bis zu 25 Zeilen hintereinander der Fall ist, innerhalb weniger Minuten, kommt es zu "Lags".  (Ob dies die Ursache ist, kann ich nicht sagen)

![Konsole](https://user-images.githubusercontent.com/61556294/75561042-9c9d8180-5a46-11ea-8e11-5c5a8ad3e356.png)

Nach einem Serverneustart ist alles in Ordnung, sobald dann ca. 20min gespielt wurden, tritt der Fehler immer öfter auf und irgendwann fangen die Traktoren an zu "laggen". Wohlgemerkt nur der Traktor, keine angehängten Geräte, Animationen etc. Dies führt dazu, dass der Traktor teilw. in den Geräten hängt und die Geschwindigkeit alle paar Meter um bis zu 3/4 reduziert, kurz festhängt und dann wieder auf die "Anfangsgeschwindigkeit" vor dem Lag beschleunigt.
Dieses Problem lässt durch einen Neustart des lokalen Rechners oder von LS19 nicht lösen. Nur durch einen Serverneustart.
Dieses Problem tritt nicht mehr, sobald das VCA nicht mehr auf dem Server ist.

Ich habe sämtliche anderen Mods, die seit dem Auftreten des Problems auf den Server kamen wieder heruntergenommen bzw. die Updates rückabgewickelt. Ich habe auch einige ältere Versionen versucht, bin jedoch auf keine Lösung gekommen.

Ich habe versucht Dinge auszuschließen wie, ein spezielles Getriebe, eine spezielle Geschwindigkeit etc., jedoch bin ich auf keine Ursache gestoßen.

Grüße sehannss

P.S.: Danke für die tolle Arbeit und die regelmäßigen Updates

**Comment by sehannss** [comment]
Wahrscheinlich lässt sich der Fehler in Zeile 1530 dadurch beheben, dass die if-Abfrage auf zwei Zeilen aufgeteilt wird und die `<=`-Abfrage nur erfolgt, wenn der `lt != nil` ist.

**Comment by sehannss** [comment]
Ich habe mittlerweile diese ganzen Konstellationen auch in einem lokalen Spiel getestet. Zum einen treten die "seltsamen Lags" nicht auf und die Lua-Fehler in Z. 1530 auch nicht.

**Comment by DerMicha23** [comment]
könntest du die lösung mal posten denn wir haben die fehler auch und wurden den gern beseitigen

**Comment by sehannss** [comment]
@DerMicha23 Es gibt keine Lösung. Wie kommst du darauf?

**Comment by sehannss** [comment]
danke für das schnelle Update
