### ISSUE TITLE
Lua Error Im Multiplayer 

### ISSUE THREAD

**Issue by Wim1904** [Mogli12/VehicleControlAddon#279]
Hallo, bei uns tritt jedesmal ein error auf wenn man ein fahrzeug startet.

Error: Running LUA method 'update'.

Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:1530: attempt to compare nil with number

und unten wo sonst der Gang angezeigt wird, steht dann "nil"

vielen dank im vorraus

**Comment by Mogli12** [comment]
Das ist korrigiert ab Version 0.1.2.2.
