### ISSUE TITLE
How to use "Neutral" in shifter

### ISSUE THREAD

**Issue by vemendoza** [Mogli12/VehicleControlAddon#282]
Hi Mogli, and thank you for your great job.
So, I have a question about using G29 shifter. (I have steering and shifter)
If I need only use gears 3 and 4 to "Drive forwards" and "Drive backwards", how can I configure if both isn't select the system understand it to "Neutral"...?? (in this case i'm using "Transmission = OFF")

I known that "Ç" is keybind to neutral but I prefer to use my shifter to do it.

Thank you for your attention and have a nice weekend

**Comment by Mogli12** [comment]
Hi,
Please look at the README.md: 
> "D/R , G+/-, R+/-" - gear 1 swtiches to forward, gear 2 switches to backward, vehicle is in neutral in neither 1 nor 2 are pressed, gears 3 and 4 change the gear, gears 5 and 6 change the range
Please use this gear shifter mode.
