### ISSUE TITLE
Lua error im MP

### ISSUE THREAD

**Issue by Fab7331** [Mogli12/VehicleControlAddon#283]
bei uns im MP tritt ein lua error auf 

2020-03-08 19:18 Error: Running LUA method 'draw'.
2020-03-08 19:18 C:/Users/fabia/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:2296: attempt to concatenate local 'text' (a boolean value)

und bei der Ganganzeige steht nil

**Comment by Mogli12** [comment]
Kann ich die komplette tog.txt sehen? Tritt am Server oder am Client auf?

**Comment by Fab7331** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4309285/log.txt)
Das is im client. Dann is das ganze Hud auch verbuggt ^^

**Comment by Mogli12** [comment]
Solle mit Version 0.1.1.4 gelöst sein

**Comment by Fab7331** [comment]
Der error is weg und das HUD buggt auch nichtmehr, aber bei der Ganganzeige steht immernoch nil bei jedem Mal neu joinen aufm Server

**Comment by Mogli12** [comment]
Kannst Du das etwas genauer erklären? Wenn Spieler A joint, dann wird bei Spieler A oder bei Spieler B etwas falsch angezeigt?

**Comment by Fab7331** [comment]
Wenn ich joine, wird mir jedesmal nil angezeigt. Einmal die Getriebeart hin und her geschaltet und es wird richtig dargestellt.

**Comment by Mogli12** [comment]
Bitte teste mal Version 0,1.1.9.

**Comment by Fab7331** [comment]
geht :)

**Comment by Fab7331** [comment]
oder auch nicht, jetzt kann ich nichtmehr fahren, wenn ich ein getriebe ausgewählt hab :(

**Comment by Mogli12** [comment]
Ich habe mir schnell einen Server für 30 Tage gemietet. Bei mir läuft es ohne Probleme

**Comment by Fab7331** [comment]
Das Problem sieht wie folgt aus: Alle Bremslichter leuchten, ohne dass man die Bremse drückt. Einmal das Licht durchgeschaltet geht das Licht zwar aus, aber der Lichtschein bleibt. Schalt ich das Getriebe aus, kann ich wieder fahren.

**Comment by Fab7331** [comment]
Das ganze scheint ein Modkonflikt zu sein

**Comment by bgo1973** [comment]
Haste RMT im Ordner?

**Comment by Fab7331** [comment]
nope, scheint was mit global company zu sein

**Comment by Mogli12** [comment]
Probier mal Version 0.1.2.2.
