### ISSUE TITLE
Vehicles do not stop with AD, CP or Helper

### ISSUE THREAD

**Issue by alku50** [Mogli12/VehicleControlAddon#284]
Fortunately there are cracks like you.... I could not imagine playing FS without mods like VCA.
Thanks.   But ..... :-))   I like using "Geschwindigkeit permanent an: on" and "Shuttle control: off"and the new function "Getriebe und Helfer: off". The vehicles do stop but then takeoff again.
What can I do that the vehicle stop at the target of AD, CP and helper?  
Thanks for an answer.

**Comment by Mogli12** [comment]
The problem should be fixed with version 0.1.1.8.

**Comment by alku50** [comment]
Thank you Stefan. The vehicles do reliably stop. It's a big relive.
