### ISSUE TITLE
Problem auf dem Server in Verbindung mit TSX

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#285]
Hi, uns ist auf dem Server aufgefallen das wenn man die shuttlecontrol vom TSX nutzt und den XML Eintrag wie in der Beschreibung angegeben ändert, die shuttlecontrol vom TSX nicht funktioniert. Im SP und normalen MP funktiniert es problemlos.

**Comment by Mogli12** [comment]
Wenn man TSX und VCA nutzt, dann sollte immer Shuttlecontrol von VCA verwendet werden.
