### ISSUE TITLE
Getriebearten und RPM

### ISSUE THREAD

**Issue by DerBauer2** [Mogli12/VehicleControlAddon#286]
Ich habe mir mal wieder deinen Mod herunter geladen um zu schauen was verbessert wurde. Top erst mal. Nun möchte ich ja die Getriebeart einstellen die die Trakoren haben aber finde die passenden nicht oder versth sie einfach Falsch. Zum Beispiel John Deer R6 diese hagen Automatik bzw stufenlos (fahre ich selber in unseren Betrieb) welche wären dies denn um das realistischdar zu stellen?

Was mir wieder aufgefallen ist sind die RPM beim losfahren diese fallen ab und zu unter 700 RPM und dann kommt eine Warnmeldung. Ich fahre nicht mit Lenkrad und Pedall. Könnte es nicht so sein wenn man W o. S Drückst das erst die RPM nach oben gehn und ne sec. später fährt er los, also ehr gesagt kuppellt er zu schnell. 

Eine Idee?

**Comment by DerBauer2** [comment]
Nett das du was gemacht hast aber wolte mit dir über die Getriebearten Sprechen? :)

**Comment by DerBauer2** [comment]
weiß nicht was du geändert hast aber mir säuft nun ständig die kiste ab am schmlimmsten mit frondlader

**Comment by Mogli12** [comment]
Vielleicht waren die Zeiten für das Schließen der Kupplung zu kurz. Außerdem habe ich jetzt die Strömunskupplung freigeschaltet. Die fährt mit höherer Drehzahl an und öffnet automatisch.

**Comment by DerBauer2** [comment]
Okay naja ich weiß nicht also normal bekommste kein Diesel abgewürgt erst recht kein Trecker :D
da müsstest du vlt an dem an fahren was basteln denn wie gesagt das ist nicht möglich denn Leer und ohne Last absaufen zu lasen 👍

**Comment by DerBauer2** [comment]
> Außerdem habe ich jetzt die Strömunskupplung freigeschaltet.

hydrodynamische kupplung   auch nett  das werde ich gerne mal Testen

**Comment by DerBauer2** [comment]
Hier siehst du das Porblem läuft einfach nicht und säuft ab:
https://drive.google.com/file/d/1aFZ6MRsFKsX4ZaWEh9jzx2hOSfIK8gzo/view?usp=sharing

**Comment by Mogli12** [comment]
Meiner Ansicht nach fährst Du im falschen Gang an. Außerdem sind die Fahrzeuge rückwärts auf 15 km/h begrenzt. Wenn das Fahrzeug 65 km/h bei 2200 U/min erreicht, dann sind das nur 508 U/min bei 15 km/h. Leerlaufdrehzahl ist aber 1000 U/min.

**Comment by DerBauer2** [comment]
Wie soll ich im Falschen Gang fahren wenn er auf Automatik ist? Ich schalte nicht.

**Comment by Mogli12** [comment]
Wenn du stehst und dann den Gang wechselst, dann fährt das Fahrzeug in dem Gang an. Automatisch wird es in keinen kleineren Gang schalten. Aber diesen Gang zum Anfahren musst du selber wenigstens einmal festlegen. 

Das 6x4 Getriebe ist auch für Traktoren gedacht. Für LKW passt das 2x6 Getriebe besser.

**Comment by DerBauer2** [comment]
Okay ich werde das noch mal Testen was du meinst
