### ISSUE TITLE
Question: adding support for this mod

### ISSUE THREAD

**Issue by ryanccard** [Mogli12/VehicleControlAddon#288]
I use a couple of mods in FS19 and I'm just wondering what would cause a mod not to support the vehicle control mod, and is there anything I can do to add it myself?

Thank you for the great work on this.

**Comment by Mogli12** [comment]
The vehicle needs the following specializations: "drivable", "motorized", "enterable", "lights" and "wheels". Specialization "attachable" is not allowed.
