### ISSUE TITLE
Kupplungsprobleme im MP

### ISSUE THREAD

**Issue by FloSch02** [Mogli12/VehicleControlAddon#289]
Hallo Zusammen

Bei mir tritt das Problem auf, dass meine Kupplung (ich bin nicht Host, nur Mitspieler) auf 100% geht, wenn der Host im Shop ist oder Texte im Multiplayer schreibt (also immer dann, wenn eingentlich nur sein Fahrzeug Auskuppeln sollte...).

Woran kann das liegen?

V 1.2.1

Besten Dank für die tolle Mod!

**Comment by Mogli12** [comment]
Das ist korrigiert ab Version 0.1.2.2.
