### ISSUE TITLE
Fahren unmöglich

### ISSUE THREAD

**Issue by sehannss** [Mogli12/VehicleControlAddon#290]
Mit dem Update auf 1.2.1 war es nicht mehr möglich ohne Tempomat vorwärts zu kommen.
Das switchen zwischen Leerlauf/Kein Leerlauf hat nur dazu geführt, dass man mit dem Tempomat vorwärts kommt. Allerdings ohne Shuttle Control (ich gehöre nicht zu den Shuttle-Control-Spielern) kann man nicht rückwärts fahren.

Keine Meldungen in der Konsole.

**Comment by Mogli12** [comment]
MultiPlayer? log.txt? Screenshot?

**Comment by sehannss** [comment]
Das Ganze ist auf einem MP-DediServer passiert. Die Log zeigte keine zusätzlichen Einträge.
Einen Screenshot habe ich zu diesem Zeitpunkt nicht gemacht.

Ich habe verschiedene Einstellungen versucht, wie gesagt, mit ShuttleControl etc. Jedoch konnte ich nur mit Tempomat fahren.
Die Parkbremse konnte ich mit der Ö-Taste aktivieren, dann ging gar nichts mehr. Sobald ich diese dann wieder deaktiviert habe, konnte ich wieder mit dem Tempomat fahren. Aber nur mit dem Tempomat.

**Comment by sehannss** [comment]
Nach dem Update auf 1.2.2 funktioniert es wieder auf dem MP-DediServer.
Danke für den schnellen Fix.

**Comment by DickerSauerlaender** [comment]
Danke für das schnelle Update, klappt wieder! <3
