### ISSUE TITLE
Differentialsperre und Allrad / Differential lock and 4WD

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#291]
Hallo Stefan, wäre es wohl möglich in das VCA noch Schalter für den Allradantrieb und die Differentialsperren vorne / hinten einzubauen?
Schon echt genial was du im Laufe der Zeit hier alles reingebaut hast 👍

**Comment by Mogli12** [comment]
Das Thema Allrad und Differentialsperren sehe ich weiter schwierig. Zwar habe ich das Coding aus FS17 vom GearboxAddon, aber das war schon echt knifflig.

**Comment by Bomberman82** [comment]
Es gibt ja das Enhanced Vehicle Mod was man parallel zum VCA laufen lassen kann. Da kann man auch zusätzlich Vor und Rückwärtsgang sowie die einzelnen Allrad Modi einstellen.

**Comment by Williwillswisse** [comment]
Den Mod habe ich wegen Diff und 4WD auch im Einsatz. Aber das Repository ist archiviert und der Mod wird nicht mehr gepflegt. Aus diesem Grund fände ich es toll wenn diese Funktion hier mit einfließen würde. Es braucht auch keine anspruchsvolle Lösung sein und man hätte einen Mod weniger im Ordner.

**Comment by Williwillswisse** [comment]
Danke Stefan :-) , echt genial gemacht !
Ich muss mich nur noch mal durch die Tastenkombis denken was da wie schaltet.
Aber schon mal ein dickes Dankeschön an dich.

**Comment by Mogli12** [comment]
StrgL Ä schaltet zwischen Vanilla, 2WD und 4WD um. StrgL + sperrt die Vorderachse, aber nur bei 4WD. Und StrgL # sperrt die Hinterachse bei 2WD und 4WD.

**Comment by Williwillswisse** [comment]
Danke, was ich bis jetzt getestet habe funktioniert echt super.
![image](https://user-images.githubusercontent.com/47098121/81038036-ff772300-8ea4-11ea-872d-4b237e15e0d3.png)
Da scheint noch ein Eintrag zu fehlen ?

**Comment by Mogli12** [comment]
Ja, es ist noch nicht fertig. Aber da es schon funktioniert, wollte ich schauen ob es gefällt.

**Comment by Williwillswisse** [comment]
Es gefällt sehr
;-)

**Comment by tomy852** [comment]
Sehr cool gemacht Danke. Wirst du die Hydraulik Steuerung auch noch einbauen wie beim Enhanced Vehicle Mod? Diese finde ich auch noch praktisch :D

**Comment by Williwillswisse** [comment]
Zu ist ja noch nicht fertig:
Auf dem Dedi Server wird das Symbol noch nicht angezeigt ?

**Comment by Evilman2517** [comment]
Sehr geil, vielen Dank, dass du die Differentialfunktionen eingebaut hast. Sieht super aus und noch viel wichtiger, fährt sich einfach klasse.

Kann bestätigen, auf dem Dedi werden die Symbole für das Differential nicht angezeigt, im Menü kann ich AntiSlip und Co einstellen, aber es taucht bei keinem Fahrzeug auf.

SP ist alles super

**Comment by SuperSeba** [comment]
Vielen lieben Dank für die Erweiterung. Funktioniert im SP einwandfrei.

**Comment by Mogli12** [comment]
Ich habe nochmal einziges in Build 144/145 geändert. Man muss jetzt über Strg C ein den Einstellungen den Allradantrieb auf manuell stellen.

**Comment by Williwillswisse** [comment]
Typisch Stefan mal wieder....
Traktionskontrolle....
.....Voreilung der Vorderachse....
.....Front- oder Heckantrieb ......
Ganz oder gar nicht.....so wollen wir das haben!!!

1+ mit Auszeichnung und Sternchen
Danke

**Comment by Williwillswisse** [comment]
....Ups, gerade noch auf meinem Dedi getestet.
Dort erscheint jetzt die Grafik, aber die Sperren und Allrad lassen sich nicht schalten.

**Comment by Evilman2517** [comment]
Also ernsthaft, das heutige Update ist wirklich der Hammer, bin schwer begeistert.
Kann den Fehler auf dem Dedi bestätigen, Grafik ist jetzt da, aber weder Allrad noch die Differentiale lassen sich aktivieren. Wenn Differentiale im VCA Menü aktiviert wurde, fahren die Fahrzeuge immer im 2WD Modus

**Comment by Mogli12** [comment]
Jetzt sollte es auch in MP funktionieren. onPostLoad scheint nur auf dem Server zu laufen.

**Comment by Williwillswisse** [comment]
Hallo Stefan, habe gerade mal schnell runtergeladen.
Gehen die Differentialsperren bei 20 km/h automatisch raus?

**Comment by Mogli12** [comment]
Ja, und Allrad bei Voreilung auch. Ich bin mir noch nicht ganz sicher, ob es auch automatisch wieder angehen soll. Gestern bin ich so 2-mal fast stecken geblieben...

**Comment by Williwillswisse** [comment]
Könntest du da in den Settings nicht einen Schalter einbauen? Dann kann jeder selbst entscheiden.
Automatisch wieder einschalten wäre auch Klasse. Wenn vorgewählt und schneller als 20 km/h könntest du die Differenziale ja gelb einfärben damit man das erkennt.

**Comment by cabmac** [comment]
Hallo...wirklich klasse Sachen mal wieder mit dem Allrad....ich waere auch dafuer, den Allrad wieder automatisch angehen zu lassen...ist mir jetzt auch mehrmals passiert auf dem Acker, dass ich wieder vergessen habe, den anzustellen...

Schoene Gruesse,

Claudio

**Comment by Mogli12** [comment]
Wenn man Allrad oberhalb von 20 km/h abstellt und wieder einschaltet, sobald man langsamer fährt, dann stellt das ja niemand mehr aus. 

Man könnte auch eine Warnung einblenden, z.B. zu schnell für Allrad?

Ohne Voreilung der Vorderachse bleibt Allrad zumindest an.

**Comment by Evilman2517** [comment]
Finde ich perfekt so. Ansonsten hat man wirklich keinen Grund es an- und auszuschalten

**Comment by Mogli12** [comment]
We ist es denn im echten Traktor. Ich habe irgendwo gelesen, dass es sich dort automatisch abstellt. Bleibt es auch aus?

**Comment by Evilman2517** [comment]
Das ist höchst unterschiedlich und lässt sich nicht pauschal beantworten. Es gibt Fahrzeuge mit permanenten Allrad (also immer an), es gibt Fahrzeuge mit zuschaltbarem Allrad und auch da gibt es welche, bei denen bleibt es an und welche da geht es aus ab einer bestimmten Geschwindigkeit. Du musst du wohl einen Kompromiss fürs Gameplay finden. Meine persönliche Meinung, so wie es jetzt ist, ist es perfekt.

**Comment by LS15-17-19Farmer** [comment]
Hallo Mogli12

Ich nutze deinem Mod schon lange und finde ihn Super, aber seit der Version 9.1.4.4 die gestern erschien ist er nicht mehr mit der Hof Bergmann 1.0.0.6 kompatibel.
zwar kann man die Map starten aber nur über Task-Manger wieder beenden.

Das gleiche Problem gab es auch mit dem TSX_EnhancedVehicle wo Ifko[nator] ein Fix in die Map eingebaut hat.
Aber er meint ich soll mich diesmal an dich wenden.
folgende Meldung in der Log nach dem Start:
020-05-07 17:58 C:/Users/Andy/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:2390: bad argument #2 to 'format' (number expected, got nil)

Kann mich im Spiel dann nur noch im Esc Menü bewegen.

Und beim Beenden mit Task Manger folgende Meldung:
2020-05-07 17:58 dataS/scripts/gui/hud/HUDElement.lua(216) : attempt to index field 'overlay' (a nil value)
2020-05-07 17:58 Error: Running LUA method 'update'.
2020-05-07 17:58 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
2020-05-07 17:58 Error: Running LUA method 'draw'.

Würde mich freuen wen du dir es mal anschaust.

Gruß
LS15-17-19Farmer

**Comment by Evilman2517** [comment]
@LS15-17-19Farmer da es sich um ein gänzlich neues Thema Handel solltest du eher ein neues Issue aufmachen. Hier geht es um die neuen Differentialfunktionen.

**Comment by LS15-17-19Farmer** [comment]
Hallo Evilman2517

Das gehört hier zum Thema den die Differentialsperre+Allrad ist der Grund dafür, wie schon gesagt war es auch beim TSX_EnhancedVehicle.
Den Farmer Andy nutzt zB: für seine Mischfutter u. Schweinefutter Herstellung das Fahrzeug Script von Giants um in die Geräte einzusteigen darum kommt es zu konflikt mit Differentialsperre+Allrad
den die Geräte sind fest verbaut.

Gruß
LS15-17-19Farmer

**Comment by Mogli12** [comment]
@LS15-17-19Farmer Bitte lege ein neues Issue an. In diesem Issue ging es weder um Fehler in der log.txt noch um die Hof Bergmann Karte. Diese ist meiner Ansicht nach weder mit AIVE noch mit VCA kompatibel.

**Comment by LS15-17-19Farmer** [comment]
Hallo Mogli12

Hab mich gestern erst bei GitHub Registriert, weiss noch nicht wo was hin muß nehm es mir nicht Übel.
Auf jeden Fall hat deine Änderung Build 148/149 FS19_VehicleControlAddon/vehicleControlAddon.lua Zeile 2390,2391 und 2410-2414 Abhilfe geschafft, Map lässt sich wieder normal starten und beenden ohne Log fehler.
Erstmal Danke dafür!!

Nun zum zweiten im Build 148/149 wird das Icon für Differentialsperre und Allrad nicht mehr eingeblendet auch wenn ich in der Einstellung auf ja stelle

Gruß
LS15-17-19Farmer

**Comment by Evilman2517** [comment]
Hast du das Fahrzeug / den Motor gestartet?

**Comment by loenne-michel** [comment]
Hi... ich kann bestätigen, daß das Allrad Icon im MP nicht angezeigt wird. Auch lassen sich Allrad und Sperren nicht schalten. Motor ist an und Allrad/Sperre manuell ist ausgewählt. Im SP funktioniert alles.
Habe 149 heruntergeladen und auf dem Server. In der modDesc steht allerdings noch 148.
Grüße...Micha

**Comment by LS15-17-19Farmer** [comment]
Hi Evilman2517 
Fahrzeug/ Motor ist gestartet nur das bei mir auch im SP nicht angezeigt wird.
Gruß
LS15-17-19Farmer

**Comment by MichalKucavik** [comment]
My insights into the VCA feature:
**1.** Great decision to incorporate this feature in VCA, finally I can also uninstall mod enhanced vehicles and i can use only VCA. 
**2.** Icons in the VCA menu and in the HUD look really great.
**3.** The vehicle has too much traction when driving one axle - on a unpaved road with a full trailer, every hill on the map will come out without losing traction (the need to use 4WD is then minimal)
**4.** When is driving one axle (rear), the wheels also engage the other (front) axle  - when viewed from the outside of vehicle, you can see how they are visibly turning and oversteering (which should not be driven at that time)
**5.** When is activating differential lock, the wheels on both sides of the axle (left and right) should have exactly the same speed.
**6.** Would it be possible to add in the VCA menu to choose what type of drive the vehicle has?
- FWD (cars, harvesters, forklifts, etc.)
- RWD (some cars, trucks with 4x2, 6x4 drive, etc.)
- 4WD (4x4, 6x6, 8x8), and based on that it would then be possible to activate the drive and differential lock of the axle?  It is unrealistic if I have for example MAN with a 6x4 drive and I can activate both the front axle drive and the differential lock on it anyway.

**Comment by Evilman2517** [comment]
@LS15-17-19Farmer welches Fahrzeug nutzt du?

**Comment by LS15-17-19Farmer** [comment]
Hallo Mogli12/Evilman2517

Hab nochmal alles ausprobiert Icon wird bei mir jetzt wieder angezeigt.
Auslöser ist der TSX_EnhancedVehicle, die Differentialsperre und Allrad anzeige von beiden zusammen gibt es konflikte, entweder TSX_EnhancedVehicle aus dem Modordner nehmen oder
in der modsSettings TSX_EnhancedVehicle_v1 die differentialIsEnabled="true" auf false stellen.

Gruß
LS15-17-19Farmer

**Comment by Mogli12** [comment]
Differentialsperren funktionieren nur, wenn sie im Fahrzeug nach dem erwarteten Muster verbaut sind. Das wäre:
- Genau ein Differential => RWD
- 3 Differentiale, die ersten zwei verwenden nur Räder, das dritte verwendet nur Differentiale
- 7 Differentiale, die ersten vier verwenden nur Räder, die letzen drei verwenden nur Differentiale
VCA steuert dann jeweils die letzen drei Differentiale.

Wahrscheinlich muss ich noch weitere Muster hinzufügen.

**Comment by Mogli12** [comment]
VCA Allrad geht natürlich nur, wenn TSX Allrad nicht an ist.

**Comment by loenne-michel** [comment]
Danke für den Tipp mit TSX Allrad. Hab TSX vom Server genommen. Jetzt funktioniert es!

**Comment by Snottus** [comment]
Stefan, you are amazing - vielen dank!
Any chance you could add an option in the settings screen to manually adjust at which speed the AWD is disconnected? My preference would be 30 kmh instead of 20.

**Comment by Mogli12** [comment]
Hi,

In Version 149 habe ich nochmal einiges geändert. Wenn Allrad aus ist, dann werden die entsprechenden Differentiale aus der Physik genommen. Ansonsten kam es immer wieder zu Fehlern.

VCA sortiert sich nun die Differentiale nach
- Steuert nur gelenkte Räder
- Steuert nur ungelenkte Räder
- Steuert andere Differentiale, die gelenkte und ungelenkte Räder enthalten
- Alles andere führt dazu, dass VCA es nicht untersützt

Damit sollten jetzt recht viele Fahrzeuge unterstützt werden,

Fahrzeuge mit Crawler gehen grundsätzlich erstmal nicht.

Viele Grüße

**Comment by Mogli12** [comment]
Hi,

I re-implemented the differentials in build 149. If AWD is off then the disabled differentials are removed from physics. 

And VCA sorts the differentials:
- with steerable wheels
- with fixed wheels
- differentials using differentials with both wheels
- everything else disabled VCAs diffs

Most vehicles should work now. But vehicles with crawler spec. are not supported at all.

BR

**Comment by Williwillswisse** [comment]
Hi Stefan, funktioniert soweit super.
Was mir noch aufgefallen ist sind anscheinend die Knicklenker.
Beim Claas Xerion aus dem Claas DLC und dem Vanilla New Holland T9 lässt sich nur die Vorderachse einschalten (Tausch der Differentiale auf An). Stelle ich diesen Parameter auf Aus verschwindet das Symbol komplett.
Bei Radladern ist es mit Vorder- und Hinterachse genau anders herum.

**Comment by Evilman2517** [comment]
Der Xerion ist aber kein Knickenker

**Comment by Mogli12** [comment]
Wenn das Fahrzeug Crawler hat, dann geht es erstmal nicht. Vermutlich reicht die Möglichkeit, es zu konfigueren.

**Comment by Evilman2517** [comment]
Mir ist gerade eine Kleinigkeit aufgefallen, leider "merkt" sich VCA momentan nicht die manuellen Differentiale (getestet SP und lokales MP). Nach jeden Neustart muss man die Differentiale im VCA-Menü wieder auf manuell stellen.

**Comment by Evilman2517** [comment]
Perfekt, die Einstellungen werden nun im SP, lokalem MP und auf dem Dedi korrekt gespeichert und sind dann beim nächsten Spielstart weiterhin aktiv. Danke für den schnellen Fix.
