### ISSUE TITLE
General Error

### ISSUE THREAD

**Issue by SZGActosa** [Mogli12/VehicleControlAddon#292]
Version Number: 0.1.2.5?
Used Vehicles: 5
Vehicles with issue: In-Game Case IH 2710 Pro
                             Modded MAN TGS 18.500 4x4
                             In-Game Fendt 1159 MT 
                             In-Game New Holland L218

On my Harvster, the Case IH 1660 Mod, it works without problems just the rest of the Machines wont budge

Pastebin Log :   https://pastebin.com/263v9LBN

**Comment by Mogli12** [comment]
???

**Comment by SZGActosa** [comment]
Ok erstmal entschuldigung für die schlechte ausführung, habe aktuell viel stress mit unsrem tollen Virus...

Habe ganz vergessen das Problem zu beschreiben... Mein Fehler.


Ich hatte den Mod für 20 Minuten am laufen, dann aus dem nichts haben die Traktoren aufgehört zu laufen, der Drescher funktioniert immernoch.

Die Traktoren liefen nach einem neustart wieder problemlos , nur ohne Modfunktionen

**Comment by Mogli12** [comment]
> Ich hatte den Mod für 20 Minuten am laufen, dann aus dem nichts haben die Traktoren aufgehört zu laufen, der Drescher funktioniert immernoch.

Was meinst Du mit "...haben die Traktoren aufgehört zu laufen..."? War der Helfer an?

**Comment by cabmac** [comment]
Moin, wenn ich mich einschalten darf, bei mir liefs gestern bestimmt 5 Std ohne jeglichen Fehler.

Schoene Gruesse

**Comment by SZGActosa** [comment]
Ok danke für die schnelle Hilfe, ich kann mir nicht erklären warum aber nach löschen aller Mods und nur neuinstallation von VCA läuft alles problemlos...

Trotzdem danke für die Hilfe :)
