### ISSUE TITLE
Eigenes Getriebe zusammen bauen

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#293]
Hallo Mogli12

Erst mal möchte ich mich für die Mod bedanken. Mach echt Spaß damit zu spielen.

Jetzt zu meiner Frage bzw meinem Problem. Ich versuche, seit dem ich die Mod kenne, das passende Getriebe für LKW's zu finden. In der Regel spiele ich mit dem 6 Gang incl. Splitter Getriebe zu spielen. Seit dem neuen Update bin ich aber auf eigenes Getriebe umgestiegen.

Leider bin ich zu doof um zu bedienen. Schau am besten das Video an.

https://youtu.be/7iXbAkZPm2A

Sind meine Einstellungen falsch oder warum werden einige Gänge übersprungen?
Hab auch 2x6 Getriebe ausprobiert. Ist viel besser als mein Getriebe.

Trotzdem möchte ich verstehen warum es mit meinem Getriebe nicht funktioniert.

Vielen Dank für deine Hilfe

**Comment by Mogli12** [comment]
Ich schaue es mir an.

**Comment by Michael170978** [comment]
Alles klar probiere ich aus. Ich hab spaßeshalber die Übersetzung 1. Gang in vorletzter Gruppe geändert. Ich merke aber keine Unterschied. Wo zu ist die Option denn gut? Ich meine was bewirke ich  wenn ich die Übersetzung verkürze bzw. verlängere?

**Comment by Mogli12** [comment]
Du hast nur 1 Gruppe, deshalb haben die Werte dann keinen Sinn.

**Comment by Merrlin** [comment]
Ich glaub, da kann ich ein bißchen Helfen. Ich fahr in der Arbeit nen TGS 18.440. Der hat (wie fast alle MAN bis BJ 2019) ne ZF AsTronic 12 Gang Automatik verbaut.
Die haben ein bißchen Intelligenz und passen ihre Schaltstrategie der Topologie der Beladung und dem Fahrerwunsch Kind Grenzen an.

Das Volle Fahrzeug fährt in der Ebene mit G2 an, das leere mit G4. Je nach Fahrpedalstellung geht die Drehzahl dann bis 1300 bis 1700 U/min hoch und springt dann 1-2 (ohne Gas 3) Gänge runter, also im Bereich zwischen 850 und 1700 U/Min.
In starken Steigungen schaltet das Getriebe in 1 (voll) - 3(leer). Ohne Gasgeben bleibt die Kupplung auch offen.
Das passiert wenn man das Getriebe auf D stellt.
Dann gibt es noch die Manöverstellungen Dm und Rm. Da dient das Fahrpedalauch  als Kupplungspedal. Bis ca. 75% wird die Kupplung geschlossen, von 75% bis 95% wird dann die Drehzahl von 650 uMin bis 1100 uMin erhöht. Bei letztgenannten Drehzahlen bin ich mir (insbesondere bei den 650) nicht ganz sicher
