### ISSUE TITLE
Trisix issue

### ISSUE THREAD

**Issue by Bigmack73** [Mogli12/VehicleControlAddon#294]
when the VCA mod is active. trying to start the engine in the trisix, it crashes the game.
after disabling the VCA mod, it doesn't crash.

**Comment by Mogli12** [comment]
The Trisix is not an official mod, right?

**Comment by Bigmack73** [comment]
Its one of those mods that has been converted over from FS17. 

And one that I can survive without. lol

**Comment by Mogli12** [comment]
Is there an error message in log.txt?

**Comment by Bigmack73** [comment]
did not see any at all, the mod looks clean. I have asked others about it. it seems to be just me experiencing this issue.

**Comment by Mogli12** [comment]
I do not think that VCA can crash the game.
