### ISSUE TITLE
Some wishes

### ISSUE THREAD

**Issue by MichalKucavik** [Mogli12/VehicleControlAddon#297]
At first, thank you for your great mod!

A have some wishes:
1. add in VCA menu **"enable/dissable" for auto hold** => add manual neutral with gear shifters _(G25/G29/Trustmaster)_ and manual parking brake off.
2. add in setting menu in FS19 another button for parking brake => parking brake on and brake off _(for using homemade SIM hand brakes)_.
2. change place for parking brake indicator - because of overlap with shuttle arrows and poor visibility
3. **add a gearbox** "2x6 gearbox + splitter" or (2x4 gearbox + splitter)
4. add in settings in menu FS19 another button for gear splitter => it will be 2 buttons - gear splitter Hi and gear Splitter Lo (for using gear shifter knobs from trucks)

Thank you so much
Michal

**Comment by Mogli12** [comment]
Hi Michal,

4. Sorry, but VCA is limited to one set of gears and one group of ranges.
5. I propose to try out "6G, R+/-, 1R" or "6G, R+/-, Shuttle". It allows you to use buttons vcaShifter7 and vcaShifter8 to shift range down or up. Action vcaShifter9 is for reverse.

I will look at the auto hold / park break stuff. But keep in mind that VCA was never meant to be a super realistic gearbox simulation. It will always be a compromise.

Best regards,
Stefan

**Comment by Mogli12** [comment]
3. It would too much work to have a park break with the G27 logic. But with v0.1.2.7 the input binding for vcaNEUTRAL will toggle the park break.

**Comment by MichalKucavik** [comment]
Thank you for your response and for adjusting the parking brake. Now it works better, you have to release the brake manually.
1.  But the problem is that, it is not necessary to activate the handbrake, because Auto hold is automatically activated after stopping and the tractor does not move, not even down the hill and you take your foot off the brake. It would be nice if the menu could be set to deactivate the autohold and its not activate after stopping.
I know that the VCA is not supposed to be an explicitly realistic transmission, but is already close enough to it.

2. And this is possible?
"change the parking brake indicator - because of overlap with shuttle arrows and poor visibility"
 Change the place for parking brake indicator, or do not show shuttle arrows during hand brake activation.

3. would it be much work to add a function (or to create a mode itself), in which all the equipment connected to the tractor (hydralic or power-driven) could only be used after the engine was started?

**Comment by Mogli12** [comment]
1. Maybe in a future version
2. These are individual icons. Right now I want to keep them as they are
3. This does not fit into VCA

**Comment by MichalKucavik** [comment]
1. Hi, thank you very much for version 1.31. Although the tractor is not on a large slope, although it does not tend to drive down the hill itself, but even now the ride is much more realistic ... Thanks a lot.

2. OK I understand. It would be enough just that the shuttle arrows do not appear when the handbrake is applied.

3. It was more of a question for you as an expert on mods, if it would be difficult to do.

**Comment by Anonymous-any** [comment]
Hi Stephan,

I search with no success about how to increase faster the auto hold / park break stuff, is there any command I can add to config.xml ?

Danke

**Comment by Mogli12** [comment]
Hi,

Currently, auto hold is activated after 1 second. This is hard coded. I will add a new value to config.xml (autoHoldTimer) with the next build (197).

Regards,
Stefan

**Comment by Anonymous-any** [comment]
Hi Stephan,

Glad ! Yes I saw it was not easy to add or found to tweak contrary to GearboxAddon :)
Many Thank Maestro I really wait for it ;) next time.
Keep up ! Br

**Comment by Anonymous-any** [comment]
Hello Stephan, 
Hey you on modhub today ^-^, question again, I read you write "disable auto hold via config (autoHoldTimer 0)" but how I simply increase faster ? how the value is bool, float, or the other one ?
Br

**Comment by Mogli12** [comment]
Hi,
You find an example in the modSettings folder here on github:
```xml
	<autoHoldTimer       type="int"   value="1000"/> <!-- ms; 0 = no auto hold -->
```
If you use `value="0"` then auto hold is off.
BR
