### ISSUE TITLE
Einfach mal wieder Danke!!!! sagen....

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#298]
Hallo @Mogli12, 

das letzte Update nur noch Zucker, 1. die Möglichkeiten die du eingebaut hast und 2. die Funktion die Fahrzeuge lassen sich nun Butterweich fahren und sind sehr unterschiedlich zu Hand haben. 

Es ist einfach nur noch Geil!!! Habe wieder soooo viel spaß am Trekker fahren, wie schon lange net mehr. Danke dafür. 

Eine Klitzekleine Frage zum HUD wie kann ich die Anzeige soweit ändern das ich nur die Getriebeart anzeigt alles andere brauche ich nicht wirklich nur die Getriebeanzeige wäre nice???. 

Danke im Voraus Stefan 

Stefan....hmmm wenn ich dir sagen würde wie ich heiße würdest du lachen ;)

**Comment by tomy852** [comment]
Dem Danke möchte ich mich direkt anschliessen. Es sind die Mods wie dieser die das Spiel erst so richtig zum "Simulator" machen. 
Bitte weiter so :)
