### ISSUE TITLE
error: lua:4013

### ISSUE THREAD

**Issue by astro80** [Mogli12/VehicleControlAddon#299]
FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:4013: attempt to perform arithmetic on global 'launchSpeed' (a nil value)

**Comment by Mogli12** [comment]
Please post the complete log.txt in [gist](https://gist.github.com/)

**Comment by astro80** [comment]
https://gist.github.com/astro80/85787e22607a83cf9c6e1a3ef77c1aa4

**Comment by Mogli12** [comment]
Please try the latest version
