### ISSUE TITLE
Automatische Erkennung der Arbeitsbreite / Automatic detection of the working width

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#300]
Hallo Stefan,
wäre es wohl möglich beim GPS als Option eine automatische Erkennung der Arbeitsbreite einzubauen? Das wäre sehr hilfreich. Die Möglichkeit den Wert von Hand einzugeben sollte dann zur Sicherheit erhalten bleiben wenn mit der Automatik mal was nicht klappt.

**Comment by Mogli12** [comment]
Einfach das Textfeld leer machen und Enter drücken...

**Comment by Williwillswisse** [comment]
Ha, da muss man erst einmal drauf kommen. Hidden Features ;-)
Danke für die schnelle Antwort.

**Comment by Williwillswisse** [comment]
So, ich habe gerade noch mal getestet. Bei mir übernimmt er die Breite nicht.

**Comment by Williwillswisse** [comment]
Ich habe noch mehr getestet. Man muss das Eingabefeld nicht leer machen sondern eine Null eintippen und dann Enter.
Dann funktioniert es.
Danke nochmal für deine schönen Mods und den Support.
Hier mache ich jetzt zu.
