### ISSUE TITLE
Don't see GPS Lines/GPS Linien nicht mehr sichtbar

### ISSUE THREAD

**Issue by Fuzzy86** [Mogli12/VehicleControlAddon#301]
Sehe die GPS Linien nicht mehr. Habe es auch ohne Mods auf der Felsbrunn versucht jedoch sind sie da auch nicht zu sehen. In den Einstellungen bei "Anzeige  der Rasterbahn" ist auch egal was man da drückt. Habe ich da irgendwas übersehen?

Ich bitte um Hilfe

lg

Version: 0.1.2.7

**Comment by Mogli12** [comment]
Hi, bitte kontrolliere die Arbeitsbreite in den VCA Einstellungen.

**Comment by Fuzzy86** [comment]
Super danke das war es. Es war auf null! Nutz die GPS Funktion nämlich um AD Kurse auf geraden ein zu fahren.

Danke für die Rasche Antwort
lg
