### ISSUE TITLE
Gear/Range swap

### ISSUE THREAD

**Issue by TanteGretti** [Mogli12/VehicleControlAddon#302]
hallo mogli 
Erstmal danke für diese mod, wieder mal klasse arbeit!!!

Hätte nur eine frage:
Ist es zum jetzigen zeitpunkt irgendwie möglich mit dem th8a shifter nicht die Gänge sondern die Gruppen zu schalten?
Schaffe es iwie mit den jetzigen Einstellungsmöglichkeiten nicht.
War ja im gearbox addon auch so?
Oder verstehe ich da was falsch?
Quasi die Gruppen mit dem shifter und die Gänge als lastschaltstufen mit den knöpfen am Schaltknauf - 32x32 Lastschaltgetriebe

**Comment by Bomberman82** [comment]
Der th8a hat doch keine Knöpfe am Schaltknauf?!?. Ich meine i nutze selber den Shifter und da habe ich nur den reinen 7Gang + R zum schalten. Und die Einstellungen kann ich ohne Probleme intern im Spiel einstellen. Ich habe es in der Vergangenheit mal so eingestellt das ich die beiden letzten Gänge des Shifters zum schalten der Gruppen missbraucht habe, war mir dann umständlich also nutze ich die Knöpfe am Lenkrad. Andernfalls bietet das VCA ordentlich viele Anpassungsmöglichkeit wie man Schalten will. Sollte eigentlich kein Problem sein es im Optionsmenu einzustellen oder?!?

**Comment by JASNDE** [comment]
Ich hab auch den TH8A und ich weiß schon was TanteGretti vorhat. Leider geht es momentan nicht, die z.B. ersten 6 Gänge des Schalters auf die ersten 6 Ranges zu verteilen, einfach weil es dafür keine Inputs gibt. Gänge gehen direkt, Range nur up/down. 

Ein JohnDeere PowrQuad hat aber z.B. 6 Ranges die mit der H-Schaltung geschaltet werden, und 4 Gänge die per Knopf gehen (oder automatisch). Knopf ließe sich auch anderweitig ändern, oder man besorgt sich/hat einen anderen knauf mit Knöpfen.

Direkte Inputs für 6 Ranges wären super.

**Comment by Mogli12** [comment]
Hallo,

das geht leider nicht. Aber mit dem Getriebe "own" kommt man nah dran:
[screen shot](https://github.com/Mogli12/VehicleControlAddon/blob/master/Documents/ownTransmission.png)
Den G27 Modus muss man dazu auf "6G, R+/-, Shuttle" stellen.

Viele Grüße

**Comment by JASNDE** [comment]
Hm, das wäre eine Option.

Ich hab mein Getriebe aus meiner transmissions.xml mal umgerechnet, eigentlich sollte das andersrum (gänge=ranges und umgekehrt) auch funktionieren. Mal testen heute abend.

Damit das halbautomatisch funktioniert (Gänge per Hand, Ranges auto), auf was muss die Einstellung im Menü dann stehen, Automatik AN oder AUS?

**Comment by Mogli12** [comment]
´autoShiftGears="false" autoShiftRanges="true"`

**Comment by Mogli12** [comment]
Probier doch mal "own transmission". Im Beispiel habe ich 58 als theoretische Endgeschwindigkeit gewählt. Die Abstufung zw. Lastschaltsufen ist meistens 0,8 oder 1,25 in der anderen Richtung. So bin ich auf 47 km/h in der vorletzen Gruppe gekommen. Damit die 6  Gänge einen großen Bereich abdecken habe ich 3 km/h für den 1, Gang genommen. das sind dann 1,77 km/h im Gang 1 in der kleinsten Gruppe.

**Comment by JASNDE** [comment]
Danke! Ich werds testen, die 0,8 pro Range sind nah genug am echten Getriebe, dass das klappen könnte.
