### ISSUE TITLE
Probleme mit AD Abfahrer Modus

### ISSUE THREAD

**Issue by Fuzzy86** [Mogli12/VehicleControlAddon#303]
Hy! Habe soeben festgestellt das der VCA sich mit dem AD Drescher Abfahrer nicht verträgt.

Normal setzt der AD Abfahrer nach dem Drescher Abtanken ein paar Meter zurück damit der Drescher wieder weiter fahren kann. Mit dem VCA funktioniert das aber nicht. Auch nicht wenn die Getriebe Helfer Einstellung auf Off ist. Er ruckelt nur mm weise vor fährt aber nicht zurück.

lg

**Comment by RalfGorden** [comment]
hallo hab das selbe Problem leider

**Comment by gerrit0476** [comment]
Das gleich habe ich auch! So kann ich VCA gerade nicht nutzen! 
Hoffe du findest den Fehler bald!

Und danke für deine Super Arbeit!

**Comment by caplink811** [comment]
Morning,

die Frage ist, wird hier der richtige Baum angebellt? M.E. trifft das alle Mods, die Shuttle Control verwenden, nicht nur VCA.

ciao 
 JrB

**Comment by Fuzzy86** [comment]
Hey caplink811, das sehe ich nicht so weil der TSX_EnhancedVehicle Mod hat auch shuttle Control den ich deaktiviert habe und da geht es doch auch

**Comment by caplink811** [comment]
Morning,
so sind die Erfahrungen unterschiedlich, TSX macht bei mir Shuttle Control, VCA Rollwiderstand und GPS (also SHuttle Control deaktiviert), und da verweigert sich AD dem zurückstoßen...
Ich habe verschiedene Kombinationen probiert, und das Ergebnis war, das AD funktioniert, und Shttle Control in allen Mods deaktiviert war. In dem Moment, wo Du SC auch nur einschaltest, selbst wenn das Fahrzeug nur rumsteht, passiet irgendwas, und AD schmollt. (für letztere These hab ich leider keinen Videobeweis)

ciao
 JrB

**Comment by Mogli12** [comment]
Probiert mal version 0.1.3.1. Eventuell fährt AD zu langsam um die automatische Bremse zu lösen.

**Comment by caplink811** [comment]
Morning,
danke für den Tip, 
V0.1.3.1 - TSX nicht geladen, VCA mit Shuttle Control, nach dem abtanken bleibt AD mit dem Wunsch zurückzusetzen vom Drescher "hängen"... 
Warte ich halt auf einen CP Mode 2 der LS17 Niveau erreicht, oder spiele kleine Karten :-)

ciao JrB

**Comment by Mogli12** [comment]
Helferbetrieb schaltet ShuttleControl aus. Ich vermute mal, dass AD vergessen hat, das Fahrzeug auf Helfer umzustellen.
