### ISSUE TITLE
Mouse/keyboard interference(?)

### ISSUE THREAD

**Issue by kandk1** [Mogli12/VehicleControlAddon#304]
Hi Mogli.
Thank you for creating this awesome and most important (at least for me) mod for FS19.
I have an issue though, but as i can't find anything about it anywhere, it seems like this is at my end.
That said, this only happens with the VCA installed (also with VCA as the only mod in mod-folder) so i thought you might have an idea what could cause this.

Issue: If i click any of the mouse-buttons, or the G on my keyboard, the vehicle suddenly slows down, as if it were braking. If i click once, the rpm drops and then rise again. If i continue pushing the buttons, it will bring the vehicle to a halt.
This does only happen when using the throttle pedal, not when using cruise control.
Also, when i push these buttons, i san see the driver placing his foot on the clutch and brake, so that's why i think there might be some interference.
I tried resetting and remapping inputs and also unplugging the joystick but to no avail.

I'm using a Logitech Driving Force GT and Saitek AV8R-01.
Thanks in advance for any tips or solutions you might have. and again, thanks a lot for this immersive mod.

**Comment by Mogli12** [comment]
Hi,
I think Giants still has some problems with inputs. Sometimes, it helps to rename inputBinding.xml. The mod is simply registered to action bindings. So I cannot help here.
Best regards
