### ISSUE TITLE
Gear Problem

### ISSUE THREAD

**Issue by adamc2001** [Mogli12/VehicleControlAddon#305]
When i get into a tractor it drives itself even when my gearstick is in neutral. How can i fix this?

**Comment by Mogli12** [comment]
Enter a gear and then go to neutral again

**Comment by adamc2001** [comment]
that is what i am doing currently but it is kind of annoying when i tab to a tractor and it drives away on me. Keep up the good work its a great mod.

**Comment by Mogli12** [comment]
Please try v0.1.2.9.
