### ISSUE TITLE
Einstellung werden nicht gespeichert

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#306]
Hallo,
danke erstmal für den tollen Mod, ich hab aber das Problem, dass meine Einstellungen bei einem Neustart wieder weg sind. Ich schalte z.b. das Getriebe immer auf "off", nach dem Neustart steht es wieder auf "IVT"
Auch die globals in der config.xml werden nciht übernommen.
Hab jetzt einfach mal die Werte in der vehicleControlAddonConfig.xml an meine Bedürfnisse angepasst, nun läuft es so wie ich will.

**Comment by Mogli12** [comment]
Keine log.txt, kein Screenhot => ich kann nicht helfen

**Comment by Caamo** [comment]
Global settings resets at every gamestart.
Config.xml is now totally useless...

**Comment by Mogli12** [comment]
Still no log.txt attached => closed
