### ISSUE TITLE
Shifting problem

### ISSUE THREAD

**Issue by mielman** [Mogli12/VehicleControlAddon#307]
I can't seem to shift up a range/gear in any way.
When I put the transmission in automatic (hexashift or 6x4 powershift) I can shift down a range once, but then none of the shifting buttons do anything for me, which means I'm stuck in either A 6 or D 1. Changing the key mapping does not solve the problem. Choosing another gearbox for the vehicle does, until I try to change gears/range again.

EDIT: I'm using a keyboard & mouse combination, btw.

**Comment by Mogli12** [comment]
Sorry, but what should I do if you have problems with your action bindings, You can try to rename inputBinding.xml.

**Comment by ExocetC3i** [comment]
@mielman check for overlapping keybindings for ] and \ from Courseplay and remove those. Recent dev versions of Courseplay use those keys as defaults for the course editor feature. If you clear those bindings you'll be able to shift/range up again (problem happened to me too).

**Comment by mielman** [comment]
Thanks @ExocetC3i, That seemed to have been the problem.
