### ISSUE TITLE
Config.xml

### ISSUE THREAD

**Issue by Caamo** [Mogli12/VehicleControlAddon#308]
So you closed the open issue about useless config.xml.
Well.. absolutely NOT my problem. It's your mod :D  
I already fixed it by myself, but for others who use your mod, it might still be a big problem ;)
Anyways... I didn't need your help. It was someone else :)
I hope you see it yourself, because there IS a problem. You don't need a fucking log.txt for it. You can see it if you just look at it :D
Your config.xml just is useless now. It keeps resetting, no matter what.
With or without other mods. AND it only saves the settings you change, not all settings.
Still next time you start a new game, it has been reset again ;)
You can close this too if you like. It's your problem, not mine :D 
But if you want to help others, you might just have to fix it ;)
Have a nice day! :D :D :D

**Comment by Caamo** [comment]
If you still can't figure it out (without log.txt) then try this...
Change those global settings.
Then restart the game, and then buy a new tractor.
You can clearly see, there is NO use of your global settings, because they are reset.
EVERY time you have to change those settings again. It doesn't matter what you change to globals... THEY are useless.
I fixed it, but I can't provide it to others, because it's your mod. So... ;)

**Comment by Caamo** [comment]
Here's a little hint for you...

2020-04-03 03:46 Creating file "C:/Users/*****/Documents/My Games/FarmingSimulator2019/modsSettings/FS19_VehicleControlAddon/config.xml"...
2020-04-03 03:53 Creating file "C:/Users/*****/Documents/My Games/FarmingSimulator2019/modsSettings/FS19_VehicleControlAddon/config.xml"...

It keeps CREATING new file. It does not load those settings. Just keeps resetting it...

**Comment by Mogli12** [comment]
Please read [README.md](https://github.com/Mogli12/VehicleControlAddon/blob/master/README.md) and post the complete log.txt in Gist.

**Comment by Caamo** [comment]
You get nothing from me anymore. I just tried to help, but you want to just ignore the real problem in your mod.
I already told you, I fixed it. But it still exists in your mod.
If you don't want to try it yourself by how I told you (how the hell can you even be that ignorant fool, that you can't see it...), then just leave it! I couldn't care less :)
At this point, Config.xml is totally useless!
I'm out! Have a good life ;)

**Comment by Bomberman82** [comment]
Nobody forces you man, @Mogli12 make everything for his community, and you, you annoying around with your phising mail´s, it´s his own mod, when you think you could do this type of mod better?!?.Than here you go!!!. 

Make a new discord, github or whatelse it´s in your hand. But don´t bother other people for his works, he don´t need be make it commercial, it´s only for fun man.

**Comment by Caamo** [comment]
Well... If you like to keep it unfinished and broken, then keep it :)
Like I said, I already FIXED it. But I was talking for others who like to use this mod. Sorry for them, they can't use it how they would like to ;)
Too sad comment from you, BOMBER :D 
If Mogli is so stupid to understand this problem in HIS mod, then I'm not going to even think about it anymore :D Sadly it just doesn't work now :D Fun or not! ;)

**Comment by Bomberman82** [comment]
I´m very greatfull, thankfull for this. And people they do they time with that and make it public. Because all the Farming Sim. History live with the modders. It doesn´t madder how big or small a mod is, it must be usefull and this mod is more than that. Strange thing is, i don´t have problems all my setups in my tractors are in place when i save it and when i start my vehicle again the setup is also in place. (v.1.28)?!?. 

And do you know what? 

You don´t need money for making mods or have fun with FS-Series. The biggest foundation in the FS-Series are sharing and helping eacht other with the people and community. Just think about it, when you mean you got a working version than share/divide it, i think it´s not a big think. 

I seen so many people that mean i got something and than just nothing.

**Comment by Caamo** [comment]
@Bomberman82 
Are you totally lost it yourself too? Don't you understand English?
I said... VehicleControlAddon's config.xml is useless. Yes, it does save those settings in game save, but it doesn't load any global settings next time you start a new game. Those global settings are USELESS!
It has nothing to do with that where you fucking tractors are, moron! :D :D 
OMG! How is it so hard to understand.
WE have tested this problem with 5 different computers, with 5 different computer setups, and guess what... THEY ALL HAD THIS SAME PROBLEM.
This mod worked fine before, but now it doesn't load global settings! GET IT!?!?

**Comment by Caamo** [comment]
@Mogli12 
You can close this too, if you like :D 
I have no time for this anymore... Don't fix it, just leave it ;)

**Comment by bgo1973** [comment]
Hopefully he will. That annoying you  just sucks. You got it fixed? Applause.  Well done. VCA is still WIP, am I right? Sometimes changes will end in errors. What's the problem. It won't help to be that annoying like you are. I guess Mogli will exactly know what to do.

**Comment by Bomberman82** [comment]
oh man don´t need to be insulting people that´s crazy man. I said when you make it better than make your own Github or share it with people but don´t tell me what´s right or wrong. 

The mod is not finished and still WIP. 

Your first posts 10hours ago sometimes it take a few days before you get an answer but @Mogli12 are still on it.

**Comment by Mogli12** [comment]
no comment
