### ISSUE TITLE
'Invalid XML type' messages printed in the log by recent versions of VCA

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/VehicleControlAddon#309]
Since a couple of versions VCA has started to print the following messages in the log.txt:
`
2020-04-03 11:03     <debugPrint .../>: invalid XML type : nil
2020-04-03 11:03     <mouseAutoRotateBack .../>: invalid XML type : nil
`

This happens on a fresh save game with only VCA in the mods folder and it doesn't matter if the  'modsSettings/FS19_VehicleControlAddon'config.xml' file is present or not.

The full log.txt is available here:
https://gist.github.com/fdanapfel/9f0a10738d3ac4e0d1ab6a90834394ed

**Comment by Mogli12** [comment]
Es sollte mit 0.1.3.0 gelöst sein. Ansonsten bitte wieder aufmachen.

Danke
