### ISSUE TITLE
Error in der Log auf Dedi-Server

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/VehicleControlAddon#310]
Hallo,

auf einem Dedi-Server bekommen wir nach dem Joinen neuerdings einen Fehler in der Log:

Error: mogliBase30Request received invalid NodeObject
2020-04-03 23:14 Error: mogliBase30Event received invalid NodeObject
2020-04-03 23:14 vehicleControlAddon; vcaShuttleFwd; false
2020-04-03 23:14 Error: mogliBase30Request received invalid NodeObject
2020-04-03 23:14 Error: mogliBase30Event received invalid NodeObject
2020-04-03 23:14 vehicleControlAddon; vcaShuttleFwd; false

Aktuell wird die 0.1.2.8 verwendet.
Machen wir was falsch?

**Comment by Mogli12** [comment]
Hallo,

Probiert bitte mal Version 0.1.3.0. Es sollte auch beim Spieler (Client) was in der log.txt stehen. 

Danke

**Comment by Evilman2517** [comment]
Ich schaue es mir heute Abend an, melde mich dann wieder. Vielen Dank für die Mühe und die schnelle Reaktion

**Comment by Evilman2517** [comment]
Der Error ist weg, jetzt ist es (aufgrund deiner Änderung) nur noch ein Warning. Ich konnte beobachten, die Warnung kommt, wenn man bei einem Fahrzeug die Fahrtrichtung ändert , also die Kabine dreht.

**Comment by Mogli12** [comment]
Kann ich trotzdem einmal die game.log mit Warnung vom Server plus die log.txt vom Client sehen?

**Comment by Evilman2517** [comment]
Natürlich kannst du die Logs bekommen

Client:
[https://gist.github.com/Evilman2517/ebb4dabeed7d595c2cc16463f43ec07f](url)

Server
[https://gist.github.com/Evilman2517/7cdb40246798602561d2f03d6d509f9c](url)

**Comment by Evilman2517** [comment]
Klar, kannst du die Logs bekommen 
[Server.txt](https://github.com/Mogli12/VehicleControlAddon/files/4433529/Server.txt)
[Client.txt](https://github.com/Mogli12/VehicleControlAddon/files/4433530/Client.txt)

**Comment by Mogli12** [comment]
Ok, sieht soweit alles gut aus
