### ISSUE TITLE
Menu not working anymore?

### ISSUE THREAD

**Issue by LindavK1972** [Mogli12/VehicleControlAddon#311]
Dear Sir,

All of a sudden, without installing any new mods, CTRL-C won't let me in the menu anymore?
I'm using, besides your mod, Enhanced Vehicle ( for the differential and such ) and Extended Vehcile because your shuttle didn't work either?

Anyway we can solve this?

Kind regards,

Linda

**Comment by Merrlin** [comment]
Whole Log please... I've observed similar problems yesterday, when opened a new save... Was a mod conflict.

**Comment by Mogli12** [comment]
Do you use a tow bar mod?

**Comment by LindavK1972** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4432054/log.txt)

**Comment by LindavK1972** [comment]
Yep, the one from the modhub?

**Comment by LindavK1972** [comment]
> Do you use a tow bar mod?

Yep, the one from the modhub?

**Comment by Merrlin** [comment]
I did... I removed some mods and all was fine. It was to 99% the FS19_TowBarWight.zip.

@LindavK1972 The ModFolder is not a Litterbin. There are many warnings and errors in your Logfile. You should consider to clean it up. Only one Map and only active used Mods in the Modfolder

**Comment by LindavK1972** [comment]
Its working again. Definitly the towbar mod...
