### ISSUE TITLE
Probleme auf Dedi-Server

### ISSUE THREAD

**Issue by BarnyHarz** [Mogli12/VehicleControlAddon#312]
Hallo @Mogli12 ,

zu aller erst mal echt toller Mod. Macht viel Spaß den zu nutzen.
Ich habe leider ein Problem auf meinem dedizierten Server. Und zwar nutze ich da sowohl VCA und EV als auch RMT. Jetzt ist es leider so, dass ich zwar problemlos ein RMT in einem Traktor nutzen kann, aber ich das VCA Menü nicht öffnen kann um zum Beispiel die automatische Kameraführung beim Kurven fahren zu nutzen.
Grundsätzlich hab ich kein Problem damit, das VCA bei den Fahrzeugen mit RMT nicht funktioniert, aber aktuell kann ich das VCA Menü nur beim Drescher öffnen, obwohl ich einen Vanilla JD 6R Schlepper ohne RMT hab. Server.log und game.log kann ich dir gerne mal zukommen lassen, auch die client log hab ich mal angehängt.

Würde mich freuen wenn wir das Problem zusammen lösen könnten.

Viele Grüße

Barny
[server.log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4445361/server.log.txt)
[game.log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4445362/game.log.txt)
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4445367/log.txt)

**Comment by Mogli12** [comment]
Hi Benny,

wenn der Dialog bei einigen Fahrzeugen nicht öffnet, dann liegt es wohl an doppelt belegten Tasten.

Viele Grüße

**Comment by Mogli12** [comment]
Hallo Benny,

ach, Du verwendest FS19_towBar. Das geht nicht zusammen.
