### ISSUE TITLE
Frage zur Ganggeschwindigkeit

### ISSUE THREAD

**Issue by oschuhm** [Mogli12/VehicleControlAddon#314]
Hi,
ich habe jetzt gegoogelt ... und mir auch die Issues durchgelesen ... aber ich konnte leider nichts zu den Eintellungen bei der "Ganggeschwindigkeit" finden.
Kannst Du mir verraten was sich mit den Einstellungen verändert?
VG
Oliver

**Comment by Mogli12** [comment]
Hallo.
Gemeint ist die Geschwindigkeit des Ganges bei Nenndrehtahl. Das macht nur beu stufenlosen oder automatischen Getrieben Sinn
Viele Grüße
