### ISSUE TITLE
Turbo Clutch

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/VehicleControlAddon#316]
Hi,

Love the mod! makes the the game for me IMO.  I cant quite figure out what the 'turbo clutch does'?

Is it faster shifts?

Thanks

Matt

**Comment by Mogli12** [comment]
Hi,

It is a simulation of a [hydrodynamic clutch](https://en.wikipedia.org/wiki/Fluid_coupling?wprov=sfla1). I called it turbo clutch like in old Fendt tractors. 

It closes a higher RPM and it opens automatically instead of stalling the engine. 

BR

**Comment by miracleman51** [comment]
Ah OK nice so its implementing what id call a Torque converter.  So good for loaders and diggers etc.

M

________________________________

**Comment by Mogli12** [comment]
A torque converter is a special kind of hydrodynamic clutch. It can increase the torque up to a factor of 3.

A turbo clutch is just a hydrodynamic clutch without torque amplification.
