### ISSUE TITLE
VCA speichert einstellungen nicht / VCA doesn´t save settings

### ISSUE THREAD

**Issue by galadhris** [Mogli12/VehicleControlAddon#319]
Hallo! 
Erstmal vielen Dank für das Addon! Für Leute wie mich die auf dem Monitor nicht geradeaus fahren können das absolut perfekte :-) ...
Allerdings speichert das addon meine Einstellungen nicht. Ich muß jedesmal nach neustart des Spiels bei jedem Fahrzeug alles neu einstellen. Muß ich da noch etwas einstellen oder ist das ein Bug der noch behoben wird?

Hello!
Many thanks for this addon! It is great specially for me so i cannot take a straight on the field :-) ...
My issue is this addon cannot save my settings. Every time i get the game started i have to take every vehicle again and make all settings new...do i have to do something else or is this a bug which you take care soon?

Beste Grüße / Kind regards
galadhris

**Comment by Fuzzy86** [comment]
Hy! Ich habe dafür die groben Grundeinstellungen in der VCA Config datei geändert. 
lg

**Comment by Mogli12** [comment]
Keine log.txt, kein Screenshot, keine Erklärung, was genau nicht gespeichert wird

**Comment by galadhris** [comment]
Danke Fuzzy! Ich steh grad aufm Schlauch, wo finde ich die?

Mogil12: Das Addon speichert meine Einstellungen nicht...sagt alles aus aber ich werde genauer darauf eingehen:

Meist stelle ich das Getriebe auf Standard, die Shuttle-Control aus, die Automatische Kupplung aus, Lineare Lautstärkeanpassung aus und die Navigationslinien auf an.
Ist aber prinzipiell egal weil NICHTS gespeichert wird und sobald ich neu ins SPiel komme darf ich alles wieder einstellen.
Zumal ist mir aufgefallen, daß die Motordrehzahl nicht immer runtergeht nachdem ich das Fahrzeug gestoppt habe.
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4481402/log.txt)

Danke schonmal!

**Comment by Mogli12** [comment]
Lade mal die vehicle.xml hoch. Ist das MP oder SP?

**Comment by galadhris** [comment]
Single Player

Kann die file nicht hochladen...meckert daß er den filetyp nicht unterstützt...

**Comment by Fuzzy86** [comment]
Hey galadhris, genau diese Einstellungen wie Shuttle-Control und Adaptive Lenkung kannst du in der vehicleControlAddonConfig.xml ändern. Einfach den gezippten Ordner öffnen und diese Datei z.B.: im Notepad++ öffnen. und dann bei z.B. Shuttle-Control statt True, False eingeben und speichern. Er fragt dich dann ob du die Datei im Zip Ordner ersetzen willst das du dann bestätigst und fertig.

Du kannst die datei natürlich auch raus kopieren und vorab Sichern und dann ändern.

**Comment by Mogli12** [comment]
@Fuzzy86 ES GIBT KEINE SUPPORT FÜR GEÄNDERTE ZIP-DATEIEN !!!

**Comment by Mogli12** [comment]
Was genau wird denn jetzt nicht gespeichert? Bei mir funktioniert es ohne Probleme. Ich habe immer noch keine Ahnung, was hier nicht klappen soll.

**Comment by galadhris** [comment]
WTF wo ist mein post von gestern? Hab ich den nicht abgeschickt? ARGHS...
Die XML Datei will er hier nicht. Meckert mich an mit sowas wie file not supported...

**Comment by Mogli12** [comment]
Nein, mir ist nichts klar. Bitte packe das komplette savegame in eine ZIP-Datei, damit ich selber mal schauen kann.

Wird das Spiel gespeicher? Das Getriebe "Standard" gibt es nicht, welches wird also ausgewählt? Wenn kein Schaltgetriebe ausgewählt wird, dann gibt es keine Kupplung.

**Comment by Evilman2517** [comment]
Ich würde mich hier gerne anschließen. Habe auch das Problem, dass VCA keine Einstellungen speichert. Ich rede von den globalen Einstellungen auf der letzten Seite im VCA-Menü. Ich deaktiviere da immer die Kamera-Bewegungen, in der Log steht auch, dass ein File erstellt wurde, allerdings gibt es das File im Ordner Modsettings dann nicht und meine "neuen" Standard-Einstellungen werden bei neuen Schleppern auch nicht berücksichtigt (Kamerabewegungen sind wieder an).

**Comment by BauerNepo** [comment]
Hallo,
bei mir war ein ähnliches Problem. Die globalen Einstellungen wurden nicht in ModSetting Ordner gespeichert (der Ordner "FS19_VehicleControlAddon" war nicht vorhanden), obschon in der Log stand dass gespeichert wurde. Der Pfad in der Log war auch korrekt. Ich konnte es bei mir beheben, indem ich manuell im ModSettings Ordner den Unterordner "FS19_VehicleControlAddon" erstellt habe. Nun wurde bei der nächsten Änderung bei den globalen Einstellungen die Datei config.xml geschrieben.

Vielleicht hilft es ja euch weiter...
Sorry, auch keine Log von mir da ich es für mich beheben konnte...

**Comment by Mogli12** [comment]
Danke, @BauerNepo. Das Problem ist offensichtlich, dass es das Verzeichnis modsSettings\FS19_VehicleControlAddon noch nicht gibt.

**Comment by BauerNepo** [comment]
Hi Mogli,
mir war halt einfach nicht bewusst dass dieses Verzeichnis manuell erstellt werden muss. Aber nun gehts ja.
Besten Dank für deine Arbeit.

**Comment by Mogli12** [comment]
Ab Version 0.1.3.2 sollte das Verzeichnis automatisch erstellt werden.

**Comment by Williwillswisse** [comment]
Hallo Stefan,
ich habe bei mir mal geschaut mit der Version 0.1.3.2
Wenn das Verzeichnis im Ordner modsSettings nicht da ist wird es nicht angelegt.
Ist es vorhanden wird dort bei mir keine Config abgelegt.

**Comment by Evilman2517** [comment]
Mein Problem wurde mit diesem Update behoben. Datei wird angelegt und Einstellungen werden somit gespeichert. Vielen lieben Dank für die Mühe und das Update.

P.S. VCA gehört definitiv im ModHub released ;-) Einer der besten Skript-Mods für den LS19

**Comment by Mogli12** [comment]
Ich arbeite schon daran

**Comment by galadhris** [comment]
Also vielen Dank erstmal für alle Kommentare und Hilfestellungen!! Die Anpassung der COnfig-XML hat erstmal ausgereicht und konnte so das Addon ohne weitere Nervenaufreibende einstellungen jedes einzelenen Fahrzeuges nutzen.
@Mogli: Es ist nicht notwendig jemand anzuschreien nur weil er einen Tip gibt bis Du das Problem gelöst hast (Großbuchstaben = schreien...).
Ich möchte mich hier auch den Leuten anschließen und sagen daß diese Mod ein musthave ist und in den Modhub gehört!
Klasse Arbeit Mogli!!

Danke Euch allen! Danke Mogli!

**Comment by Mogli12** [comment]
https://forum.giants-software.com/viewtopic.php?f=955&t=140421
