### ISSUE TITLE
Working width not adjusting when changing equipment/tool

### ISSUE THREAD

**Issue by kroddn** [Mogli12/VehicleControlAddon#320]
When changing equipment, I would expect VCA to adjust the working width just like it would when you enter '0' in the dialog.

Would be nice if an option is introduced to activate this "automatic adjustment" when changing equipment (when mounting a new one).

**Comment by Williwillswisse** [comment]
I think that would make sense.

**Comment by Mogli12** [comment]
Hmm, maybe I show a small popup if a new tool is attached?

**Comment by Williwillswisse** [comment]
Would it be an informational popup only?
Can you realize an automatic detection when a new tool is attached?
Then the popup could be:  "Plow attached: width 4.2 m"
