### ISSUE TITLE
Fahrzeug rollt ungebremst

### ISSUE THREAD

**Issue by MistaFreezy** [Mogli12/VehicleControlAddon#321]
Hallo Mogli, erstmal auch von mir einen riesen Dank für den Mod im Namen meiner ganzen Community ;) Top Arbeit

Zu unserem Problem:
Wir haben momentan die Version 0.1.3.1 auf dem Server laufen. Dabei fällt auf, wenn im IVT bzw Vario Getriebe gefahren wird (alles auf automatisch) der Rollwiederstand gleich null ist und das Fahrzeug etliche Meter ohne weiteres Beschleunigen rollt. Dieses Problem besteht mit angeschalteteten Shuttle-Control. Bei deaktivierten Shuttle-Control taucht dieses Problem nicht auf. Kann man da was machen?

**Comment by kroddn** [comment]
Hallo,

ich kann ähnliche Probleme berichten, allerdings in einem anderen Kontext. Ohne Shuttle Control und mit Getriebe aus. Trotz sonst Einstellungen bei einigen Fahrzeugen gleich, verhält sich der Vanilla Valtra S und der JCB 4220 seltam. Alle andren Fahrzeuge scheinen sich korrekt zu verhalten.

Das Verhalten ist (Erinnerung: alle VCA Funktionen sind aus):
- Ich Beschleunige Vorwärts mit W.
- Ich Bremse mit S.
- Fahrzeug kommt zum Stillstand
- Fahrzeug fährt NICHT direkt Rückwärts. Es dauert 5 Sekunden, bevor das Fahrzeug Rückwärts fährt.
- Dasselbe passiert nach Rückwärtsfahrt

**Comment by Mogli12** [comment]
@kroddn Das hat nichts mit VCA zu tun.

**Comment by MistaFreezy** [comment]
Hallo Mogli,

riesen Dank für die schnelle Bearbeitung. Die Änderungen haben für uns persönlich wieder das richtige Fahrverhalten. Super Arbeit, Vielen Dank. Thema kann geschlossen werden. ;)

**Comment by Evilman2517** [comment]
@kroddn Schau mal in Spiel in den Einstellungen wie bei dir Stop-and-Go-Bremsung eingestellt ist

**Comment by markussinner** [comment]
Schon klar. Das ist alles korrekt eingestellt. Für alle Fahrzeuge gleich. Trotzdem machen mir genau die beiden Fahrzeuge immer ärger. Und wenn ich dann mit VCA Einstellungen "rumspiele", gehts irgendwann wieder.

**Comment by Mogli12** [comment]
Wenn das Getriebe und ShuttleControl aus sind, dann hat es nichts mit VCA zu tun.

**Comment by markussinner** [comment]
Es liegt an VCA. Wenn ich an der Bremskraftc drehe, Motor ausmache, aussteige und wiedereinsteige, Motor anmache, dann ist das Symptom weg.

Das Problem tritt immer dann auch, wenn mein Multiplayer Kollege dem Spiel beitritt.

**Comment by kroddn** [comment]
Mogli, soll ich ein neues Isssue für mein Problem aufmachen? Weil hier ist ja bereits closed, das Problem besteht weiter.

**Comment by kroddn** [comment]
[vehicles.zip](https://github.com/Mogli12/VehicleControlAddon/files/4498549/vehicles.zip)

**Comment by Mogli12** [comment]
@kroddn : ja
