### ISSUE TITLE
Wrong steering reverse direction / falsche Lenkung bei Rückwärtsfahrt

### ISSUE THREAD

**Issue by kroddn** [Mogli12/VehicleControlAddon#322]
Einige Fahrzeuge können bekanntermaßen in den Rückwärtsmodus gewechselt werden (reverse driving STRG+B). Damit kann man die Last besser verteilen, z.B. mit einem Mähwerk HINTEN und einem Ballensammler/Wender VORNE, oder Nadal vorne und Ballenpresse hinten).

Wenn man diesen Modus anschaltet, dann lenkt VCA in die falsche Richtung.

**Comment by Mogli12** [comment]
Und ohne VCA klappt es besser?

**Comment by markussinner** [comment]
Okay, ein Detail fehlt noch: es geht um den Spurhalte-Assistenz. Andere Einflüsse hst VCA wohl eher nicht.

**Comment by kroddn** [comment]
Funktioniert mit 0.1.3.4 noch nicht.

Brauchst Du sonst noch Infos?

Valtra S, "hinten" Mähwerk, vorne Heuwender.
