### ISSUE TITLE
Seltsames Verhalten von Fahrzeug

### ISSUE THREAD

**Issue by kroddn** [Mogli12/VehicleControlAddon#323]
Ich verwende den Mod hauptsächlich wegen der automatischen Lenkung.
Wir spielen zu zweit im Multiplayer.
Version 0.1.3.0

Ohne Shuttle Control und Getriebe aus. 
Sonst sind alle Einstellungen bei allen Fahrzeugen gleich
Der Vanilla Valtra S und der JCB 4220 verhalten seltam. Alle andren Fahrzeuge scheinen sich korrekt zu verhalten. (Ich vermute aber, dass die beiden Fahrzeuge willkürlich sind.

Das Verhalten ist (Erinnerung: alle VCA Funktionen sind aus):

- Ich Beschleunige Vorwärts mit W.
- Ich Bremse mit S.
- Fahrzeug kommt zum Stillstand
- Fahrzeug fährt NICHT direkt Rückwärts. Es dauert 5 Sekunden, bevor das Fahrzeug Rückwärts fährt.
- Dasselbe passiert nach Rückwärtsfahrt

Das Problem scheint immer dann aufzutreten, wenn mein Multiplayer-Partner dem Spiel beitritt.

Beheben lässt es sich, indem man die Bremsverzögerung hoch/runter stellt (wieder auf 15%), Shuttle Control ein/aus schaltet. Dann Motor aus. Dann das Fahrzeug verlassen. Dann einsteigen. Motor wieder an. Ab dann verhält sich das Fahrzeug normal.

Randnotiz:
Auf meinem Server Dedicated Server existiert das Verzeichnis "modSettings" nicht.
Lokal war kein Ordner "FS19_VehicleControlAddon" in modSettings vorhanden, wird auch nicht angelegt.

[vehicles.zip](https://github.com/Mogli12/VehicleControlAddon/files/4499680/vehicles.zip)

**Comment by Williwillswisse** [comment]
Das Verhalten kann ich mit dem Krone Häcksler und dem Case Optum bestätigen. Zudem ist die Bremsleistung fast Null und die Bremslichter gehen beim Bremsen auch nicht an.
