### ISSUE TITLE
Bremse zu stark beim Gaswegnhemen

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#324]
Hallo,

haber gerade die neue Version probiert, sobald man vom Gas geht (ohne zu bremsen) scheint das Fahrzeug von alleine ziemlich unreal runterzubremsen. Das war bei 0.1.3.1 definitiv noch nicht so...Ich habe jetzt auch nicht verfolgt, was du in den letzten Versionen geaendert hast,aber das hat sich auf jeden Fall (zum negativen mMn. ) geaendert.

Schoene Gruesse

Claudio

**Comment by Mogli12** [comment]
Hallo Claudio,

stell den Wert von "Niedrige Bremskraft" auf 0%. Irgendwie klappt das noch nicht ganz nach meinem Geschmack. Vorher waren es aufgrund eines Bugs 0%.

Viele Grüße, Stefan

**Comment by cabmac** [comment]
moin...mit der 0.1.3.6 scheintyha wieder alles wie gehabt, oder?
MMn alles ok...

Schoene Gruesse

Claudio
