### ISSUE TITLE
Missmatch in "shiftTimeMS" and "shiftTimeMs"

### ISSUE THREAD

**Issue by oschuhm** [Mogli12/VehicleControlAddon#325]
Hi,

ich habe mich jetzt ein wenig schwindelig gesucht, weil er mir bei meinem manuell angelegten Getriebe die shiftTimeMS nicht genommen hat. Er ist immer auf die Defaults gegangen.

Beim debugging habe ich festgestellt, dass in der transmission.xml der Parameter "shiftTimeMS" geschrieben wird. In der LUA wird aber nach "shiftTimeMs" gesucht. Dieser Wert ist in der transition.xml nicht drin und deshalb immer nil.

Ich habe jetzt meine transition.xml entsprechend angepasst. Nun funktioniert auch mein Getriebe wie gewünscht.

Vielleicht kannst Du ja LUA und XML noch aufeinander abstimmen damit nicht der nächste auch in der Problem rennt.

VG
Olli

`	<transmission label="Test 6-speed with low range">
		<gears shiftTimeMS="750" baseSpeed="180">
			<gear speed="50"  text="I"/>
			<gear speed="70"  text="II"/>
			<gear speed="95"  text="III"/>
			<gear speed="130" text="IV"/>
			<gear speed="180" text="V"/>
			<gear speed="250" text="VI"/>
		</gears>
		<ranges shiftTimeMS="1500">
			<range ratio="0.357" text="Low" />
			<range ratio="1.0"   text="High"/>
		</ranges>
	</transmission>	`

**Comment by Mogli12** [comment]
Hallo Olli,

ich habe das Beispiel angepasst.

Danke

**Comment by oschuhm** [comment]
Vielen Dank.
Auch wenn Du dieses Feature nicht mehr weiter entwickeln möchtest .... finde ich es doch mit dem aktuellen Stand sehr gelungen.
Es macht das Fahrzeug noch mal ein wenig realistischer.
Bei RMT muß man leider manuell schalten. Eine Automatik gibt es da nicht.
Insofern ist Dein Mod hier erste Wahl.
VG
Olli

**Comment by Mogli12** [comment]
Hi Olli,
Ich verwende jetzt "own transmission" und stelle mir das Getriebe im Spiel ein.
Viele Grüße

**Comment by oschuhm** [comment]
Ja,
das wäre ein Kompromiss.
Allerdings sind die Schaltstufen bzw. Zwischenstufen nur berechnet. Kommen also nur näherungsweise an das gewünschte Getriebe dran.
Eine Bezeichnung für Gruppen und Gänge kann ich da glaube leider auch nicht mitgeben.
Kann ich die KOnfiguration speichern damit ich Sie bei mehreren Traktoren / Fahrzeugen nutzen kann?
Oder muß ich es da wieder erneut einstellen?
VG
Olli

**Comment by Jan238** [comment]
Hallo, 
für eigene Getriebe-Konfigurationen kannst du die transmissions.xml im modsSettings Ordner anlegen (Datei mit Beispiel gibts hier auf Gibhub). Dabei kannst du die Geschwindigkeiten der einzelnen Gänge und Gruppen genau festlegen und auch deine eigenen Bezeichnungen benutzen, ähnlich wie beim GearboxAddon. Die Getriebe stehen dann im VCA Menu mit dem festgelegtem Namen zur Auswahl.
Gruß
Jan
