### ISSUE TITLE
Conflicht between VCA and AutoDrive "unload combine"

### ISSUE THREAD

**Issue by alku50** [Mogli12/VehicleControlAddon#326]
Hallo Stefan
Maybe you are aware that AD "unload combine" is not working properly with VCA engaged (no set back of the tractor after finishing unloading e.g. resulting in a crash of the two vehicles).
I'm using your VCA 0.1.3.5  and AD 1.1.0.4 or 1.1.0.5.  Is there anything I can do? I'm mainly using your constant speed and your compass bearing. Or will there be a fix on your side for the problem?
 Thanks for your answer. Alex

**Comment by Mogli12** [comment]
Hi,
It seems that AutoDrive has a general problem with all mods that add shuttle control to the game. In my opinion AutoDrive operates the vehicle without setting it into "is hired" state.
Regards, Stefan

**Comment by alku50** [comment]
Hi Stefan
Thank you for the quick answer. I think both Mods are very essential to play FS19. Is it ok for you, when I go forwarding your opinion to Andre or Stefan from AutoDrive ?

Best regards and stay healthy. Alex

Von meinem iPad gesendet

**Comment by Mogli12** [comment]
Hi Alex,

Yes, of course, please contact AD team. Please mention issue #303 as well. I think they do not switch the vehicle into hired worker mode.

Regards, Stefan
