### ISSUE TITLE
maxSpeed für das Getriebe in der transmission.xml eintragen

### ISSUE THREAD

**Issue by oschuhm** [Mogli12/VehicleControlAddon#327]
Hallo,
wäre es möglich, dass ich die max. Geschwindigkeit für das Getriebe in der Transmission.xml eintragen kann?
Aktuell wird die max.Geschwindigkeit ja aus dem Config Menü im Spiel geholt. Dann passen leider die Settings in der transmission.xml nicht mehr so ganz.
Schöner wäre es, dass wenn der max. Geschwindigkeit Wert in der transmission.xml vorgegeben wird der Wert aus dem Konfig Menü im Spiel ignoriert wird.
VG
Olli

**Comment by Mogli12** [comment]
Hi Olli,
ich werde die transmissions.xml zwar nicht wieder ausbauen. Aber den Weg werde ich nicht weiter verfolgen. Im Grunde kann man sich ein einfaches Getriebe unter "own transmission" selber konfigurieren.
Wer es realistischer möchte, sollte sich mal [FS19_realManualTransmission](https://github.com/modelleicher/FS19_realManualTransmission) anschauen.
Viele Grüße, Stefan
