### ISSUE TITLE
Fehlendes VehicleControlAddon nach Update

### ISSUE THREAD

**Issue by NewYorck** [Mogli12/VehicleControlAddon#328]
Guten Abend, 
ich habe heute Abend die neuste Version des VCA installiert. Habe es ohne Probleme nutzen können. Nach einer Pause wollte ich weiter ackern. Leider fehlt nun in einigen Schleppern das VCA. Auch das Menü lässt sich für diese Maschinen nicht aufrufen. Bei wenigen Maschinen ist es weiter da & funktioniert normal.
Die log ist komplett frei von Error-Meldungen.
Auch ein Abwählen, speichern und erneutes anwählen hat für die Fahrzeuge, bei denen VCA fehlt, keinen Einfluss.

VCA ist für mich - als Landwirt im Realen - im LS eine wahre Bereicherung ich möchte es nicht mehr missen. Wie kann sich der VCA aus einigen Fahrzeugen "deinstallieren"? In der Vehicle.xml fehlen bei diesen auch die Einträge...
Kann mir jemand helfen?

Liebe Grüße

**Comment by Mogli12** [comment]
Hallo,
sicher, dass in der log.txt keine Fehlermeldungen drin sind. Und wie sieht es mit Abschleppstangen aus?
Viele Grüße

**Comment by googleplex2010** [comment]
Entfernen Sie dies und versuchen Sie es erneut:
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=156390

**Comment by NewYorck** [comment]
Hallo,
Ja, die Log ist nahezu fehlerfrei. Die einzigen kommen von GlobalCompany, und hier von den Hud Icons.
@googleplex2010 Ich habe diesen Mod nicht benutzt.
Ich habe einen neuen Spielstand begonnen, alle relevanten Daten übertragen und es funktioniert wieder. Ich frage mich, ob es möglich ist, dass beim speichern ein Problem aufgetreten ist und sich dieser Teil des Savegames zerlegt hat?

**Comment by Mogli12** [comment]
I think that the latest build should work together with tow bar.
