### ISSUE TITLE
sound problem in idle 

### ISSUE THREAD

**Issue by astro80** [Mogli12/VehicleControlAddon#329]
Hello Stefan, i have a strange problem with the sound. when i am out of the tractor, and this is in idle mod, i hear a very low sound as if the engine engulfed. 
version of the mod is the 0.1.3.6 
https://gist.github.com/astro80/85787e22607a83cf9c6e1a3ef77c1aa4

**Comment by Mogli12** [comment]
Some mods do not work with the linear sound setting. You can turn it off on the 2nd page.

**Comment by MichalKucavik** [comment]
I have the same problem. And the linear sound setting has no effect on it (when it's activated or not, it does) too.

**Comment by Mogli12** [comment]
Which vehicle?

**Comment by astro80** [comment]
For me in mod vehicle. Do you want to know the specific mod name?

**Comment by Mogli12** [comment]
If you want to have this fixed then I need to reproduce it. So how can I?

**Comment by MichalKucavik** [comment]
I tested it and it's not a problem of the vehicle as such (I tested it on FENDT 939, FENDT 1050, Mannitou, front loader), but it does when a manual transmission is chosen (specifically for me 2x6). When I choose that particular vehicle for automatic transmissions (IVT, Vario), it does not.

**Comment by Mogli12** [comment]
Please try build 140

**Comment by MichalKucavik** [comment]
The problem has been fixed, good work.

**Comment by astro80** [comment]
Same for me, thank you very much.
