### ISSUE TITLE
Kleine Frage am Rande?!?

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#330]
Hallo @Mogli12, 

nochmals tausend Dank!!! für dieses geile Script. Eine Frage am Rande ich habe jetzt erst gesehen das dein Mod im Modhub gelandet ist mit der Version 1.0. Hmmm ist das die selbe Version 1.36 die du zuletzt veröffentlicht hast?. 

Und werden weiteren Updates vom Github dann auf den Modhub übertragen, sodass beides parrallel läuft?. Oder ist Github aktueller?. 

Danke im Voraus und hoffe deine Motivation und Muse bleiben bestehen :)

**Comment by Mogli12** [comment]
Nein, die Version in ModHub entspricht 0.1.3.5. Die Korrektur von 0.1.3.6 habe ich gemacht, als ich den Mod im ModHub bereits eingereicht hatte. Github wird immer aktueller sein. Wenn wieder genug Korrekturen beisammen gekommen sind, dann werde ich eine Version 1.0.0.1 oder 1.1.0.0 im Modhub einreichen.

**Comment by Bomberman82** [comment]
Danke für die Info. Und viel Erfolg weiterhin. 

mfg 
Bomberman82
