### ISSUE TITLE
Turbo blow off value added to settings xml

### ISSUE THREAD

**Issue by 51stHD** [Mogli12/VehicleControlAddon#331]
Really enjoy your mods and have done since FS15 Auto tractor etc., so a big thank you from me for all of that.

As the title suggests, I would like to see an additional line in the settings xml for the turbo blow off volume, if that would be at all possible, it would be much appreciated as I generally use old tractors that don't have a turbo.

Thanks again.

**Comment by Mogli12** [comment]
Please try the latest build

**Comment by 51stHD** [comment]
Yes that's just what I was looking for, thank you.

Great mod, essential !
