### ISSUE TITLE
Issue with TowBars

### ISSUE THREAD

**Issue by Nomad002** [Mogli12/VehicleControlAddon#332]
I found out that while using any kind of TowBar(excluding towing ropes) with VCA, VCA doesn't work, it doesn't even show up while in game, I do activate it in mods but while in game it doesn't show up and you cant enter menu(CTRL+C).

**Comment by Mogli12** [comment]
The TowBar makes all vehicles attachable. VCA work only for vehicles w/o spec attachable. Please look for closed issues before opening another one.
