### ISSUE TITLE
Vario gearbox stuck in 'high' gear

### ISSUE THREAD

**Issue by ElfVierzehn** [Mogli12/VehicleControlAddon#333]
Hey there!

First of all I want to thank you for this amazing mod. Without it, the game would be a lot more boring. =)

I have a little issue when choosing the Vario gearbox for a tractor. When I use it the first time with a tractor, it does work. If I want to use that tractor again later, I am stuck in high and cannot seem to switch to low ever again. Do you know anything about this? Thanks a lot!

/edit: I have to add something: It seems to be an issue with groups. This happens to me when using the function 'VCA Group up' and 'VCA Group down'.

**Comment by patch110** [comment]
Hi i had a similar problem with  changing groups/range. Turns out these 2 keys [  ] are also used by courseplay editor so i removed the bindings for cp editor in game. Or i maybe be talking about something completely different?

**Comment by ElfVierzehn** [comment]
Is it likely, that some kind of keys won't work with it, that are not US or ENG keyboard layout? I use the letters Ä and Ü for the groups. I bound those to some keys on my mouse I had left. So my mouse uses Ä and Ü.  I also noticed, that group up always works with Ä, group down does not work with Ü. Ü is not bound to any function in the game.

I now tried it with Shift+Num7 and Shift+Num8. This works fine. seems like Ü can't be used for VCA. Could this be the case?

Thanks a lot for your reply!

**Comment by Mogli12** [comment]
Do you use courseplay. The course editor key bindings block all other keys even if the editor is not visible. I changed them.

**Comment by ElfVierzehn** [comment]
I just unbound the keys for all the course editor functions. As I deleted the binding with the keys [ and ] it started working as intended. I cannot see the connection here, but I am glad that it works. Thanks for your answers and the heads up with cp editor.
