### ISSUE TITLE
Can only shift down, shifting gets stuck after some time spent in savegame.

### ISSUE THREAD

**Issue by T90Vladimir** [Mogli12/VehicleControlAddon#334]
Hello,

The mod is absolutely amazing, though there is a big issue I experience. This applies to all tractors, vanilla and modded too.

The issue is that after I spend some time in a savegame (this time is random), I suddenly can only shift down (any transmission modes, even own). I can shift until I reach Gear 1 in the lowest range, and then the shifter is stuck. Can't shift up. Changing to different mode does not help. The issue stays. The vehicle remains driveable, although slowly because of the low range + gear 1. 

The issue goes away if I reload the savegame. The log does not produce anything related to the mod. I have removed KeyboardSteer before installing VCA.

I would be eternally grateful if you could fix this issue, now that I experienced this mod, I never want to go back to stock FS. The tractors driving like gokarts puts me off so much. 

In case it is neccessary, I have the following scripts running along with VCA: RealMassAdjustment, the script that adds Slip and Motor Load (sorry I forgot the name), Extended Vehicle, Courseplay. 

Edit: Also a minor issue is that the steering snaps back to straight very quickly, almost instantly. Not a huge deal, but may be an issue for others.

**Comment by Mogli12** [comment]
Hi,

I never had this problem. But I know that FS19 has some problems with inputBinding.xml. Sometimes such issues go away after deleting or renaming this file.

The quick steering back to straight is part of the adaptive steering. But you can turn it off.

Regards

**Comment by T90Vladimir** [comment]
Thank you for the reply.
If I delete the inputBinding.xml, will itt regenerate next time I launch the game?

Regarding the quick steering, I know it's part of the Adaptive Steering, which I like and would not want to turn off, the only problem I have is that the steering to straight is impossibly quick. Is there a line somewhere in the config I can edit to change that?

**Comment by T90Vladimir** [comment]
I am closing this issue, after about 2 hours of investigative work, I found out it was caused by a keybind conflict with Courseplay. The Shift up and Range Up keys were used by CP for some other purpose. Thank you for trying to help, and I am sorry if I took up your time with this. The mod is fantastic, wish you all the best!

**Comment by Mogli12** [comment]
Maybe you open an issue in coursepley repository.
