### ISSUE TITLE
Attach detach equipment 

### ISSUE THREAD

**Issue by BreadedVirus** [Mogli12/VehicleControlAddon#336]
Unable to detach or attach equipment without having to turn shuttle on and off repeatedly.

Apart from that really enjoying the mod..👍

**Comment by Mogli12** [comment]
Version? Log.txt? Screeshot?

**Comment by 51stHD** [comment]
It would appear that this issue can be closed, as BreadedVirus has found the solution to the problem they raised here, but have forgotten for some reason to let you know.

Problem
[https://forum.giants-software.com/viewtopic.php?f=963&t=163245&start=15#p1273109](url)

Solution
[https://forum.giants-software.com/viewtopic.php?f=963&t=163245&start=15#p1273141](url)

**Comment by BreadedVirus** [comment]
> Version? Log.txt? Screeshot?

It was a key binding issue on my end. Deleted the keybinding xml, fired up the game and all is well. 

Thanks for an outstanding mod.
