### ISSUE TITLE
Frage: Auto Hold bei ESK Menü deaktivieren

### ISSUE THREAD

**Issue by Bohne11297** [Mogli12/VehicleControlAddon#337]
Moin, 
zu allererst möchte ich für dieses geniale Skript danken, was den LS so bereichert wie kaum ein anderer Mod.
Seid einer der letzten VCA Versionen ist es ja so, das wenn man in das ESK Menü Tabt Auto Hold Aktiviert wird. Wenn dabei der Tempomat Aktiviert ist passiert dies nicht. Da ich aber gerne nur mit der Gangs Auswahl und mit Handgas arbeite stört es doch wenn man mal eben im Menü auf der Karte sich den Fortschritt auf der Fläche ansehen will und dabei jedes mal der Schlepper stoppt.
Kann man das Auto Hold bei ESK  irgendwie deaktivieren? Habe den entsprechenden Eintrag leider nicht finden können. 
Gruß Lucas

**Comment by Mogli12** [comment]
Probiere bitte Version 140.

**Comment by Bohne11297** [comment]
Super! danke für die schnelle Hilfe DANKE! euch.

**Comment by Mogli12** [comment]
Ich spiele meistens mit "Geschwindigkeit permanent halten", aber nicht mit Handgas. Das kann man über Strg rechts und Entf (de-)aktivieren, und mit Entf kurzfristig umschalten.
