### ISSUE TITLE
Frage zu Max.drehzahl bei Tempomat

### ISSUE THREAD

**Issue by pixel785** [Mogli12/VehicleControlAddon#338]
Bei eingeschaltetem Tempomat lässt sich zusätzlich Gas geben/ Drehzahl erhöhen und die Lautstärke nimmt nochmals zu.
Ist das so gewollt oder lässt sich das ändern?

**Comment by Mogli12** [comment]
Das ist so gewollt. Man kann mit dem Tempomaten die minimale Geschwindigkeit (z.B. 7 km/h) einstellen. Wenn dann da Gerät (Grubber, Pflug, ...) abgesenkt ist, dann kann man zusätzlich beschleunigen, da ja das Gerät automatisch eine maximale Geschwindigkeit vorgibt. Am Vorgewende fährt man dann wieder mit Tempomat, also z.B. 7 km/h.

**Comment by pixel785** [comment]
Vielen Dank erstmal für die schnelle Antwort!

Ich weiß gerade nicht, ob wir wirklich vom gleichen sprechen.
Das ein Tempomat verbaut ist, der durch weiteres Beschleunigen die Tempomatgeschw. anpasst ist mir bekannt.
Ich spreche vom "regulären" Tempomat. Ich stelle ihn an und obwohl der Schlepper fast voll ausgelastet ist, lässt sich mittels "W-Taste" zusätzlich Gas/ Drehzahl erhöhen. Mich stört daran nur, dass die Lautstärke nochmals zunimmt, die sonst nie zu erreichen ist. Egal ob ich "manuell" die volle Auslastung bewirke, über den "regulären" Tempomat oder mittels Handgas. Als würde die Lautstärke dadurch von 100% nochmal auf 110% hochgeregelt.
Hoffe es ist verständlich ;)

**Comment by Mogli12** [comment]
Ich kann mir nicht vorstellen, dass das Gssgeben die Lautstärke einfach so erhöht. Die Lautstärke wird von VCA gar nicht verändert. Das geht nur über Motorlast und Drehzahl.

**Comment by pixel785** [comment]
Hm, vlt. liegt es am Mod, weil da schon "Sound-Gears" in der .xml verbaut sind.
Trotzdem vielen Dank!
