### ISSUE TITLE
Kein Fehler... nur eine Frage.

### ISSUE THREAD

**Issue by loenne-michel** [Mogli12/VehicleControlAddon#340]
Zunächst möchte ich dir für diese unverzichtbare Mod danken! Ohne deine Getriebe und anderen Mods wäre LS schon längst für mich passe... hervorzuheben ist auch dein klasse GPS...genial einfach! Nun zu meiner Frage:
Wäre es möglich den Wechsel zwischen Manueller Schaltung und Automatik auf eine Controllertaste
zu belegen?  Hintergrund ist, daß ich bei Full Powershift Getriebe die Strassenfahrt im Automatikmodus und die Feldarbeit im Manuellen Modus mache. Wäre sehr hilfreich, für jeden Switch nicht immer ins Strg+C Menü gehen zu müssen. 

Grüsse... Micha

**Comment by Mogli12** [comment]
Ja, das sollte möglich sein

**Comment by Mogli12** [comment]
Ab Version 142 kann man die automatische Schaltung mit STRG Ü umschalten.

**Comment by Bomberman82** [comment]
Mensch @Mogli12,

ist ja wie Weihnachten bei dir, einfach top das du User Wünsche so moderat umsetzt "Daumen Hoch!". 

mfg
Bomberman82

**Comment by loenne-michel** [comment]
Perfekt! Freu mich! Danke dir!!!!
