### ISSUE TITLE
VCA versions > 0.1.2.8 - change in standbrake behaviour?

### ISSUE THREAD

**Issue by caplink811** [Mogli12/VehicleControlAddon#341]
morning,

for me it seems, that the last versions of VCA (guessing at least the versions with brake force factor settings in 25% steps on pp 2) shown a different behaviour in what happens when the motor switched off.

I used to use ExtVehicle for SC and VCA for steering and GPS, transmission is set to IVT. When I switched off the machine it stood still on all grounds, even or odd.
With the new versions when I switch the machine off, it rolls and I could only break, when I start the machine again. That behaviour changed when I use those versions of VCA for SC too, and transmision IVT as well.

Is this behaviour intended and do I only not find the handbrake function?

thanks for the mod, and your answer as well
ciao
 JrB

**Comment by Mogli12** [comment]
If you use the VCA transmission, then please use shuttle control of VCA.

**Comment by caplink811** [comment]
thanks for your answer, I'll close this ticket now.
Stay healthy and have a nice weekend
Ciao
 JrB
