### ISSUE TITLE
Fahrzeug rollt davon

### ISSUE THREAD

**Issue by ZhooL** [Mogli12/VehicleControlAddon#342]
Moin Stefan,

kannst Du/irgendwer bitte einmal verifizieren:
* Multiplayer (SP hab ich noch nicht getestet)
* in ein Fahrzeug einsteigen
* Motor aus lassen
* Shuttle Control auf "aus"
* links/rechts lenken
Bei mir fangen die Fahrzeuge dann langsam an davon zu rollen.

Gruß
ZhooL

**Comment by Mogli12** [comment]
Das ist normal. Damit das Fahrzeug lenken kann, wird die Parkbremse gelöst.
