### ISSUE TITLE
Anzeige des des derzeitigen Gangs verschieben?

### ISSUE THREAD

**Issue by Dagelkop** [Mogli12/VehicleControlAddon#344]
Hallo fand vor kurzen diesen Mod, ist echt geil!

Da ich den Mod mit anderen Mods nutzte, wird die Anzeige von den derzeitigen Gang von einer weiteren Modifikation verdeckt. Möchte deshalb diese etwas nach oben verschieben.
Habe schon einen Beitrag gesehen, in dem dass eigentlich schon beschrieben wäre, doch finde ich keine "keyboardSteerMogliConfig.xml" im modsSettings - Ordner.

Ich hoffe, mir könnte jemand helfen, da mir der Mod, wie gesagt, sehr gefällt.

**Comment by Mogli12** [comment]
Hallo, 
in den Einstellungen bei der Weltkugel sind unten 2 Eingabefelder für die Pixel-Position. Wenn Du das Feld leer machst und Enter drückst, dann kommt wieder der Default.
Viele Grüße

**Comment by Dagelkop** [comment]
Ah, viel besser. :D
Danke für die Erweiterung, echt praktisch 👍

**Comment by Mogli12** [comment]
Gerne
