### ISSUE TITLE
Fahrzeug rollt | Shuttle Control

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#345]
Hab ein seltsames Phänomen festgestellt. Wenn man den Traktor zum Stillstand bringt, bspw. auf einer leicht abschüssigen Strecke und den Motor ausmacht, aber im Traktor sitzen bleibt, dann fängt er an, weg zu rollen, ganz langsam. Shuttlecontrol ist aus. Wenn man dann in den Einstellungen Shuttlecontrol anschaltet, bleibt der Traktor stehen. Schaltet man wieder auf "aus" um, rollt er wieder. Das passiert so seit den letzten 3 oder 4 Versionen, kann es nicht genau sagen. Logdatei m.E. ist unauffällig.
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4588771/log.txt)
![fsScreen_2020_05_06_20_31_44](https://user-images.githubusercontent.com/21023840/81215137-2afb2a00-8fd9-11ea-9da0-29d51c2310f4.png)

**Comment by cabmac** [comment]
sollte mMn auch so sein....

**Comment by MichalKucavik** [comment]
this feature simulates neutral and was the reason to use the parking brake when you want to stand in one place. For more realism, it might still work when you leave the vehicle (the vehicle would move slowly downhill.

**Comment by iljarogoff** [comment]
Wusste nicht dass es erwünscht ist. Ich finds nervig, wäre schön wenn man dieses Feature deaktiviern könnte

**Comment by MichalKucavik** [comment]
And do you use a handbrake? A real tractor would do the same without it ...
But there could also be an Autohold On / Off option in the VCA menu for those who don't want to drive real.

**Comment by Mogli12** [comment]
Just use build 147. With shuttle control VCA did the handbrake in case motor was off. Now it does it even w/o shuttle control.

**Comment by iljarogoff** [comment]
> 
> 
> And do you use a handbrake? A real tractor would do the same without it ...
> But there could also be an Autohold On / Off option in the VCA menu for those who don't want to drive real.

playing with keyboard and I do not use a handbrake, didn't know that FS19 has a handbrake at all...

**Comment by iljarogoff** [comment]
> 
> 
> Just use build 147. With shuttle control VCA did the handbrake in case motor was off. Now it does it even w/o shuttle control.

thanks for your efforts!
