### ISSUE TITLE
Differentialsperre, Allrad

### ISSUE THREAD

**Issue by tomy852** [Mogli12/VehicleControlAddon#348]
Hallo Mogli12,
Erstmal danke für deine unglaubliche Arbeit die du machst. 
Natürlich habe ich die neue Diff. sperre ausprobiert und finde sie ist wirklich gut gelungen.
Nur beim Claas 960 Terra Trac (Giants Mod) funktioniert es noch nicht so richtig. 
Es zeigt das Fahrzeugsymbol zwar an aber sie lässt sich nicht zuschalten. 
 
mfg tomy852

**Comment by Mogli12** [comment]
Hi,

Beim Claas sind die 5(!!!) Differentiale so verteilt, dass hier Allrad nicht eingestellt werden kann.

Viele Grüße
