### ISSUE TITLE
Differenzial Sperren und Allrad lässt sich bei LKW´s nicht schalten

### ISSUE THREAD

**Issue by SuperSeba** [Mogli12/VehicleControlAddon#349]
Bei mehreren LKW´s, z.B. ATC Containerpack wird zwar das Symbol für Differenzial Sperre und Allrad wird zwar angezeigt es lässt sich aber nichts Schalten.

Werden denn noch irgendwelche sonstigen Infos benötigt, oder ist das ein bekanntes Problem?

**Comment by Mogli12** [comment]
Es geht nur ein ganz bestimmtes Differential-Muster.
