### ISSUE TITLE
Fahrzeugsteuerung 

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#351]
Erstmal super was du in letzter Zeit am VCA gemacht hast. Das Getriebe läuft bald besser als RMT, die Allradsteuerung ist der Hammer funktioniert nur momentan auf dem Server nicht, im SP und ingame MP läuft es. Wir hätten da kein Problem, eher einen Wunsch. ;D Könnte man im VCA das separate heben und senken bzw anschalten/ausschalten der Geräte einbauen wie beim TSX.? Da könnten wir als Team auf unseren Server das TSX endlich verbannen ;D  MfG das Ag-OVP Team ^^

**Comment by Mogli12** [comment]
Hallo,
Ich fände es ganz interessant, wenn man 2 Tasten hätte, so dass alle Geräte incl. Frontlader in eine vorher gespeicherte Position gingen. Ich bin mir aber nicht sicher, ob das noch Teil von VCA wäre.
Viele Grüße

**Comment by cabmac** [comment]
> Ich bin mir aber nicht sicher, ob das noch Teil von VCA wäre.

heisst doch VehicleControl..... :) ...gibt es das real nicht auch, dass man ein Steuergeraet mit einer Funktion belegt?  Ich habe den enhanced NUR drin wegen diesem Feature, auf meiner Maus 2 tasten belegt fuer hinteres und vorderes Anbaugeraet, also hoch und runter (das hin- und herschalten mit G geht mir ziemlich auf den Nerv, zumal beim maehen)...

Schoene Gruesse

**Comment by Mogli12** [comment]
Bei 2 Mähwerken müsste doch LOWER_ALL_IMPLEMENTS / "KEY_lctrl KEY_v" gehen, oder?

**Comment by ChrisJD8400R** [comment]
Bei den Mähwerken mag das funktionieren. Mit Frontpacker ist es aber schwierig da man immer hin und her switchen muss damit er am Gewende oben bleibt und nicht das gedrillte wieder umbricht. Vlt kannst du die Zeilen vom TSX nutzen um dir einen Überblick zu verschaffen. Wäre echt toll wenn das mit wenig Aufwand im VCA einen Platz finden würde. Die Allradsteuerung läuft wie gesagt gut nur halt auf dem dedicated Server reagiert es nicht (im TSX ist der Allrad deaktiviert und war beim 2. Test auch nicht im Modsordner)  Grüße vom AG-OVP-Team 😁

**Comment by cabmac** [comment]
> Bei 2 Mähwerken müsste doch LOWER_ALL_IMPLEMENTS / "KEY_lctrl KEY_v" gehen, oder?

das geht auch, aber es geht halt nicht unabhängig voneinander sondern zeitgesteuert... Mit dem enhanced kann ich vorderes und hinteres auf zwei Buttons meiner Maus legen und Steuer die, wo ich will, im mal beim Beispiel MW zu bleiben.... das Ding ist, dass man damit die Taste "g" komplett ignorieren kann.

**Comment by Mogli12** [comment]
Ok, ich habe mal etwas ausprobiert...

Mit LShift und den Tasten V und B kann man das vordere Gerät heben/senken bzw. ein-/ausschalten. Mit RShift steuert man entsprechend das hintere Gerät. 

Zuerst wollte ich es rekursive machen. Aber so wie es jetzt ist funktioniert es auch mit Agos M.H. From 3000. Wenn man es benötigt, dann kann man ein drittes Gerät kann man ja direkt selektieren und steuern.

**Comment by ChrisJD8400R** [comment]
Hi, super das Du dir die Sache angenommen hast. Meine Frage wäre jetzt, ob man das jetzt selektiv in der Tastenbelgung ändern kann um z. B. auf der Seitenkonsole/Gamepad die 4 Funktion zu nutzen.
  Auf diesen Weg würde ich vllt noch ne Kleinigkeit ansprechen wollen. Ob man im own config Menü vom Getriebe noch eine separat Rückwärtsgruppe festlegen könnte um den Effekt eines 18/6 Getriebes zu simulieren. 
Noch einmal ein riesen Lob vor deinen Leistungen. Wir sind mit deinem Script zufriedener als mit RMT und TSX. Wir finden auch das dein Getriebe keinen spürbaren Unterschied zum RMT aufweißt.
MfG Chris vom AG-OVP-Team 😉 
 
  Am Di., Mai 12, 2020 at 21:44 schrieb Stefan Biedenstein<notifications@github.com>:   


Ok, ich habe mal etwas ausprobiert...

Mit LShift und den Tasten V und B kann man das vordere Gerät heben/senken bzw. ein-/ausschalten. Mit RShift steuert man entsprechend das hintere Gerät.

Zuerst wollte ich es rekursive machen. Aber so wie es jetzt ist funktioniert es auch mit Agos M.H. From 3000. Wenn man es benötigt, dann kann man ein drittes Gerät kann man ja direkt selektieren und steuern.

**Comment by Mogli12** [comment]
Hi,

die Tasten kann man sich selber konfigurieren. Die Aktionen von VCA beginnen alle mit VCA:

LG

**Comment by ChrisJD8400R** [comment]
Hi, vielen Dank für die schnelle Antwort. Ist die Allradsteuerung jetzt Server ready und ist es möglich eine separate Rückwärtsgruppe in die Own config einzubauen.?😉😎 
Ich bin gespannt was du noch alles verfeinerst 😎
LG Chris vom AG-OVP-Team 😉

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Mai 13, 2020 at 12:27 schrieb Stefan Biedenstein<notifications@github.com>:   


Hi,

die Tasten kann man sich selber konfigurieren. Die Aktionen von VCA beginnen alle mit VCA:

LG

**Comment by cabmac** [comment]
> Hi,
> 
> die Tasten kann man sich selber konfigurieren. Die Aktionen von VCA beginnen alle mit VCA:
> 
> LG

Moin...wirklich klasse Sache...funktioniert einwandfrei...vielen Dank..

Schoene Gruesse,

Claudio
