### ISSUE TITLE
Hand Throttle Full Function Range

### ISSUE THREAD

**Issue by Procobator** [Mogli12/VehicleControlAddon#352]
I was having an issue with using the full range of my analog throttle for the hand throttle function.  I found the issue starting at line 1021 that reads:

if     isAnalog then 
			h = 1 + keyStatus 
		elseif keyStatus > 0.5 then 
			h = math.min( 1, h + 0.0005 * self.vcaTickDt )
		elseif keyStatus < 0.5 then 
			h = math.max( 0, h - 0.0005 * self.vcaTickDt )
		end 

In testing I found that this gives me hand throttle up to half the full rpm range and then goes directly to full rpm.  In order for my analog throttle controller to work with full adjustment of the rpm's it needs to read something along these lines:

 if     isAnalog then 
			if keyStatus > 0.5 then 
				h = math.min(1, keyStatus + 0.005 * self.vcaTickDt )
			elseif keyStatus < 0.5 then 
				h = math.max(0, 1 + keyStatus - 0.005 * self.vcaTickDt )
			end
		end 

This is a fantastic mod.  Keep up the good work.  Thank you.

**Comment by Mogli12** [comment]
Hi,

Analog hand throttle was designed for a slider. It uses only half of an axis.

Regards

**Comment by Procobator** [comment]
That makes sense.  That part of the code works exactly as intended then.  Thank you.
