### ISSUE TITLE
vehiclecontrolconfig.xml

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#353]
Moin Stefan,

ich sehe grad,dass es nun eine Option fuer die Geschwindigkeit (AWD) zum aut. Abstellen des Allrad gibt....klasse Sache...da ich mir die xml immer von Version zu Version "mitnehme",koenntest du da vielleicht noch eine Einstellung zur globalen Voreilung und des Allrads hinzufuegen?

Schoene Gruesse,

Claudio

**Comment by Mogli12** [comment]
Ist das wirklich notwendig?

**Comment by cabmac** [comment]
Hallo, nein, jetzt speichert er ja was ja vorher nicht war.. vielen Dank.
