### ISSUE TITLE
Kleine Korrektur/Schreibfehler

### ISSUE THREAD

**Issue by Amadeo01** [Mogli12/VehicleControlAddon#354]
Moin Stefan,
ich habe in der >modDesc_l10n_de< 3 "kleinere" Schreibfehler entdeckt:
Zeile 66   ...gedrecht in ...gedreht zu ändern
Zeile 67  wie Zeile 66
Zeile 135   VCA: Tempogeschindigkeit . Es fehlt das ...w...
Wenn Du Zeit hast, kannst du das vielleicht verbessern.

**Comment by Mogli12** [comment]
Danke, ich habe es korrigiert.
