### ISSUE TITLE
hinteres Gerät heben/senken funktioniert beim Ladewagen nicht

### ISSUE THREAD

**Issue by SuperSeba** [Mogli12/VehicleControlAddon#357]
Danke erstmal für den Einbau der Funktion. 

Beim betreiben eines Ladewagen´s ist mir allerdings aufgefallen das ich mit dieser Funktion den Pickup am Ladewagen nicht heben und senken kann.

**Comment by cabmac** [comment]
Moin...die Pick-ups gehen jetzt. hier noch etwas, was nicht geht... der Grubber hinter dem Guellefass z.B. (hab ich garnicht dran gedacht)
![fsScreen_2020_05_14_17_24_15](https://user-images.githubusercontent.com/16596142/81953612-2d2c3c80-9608-11ea-9a5f-ac656d47f6dd.png)

**Comment by cabmac** [comment]
Hallo Stefan, perfekt, kann man glaube ich, schliessen,

Schoene Gruesse
Claudio

**Comment by Mogli12** [comment]
Danke
