### ISSUE TITLE
Gang Hebel mit Gruppen belegen

### ISSUE THREAD

**Issue by Dagelkop** [Mogli12/VehicleControlAddon#358]
Hallo nochmal 😄,
den Mod finde ich nach wie vor geil, doch es gibt noch eine Sache, die mich ein bisschen stört. 😅

Ich möchte mit diesem Script mit meinem Lenkrad und shifter mit dem 4x4 PowerShift Getriebe spielen, funktioniert auch soweit gut.
Aber: wenn ich den Gang hebel konfiguriere, möchte ich die Gruppen (also bei 4 Gruppen LL, L, M und H) für die einzelnen Gänge nutzen. Also wenn ich den 1. Gang einlege möchte ich die Gruppe LL aktiviert haben. Die Gänge würde ich mit einem Kippschalter schalten, das funktioniert auch jetzt schon.

Also zusammengefasst möchte ich meinen Gang Hebel statt den Gängen mit den Gruppen belegen.

Hoffe es ist verständlich, was ich meine. 😄

**Comment by Mogli12** [comment]
Hallo,

nein, das geht leider nicht. Du kannst Dir aber ein eigenes Getriebe bauen.
Beispiel:
![image](https://user-images.githubusercontent.com/8790374/82034819-fb19e980-969e-11ea-99be-1a439b2a3f0d.png)

**Comment by Dagelkop** [comment]
Das würde ungefähr funktionieren. Problem dabei ist aber, dass beim PowerShift anstatt der Gruppen, die feiner geteilt sind, die Gänge geschaltet werden, welche größere Geschwindigkeitsabstände haben.

**Comment by Mogli12** [comment]
In meinem Beispiel oben sind halt die Gruppen feiner abgestuft. Wie bei Lastschaltstufen üblich, verringert sich von einer Gruppen zur nächsten die Maximalgeschwindigkeit um 80%.

Der G27-Hebel schaltet halt Gänge.

**Comment by Dagelkop** [comment]
Ah, jetzt hab ich. :D
Funktioniert jetzt so, wie ich es möchte, danke für die Hilfe. :)

**Comment by Mogli12** [comment]
Ich gebe immer zuerst die theoretische Geschwindigkeit bei Nenndrehzahl im höchsten Gang an. Das kling jetzt kompliziert. Wenn der Traktor voll ausdreht, dann ist das halt die Höchstgeschwindigkeit (z.B. 43 oder 53). Bei 53 km/h Höchstgeschwindigkeit funktionieren 58 oder 65 km/h ganz gut.

Danach gebe ich hier den Wert für Übersetzung vorletzte Gruppe ein, Bei einer Lastschaltung sind das meisten 80% => 0.8 * 53 = 42.4

Und nun kann man mit der Übersetzung 1. Gang herumspielen. Es kommen ja noch 3 Reduktionen von den Gruppen (hier Lastschalstufen) drauf, also 0.8*0.8*0.8 = 0.512. Gänge mit weniger als 5 km/h benötigt man kaum im Landwirtschafts Simulator. Ich gebe also irgendwas kleines ein, schliese das Menu und probiere die Gänge aus. Hier schaut man, ob die Übergänge zwischen den Gruppen und Gängen passen.

Viele Grüße

**Comment by Dagelkop** [comment]
Ich werd mein Glück dran versuchen. :)
Ich finds echt geil wie viel Mühe und Zeit dafür steckst, echt hammer!
