### ISSUE TITLE
Vorschlag manuelle Kupplung

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#359]
Hi Mogli

Wäre es machbar so wie PTO manuell die Kupplung zu steuern?

Ich spiele in der Regel mit der Tastatur  weil Lenkrad ständig an und abzubauen auf die Nerven geht.
Ich spiele gerne mit  "Permanent Geschwindigkeit halten" weil so einfacher ist mit Drehschemel rückwärts zufahren. Und jetzt kommen wir zum eigentlichen Problem. Bei Schrittgeschwindigkeit "2-7 km/h" ruckelt das Fahrzeug extrem.  Die Kupplung weiß nicht ob öffnen oder schleißen soll. Mein Wunsch wäre, dass ich selber entscheide wie stark die Kupplung "schleifen" soll. Ich meine im echten Leben fährst du rückwärts auch nicht mit dem Gas sondern mit der Kupplung . Und das ruckeln ist nicht nur bei Rückwärts fahren. Wenn ich die Kühe mit Futterwagen futtere dann spielt die Umdrehungsmesser verrückt .

Was hältst du von einem Kupplungsbegrenzer?

Ich hab dir ein kurzes Video hochgeladen, damit du weiß was ich meine 

https://youtu.be/4vxt4vnarsI

**Comment by Mogli12** [comment]
Es gibt ja bereits die analoge Kupplung über eine entsprechend belegte Achse. 

Ich habe in build 155 die Kupplung aber nochmal grundsätzlich überholt. Bislang war das Problem, dass die Kupplung irgendwie langweilig wurde, wenn VCA die Drehzahl gut getroffen hat. Da die Kupplung über eine Änderung der Übersetzung simuliert wird, hat das gleichzeitig zu einer Drehmomenterhöhung geführt. Über PowerConsumer zieht VCA nun dieses zusätzlich Drehmoment wieder ab. 

Wenn nun die Drehzahl zu hoch ist, oder der Gang zu lang übersetzt, dann kommt einfach zu wenig Drehmoment an den Rädern an. Gleichzeitig schließt jetzt die automatische Kupplung innerhalb von maximal 5 Sekunden. Und für Tempomat gibt es eine Sonderlocke.
