### ISSUE TITLE
Allradschltung vs Enhanced vehicle

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#360]
Hi

Könntest du bitte eine Sperre einbauen, damit man die Allradsteuerung von Enhaced Vehhicle Mod deaktivieren kann?

Ich nutze gerne Enhanced Vehicle Mod um das Gewicht der Fahrzeuge zu ermitteln oder um zu schauen wie stark die Fahrzeuge abgenutzt sind. Die Mod verhindert aber die Nutzung der Allradfunktion von VCA.

**Comment by cabmac** [comment]
das kannst du in der XM config des enhanced abschalten...

**Comment by Michael170978** [comment]
Gerne. Sag mir bitte wonach muss ich in der XML Datei suchen und ich schalte es ab. Ich finde die Zeile mit dem Allrad nicht. Hab nur Shuttle und die Differenzial Funktion gefunden.

**Comment by cabmac** [comment]
hm.. bin nur leider nicht am PC bis morgen frueh

**Comment by oschuhm** [comment]
Ich würde den Eintrag bei differentialIsEnabled auf false setzen

 <functions differentialIsEnabled="true" hydraulicIsEnabled="true" shuttleIsEnabled="false"/>

**Comment by Michael170978** [comment]
@oschuhm Könntest du bitte mir sagen welche Lua. datei das ist?

In der Enhanced Vehicle. lua hat mir die Suchfunktion nichts gefunden

**Comment by oschuhm** [comment]
> @oschuhm Könntest du bitte mir sagen welche Lua. datei das ist?
> 
> In der Enhanced Vehicle. lua hat mir die Suchfunktion nichts gefunden

Das steht in der Konfigurationsdatei für Enhanced Vehicle
https://www.ls-farmers.de/index.php?article/19-tsx-enhanced-vehicle-mod-konfigurieren/

**Comment by Michael170978** [comment]
Also ich weiß ja nicht mit welcher Version der jenige arbeitet, der diesen Text im Internet verfasst hat. Aber in der neuesten Version gibt es keine Enhanced Vehicle.xml Datei. Es gibt 4 Lua Dateien. Un in jeder hab ich gesucht und diese Zeilen so wie da auf der Seite steht gibt es nicht. Anscheinend wurde Enhaced Vehicle überarbeitet. Aber trotzdem für die Hilfe. Ich schau weiter vielleicht gelingt es mir doch zu deaktivieren.

**Comment by oschuhm** [comment]
Hast Du den Beitrag richtig gelesen?

> Im Spieleverzeichnis, dort wo sich auch der "mods" Order befindet, gibt es einen Ordner mit dem Namen "modsSettings".
In diesem Ordner findet ihr einen Order mit dem Namen "TSX_EnhancedVehicle".
Darin gibt es eine Datei mit dem Namen "TSX_EnhancedVehicle_v1.xml".

**Comment by Michael170978** [comment]
Sorry wegen dem ganzen Frust und so hab ich leider übersehen. Hab umgeändert. Jetzt geht es. Danke

**Comment by oschuhm** [comment]
> Sorry wegen dem ganzen Frust und so hab ich leider übersehen. Hab umgeändert. Jetzt geht es. Danke

Gern geschehen

**Comment by Mogli12** [comment]
TSX Enhanced Vehicle hat Allrad eher angeboten. ich denke aber, dass vor allem der 2-Rad-Antrieb in VCA besser implementiert ist, da in VCA die Differentiale auch wirklich aus der Physik genommen werden.

Daher ist es nun so, dass Allrad in VCA aus bleibt, wenn er in TSX an ist. Eine andere Lösung sehe ich nicht.

**Comment by Michael170978** [comment]
Alles gut. Ich möchte erst mal testen wie Autodrive mit der Allrad Funktion bei VCA klar kommt. Mir ist bei TSX aufgefallen, dass obwohl Allrad deaktiviert war hat Autodrive wieder eingeschaltet. Ich möchte sehen wie das bei VCA aussieht.
