### ISSUE TITLE
Duplicate entry for 'Linear sound pitch' setting and no option to control 'drawHud' parameter

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/VehicleControlAddon#361]
Using the latest developer version of VCA (FS19_VehicleControlAddon (Version: 9.1.5.4)).

The setting for Linear Sound pitch is available in both the 'Throttle and Snap Driving Direction' screen and in the 'Global Settings' screen:

![fsScreen_2020_05_16_11_39_29](https://user-images.githubusercontent.com/8794862/82116549-f4f13f00-976a-11ea-921c-4b3e5d0b33dd.png)
![fsScreen_2020_05_16_11_39_38](https://user-images.githubusercontent.com/8794862/82116553-fd497a00-976a-11ea-95fa-7e5884c2a114.png)

Is this intentional?

Also there is an option 'drawHud' in the config.xml to enable or disable the in-game HUD (compass, etc.), but there seems to be no item in the 'Global settings' screen to control this option (only the HUD position can be changed). Would it be possible to add this to the settings?

If needed log.txt is available at https://gist.github.com/fdanapfel/2d6fc4c196864f4b2762570279222d88

**Comment by Mogli12** [comment]
The HUD setting is on the second tab the last entry in the left column.

Please rad the text of the global settings tab. These are the global settings, written to modsSettings/FS19_VehicleControlAddon/config.xml. They do not change the current vehicle.

**Comment by fdanapfel** [comment]
> The HUD setting is on the second tab the last entry in the left column.

You mean the setting labeled 'Transmission HUD'? If yes, then it is a bit confusing, since because it is named 'Transmission HUD' you would not think that it also switches the display of the compass on and off.

> Please rad the text of the global settings tab. These are the global settings, written to modsSettings/FS19_VehicleControlAddon/config.xml. They do not change the current vehicle.

Hmm, since 'drawHUD' is a global setting that is written to modsSettings/FS19_VehicleControlAddon/config.xml I would have expected to find the option to change it under the 'Global Settings' tab.

What about the other issue regarding the duplicate 'Linear sound pitch' setting. Is this expected to be there twice?

**Comment by Mogli12** [comment]
Yes, once for the current vehicle and once to edit modsSettings/FS19_VehicleControlAddon/config.xml
