### ISSUE TITLE
Wunsch beim Getriebe 

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#362]
Ich hätte da noch eine kleine Anregung. Vllt könnte man in dem own Config Getriebemenü noch eine separate Rückwärtsgruppe einbauen das man auch z.B. ein Getriebe mit 18 Vorwärts und 6 Rückwärtsgängen bauen kann. 

Wäre es möglich die manuelle Allradsteuerung auch für Telelader, Quadtrac, Raupen usw zu nutzen? Beim Holmer DLC funktioniert der manuelle Allrade auch nicht .

LG Chris

**Comment by Mogli12** [comment]
Hallo Chris,

mit Build 312 kannst Du die Rückwärtsgänge oder -gruppen auswählen. Es hat halt so lange gebraucht, da ich zunächst eine Idee brauchte, wie man am besten eine Liste eintippt. Man kann mehre Gänge durch Komma getrennt eintippen. Das Dezimaltrennzeichen ist ja ohnehin der Punkt und nicht das Komma.

![fsScreen_2021_01_14_22_35_08](https://user-images.githubusercontent.com/8790374/104652042-d3a96f80-56b8-11eb-85f7-b4917fad65b0.png)

Beim 2x6 Getriebe für LKW sind z.B. die nur dir Gänge 3 und 6 in der 1. Gruppe als Rückwärtsgänge verfügbar. ich habe auch die beiden John Deere Getriebe 16x5 und e23 bereits im Mod hinterlegt.

Viele Grüße,
Stefan

**Comment by ChrisJD8400R** [comment]
Vielen Dank für die Antwort und Respekt für deine Leistungen mit dem VCA. 
Wenn man jetzt nur noch eine splittergruppe als separate Gruppe erstellen könnte im own Config wäre das top. Ich weiß das da die Tastenbelegungen das Problem sind, aber vllt findest du ja da auch noch einen Lösung über eine Strg Alt Ü und Ä zum schalten. 

Liebe Grüße, Chris

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Jan. 14, 2021 at 22:36 schrieb Stefan Biedenstein<notifications@github.com>:   


Hallo Chris,

mit Build 312 kannst Du die Rückwärtsgänge oder -gruppen auswählen. Es hat halt so lange gebraucht, da ich zunächst eine Idee brauchte, wie man am besten eine Liste eintippt. Man kann mehre Gänge durch Komma getrennt eintippen. Das Dezimaltrennzeichen ist ja ohnehin der Punkt und nicht das Komma.



Beim 2x6 Getriebe für LKW sind z.B. die nur dir Gänge 3 und 6 in der 1. Gruppe als Rückwärtsgänge verfügbar. ich habe auch die beiden John Deere Getriebe 16x5 und e23 bereits im Mod hinterlegt.

Viele Grüße,
Stefan

**Comment by ChrisJD8400R** [comment]
Noch ein Anliegen lieber Stefan, die neuste Version legt den Dedicated Server lahm beim laden. Im Single Player läuft es. 

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Jan. 14, 2021 at 22:36 schrieb Stefan Biedenstein<notifications@github.com>:   


Hallo Chris,

mit Build 312 kannst Du die Rückwärtsgänge oder -gruppen auswählen. Es hat halt so lange gebraucht, da ich zunächst eine Idee brauchte, wie man am besten eine Liste eintippt. Man kann mehre Gänge durch Komma getrennt eintippen. Das Dezimaltrennzeichen ist ja ohnehin der Punkt und nicht das Komma.



Beim 2x6 Getriebe für LKW sind z.B. die nur dir Gänge 3 und 6 in der 1. Gruppe als Rückwärtsgänge verfügbar. ich habe auch die beiden John Deere Getriebe 16x5 und e23 bereits im Mod hinterlegt.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo,

falls es Probleme verursacht durch VCA im Dedi-Server gibt, dann mach bitte ein neues Issue auf und lade die Log-Dateien vom Server hoch.

Danke

**Comment by Mogli12** [comment]
Hallo,

Das Dedi-Problem wurde in #511 gelöst.

Viele Grüße
