### ISSUE TITLE
Hilfe mein Fendt hat einen Schluckauf

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#364]
Hi

https://youtu.be/2_JSGFjj4MY

Seit dem neuen Update stottert mein Fendt nur.

Egal welchen Gang ich einlege. Bis 20km/h geht die Umdrehung hoch und runter. Ab 20km/h beruhigt sich das Ganze oder die Kupplung schleift. Das passiert nur wenn Autopilot aktiviert ist. Sobald die Kupplung anfängt zu schleifen verschwindet das Schottern wieder.

**Comment by Mogli12** [comment]
Bei so einem alten Traktor kann der Tempomat doch mal spinnen, oder?

**Comment by Michael170978** [comment]
Ähm....jein. Wenn das nur bei dem olen Tracker wäre, dann wäre halb so schlimm.

Vor allem ich nutze den um Heuballen vom Feld auf den Anhänger zu laden. Jetzt stell dir mal vor wie das ist wenn du versuchst sauber die Ballen auf den Anhänger zu laden. Das ist Abenteuer pur
