### ISSUE TITLE
VCA-REA (4WD)

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#365]
Hallo,
sobald man mit REA den Allrad dazuschaltet, geht die Geschwindigkeit (bei meinem Beispiel beim maehen) deutlich runter...schalte ich den Allrad wieder aus, geht die Arbeitsgeschwindigkeit wieder rauf...als ob da irgendwo mit allrad ein consumption da ist. Beim meinem Video kann mann das deutlich sehen (schlechte Qualitaet, ich weiss)

https://www.youtube.com/watch?v=9VFMxzlqyHg&feature=youtu.be

ich denke mal, dass das eher ein Problem von REA ist als von VCA, da das Ding leider noch eine ganze Menge Feintunig braucht, oder?
Bei sek 7 schalte ich den Allrad ein und verliere 6km/h auf einmal....schalte ich den wieder ab, gehts wieder.

Schoene Gruesse

**Comment by Mogli12** [comment]
Hast Du Voreilung an? Dabei lässt das Mitteldifferential einen gewissen Geschwindigkeitsunterschied zu. Die Voreilung wird dann über Abbremsen der Hinterräder erreicht.

**Comment by cabmac** [comment]
ahhh.. Voreilung war an, ja, das wird es wohl sein, bin nur leider nicht mehr am PC... Berichte morgen frueh

**Comment by Michael170978** [comment]
Könnt ihr mir bitte sagen was eine Voreilung ist und wo man aktiviert bzw. deaktiviert?

**Comment by Mogli12** [comment]
@Michael170978 

> Der Allradantrieb hat verbreitet die sogenannte Voreilung: dabei erreichen die Vorderräder eine etwa zwei Prozent höhere Drehzahl als die Hinterräder und beugen dadurch Verspannungen im Getriebe bei Kurvenfahrten vor. Der zwangsweise entstehende Schlupf ist tolerierbar, solange keine Straßenfahrt oder Arbeiten mit Geschwindigkeiten über 15 km/h stattfinden.

aus: https://de.wikipedia.org/wiki/Traktor

**Comment by Michael170978** [comment]
Ok. Und wo schaltet man das bei REA Mod an? Ich frage deshalb weil ich nutze auch die Mod und möchte nachschauen ob bei mir ebenfalls aktiviert ist.

**Comment by cabmac** [comment]
moin, das schaltet man in VCA ein im vorletzten "Differenziel-Reiter"

zum Thema, Voreilung abgestellt aber dasgleiche Dilema...beim Allradzuschalten geht die Geschwindigkeit bis zu 7km/h runter, mit REA...habe allerdings dann REA mal rausgenommen und da war praktisch kein Unterschied mit Allrad oder ohne merkbar. Scheint wohl doch an REA zu liegen...(?)

**Comment by Michael170978** [comment]
Sooo..... Nach dem ich von euch aufgeklärt wurde, kann ich meinen Senf zugeben. Ich hab das gleiche bei mir, mit Kombination einer Sämaschine, gemacht. Voreilung aus, Allrad aus uns ich säe 1-2 km/h langsamer als mit Allrad an. Also quasi genau umgekehrt als bei dir. Ich muss dazu sagen ich hab das mit Vario Getriebe ausprobiert. Ich weiß nicht ob das Getriebe einen Einfluss da drauf hat.

**Comment by cabmac** [comment]
Wenn du mit REA spielst sollte das eigentlich so sein....

**Comment by cabmac** [comment]
Hallo,
geht leider immer noch nicht und ich denke, dass das doch nichts mit REA zu tun hat,:

mit REA:
https://www.youtube.com/watch?v=JrmpcYqhoAQ&feature=youtu.be

ohne REA:
https://www.youtube.com/watch?v=4M2vavxEBFM&feature=youtu.be

vanilla mit Fendt und Claas-Pack
https://www.youtube.com/watch?v=QLx_LuxF4MM&feature=youtu.be

ohne REA geht die Geschwindigkeit beim aktivieren des 4WD sogar extrem auf 4km/h runter.

DAs letzte ist praktisch vanilla-game, also muesste das bei anderen ja eigentlich auch sein,oder?

Schoene Gruesse,

Claudio

**Comment by Michael170978** [comment]
Was ist das für ein MW was du dran hast?

Ich möchte schauen ob bei mir auch so extrem ist?

Ich wollte schon schreiben ob es sein kann, ob dein Schlepper zu wenig Leistung hat. Aber nach dem ich gesehen hab dass es ein 939 ist, wusste ich der hat mehr als genug  Leistung.

**Comment by cabmac** [comment]
Hallo...ich habe jetzt nochmal hin- und hergetestet..jetzt wirst du mich totschlagen ( :D )es kann sein, dass das der Trecker ist, ich habe selbe Situation jetzt mit einem MF und dem 900 Claas aus dem PAck ausprobiert und da habe ich den Effekt nicht...kann ich hier irgendwo den Fendt anhaengen und du vielleicht probieren, ob es wirklich der Fendt ist?

**Comment by cabmac** [comment]
https://filehorst.de/d/duJidAqb
 das ist der Fendt...waere ja aufschlussreich, ob es daran liegt...

**Comment by Michael170978** [comment]
Ich glaube du kannst hier ZIP datei dranhängen. Und das würde super passen, den ich hatte heute vor gehabt Grasballen zu machen. Dann würde ich über meine Grasfläche  drüberfahren und in wenigen Minuten eine Antwort haben

**Comment by Mogli12** [comment]
mbiedens@gmail.com

**Comment by Michael170978** [comment]
Läuft einwandfrei bei mir

https://youtu.be/-lwGKbAymyY

**Comment by cabmac** [comment]
mach mal ein FM dran und hau den Allrad bitte mal waehrend dem fahren rein wenn du kannst...

**Comment by Michael170978** [comment]
Läuft wie ein Kätzchen

https://youtu.be/Q51KcUxVGzc

**Comment by cabmac** [comment]
ich meinte eigentlich beide MW...nur ums mal zu sehen....jedenfalls hast du ebenfalls die Drezahlschwankung beim aus- und beim anschalten drin...

**Comment by Michael170978** [comment]
Drehzahlschwankungen habe ich oft wenn dem Boden uneben ist.

Hier hast beide dran

https://youtu.be/KBY4c0cOh_A

**Comment by cabmac** [comment]
Die Drezahlschwankung ist beim Ein- und Ausschalten des 4wd bei dem Schlepper, das ist bei anderen nicht...also irgendwas stimmt dabei nicht...Stefan, wenns wirklich "nur" der Fendt sein sollte, mach dir den Kopf nicht heiss...schmeiss ich den raus und gut ist....

**Comment by cabmac** [comment]
Moin..immernoch dasselbe...ich habe selbe Situation (map, MW,mods) jetzt mit einem JD , da passiert das nicht. Ich hatte sogar dasselbe Getriebe ausgewaehlt (Vario) aber nichts zu machen...Das ist anscheinden wirklich nur der eine Modtraktor...nur das warum.....

Schoene Vatertag euch (hier gibts das nicht)

**Comment by cabmac** [comment]
moin....wirklich komische Sache...

https://www.youtube.com/watch?v=lPbVWUhVj3s&feature=youtu.be

mittlerweile scheint das auch "nur" noch an Steigungen zu sein, das wo das nicht so steil ist , gehts anscheinden (anfangs hat der das auch bei ganz leichten Steigungen oder im geraden gemacht)

**Comment by Mogli12** [comment]
Probier mal Build 164 aus. REA führt leider zu sehr großen Einbrüchen in der Geschwindigkeit. Gleichzeitig ist in der Engine aber vorgesehen, dass man die Beschleunigung des Fahrzeugs begrenzt. Durch einen simulierten "Bump" bricht die Geschwindigkeit also um mehrere km/h ein, aber die erlaubte Beschleunigung (Vanilla 2 m/s^2) reicht gar nicht aus, um das in den nächsten Frames überhaupt auszugleichen, Am Ende ist die Geschwindigkeit zu niedrig, obwohl das Fahrzeug nur zu gut 85% ausgelastet ist.

Ich vermute, dass das Problem gar nicht so sehr in REA ist. Die Giants Engine kann einfach so viel Schlupf nicht richtig.

Anstatt die Beschleunigung generell auf 2 m/s^2 zu begrenzen, errechnet VCA nun die mögliche Geschwindigkeit im nächsten Frame mit der maximalen Steigerung addiert. Um die Einbrüche zu überbrücken, wir als Basis die Maximalgeschwindigkeit der letzen 500 ms verwendet, Damit schaffe ich es auch wieder, trotz REA das Fahrzeug zu über 95% auszulasten.

**Comment by cabmac** [comment]
Hallo, die Aufnahme ist mit 164 und REA aus (REA ist zwar ein schoener Ansatz aber das sind noch einige viele Sachen im Argen, die so unrealistisch und/oder einfach nicht funktionieren). Ich bin davon ueberzeugt,dass das mit dem Traktor zu tun hat (ich weiss zwar nicht warum, das es eigentlich ein standart 900 ist mit paar anderen Raedern, Fenster und seatcam).
Hier nochmal einen John Deere 8R , wieder ohne REA und mit 164...da ruehrt sich garnichts,wenn ich den Allrad dazuschalte...

https://www.youtube.com/watch?v=3X9lQwgZ2MQ&feature=youtu.be
