### ISSUE TITLE
Anbaugeräte schalten sich ab

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/VehicleControlAddon#366]
Hallo zusammen,
ich habe mit den aktuellen Versionen von VCA (Build  156 und 157) das Problem, dass sich Anbaugeräte immer wieder abschalten. Ich hatte eine Mähwerkkombi (Front und Heck) am Traktor und bei jedem Wechsel der Fahrtrichtung (ShuttleControl) und ab und an auch direkt beim Anfahren ist das Heckmähwerk ausgegangen. Mit Build 155 tritt das nicht auf.

**Comment by Mogli12** [comment]
Traktor, Getriebe, Gang, Screen Shot?

**Comment by Evilman2517** [comment]
Entschuldige bitte meinen unqualifizierten Report, da fehlen wirklich viele Infos (Claas Arion 630 / HexaShift / C 1-4) . Aber dein Fix hat das Problem bereits behoben. Vielen Dank für das schnelle Beheben des Fehlers.
