### ISSUE TITLE
implementation suggestion

### ISSUE THREAD

**Issue by denut** [Mogli12/VehicleControlAddon#367]
hello
you are working to implement 4x4 and diff lock
we are using https://gamesmods.net/farming-simulator-2019/other-fs19-mods/98445-enhancedvehicle-v1631.html
if we want to remplace this mod with only yours there is some fonction we need in yours 

1: possibility to assign front and back lifter eatch to a bouton
2: possibility to assign front and back pto eatch to a bouton
3: if you can because zhool have not found the solution possibility to assign plow rotarion to the same PTO bouton (in the case of use a front and rear plow) or one bouton to rotate the 2 plow together

4: change the max speed storage in savegame that the speed is unique for all players and the modification locked by password to avoid players to drive the vehicles at 90km/h with a fiat dt1300 for exemple

thanks again for your mod 
hope you and your family are all fit
have a nice day and take care in this difficult periode with this viruses

**Comment by cabmac** [comment]
hi...1 and 2 is done yet....

**Comment by denut** [comment]
sorry don't have see ..

**Comment by Mogli12** [comment]
What is your screen resolution?

**Comment by denut** [comment]
Effective Window Resolution:  5760 x 1080

**Comment by denut** [comment]
i found a small issues by reverse driving on xerion for sample the front and back lifter will not be automaricaly reverted

**Comment by Mogli12** [comment]
Hi, It is not even expected that they are reverted.

**Comment by Andman1988** [comment]
Hi, 
I have the same problem (5760x1200).
For now i have fixed it by editing the position for shuttle control and differential 
![hud](https://user-images.githubusercontent.com/17678470/82737779-bb54a100-9d33-11ea-9b9e-9d0d45651942.png)
@Mogli12  Maybe it is possible to define the positions in the menu like for the shift and GPS text
