### ISSUE TITLE
Umfrage zur Kupplung

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/VehicleControlAddon#368]
Hi 

Was haltet ihr von der Kupplung, die ich in den Version 155 bis 160 gebaut habe?

Zum Hintergrund: Seit FS19 wird einmalig die Drehmomentkurve an die Engine übergeben. Dort wird dann passend zur Drehzahl das entsprechende Drehmoment ermittelt. Damit muss auch mit einer Kupplung die hör- und sichtbare Drehzahl der Drehzahl in der Engine entsprechen. Daher ist die Kupplung recht ähnlich zum stufenlosen Getriebe. VCA gibt eine Korridor für Drehzahl und Übersetzung vor. Der Korridor für Drehzahl wird beim beim Schließen der Kupplung immer weiter, der Korridor der Übersetzung wird schmaler und nähert sich der Übersetzung des Ganges an.

Mit der geänderten Übersetzung erhöht sich damit aber auch das Raddrehmoment, was das Anfahren unrealistisch und für mich zu einfach macht. Durch eine Kupplung erhöht sich nicht das Raddrehmoment. Bei einem Drehmomentwandler erhöht sich das Drehmoment auch nur bis ca. Faktor 3. Beim Anfahren hat man aber anfangs den Faktor 30. 

Also "klaut" VCA jetzt dem Motor beim Drehmoment über die Spezialisierung PowerConsumer. Da verhält sich die Engine übrigens ganz "lustig". Wenn man mehr klaut, als da ist, dann ergibt das nicht ein Drehmoment von 0, sondern das externe Drehmoment wird einfach komplett ignoriert. 

Wie kommt ihr im Spiel mit der Kupplung im Spiel klar? Habt ihr (z.B. beim alten Fendt 500) mal die Strömungskupplung probiert?

LG

**Comment by Evilman2517** [comment]
Ich persönlich finde die neue Kupplung klasse. Das verzögerte langsamere Anfahren, aber auch den Schaltvorgang, der jetzt "Schwung" wegnimmt. Bin zum Test einmal auf die alte 154 gegegangen und merke jetzt, wie "komisch" unnatürlich das Verhalten da war.

**Comment by cabmac** [comment]
hi, ich habe es nur kurz mal getestet, da ich die ganze Zeit mit dem anderen Thema beschäftigt war.. Ich habe es bei dem 500 mit selbstgebautem Getriebe und Aut kupplung (wegen Tastatur) ein bisschen rukelig gefunden.... werde morgen nochmal genauer schauen. 

Schoene Gruesse

**Comment by Bomberman82** [comment]
Hallo @Mogli12,

ich werde es mal testen wenn ich mal Zeit habe @Mogli12 muss leider arbeiten komme kaum dazu mal den Rechner anzuschmeißen. 

Aber ich weiß es jetzt schon das es super wird. @Mogli12 deine VCA kenne  ich schon seit längerm und freue mich immer wieder das du neue Updates veröffentlichst. 

Klasse das du am Ball bleibst. Wenn du noch deine Paypal Adresse oder nen Spendenbutton hättest würde ich dir was zukommen lassen für ein Bierchen hat man ja immer mal Zeit oder? ;)

**Comment by Mogli12** [comment]
@cabmac Ja, es kann schon etwas ruckeln. Ich habe erst gedacht, dass ich die Drehzahl mit Kupplung noch etwas glätte, habe ich aber dagegen entschieden.

Allerdings hat mit Passat mit Doppelkupplung das IRL auch nicht besser hinbekommen...

**Comment by cabmac** [comment]
Hi..also nochmal getestet...klasse Sache, wie gesagt, das einzige ist, z.B. beim FL-Arbeiten mit dem 500 ein bissl ruckig mit aut. Kupplung( kann ich persoenlich mit leben), ansonsten sehr feine Sache...
