### ISSUE TITLE
Tempomat

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#370]
Hallo Stefan,
gerade beim Ausprobieren der Kupplung ist mir etwas aufgefallen. Wenn ich das richtig verstehe, kann man 3  Geschwindikeiten in jeder der 3 Tempomatstufen "speichern", so dass man doch z.B: die 1 fuer Hofarbeiten, die 2 fuer Feldarbeiten und die 3 fuer Strassenfahrt mit den jeweiligen 3 Geschwindigkeiten "programmieren" kann und diese innerhalb mit 4 verstellen kann, oder verstehe ich das falsch?
Sollte das so sein, bei mir speichern sich die verschiedenen Geschwindigkeiten nicht ab, also wenn ich von Stufe 1 auf 3 gehe z.B, haben sich die Geschwindigkeiten wieder veraendert......

Vielleicht sitzt das Problem auch mal wieder vor dem Bildschirm, k.A. ;D

**Comment by Mogli12** [comment]
Also war das ein Modkonflikt? Ich nehme gerade bei stufenlosen Traktoren meisten Strg+Entf (konstant Geschwindigkeit halten). Man kann die nächste Geschwindigkeit gemütlich vorwählen und mit 3 aktivieren.
