### ISSUE TITLE
IVT or Vario Gearbox efficiency

### ISSUE THREAD

**Issue by RedStan89** [Mogli12/VehicleControlAddon#371]
Hi,

First, thank you a lot for your mod !
I always search a edit the game to be more realistic ! And your mod is awesome !

I have just a question / request.
In fact, when using Infinite varation gearbox like IVT or Vario I have an efficiency problem...
I did some test, with a tractor and a full load trailer on a hill road.
**With the defaut gearbox :** 1892rpm and 7.3km/h = Ok
**With an FullPowershift gearbox :** 2000rpm 7.3km/h = Ok (Rpm depend of the gear ratio)
**But with a vario or IVT Gearbox :** 2083rpm 4.8km/h = NOk
I only can reach the **7.3km/h** by lowering manually rpm's with the handthrottle.
When lowering manually rpm's at (approx) 1700 rpm, the tractor reach 7.3km/h with IVT or  Vario Gearbox.

Can you help me with this ?
I can make a video if you want

Stan
A French Follower.

**Comment by Mogli12** [comment]
Hi,

What tractor are you using. And what tool? Do you use [REA](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=138280&title=fs2019)? Maybe you can attach the log.txt plus a screen shot?

Thanks, 
Stefan

P.S.: Under full load the tractor with IVT should use 1700 RPM

**Comment by RedStan89** [comment]
Here my mod list.
Yes I'm using REA0
I've tested with differents tractors, even originals.
I'm using on the video the original John Deere, I only made a mod of it because i've change wheels and for multiplayer compatibility.
![Mogli](https://user-images.githubusercontent.com/65650783/82478424-2fdbd580-9ad1-11ea-8b0a-2e07bd5f7db3.png)

Here the video : https://www.youtube.com/watch?v=YWgeXz_Ef_0

**Comment by Mogli12** [comment]
Thanks for the video. I will try to reproduce it.

**Comment by RedStan89** [comment]
Thanks :)
If you need something else (another video...) just tell me.

**Comment by Mogli12** [comment]
Please test the latest version.

**Comment by RedStan89** [comment]
Way Better !
I can now reach the 7.3km/h thanks !
You can find bellow another video with the latest version of your mod.
Sometimes the rpm goes high and down.

https://www.youtube.com/watch?v=4Kc3_qSlSy8
