### ISSUE TITLE
Combine loading impossible

### ISSUE THREAD

**Issue by RedStan89** [Mogli12/VehicleControlAddon#372]
Hi !

Since the new version of VehicleControlAddon, impossible to load Combines with front tires.
I can load it by deleting the VehicleControlAddon mod.

Here the video : https://www.youtube.com/watch?v=1yescfEq1Bo
On attached files the log.

Thanks for your help :)
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4662522/log.txt)

**Comment by Mogli12** [comment]
Hi,

Do you really think that this is related to VCA? The log does not show it.

Regards,

**Comment by RedStan89** [comment]
You're right I think.
The problem should be on the combine Mod (not compatible with the VCA).
I think I could understand that the differential script is searching for frontwheels on the combine but it doesn't work.
I'll try to fix it.
Thanks for your help !
