### ISSUE TITLE
Coursplay/Autodrive deaktiviert Allrad

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#373]
Hi

Wenn man Courseplay bzw Autodrive aktiviert, dann verschwindet das Zeichen fürs Allrad und Differenzialsperre.
Ich bin vor allem in Winter auf die Differenzailsperre angewiesen, sonst schaffen die Lkw manche Steigungen nicht.

Komischerweise bei Enhaced Vehicle kann ich Allrad und Differenzial nutzen. Kann man Allrad so programmieren, dass obwohl Autodrive aktiviert ist trotzdem man Allradfunktion nutzen kann?

**Comment by Mogli12** [comment]
Hi,
Ab Build 162 kann man die Differentiale auch für Helfer einschalten.
Viele Grüße
