### ISSUE TITLE
Separate InputBindings für Parkbremse An/Aus

### ISSUE THREAD

**Issue by Andman1988** [Mogli12/VehicleControlAddon#376]
Hi,

erstmal Danke für deine Arbeit.

Könntest du dir vorstellen, für die Parkbremse separate InputBindings zum An- und Ausschalten hinzuzufügen.
Quasi wie bei der Shuttle Control.

Hintergrund ist, dass ich mir einen eigenen Controller für die Shuttle Control und die Zündung gebaut hab. Musste mir aber ziemlich einen abbrechen, damit die Parkbremse größtenteils richtig schaltet.

**Comment by MichalKucavik** [comment]
I agree, I'm also going to make a parking brake control (from a truck controler) and the ability to turn the parking brake on and off will probably be a necessity for it to work properly.

**Comment by Mogli12** [comment]
Hi,

There are two additional input actions vcaNeutral0 and vcaNeutral1 in buidl 164.

Regards
