### ISSUE TITLE
6PS Getriebe und g27 schifter

### ISSUE THREAD

**Issue by Jannik0210** [Mogli12/VehicleControlAddon#378]
hey Mogli,
ich mag deine Modifikation sehr und finde vor allem die Möglichkeit die automatischen Getriebe zu simulieren sehr gut. Nun zu meinem Problem bzw. eher Improvement: Ich benutze einen G27 Shifter und habe in meinem neuen John Deere 6M ;) das 6x4 Autopowershift Getriebe ausgewählt. Wenn ich nun fahre und ganz normal schalter ist auch alles gut jedoch schaltet das Getriebe nicht mehr automatisch die Lastschaltstufen. Sprich ich benutze den Schifter und komme immer direct in die 4. Stufe des Getriebes. Fahre ich jedoch unter starker last würde das Powershift getriebe normalerweise runterregulieren um das Drehmoment besser auszunuten. Nun zum kniffligen wenn ich jedoch manuell schalte funktioniert die automatische Regelung. Ich hänge mal meine Einstellungen an mit denen ich dieses Problem gefunden habe.
![Desktop Screenshot 2020 05 24 - 17 23 41 68](https://user-images.githubusercontent.com/65861316/82757862-59ec0b00-9de3-11ea-9298-2748cd140dbe.png)

**Comment by Mogli12** [comment]
Hallo,
Aktuell schaltet die Verwendung des Ganghebels die Automatik ganz aus. Du kannst mit vcaShifterLH ("VCA: G27/G29 Gang Splitter") den Bereich von Hand wechseln.
Viele Grüße

**Comment by Jannik0210** [comment]
Hi danke für die Antwort, naja der Splitter macht es natürlich etwas einfacher voran zu kommen aber so richtig realistisch ist er ja irgendwie doch nicht. Gibt es vielleicht die Möglichkeit das über eine Menüfunktion das automatische Lastschalten auch bei Handschaltung aktiviert wird. Bin absolut unerfahren was scripten angeht deshalb musst du das natürlich nach der Umsetzbarkeit beurteilen und ist auch nur eine Anregung also mach die keinen Stress. Das VCA ist trotzem eines der besten Modifikationen für den LS 19 und auch so schon allerhöchste Qualität. Danke für die geilen Mods. Chapeau!

**Comment by Jannik0210** [comment]
Hi, erstmal danke für den Aufwand. Jedoch habe ich es gerade mal ausprobiert und es scheint so als wäre es nicht anders als zuvor. Ich schalte mit dem g27 und kein Autopowershift setzt ein. Was genau hattest du denn verändert? 
MfG Jannik

**Comment by Mogli12** [comment]
Stell man auf "6G, R+/-, 1R" oder "6G, R+/-, Shuttle". Bei "6G, 1R, LH" sollte sich eigentlich gar nichts geändert haben.
