### ISSUE TITLE
LUA Error when switch on Gearbox

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#379]
Hallo Stefan,
Wenn ich beim LKW das Getriebe einschalte bekomme ich den folgenden lua-Fehler:

FS19_VehicleControlAddon/vehicleControlAddon.lua:5706: attempt to perform arithmetic on local 'vOver' (a nil value)

Ich habe mal geschaut und in Zeile 5683 den Code von
					lOver = torque 
auf
					vOver = torque 
geändert.
Keine Ahnung ob das nur ein Tippfehler ist und meine Änderung richtig ist aber jetzt bleibt der lua-Fehler aus.

Besser du schaust dir das mal an.

**Comment by Mogli12** [comment]
Danke, das scheint wirklich ein Tippfehler zu sein.

**Comment by Williwillswisse** [comment]
Immer gerne, aber wie gesagt weiß ich nicht ob die Änderung richtig ist....war nur ein Versuch. ;-)
