### ISSUE TITLE
LUA Error when enter Vehicle with build 163

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#380]
Hallo Stefan,
nach deiner letzen Änderung habe ich den folgenden Effekt:

Steige ich nach dem Start des Spiels in das erste Fahrzeug kommt der folgende Fehler:

2020-05-28 09:27 Error: Running LUA method 'update'.
2020-05-28 09:27 dataS/scripts/input/InputBinding.lua(778) : attempt to index local 'testAction' (a nil value)

Danach kann ich noch ein Fahrzeug weiter tabben und dann ist die Tastatur tot.
Kann das mit dem Issue #376 zu tun haben?

**Comment by Mogli12** [comment]
Welche Version?

**Comment by Williwillswisse** [comment]
163, wie in der Überschrift ;-)

**Comment by Mogli12** [comment]
Und in Build 164?

**Comment by Williwillswisse** [comment]
Fehler ist weg 👍

**Comment by Mogli12** [comment]
Ich habe in Build 163 vergessen, die Änderung an der modDesc.xml zu speichern.
