### ISSUE TITLE
min/max Ganggeschwindigkeit

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#381]
Hi

Ich spiele zur Zeit mit der min bzw. max. Ganggeschwindigkeit herum aber irgendwie sehe ich keine Veränderung. Ist nicht Geschwindigkeit Startgang und min. Ganggeschwindigkeit das selbe?

**Comment by Mogli12** [comment]
Hi Michael,

kannst Du das etwas konkreter machen?

Viele Grüße,
Stefan

**Comment by Michael170978** [comment]
Hallo Stefan

Naja. Ich weiß leider nicht wozu die Option/Funktion min. Ganggeschwindigkeit da ist. Daher habe ich spaßeshalber verschiedene Geschwindigkeiten z. B 9km/h angegeben. Jetzt meine Frage. 

![Unbenannt](https://user-images.githubusercontent.com/53015927/83162544-2cb49b00-a10a-11ea-8361-30ed331c4d6f.jpg)

Könntest du mir biite sagen Welches Nutzen habe  ich wenn bei min. Ganggeschwindigkeit 9km/h steht?

Viele Grüße Micha

**Comment by Mogli12** [comment]
Hallo Micha,

die Einstellung kommt vor allem vom stufenlosen Getriebe. Auch wenn 30 als Startgang gewählt wurde, kann die Automatik trotzdem einen kleineren Gang wählen. Mit dem beiden Einstellungen schränkt man den Bereich erlaubter Gänge ein.

Viele Grüße

**Comment by Michael170978** [comment]
Vario ist auch stufenlos oder sprichst du gerade vom IVT Getriebe? Dann schau ich mal bei dem Fendt nach wie er sich so bei bestimmten Einstellungen verhält. Obwohl stufenloses Getriebe ist das was am wenigsten Probleme macht. Mir machen eigentlich die LKW's zu schaffen. Vor allem wenn sie hinten doppelte Achse haben und voll beladen sind. Dann drehen die Räder durch. Und wehe ein vollgeladener Anhänger noch dran ist. Ich sprech gerade von den A.T.C LkW's.  Wenn du weißt was ich meine. Aber seit dem du an der Kupplung gedreht hast, ist es viel besser geworden.

**Comment by Mogli12** [comment]
Genau, Vario und IVT sind beide stufenlos.
