### ISSUE TITLE
ABS Einbau

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#383]
Sag mal Stefan.

Hast du mal daran gedacht ABS einzubauen? Ich meine du hast in den letzen Updates eine Traktionkontrolle eingebaut aber wie schaut es mit ABS oder mit ESP aus?

Bitte versteh mich nicht falsch. Ich bin voll zufrieden  was du so geschaffen hast.

Die Idee kommt davon, weil ich seit Kurzem mit REA Mod spiele. Und REA Mod und Seasons (Schnee auf der Straße) mit Kombination  Autodrive das ist wie Rally Fahren. Ist immer wieder  schön zu sehen wenn ein Fahrzeug in der Botanik ladet, weil die Räder beim Anbremsen blockieren oder der LKW manchmal zu viel Schwung in der Kurve hatte. Winterräder oder Schneeketten gibt es in dem Spiel nicht, deshalb wende ich mich an dich

**Comment by Mogli12** [comment]
Hallo Micha,

vor allem mit dem großen Pickup schleuder ich schon auf trockener Straße hin und her. Eventuell sollte REA den lateralen Grip auf Asphalt erhöhen.

Leider habe ich den Eindruck, dass die Engine kaum auf Bremseingriffe reagiert. Die Anti-Schlupf-Regelung funktioniert daher nach meiner Ansicht fast gar nicht. Daher glaube ich nicht so richtig an ein ESP.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo Micha,

ich schließe das Issue mal.

Viele Grüße
