### ISSUE TITLE
Fahrzeuge mit doppelten Hinterachse habe Vorderradantrieb  

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#386]
HI Stefan

Mit ist aufgefallen, daß Fahrzeuge z.B. Lkw mit doppelten Hinterachse  (Allrad aus) Antrieb auf der Vorderradachse haben.

Macht dir was aus beim nächsten Update zu fixen?

Sieht halt komisch aus wenn sich Lkw festgefahren hat und die vorderen Räder durchdrehen.
Bei allen anderen Fahrzeugen ist das Problem nicht.

**Comment by Mogli12** [comment]
Hallo Micha,

um welches Fahrzeug handelt es sich denn überhaupt. Außerdem kannst Du die Differentiale selber vertauschen, dazu gibt es bereits extra eine Einstellung.

Viele Grüße

**Comment by Michael170978** [comment]
Hi Stefan.

Ich handelt sich um dieses Fahrzeug

![fsScreen_2020_06_02_12_14_51](https://user-images.githubusercontent.com/53015927/83508822-c396a400-a4ca-11ea-8fb6-aba6cf4619c5.png)

Die Differentiale ist richtig eingestellt

Ich würde dich nie auf den Arm nehmen Stefan, deshalb überzeugt dich selbst:

https://youtu.be/hpU6Bc1jQ58

Weißt du was. Ich hab jetzt alle meine Fahrzeuge überprüft und bist jetzt ist das Problem nur bei dem einen aufgefallen. Ich könnte aber schwöre, dass noch gestern in der Nacht alle das Problem hatten.

Jetzt liegt es an dir ob man das fixen kann. Ist nichts schlimmes. Es ist halt nur ein Kosmetikfehler

**Comment by Mogli12** [comment]
![image](https://user-images.githubusercontent.com/8790374/83515599-ee3a2a00-a4d5-11ea-9f16-96ddaad0840c.png)

**Comment by Michael170978** [comment]
Ist aus bei allen Fahrzeugen

**Comment by Mogli12** [comment]
Falls die Achsen und Differentiale im Mod falsch definiert sind, dann kannst Du sie damit vertauschen.

**Comment by Michael170978** [comment]
Ich kann damit leben. 

Ich dachte ich informiere dich. Ist mir beim Rückwärts fahren aufgefallen, dass die vorderen Räder durchdrehen.
