### ISSUE TITLE
Beschleunigung mit IVT/Vario

### ISSUE THREAD

**Issue by Jan238** [Mogli12/VehicleControlAddon#388]
Hallo,

für meinen Geschmack ist die Beschleunigung mit einem stufenlosen Getriebe zu langsam, wenn ich das mit der realen Beschleunigung vergleiche (John Deere 7x30 und 6R). Ich Spiele mit der aktuellen Version (167) und REA Mod.
Natürlich ist es so feinfühliger wenn man mit Tastatur fährt, aber mich stört es bei normalen Straßenfahrten dann doch. 
Wäre es möglich hier was zu ändern oder vielleicht sogar eine Einstellung für die Beschleunigung/Aggressivität zu ermöglichen.

Vielen Dank schonmal

Gruß
Jan

**Comment by cabmac** [comment]
Hallo,

kann ich bestätigen.. seit ein paar Versionen hat man das Gefühl, das das Fzg (leer) garnicht so richtig in die Poette kommt.

**Comment by Mogli12** [comment]
Auch im Vanilla Spiel ist die Beschleunigung im Grunde auf 2 m/s^2 begrenzt. Das sind also 5 Sekunden von 0 auf 36 km/h oder 7,5 Sekunden von 0 auf 54 km/h. 

Da es bei der Begrenzung der Beschleunigung mit REA Probleme gab, setzt VCA jetzt für jeden Frame ein passend berechnetes Speed-Limit. das klappt so gut, dass der Traktor halt nicht schneller als 2 m/s^2 beschleunigt. Und das Ganze passiert dann auch noch mit schön niedriger Drehzahl.

**Comment by Mogli12** [comment]
Jetzt habe ich doch noch etwas gefunden. Anscheinend glättet die Engine das Geschwindigkeitslimit über zwei oder mehrere Frames. Daher kamen einige Traktoren nur auf 1 m/s^2 Beschleunigung.

**Comment by Shreklich** [comment]
Ich hatte das selbe empfinden mit der Beschleunigung werde die neue Version heute Abend mal antesten. 

Vielen lieben Dank aber schon mal für deine stetigen Updates. Das Skript ist einfach nur der Hammer und für mich definitiv ein "must have mod"

**Comment by Jan238** [comment]
Hab grade mal ein bisschen getestet, sieht jetzt gut aus. 
Danke für das schnelle Update und den gesamten Mod, ohne wäre ich wahrscheinlich noch beim LS 17 mit Gearbox Addon.

**Comment by tomy852** [comment]
Ich finde das IVT in der neuesten Version 168 ist tatsächlich noch besser geworden im vergleich zu den letzten Versionen. Da war es schon ein kleines bisschen zu Träge. 
Tausend Dank an Mogli12 für deine fantastische Arbeit!
