### ISSUE TITLE
Wheel slip vs REA slip

### ISSUE THREAD

**Issue by Michael170978** [Mogli12/VehicleControlAddon#389]
HI Stefan

Könntest du bitte erklären wo der Unterschied ist zwischen deinem Wheel slip und REA slip ist?

Wenn ich richtig verstehe beides simuliert wenn ein Rad durchdreht. Oder nicht?

Bei Wheel slip merkt man beim Spielen, dass die Prozent Zahl in der Regel höher ist als bei REA. Berechnet Wheel Slip etwa den Schlupf anders?

Viele Grüße Micha

**Comment by Mogli12** [comment]
Hallo Micha,

Das durchdrehende Rad kommt von der Enging. REA verringert die Haftung, so dass es überhaupt durchdreht. Was die REA Anzeige zum Schlupf zu bedeuten hat, kann ich nicht sagen.

VCA vergleicht die eigentliche Geschwindigkeit des Fahrzeugs mit der Geschwindigkeit am Getriebeausgang. Es wird angezeigt, um wie viel Prozent die Geschwindigkeit am Getriebeausgang größer ist. Dieser Wert ist intern wichtig, da das Geschwindigkeitslimit sich auf die eigentliche Geschwindigkeit des Fahrzeugs bezieht und damit um Schlupf erhöht werden muss.

Viele Grüße, Stefan

**Comment by Michael170978** [comment]
Ich sehe so, dass VCA langsam zum Konkurrenten für REA wird. Man müsste einen Vergleich starten und einen Schlepper zum Pflügen schicken und schauen wie er sich mit REA und ohne verhält.

Wenn ich keinen Unterschied merke, dann kann ich auf REA verzichten. Denn im Winter mit REA sind die Fahrzeuge unfahrbar. Es sei den ein Modder bringt Winterreifen bzw. Schneeketten raus.

**Comment by cabmac** [comment]
VCA hat keine Konkurrenz....;)

**Comment by Mogli12** [comment]
@Michael170978: Nein, VCA ergänst REA. Das Durchdrehen der Räder kommt alleine von REA. Es gibt in VCA nur eine eigene Anzeige für Schlupf, weil mir die Werte von REA nicht ganz plausible sind. Hier geht es aber nur um das Messen des Schlupfs, der grundsätzlich durch REA erzeugt wird.

Aber REA macht da nichts anderes als die Haftung der Reifen je nach Untergrund zu reduzieren,

**Comment by Mogli12** [comment]
Ich habe Wheel Slip erstmal wieder aus dem HUD genommen.
