### ISSUE TITLE
VCA+RMT Wheel Slip und hud

### ISSUE THREAD

**Issue by NiklasWGC** [Mogli12/VehicleControlAddon#390]
Ich habe das Problem,dass ich keinen Wheelslip habe,also konstant 0%.Außerdem wollte ich fragen,ob man dieses wheelslip HUD komplett ausblenden kann?

LG Niklas

**Comment by Mogli12** [comment]
Das HUD ist weg, wenn Du den VCA Allrad nicht verwendest.

**Comment by NiklasWGC** [comment]
Ich möchte den aber verwenden.Mich wundert es halt,dass ich gar keinen Schlupf habe.Ich will lieber den VCA Allrad statt den von EV.Der Schlupf auf 0% ist halt komisch.Nutze RMT,hat das was damit zu tun?Außerdem nutze ich REA

**Comment by cabmac** [comment]
hi, kann eigentlich nicht sein, bei mir mit vollem Guellefass Wiese Rauf und ohne Allrad gets schonmal auf 30%

**Comment by Mogli12** [comment]
Doch kann sein, wenn REA nicht aktiv ist.

**Comment by cabmac** [comment]
klar...aber er sagt ja er nutzt REA....deswegen meinte ich....

**Comment by NiklasWGC** [comment]
Ich glaube mogli meint dich,dass du keein rea aktiv hast.Ist das denn normal das der Reifenschlupf dann von REA übernommen wird?
