### ISSUE TITLE
MP - Tempomatstufen wechseln nicht, Begrenzer arbeitet nicht

### ISSUE THREAD

**Issue by Mantikor83** [Mogli12/VehicleControlAddon#391]
Hallo Mogli, 
ich habe im Multiplayer folgendes Phänomen beobachtet, im SP läuft alles normal.

Wechsel ich die Tempomatstufen (1-3) verweigert VCA die Annahme der neuen Tempomatstufe und fährt unbeirrt mit dem Tempo der Tempomatstufe weiter, mit der ich den Tempomaten angeworfen habe. Auch wenn ich mit einem Tempomaten fahre, dann diesen beende, eine andere Tempomatstufe wähle und diese aktiviere bleibt VCA bei der zuletzt aktivierten Tempomatstufe. Erst wenn ich die Geschwindigkeit einer Tempomatstufe ändere, +/-1 km/h reicht da, wird diese Tempomatstufe als neue aktuelle Tempomatstufe von VCA erkannt und beim einschalten des Tempomaten gefahren, unabhängig davon ob diese auch tatsächlich ausgewählt wurde.

Damit vermutlich in Verbindung steht, dass der Begrenzer (KeyBinding "Langsamer") im MP nicht funktioniert. Das GUI zeigt zwar die korrekte Reduzierung des Tempomaten an, es hat aber keinen Effekt auf VCA und die tatsächlich gefahrene Geschwindigkeit.

Im SP mit exakt den gleichen Mods/Maps etc. pp. tritt das Problem nicht auf. 

Vielleicht findest du ja die Ursache.

Danke und Grüße,

Manti

**Comment by Mantikor83** [comment]
Nachtrag: Seit der Version 172 funktioniert im MP bei mir "Geschwindigkeit permanent halten" auch nicht mehr. Der Schlepper stottert nervig rum, nimmt aber keine Fahrt auf. Geschwindigkeit vom Tempomat wird nicht mehr übernommen und der Schlepper stopt dann einfach, obwohl Geschw. halten eingeblendet ist im HUD.

**Comment by Mogli12** [comment]
Probiert bitte mal Version 177.

**Comment by Mantikor83** [comment]
KeepSpeed funktioniert wieder.

Die drei Tempomatstufen und der Gasbegrenzer funktionieren weiterhin nicht.

Bin heute etwas knapp an Zeit. Ich teste Morgen nochmal aufm Server nur mit VCA und schicke dann auch ggf. das Log

Danke bis hier hin erstmal! Super Arbeit!

**Comment by Mantikor83** [comment]
Guten Morgen,
hatte nun Gelegenheit die neue Version auf dem Server zu testen. Es war nur VCA aktiv, leider besteht der Fehler mit den 3 Tempomatstufen weiterhin wie oben beschrieben und auch das inching funktioniert weiterhin nicht. KeepSpeed geht wieder wie schon geschrieben.

Hier die Logs:
Client: https://www.dropbox.com/s/4thyi671ifiw4ef/Client_log.txt?dl=0
Server: https://www.dropbox.com/s/mdrydl87kef82kq/Server_Log.txt?dl=0

Vielleicht hilft das ja. Falls ich sonst noch irgendwie was testen kann, spann mich gerne ein, ich helfe gerne!

Grüße,

Manti

**Comment by Mogli12** [comment]
Hilft Version 178 weiter? Ich verstehe nicht, warum es im MP scheitert.

**Comment by Mantikor83** [comment]
Ich teste heute Abend! Kann ich dir mit DevTools oder ähnlichem eine bessere Fehlerbildbeschreibung zukommen lassen? Ich hab den Vorteil, dass ich auch Server-Owner bin, wir können auf der Kiste quasi alles machen. :D

**Comment by Mantikor83** [comment]
So, hatte Zeit zu testen, leider ist keine Veränderung feststellbar.

Hilft es, wenn du eine Debug Version baust, die in die Log die einzelnen Variablen bzw. if Bedingungen schreibt und ich das mal auf dem Server laufen lasse? Vielleicht kommst du der Sache so auf die Spur?

Grüße

**Comment by Mogli12** [comment]
Ok, ich habe jetzt direkt die Events aus [Drivable:onUpdate](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=70&class=10489#onUpdate165938) in Version 179 übernommen. Einen Versuch ist es wert...

**Comment by Mantikor83** [comment]
Habe es jetzt nur schnell im MP getestet, aber da läuft es jetzt! Spitze! Dank dir! Mega! =)

**Comment by Mantikor83** [comment]
Gestern Abend habe ich nochmal 2 Stunden getestet, mir sind nun keine Fehler mehr aufgefallen. Vario/IVT und 2x6 Getriebe wurden intensiv, alle anderen Getriebe kurz getestet. Scheint soweit geklappt zu haben. Inching läuft, Tempomaten laufen auch wie sie sollen.
