### ISSUE TITLE
Own Config Getriebe

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#393]
Wäre es möglich noch eine Reverser Gruppe zu erstellen? In dem man eine Rückwärtsgruppe auswählt/aktiviert und dann die Anzahl der Rückwärtsgänge bestimmen kann so wie die Gruppen und Gänge für die Vorwärtsfahrt?

Grüße Chris

**Comment by Mogli12** [comment]
Hi Chris,

kennst Du diese Einstellung schon?
![image](https://user-images.githubusercontent.com/8790374/84648116-c8187f00-af04-11ea-86c5-3001085fcfcc.png)

Viele Grüße,
Stefan

**Comment by ChrisJD8400R** [comment]
Hi, ja diese Einstellung kenne ich bereits. Leider legt man damit nur einen Gang fest für die Rückwärtsfahrt und den Gruppe. 🙂 Ich hätte vllt gedacht das man eine Rückwärtsgruppe erstellt wie du eben gezeigt hast und dann noch zusätzlich die Anzahl der Gänge in dieser Gruppe einstellen kann.
 Sodas man sagen kann, Ich habe ein Powershift Getriebe mit "einer Vorwärtsgruppe mit 16 Gängen und einer Rückwärtsgruppe mit 5 Rückwärtsgängen" 🙂
Oder ganz einfach gesagt, dass die Anzahl der Rückwärtsgängen beliebig bestimmt werden kann und dieses nicht pro Gruppe auf einen Gang festgelegt ist
LG Chris 🙂

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Juni 15, 2020 at 12:36 schrieb Stefan Biedenstein<notifications@github.com>:   


Hi Chris,

kennst Du diese Einstellung schon?


Viele Grüße,
Stefan

**Comment by ChrisJD8400R** [comment]
Hast du schon eine Lösung dafür gefunden? LG Chris :)

**Comment by Mogli12** [comment]
Hi Chris,
leider habe ich dafür noch keine Lösung. Das Problem ist die Automatik-Funktion und die Wendeschaltung. Die aktuelle Lösung "überlagert" nur den aktuellen Gang, ohne ihn wirklich zu ändern.
Viele Grüße
