### ISSUE TITLE
Durchdrehende Räder trotz Diff-Sperre und Allrad

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/VehicleControlAddon#394]
Hallo, 
mit dem neuen Kverneland Pflug habe ich nun seit langem mal wieder klassisch gepflügt. Dabei ist mir aufgefallen, dass mir die Räder permanent durchdrehen, trotz aktiviertem Allrad und gesperrten Differentialen (im Menü ist die Traktionskontrolle ebenfalls aktiviert. Bemerkt habe ich dies durch das Pflügen, wenn die eine Seite des Traktors durch bereits gepflügtes fährt.
Hier handelt es sich um ein Spielstand im lokalen MP, ich bin der Host.

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4804373/log.txt)

![fsScreen_2020_06_19_13_31_50](https://user-images.githubusercontent.com/35241745/85128558-d7176e00-b231-11ea-8cda-ce98bed229e3.png)
![fsScreen_2020_06_19_13_31_48](https://user-images.githubusercontent.com/35241745/85128577-df6fa900-b231-11ea-8b87-125dd177ad92.png)

**Comment by Mogli12** [comment]
Hallo,

VCA ändert nur die Differentiale, nicht die Griffigkeit der Reifen. Ich sehe nicht, wie VCA da helfen kann.

Viele Grüße

**Comment by cabmac** [comment]
Moin, eine Differenzialsperre verhindert ja nicht das Durchdrehen der Räder....

**Comment by Evilman2517** [comment]
Aber das Durchdrehen eines einzelnen Rades? Hatte mich im ersten Post etwas unglücklich ausgedrückt, nur die Räder auf der geplflügten Seite drehen durch, die anderen nicht

**Comment by Mogli12** [comment]
Ich kann nur das Drehmoment auf die andere Seite verschieben. Ich habe versucht, die Geschwindigkeitsdifferenz zu begrenzen (maxSpeedRatio) aber dann verhält sich die Engine ganz seltsam.
Was passiert eigentlich, wenn du den Allradantrieb komplett auf aus stellst?

**Comment by Mogli12** [comment]
Hast Du ein größeres Frontgewicht und Voreilung des Allradantriebs ausprobiert?

**Comment by Evilman2517** [comment]
Ich werde das gerne testen und melde mich dann nochmal

**Comment by Mogli12** [comment]
Oh, bei der Drehmomentverteilung ist tatsächlich noch ein Fehler drin. Korrektur ist bereits in Arbeit.

**Comment by Mogli12** [comment]
So probiert alle mal Version 173

**Comment by cabmac** [comment]
Hallo, das scheint noch nicht zu laufen, schalte ich Allrad ein ist alles ok, schalte ich die Sperre der Hinterachse ein, laeuft in meinem Beispiel das linke Rad viel schneller als das rechte...die Raeder der  Hinterachse laufen also quasi syncron nur mit Allrad und ohne Differenzialsperre ...Vorderachse scheint ok zu sein...

https://workupload.com/file/uJ5qKkazPdS

**Comment by Mogli12** [comment]
Ich habe es nochmal mit dem MF 7700 in Felsbrunn überprüft. Nur mit Allrad und Differentialsperren kann ich den Berg in Richtung Burg steil hoch fahren.

@cabmac Hast Du den aktuellen Patch instelliert?

**Comment by cabmac** [comment]
Moin, ja habe ich...

**Comment by Evilman2517** [comment]
Der gestrige Fix hat mein Problem gelöst. Kann nun auch den Hügel hoch pflügen, hier und da drehen die Räder mal durch, aber das ist völlig ok. Vielen Dank für den Fix und den tollen Support

**Comment by cabmac** [comment]
hi, dann. wird das wohl gefixt sein, ich habe es auf dem Acker noch nicht probiert, kam mir nur komisch vor in meinem Vid.

Schoene Gruesse

**Comment by Mogli12** [comment]
Wenn ich in VCA die Werte zu extrem machen, dann geht irgendwann die Geschwindigkeit durch die Decke und das Fahrzeug schießt wie eine Kanonenkugel über die Karte. Das konnte ich bei maxSpeedRatio = 100 jetzt aber noch nicht beobachten. Probiert mal Version 174.

**Comment by cabmac** [comment]
also fuer mich laeuft das nun alles perfekt..klasse mal wieder!

**Comment by Mogli12** [comment]
Ich denke, dass kann geschlossen werden, oder?
