### ISSUE TITLE
Tempomat dreht nur noch auf max RPM

### ISSUE THREAD

**Issue by Mantikor83** [Mogli12/VehicleControlAddon#395]
Hallo Mogli,
leider noch ein neuer, seit einem der letzten Updates dreht der Cruisecontrol in allen Lebenslagen nur noch auf vollen RPM, selbst wenn keine Last anliegt und/oder die max Geschwindigkeit erreicht wurde.

Tritt bei mir im SP und MP auf. Irgendwas scheint da beim Tempomaten kaputt gegangen zu sein.

Habe beide Bugs mittlerweile auch auf dem Vanilla LS verifiziert, kommt scheinbar nicht aus einem Mod-Konflikt.

Grüße

**Comment by Mogli12** [comment]
Hallo,

Traktor? Karte? Gerät? Screenshot? log.txt?

Viele Grüße

**Comment by Mantikor83** [comment]
Hallo Mogli,
Modus: SP/MP
Karte: Felsbrunn
Traktor: jeder
Gerät: jedes
Screenshots: 
Mit Gaspedal (G29) konstante niedrige RPM nach erreichen der 30km/h https://www.dropbox.com/s/0zldmite511oud9/fsScreen_2020_06_21_14_50_37.png?dl=0

Mit Tempomat bei erreichter Geschwindigkeit, RPM fallen nicht ab bleiben in etwa bei 1800-2000 RPM
https://www.dropbox.com/s/0zldmite511oud9/fsScreen_2020_06_21_14_50_37.png?dl=0

Log: https://www.dropbox.com/s/nl1ze7fbm9zfds9/log.txt?dl=0

Ich hoffe das hilft dir ;)

**Comment by Mantikor83** [comment]
Asche auf mein Haupt, ich hätte es Vanilla testen sollen, scheint ein LS Bug zu sein, auch im Vanilla ist die RPM beim Tempomat jetzt hoch, beim VCA fällt es nur auf, weil sie angezeigt werden. Entschuldige bitte. 

Fazit, Vanilla LS Tempomat dreht jetzt scheinbar unabhängig von der Last auf 70-80% der RPM, egal wie viel Last anliegt. VCA übernimmt das scheinbar nur. =/

**Comment by Mogli12** [comment]
Hallo,

das hilft schon mal. Du hast einen John Deere 7R mit Vario Getriebe konfiguriert. Ich probier das selber mal aus.

Viele Grüße,
Stefan

**Comment by Mantikor83** [comment]
Is halt bei allen Getrieben so. Das Vario is bei mir Global-Default, deswegen war es gesetzt als ich schnell die Screens gemacht habe. IVT etc. sind aber genau so betroffen. Ist im reinen Vanilla Spiel aber eben auch so.

**Comment by Mogli12** [comment]
In der aktuellen Version sinkt die Drehzahl wieder.
