### ISSUE TITLE
Text verschoben - GPS funktioniert nicht

### ISSUE THREAD

**Issue by Amadeo01** [Mogli12/VehicleControlAddon#396]
Moin Stefan.
1. Ich habe heute festgestellt, dass sich die Erläuterungstexte weit nach oben aus die umrandeten Felder verschoben haben. Sie sind zum Teil nicht lesbar. - Vielleicht tritt der Fehler auch nur bei mir auf?

2. Leider kann ich den integrierte GPS in der neuesten Version nicht aktivieren. Es werden weder die Fahrrichtungslinien angezeigt noch ist das akustische Signal zu hören.  :((

Kannst Du mir eine Hilfestellung geben? - Merci.

**Comment by Mogli12** [comment]
Hallo,

zu 1.: [https://forum.giants-software.com/viewtopic.php?f=958&t=168584](https://forum.giants-software.com/viewtopic.php?f=958&t=168584)
 
zu 2: Hast Du in den VCA Einstellungen eine Breite eingestellt?

Viele Grüße

**Comment by Amadeo01** [comment]
Hey Stefan,
heute noch einmal "probiert", leider wieder OHNE Ergebnis!
Dabei hatte ich folgende Einstellungen gemacht; siehe bitte den Anhang.
![Agrostar mit Imants 38SX_3m](https://user-images.githubusercontent.com/29040448/85302049-f2d87980-b4a8-11ea-89bb-6954f5d06416.jpg)
![VCA_Raster-Einstellung](https://user-images.githubusercontent.com/29040448/85302085-ff5cd200-b4a8-11ea-9df1-49b90809e04f.jpg)

**Comment by Mogli12** [comment]
2. hört sich nach einem Problem mit inputBinding.xml an.

**Comment by Mogli12** [comment]
Hi,

Problem 2 habe ich jetzt verstanden; siehe #400. Beim Sprung fällt offensichtlich die Raddrehzahl ab. Das ist mit Version 178 behoben.

Viele Grüße
