### ISSUE TITLE
VCA schaltet sich nach dem Drücken des Gaspedals aus

### ISSUE THREAD

**Issue by leo32128** [Mogli12/VehicleControlAddon#397]
VCA wird nach Drücken des Gaspedals deaktiviert. Ich habe ein kurzes Video gemacht, um das Problem zu zeigen. Dies geschah nach Build 175, Mir wurde auch klar, dass dies nur im IVT-Modus geschieht [https://drive.google.com/file/d/1x4ttnwHHOzGopXZ-V5ITJvF_NLGAdzQ4/view?usp=sharing](url)

**Comment by Mantikor83** [comment]
Kann den Bug bestätigen, habe das gleiche.

**Comment by Mogli12** [comment]
Bitte die log.txt anhängen.

**Comment by Mantikor83** [comment]
2020-06-22 11:48 Error in updateWheelsPhysics :C:/Users/Henning/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:5843: attempt to compare number with nil
2020-06-22 11:48 Error in updateWheelsPhysics :C:/Users/Henning/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:5843: attempt to compare number with nil

Das sind die Zeilen die du vermutlich suchst, jedes mal wenn man anfährt wirft er den Fehler und setzt alles auf Null zurück.

Ganze log kann ich erst nachher posten

**Comment by Mogli12** [comment]
Ja, die Zeilen habe ich gesucht. In VCA wird dann so ein Fehler abgefangen und das Getriebe abgeschaltet (Notlauf).

**Comment by Mantikor83** [comment]
Das nenne ich mal vorbildliche Software-Entwicklung!

**Comment by NiklasWGC** [comment]
Ich habe das Problem auch,gibt es dafür mittlererweile eine Lösung?

**Comment by leo32128** [comment]
Problem gelöst, danke für Ihre hervorragende Arbeit
