### ISSUE TITLE
Vario Getriebe über Gangschaltung

### ISSUE THREAD

**Issue by NiklasWGC** [Mogli12/VehicleControlAddon#399]
Hallo Mogli,ich habe eine Frage,wie kann ich es einstellen,dass ich das Vario Getriebe,also high und low über die gangschaltung steuern kann?Ich habe das G29 mit Gangschaltung

**Comment by Mogli12** [comment]
Hallo,

Zum Vario Getriebe sollte am besten der G27 Modus "D/R , G+/-, R+/-" passen. 

Viele Grüße

**Comment by NiklasWGC** [comment]
ok und welche Tasten muss ich dafür genau belegen?

**Comment by Mogli12** [comment]
1. Gang: D (vorwärts)
2. Gang R (rückwärts)
5. Gang R+ => high
6. Gang R- => low

**Comment by NiklasWGC** [comment]
Ah ok Danke,funktioniert.Habe jetzt noch eine Frage,ist das normal das der Traktor bei einem etwas stärkeren Huckel abbremst?

**Comment by Mogli12** [comment]
Zum Abbremsen kann ich nichts sagen.

**Comment by NiklasWGC** [comment]
ok Trotzdem Danke
