### ISSUE TITLE
Vollebremsung wenn mal beim Schaltgetriebe bergab fährt

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#400]
Hi Stefan, Wir haben festgestellt das wenn man ein Schaltgetriebe auswählt und mit z.B
 40km/h über eine Kuppe bergab fährt das Fahrzeug teilweise eine Vollbremsung hinlegt. Falls du dazu ein Video sehen willst sind wir bereit Dir eins zukommen zu lassen.

LG Chris vom AG-OVP-Team

**Comment by Mogli12** [comment]
Hi Chris,

beim Sprung fällt offensichtlich die Raddrehzahl ab. Das ist mit Version 178 behoben.

Viele Grüße
