### ISSUE TITLE
noch einmal Differenziale

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#401]
Hallo, ich habe seit ein paar Tagen ein seltsames Problem. Ich schalte die Differenzialsperren dazu, um mich irgendwo freizumachen (auf dem Feld oder auf dem Silo), bei dem jeweiligen Zug geht die Maschine auf einmal aus (ploetzlich ist der Tank leer, der vorher voll war) und das Fahrzeug schiesst ueber die map...

hierbei nur ums mal auszuprobieren, Silo rauf, Differenziale ein, Tank schlagartig leer und Traktor aus:
![fsScreen_2020_06_24_17_15_00](https://user-images.githubusercontent.com/16596142/85586840-8c3a9380-b641-11ea-820d-60f6d014f633.png)

Hier ist dasselbe passiert, der MF war auf demselben Silo...Tank leer, Traktor aus und ist in die Weide geschossen..
![fsScreen_2020_06_24_17_29_25](https://user-images.githubusercontent.com/16596142/85587220-de7bb480-b641-11ea-9bd3-7db74b513485.png)

Das ganze habe ich noch mit einem Radlader gemacht, ebenfalls ueber die map geschossen.
Dieselbe Sache auf mit diesem MF auf dem Feld, festgefahren, Differenziale rein, Gasgegeben und nach 5 SEkunden wie gehabt, Trecker aus, da Tank ploetzlich leer und ueber die map geschossen...leider habe ich da keine Screenshot von..
![fsScreen_2020_06_22_09_53_06](https://user-images.githubusercontent.com/16596142/85587530-26024080-b642-11ea-802f-b13041a0386d.png)

Solange da keine Grosse Kraft wirkt, gehts, sobald er wirklich arbeiten muss, passiert das oben geschilderte.

**Comment by Mogli12** [comment]
Hallo,

genau dieses Problem habe ich doch in einem der letzten Issues bereits erwähnt. Am Ende ist dies ein Bug in der Giants Engine. Wenn ich die Werte (Drehmomentverteilung, Geschwindigkeitsfaktor) weniger aggressiv mache, dann beschwert sich die Community, dass die Räder nicht gleich schnell drehen.

Ich schlage vor, du versuchst Giants den Bug mal zu erklären. Ich habe aber wenig Hoffnung, dass das was bringt.

Viele Grüße,

**Comment by Mogli12** [comment]
Siehe #394:

> Wenn ich in VCA die Werte zu extrem machen, dann geht irgendwann die Geschwindigkeit durch die Decke und das Fahrzeug schießt wie eine Kanonenkugel über die Karte. Das konnte ich bei maxSpeedRatio = 100 jetzt aber noch nicht beobachten. Probiert mal Version 174.

**Comment by cabmac** [comment]
Hi, ich weiss,du hattest es erwaehnt,  ich konnte den Issue von vor ein paar Tagen halt nunmal nicht mehr aufmachen. Da ist mir halt vorher noch nicht aufgefallen. DAs ist mir mit dem MF auf dem Acker mit dem Guellefass nur einmal passiert , aber jetzt auf dem Silo mit diversen Fahrzeugen mehrmals reproduziert.. Giants macht da mit 100%iger Sicherheit nichts mehr dran.

**Comment by cabmac** [comment]
Dann muss ich fuer mich persoenlich sagen, wuerde ich bevorzugen, da einen Kompromiss zu suchen, also weniger aggressiv,auch wenn die Raeder nicht hunderprozentig gleich schnell drehen....oder wie siehst du das?

**Comment by Evilman2517** [comment]
@cabmac spielst du zufällig mit REA? Frage, weil ich den Fehler bislang nicht feststellen konnte

**Comment by cabmac** [comment]
Moin..leider immer noch:

https://workupload.com/file/uD9Zqq8hz3R

Evilman..das hat mit REA nichts zu tun..:)

**Comment by Mogli12** [comment]
Hallo,

das Drehmoment wird jetzt nur noch zwischen 25% und 75% verteilt. Ohne Allrad ist es fest 50%. Noch weniger geht also nicht. 

Viele Grüße

**Comment by Mogli12** [comment]
Ok, in Version 180 habe ich noch einmal an den Parametern und auch an Notlauf bei wenig plausiblen Geschwindigkeiten gearbeitet.

**Comment by cabmac** [comment]
Hi, gestern war github down (jedenfalls bei mir), ich habe gestern eine halbe Stunde probiert und alles ok bis jetzt....
