### ISSUE TITLE
Starke Bremsung nach öffnen eines Menüs

### ISSUE THREAD

**Issue by NiklasWGC** [Mogli12/VehicleControlAddon#402]
Sobald man ein Menü öffnet,egal ob VCA Menü oder das ESC Menü,danach bremst das Fahrzeug immer stark wenn man das gaspedal los lässt.Nach einem Motorneustart geht es wieder,wenn man aber wieder menü öffnet,muss man wieder den motor neustarten damit man normale bremsen hat.

**Comment by Mogli12** [comment]
Entweder schaltet man den Tempomaten an oder man bremst vorm Öffnen des Menüs ab.

**Comment by NiklasWGC** [comment]
Ok Danke,noch ne andere Frage,kann man das Handgas so belegen,dass man eine ganze Achse als Handgas nutzen kann.Ich habe nämlich ein schubhebel für einen flight stick und würde da gerne handgas drauf legen das funktioniert aber nicht ganz so wie es soll.

**Comment by NiklasWGC** [comment]
Ok Danke

**Comment by Mogli12** [comment]
Es ist aktuelle gewollt, dass das Öffnen des Menüs die Handbremse aktiviert. Ansonsten würde das Fahrzeug unkontrolliert weiter rollen. Auch die entsprechenden Funktionen zur Motor- und Getriebesteuerung werden während des Dialog sichtbar ist gar nicht aufgerufen.
