### ISSUE TITLE
Handgas

### ISSUE THREAD

**Issue by NiklasWGC** [Mogli12/VehicleControlAddon#403]
Kann man das Handgas so belegen,dass man eine ganze Achse als Handgas nutzen kann.Ich habe nämlich ein schubhebel für einen flight stick und würde da gerne handgas drauf legen das funktioniert aber nicht ganz so wie es soll.Hier geht es nur bis zur einer bestimmten drehzahl und dann gibt es nur noch eine stufe auf volle pulle mit großem abstand.Ist es in echt nicht auch so dass man die komplett steuern kann?Korrigiere mich bitte wenn ich mich irre.LG Niklas

PS:Echt coole Arbeit,ich ziehe meinen Hut vor dir

**Comment by Mogli12** [comment]
Hallo,

probiere mal Version 181 und bewege einmal pro Fahrzeug den Schubhebel von Anschlag zu Anschlag. Wenn Du danach das Spiel speicherst, dann sollte VCA sich merken, dass das eine komplette Achse ist.

Viele Grüße

**Comment by NiklasWGC** [comment]
Ok ich werde es mal probieren.Danke dür den Tipp.

**Comment by NiklasWGC** [comment]
Es ist immernoch so,dass das vca das handgas stockend erkennt.Es war schon immer auf der ganzen achse,ich habe keine deadzone,aber trotzdem lässt er zwischendurch einen freiraum,das ist echt komisch.
Bsp.1000rpm-1500rpm mit feingefühl mögliche einstellung,danach sprung auf 1800rpm bis max rpm

**Comment by Mogli12** [comment]
Den Wert für die Achse bekomme ich von der Game Engine und übersetze ihn 1:1 in den Wert für Handgas. Daher kann ich nicht sagen, warum es bei Dir nicht linear ist.
