### ISSUE TITLE
Vario Getriebe 

### ISSUE THREAD

**Issue by Black4Hawk76** [Mogli12/VehicleControlAddon#404]
Erst mal vielen Dank für deinen tollen Mod!
Ausgangslage ist ein neuer Spielstand und der VCA als einziger Mod im Ordner, ich hab sogar die inputbindings gelöscht.🤭 Wenn ich jetzt in der Getriebeart die Low und High Gruppenschaltung mit Ä und Ü schalten möchte, geht es leider nicht. Habt ihr eine Idee?
Vielen Dank vor ab. ✌️

**Comment by Shreklich** [comment]
Hi 
Versuche mal ob es über den Splitter zu schalten geht also zwischen high und low.

**Comment by Mogli12** [comment]
Verwendest Du Courseplay?

**Comment by Black4Hawk76** [comment]
@Shreklich  Hi, ich versuche und berichte.
@Mogli12 Nein, ich hab nur VCA im Modordner.
Ursprünglich spiele ich mit einen Spielstand auf der Holzer in Kombination mit REA und RMT. Da nach dem Patch es nicht mehr funktionierte, hab ich kurzerhand einen neuen Modordner erstellt und nur VCA zum Ausschluss genutzt. 

Grüße

**Comment by Mogli12** [comment]
Ach so, das sind Gruppen, nicht Gänge. Die Gänge sind ja quasi stufenlos.
