### ISSUE TITLE
Kamerabewegung in der Außenansicht

### ISSUE THREAD

**Issue by derDeBen** [Mogli12/VehicleControlAddon#406]
Moinsen, habe folgendes Problem mit VCA Version 9.1.7.2:
Wenn ich ein Gerät/Anhänger an meinen Schlepper ankoppel kann ich wenn ich mal in die Außenansicht wechsel meine Kameraansicht nicht mehr in der Y Achse ändern. 
Auf der X Achse (links - rechts) geht alles nach wie vor.

**Comment by Shreklich** [comment]
Hallo nutzt du vllt zusätzlich die Mod Ai Vehicle Extension? Es kann nämlich schon mal sein wenn man nach dem Einstellen dieses untere Hud nicht wieder schließt und man ein Fahrzeug wechselt, dass dann die Kamera nur eingeschänkt funktioniert.

**Comment by derDeBen** [comment]
Nein, habe es nur mit VCA probiert um eventuell Konflikte mit anderen Mods auszuschließen.
Anbei die Log, neues SG auf der Felsbrunn nur mit VCA, 
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4874179/log.txt)

**Comment by Shreklich** [comment]
Da hat es dir aber ganz schön die Input bindings zerschossen. Also irgend eine Mod ist da im Konflikt. Du müsstest also deinen Modordner leeren und die Input bindings einmal löschen diese wird danach neu erstellt vom Spiel du musst allerdings Tasten neu zuweisen falls du irgendwas geändert hast. Hier ist wichtig das du keine Doppelbelegung erzeugst. Du müsstest dann nach und nach in dem du die mods hinzufügst evtl.im 5er Pack gucken ob dieser Fehler wiederkehrt. Du hast auch zwei Kamera bezogene mods drin vielleicht haben wir hier schon einen Konflikt.

Wenn du natürlich vor kurzem erst eine Mod hinzugefügt hast und dann erst der Fehler entstanden ist, könnte man zuerst mit diesen Mods anfangen. Das Problem ist Einträge in der Input Bindings bleiben bestehen auch wenn du eine Mod entfernst deswegen kann es schon sein das trotz des entfernten Mod es immer noch  nicht funktioniert.

**Comment by derDeBen** [comment]
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/4874780/log.txt)
Anbei die Log mit nur VCA im Ordner, Inputbinding wurde gelöscht.
Wie schon vermutet keine Veränderung der Lage.

**Comment by Shreklich** [comment]
Dies ist äußerst kurios. Du könntest natürlich eine neuere Version des VCA testen aber dieses Problem kenn ich nicht von dieser Mod.

**Comment by Mogli12** [comment]
Sicher, dass VCA die Ursache ist?

**Comment by Mogli12** [comment]
Es gibt in FS19 generell kleine Problem mit Tastatureingaben. Ich denke daher nicht, dass dieses Problem von VCA verursacht wird.

**Comment by derDeBen** [comment]
Ja, wenn ich VCA aus dem Modordner nehme besteht das Problem nicht mehr.
Warum das der Fall ist weiß ich auch nicht. Mir ist es auch erst aufgefallen nach der neueren Version.
