### ISSUE TITLE
Transmission when typing in chat stops tractor. then speeds up after pressing enter to send the chat.

### ISSUE THREAD

**Issue by Harag9** [Mogli12/VehicleControlAddon#407]
I used to use this mod ages ago when it was just Keyboard steer and then became VCA and really the markings, not played the game for ages and just started again, I've updated to the latest version here.

I have an issue with the Working Width of the tools. I seem to recall when I attached a tool it would detect the width of it (6m 24m etc. but it doesn't seem to do this, and my memory is really bad to remember all the correct widths (plow 2.2) offsets etc.

Is this a feature of the mod? am I misremembering it? or is there a key to auto detect? (can't see in options a key).

Thanks.

**Comment by Harag9** [comment]
Hi. Sorry I've found out how to auto detect -- type 0 into the box :)

However I've another issue

I have transmission set to IVF (default) I don't use gears or anything. What I've now noticed is when press T to chat, the tractor comes to a stop but the revs go really high - so when fertilizing it's wasting fert. The version I downloaded from the giant hub doesn't do that (but it's v1 so quite old). I've tried all sorts of settings and nothing seems to work... only works when I set transmission to OFF, but I don't like that setting as when you lift finger off A the tractor comes to a quick stop. :(

**Comment by Mogli12** [comment]
Hi,
just enter 0 as width to recalculate the width.
BR

**Comment by Harag9** [comment]
> Hi,
> just enter 0 as width to recalculate the width.
> BR

Thanks for confirming, that's what I found out -- Any idea bout the transmission problem with the tractor stopping when I press T to chat in a MP game?

**Comment by Mogli12** [comment]
Hi,
The vehicle should not stop if the chatDialog is open. But it should stop for all other dialogs. Please try build 182.
Regards

**Comment by Harag9** [comment]
> Hi,
> The vehicle should not stop if the chatDialog is open. But it should stop for all other dialogs. Please try build 182.
> Regards

Thanks for the change, I've just done a test, and it still does the same thing, no change. :( Let me know if you need any more changes testing, happy to help

**Comment by Harag9** [comment]
> Hi,
> The vehicle should not stop if the chatDialog is open. But it should stop for all other dialogs. Please try build 182.
> Regards

HI - Thanks for the change,  just tried b183 - same issue. :(

**Comment by Mogli12** [comment]
Ok, then it is like it is. Sorry.
