### ISSUE TITLE
Kein direkter Issue, aber eine andere GPS Darstellung wäre nett :)

### ISSUE THREAD

**Issue by DSBeltane** [Mogli12/VehicleControlAddon#408]
Hi Mogli,

wie schon geschrieben - ist kein direkter Issue, aber für Leute die wie ich an einer rot / grün Farbschwäche leiden ist es je nach Getreide leider nicht möglich die Markierung zu sehen. Wenn der Aufwand nicht allzu groß ist, würde ich mich sehr darüber freuen wenn die Marker etwas heraustechender wären. Beispiel wäre hier der Guidance Steering Mod, da kann zumindest ich die Spur trotz Farbschwäche noch sehen.

Viele Grüße,
Beltane

**Comment by Mogli12** [comment]
Hi Beltane,

Problem ist, dass seit FS19 drawDebugLine nicht mehr funktioniert. Ich kann nur irgendwelche Texte dreidimensional in die Gegend zeichnen.

Viele Grüße, Stefan

**Comment by DSBeltane** [comment]
Hallo Stefan,

danke für die Antwort. Wenn es zu aufwendig ist oder einfach nicht passend zu gestalten ist, kein Problem. Ist ja nicht so das man nicht drum herum arbeiten kann - an den Feldrändern sieht man ja die Spuranzeige. Zumal es bei den meisten Getreidesorten ja noch gerade so geht, Raps mal ausgenommen. In jedem Fall ists ein toller Mod der da erstellt wurde und für mich nicht mehr wegzudenken! 

Viele Grüße,
Beltane

**Comment by Mogli12** [comment]
Würde Helligkeit helfen?

**Comment by DSBeltane** [comment]
Könnte sein - bei Raps im Blütestadium ist es wie gesagt am schlimmsten. Da ist für jemandem mit Farbschwäche einfach nicht genug Kontrast da. Hört sich zumindest nach einer praktikablen Idee an ohne das man das Rad neu erfindet. Und Anwender ohne Farbschwäche dürfte es wohl kaum stören wenn das grün etwas heller ist als sonst.

**Comment by Mogli12** [comment]
Anstatt Grün/Rot verwendet VCA nun Blau/rot. Ist das besser?

**Comment by DSBeltane** [comment]
Ja, auf jeden Fall.  Das hilft ungemein, vor allem wenn man den Modus "Hoch wenn inaktiv" dazuschaltet. Selbst meine Mit-Farmer hatten vorher da teilweise ihre Probleme, auch ohne Farbschwäche. Danke dir dafür Stefan, beide Daumen hoch! 👍

**Comment by Mogli12** [comment]
Danke

**Comment by Switty003** [comment]
Moin, ich wollte nochmal mein Kommentar hinzufügen. Für uns Farbenblinde hilft ein grün oder rot leider nicht weiter. Egal welche Farbe, es hebt sich nicht vom Feld bzw Landschaft ab. Ich hab das GPS so gebaut, das es im deaktivierten Modus weiße Linien anzeigt, sobald es aktiviert ist, werden sie blau. Das hilft den Farbenblinden sehr. Vielleicht gibt es ja die Möglichkeit einen Button einzubauen wo man einen Farbenblindmodus einschalten kann. Standard die normalen Farben und für Farbenblinde weiß und blau.
