### ISSUE TITLE
Drescher-Handgas-Getriebe

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#409]
Hallo Stefan,
ich habe mir das 3-Gang Getriebe eines Dreschers konfiguriert. Der tucan hat glaube ich drei Hauptgaenge (wie die alten claas Do 108,218 etcetc, waren damals aber unsynchronisiert, tut aber nichts zur Sache). Ich weiss nicht wie das bei den "neuen"Dreschern laeuft, bei den alten Dominators hatte man einen Gang eingelegt, Handgas auf voll und dann per Hydrostat die Geschwindigkeit (hier simuliert mit ctrl-entf). Die Drezahl verhaelt sich allerdings komisch, wenn ich mit Handgas auf voll gehe und dann losfahren will, siehe Video...

https://workupload.com/file/J2NQjyG9Vnb 

eigentlich sollten doch da keine Drezahlschwankungen sein, oder?

**Comment by Shreklich** [comment]
Das selbe hab ich auch. Ich hab es für mich so gelöst das ich den ersten Gang auf meine Geschwindigkeit gesetzt habe die ich dreschen mag und bin dann mit 100% PTO unterwegs. Ist zwar nicht perfekt aber so sind die Schwankungen weg.

**Comment by cabmac** [comment]
aber beim Anfahren ist die Schwankung dann weg?

**Comment by Shreklich** [comment]
Ich bin mir da leider nicht mehr ganz so sicher ist schon was her das ich nochmal am PC war. Aber ich glaube, dass es besser gewesen ist.

**Comment by NiklasWGC** [comment]
Ich bin mir nicht zu 100% sicher aber ich glaube die neuen drescher haben keine gänge,die laufen alle auf hydrostatik.

**Comment by cabmac** [comment]
der Tucano hat aber den gleichen 3-Ganghebel wie die "alten" dominators...ist aber auch relativ wurscht, den bei dem claas dominators des Mega-Packs z.B. habe ich dasselbe "Problem"

**Comment by cabmac** [comment]
Hallo, bei mir immer noch gleich, also wie vorher...

**Comment by Mogli12** [comment]
Das eigentliche Getiebe ist nicht LUA codiert. VCA gibt dem Getriebe lediglich den Drehzahlbereich und den Übersetzungsbereich vor. Wenn sich das Getriebe dann nicht daran hält, dann kann ich da leider nichts machen.

**Comment by cabmac** [comment]
bei 0.30 hab ich es auf IVT umgestellt, da gehts dann...die Sache ist aber auch nicht allzu tragisch...

**Comment by Mogli12** [comment]
Es gibt halt kein 3-Gang stufenloses Getriebe. Aber das Vario hat 2 Gruppen und ist trotzdem stufenlos.
