### ISSUE TITLE
Schaltlautstärke

### ISSUE THREAD

**Issue by fedor1234567890** [Mogli12/VehicleControlAddon#410]
Die Schaltlautstärke ist nicht anpassbar und sehr laut im vergleich zur Maschine. (nehme auch gerne hilfe entgegen)

**Comment by Mogli12** [comment]
Hallo,
Du kannst das in der aktuellen Version in der config.xml anpassen. Ein Beispiel findest Du [hier](https://github.com/Mogli12/VehicleControlAddon/blob/master/modsSettings/FS19_VehicleControlAddon/config.xml).
Viele Grüße
