### ISSUE TITLE
VehicleControlAddon Farbenblindmodus

### ISSUE THREAD

**Issue by Switty003** [Mogli12/VehicleControlAddon#413]
Hallo, da ich von vielen gehört habe, die Farbenblind sind, hab ich den Mod angepasst. Über die normalen Einstellungen ändert sich die Farbe im Mod nicht, ich hab dies separat angepasst. Wollte dich darüber informieren bzw fragen ob es eine Möglichkeit gibt, dies standardmäßig im Mod zu verbauen. Vielen Dank, würde mich über eine Antwort freuen.

**Comment by Mogli12** [comment]
-> #408
