### ISSUE TITLE
Geschwindigkeit Permanent halten in Kombination mit Guidance Steering (GPS)

### ISSUE THREAD

**Issue by Bohne11297** [Mogli12/VehicleControlAddon#414]
Moin,
Mir ist aufgefallen das die Funktion "Geschwindigkeit Permanent halten" eingefroren wird sobald man bei Guidance Steering (GPS) die Automatische Lenkung aktiviert. Eventuell ist es ja möglich diese Funktion umzuschreiben sodass dies möglich ist.

**Comment by Mogli12** [comment]
Wie ich schon oft geschrieben habe, setzt GuidedSteering beim Fahrzeug die Eigenschaft, dass es vom Helfer gesteuert wird. Deshalb funktioniert der Mod nur eingeschränkt in Kombination mit anderen Mods, u.a. auch mit VCA. Die Art des in GuidedSteering so zu implementieren ist halt recht rücksichtslos.
