### ISSUE TITLE
No Auto Rotate Back suggestion

### ISSUE THREAD

**Issue by Harag9** [Mogli12/VehicleControlAddon#417]
Due the using the shuttle command stopping the tractor while in chat, I've altered my driving habit.

I'm now using "Free turn" to turn left and right and not to recenter the wheels so cornering isn't as jerky. I've removed the space bar from "shuttle" and applied the space bar to the "No Auto Rotate Back" - I'm finding that after cornering I can now press space bar to align my wheels forward... Great.

However, I've noticed when doing yard work pressing space bar doesn't align the wheels unless I'm moving -- Would it be possible to have it do this EVEN when speed is ZERO - ? 

Thanks

**Comment by Mogli12** [comment]
Hi, 
Sorry, but this is not possible. I propose to turn off adaptive steering.
Regards
