### ISSUE TITLE
autoRange Zeichenfehler

### ISSUE THREAD

**Issue by DonDespo1** [Mogli12/VehicleControlAddon#420]
Hallo.
Habe grade mal den Code durchgeschaut, weil ich wissen wollte, warum er "autoShiftRange" nicht aus der transmissions.xml korrekt läd. 
Scheinbar ist im gesamten Quellcode ein ` (Apostroph) hinter autoRange, nur nicht dort, wo die xml geladen wird.
Also:

autoRange`  <- zu 99% &
autoRange   <- beim lesen des xml Attributs

Mfg

**Comment by Mogli12** [comment]
Hi,

das sollte mit Build 193 gefixt sein. Bitte mach das Issue wieder auf, falls das nicht so ist.

Viele Grüße
