### ISSUE TITLE
Teilweise starker Drehzahlabfall bei Gangwechsel (Automatik / Manuell - Powershift Getriebe)

### ISSUE THREAD

**Issue by BumblebeeBob** [Mogli12/VehicleControlAddon#421]
Hallo Stefan,

Ich habe seit einiger Zeit das Problem, dass beim Gangwechsel zwischen Powershift Gängen die Motordrehzahl teilweise stark abfällt (~ Leerlaufdrehzahl), was zu einer starken Bremsung des Fahrzeugs führt, und den Beschleunigungsvorgang unterbricht. 
Nach ausführlichem Testen hier meine Beobachtungen:

- Der Effekt ist bei unterschiedlichen Fahrzeugen unterschiedlich stark ausgeprägt (Ich konnte keinen Zusammenhang feststellen).
- Die Wahl der Reifen hat einen starken Einfluss, vorallem Radgewichte verstärken den Effekt stark.
- Zusätzliche Last am Fahrzeug (z.B. schwerer Anhänger) verringert den Effekt.
- Der Effekt ist am stärksten ausgeprägt, wenn nur eine Achse angetrieben wird (durch Einstellung der VCA Differenziale), ist aber auch mit standard Differenzialen vorhanden(VCA Differenziale Einstellung aus).
- Tritt bei manuellem und automatischem Schaltmodus gleichermaßen auf (automatische Kupplung aktiv, Getriebe mit Powershift Gängen).
- Beispiel zur Reproduktion: Case IH Magnum 380 CVX mit Standard Bereifung + Radgewichten, Fullpowershift Getriebe und VCA Differenziale auf Heckantrieb.

Getestet wurde auf der standard Felsbrunn Karte mit standard Fahrzeugen. Es war nur VCA im Modordner, und das Savegame wurde extra für diese Tests erstellt. Als Teststrecke diente die Straße zwischen Händler und Start Bauernhof. Die Spieldateien wurden mit Steam verifiziert, und sollten demnach fehlerfrei sein. Die Log.txt Datei ist fehlerfrei und weist (soweit ich das beurteilen kann) keine Besonderheiten auf.

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5007514/log.txt)

Ich kann leider nicht genau sagen, wann das Problem zum ersten mal aufgetreten ist, da es nur unter den gegebenen Umständen auftritt, und ich eher unregelmäßig FS19 spiele. Ich glaube aber dass es irgendwann nach der Implementierung der VCA Differenziale war.

Vielen Dank, für die ganze Zeit und Energie die du in dieses Projekt steckst und gesteckt hast. Für mich ist VCA der wichtigste Mod, um FS19 genießen zu können.

Liebe Grüße

BumblebeeBob

**Comment by D9005** [comment]
Moin,
Bin zwar nicht Stefan, kann aber denk ich auch helfen 😅

Setz mal die Schaltzeit von 0ms eine Stufe hoch (war mein ich 150ms). Fühlt sich fast genauso an und der Drehzahlabfall ist weg.
Bei mir hat es so funktioniert. 

Mfg D9005

**Comment by Snekyno** [comment]
I have same problem with Powershift on JDs and also with Hexa shift on Claas vehicles. Speed rapidly droping down.

**Comment by BumblebeeBob** [comment]
@D9005 
Vielen Dank für den Hinweis. Ich habe seither nur mit den vorgefertigten Getrieben gespielt, bei denen man diese Einstellung nicht vornehmen kann. 
Nach einem kurzen Test muss ich sagen, dein "Workaround" funktioniert wirklich gut! Kein Drehzahlabfall mehr und schaltet fast so sanft wie das standard Powershift Getriebe. Definitiv eine Lösung bis zu einem potentiellen fix in der Zukunft. 
Vielen Dank nochmals, dass du dir die Zeit genommen hast zu antworten und deine Lösung zu teilen.

 @Snekyno 
Thanks for your answer, its nice to hear that its not just an issue on my end! I was almost going insane when the issue appeared the first time and i couldn't figure out what it was (heavily modded game as probably most of us have). 
For the meantime, try the fix posted above by D9005. It works pretty well. You need to set the Gearbox to "Own configuration" and set the gearshifting speed one notch up to 125 ms.
I hope it's just a bug in VCA that Mogli12 is able to fix, and not another stupid limitation in the Giants Game Engine.

**Comment by BumblebeeBob** [comment]
Super, schaltet wieder einwandfrei. Vielen Dank!
