### ISSUE TITLE
Wunsch um das Speedmatching zu deaktivieren 

### ISSUE THREAD

**Issue by VivienHardgas** [Mogli12/VehicleControlAddon#423]
ich würde es gerne wünschen wenn das speedmatching deaktivierbar wäre oder anpassbar das der automatik modus nicht mehr immer in den letzten gang schaltet sobald die last weg ist oder zu spät zurückschaltet

**Comment by VivienHardgas** [comment]
ich setze jetzt mal meinen vorschlag dazu weil ich mich jetzt damit mehr beschäftigt habe.

mein vorschlag währe das man neben dem speedmatching auch 2 punkte festlegen kann indem das getriebe schaltet mit und velleicht auch ohne speedmatching denn ich finde dieses ziemlich aggresiv was das hochschalten betrifft. Als beispiel wenn ich den grubber am vorgewende hochhebe schaltet das eigene und das normale 12 gang fps direkt 5 gänge hoch und wenn ich den wieder runtersetze brauch es immer 5sek um den richtigen gang zu finden.

ich würde z.b die punkte bei 1400 und 1900 bzw. 2000 u/min machen wollen so das das speedmatching nur dort agiert und schaltet und nicht immer solange hochschaltet bis es den leerlauf erreicht hat.

**Comment by Mogli12** [comment]
Hallo,

Automatik bei der Feldarbeit klappt nicht so gut. Das größte Problem ist, dass die Physik die Fahrwiderstände aus meiner Sicht komisch simuliert. 

Ich schalte meistens die Automatik aus, dass geht direkt über eine Tastenkombination (RCtrl+Ü). Alternative kann man in den VCA Einstellungen die minimale und maximale Ganggeschwindigketi einstellen. Man muss diese nach der Feldarbeit dann auch wieder ausschalten.

Viele Grüße
