### ISSUE TITLE
Shuttle not working when implement attached

### ISSUE THREAD

**Issue by ryanccard** [Mogli12/VehicleControlAddon#425]
Hello,

The shuttle direction control seems to work fine until I attach a implement or trailer. Once I do this, I have to detach the implement, change the shuttle direction, then reattach in order to change direction. I have tried a few different things like uninstalling mods that I have installed since the last time it worked correctly. Not sure what the issue is.

**Comment by Mogli12** [comment]
I propose to delete your inputBinding.xml
