### ISSUE TITLE
VCA and REA conflict

### ISSUE THREAD

**Issue by mrPassion78** [Mogli12/VehicleControlAddon#426]
I have a re-occurring problem with the VCA mod and REA active.
when i started to use the VCA difflocks (witch are far better than those of TSX_EnhancedVehicle) , i started to have problems...
With or without the RMT mod, when the wheels spin at a certain speed in mud, ( like getting stuck so from 80% slip and up) there is a point reached that VCA or REA goes nuts...The tractor starts to fly off at full speed  and no stopping it until its on its side or of the map.
The strange thing is..NO log entry's are created of any faults.
The RPM goes wild and the fuel tank is empty instantly .
It does not matter witch tractor i use, vanilla or modded, it happened to all of them.

Here is a screenshot of it: LOOK AT THE RPM !

![fsScreen_2020_08_05_20_03_46](https://user-images.githubusercontent.com/40406761/90419897-800a0a00-e0b7-11ea-95c4-82789ff72963.png)
Just look at the RPM. the tractor landed on its side after flying backwards when about to got stuck.

this even occurs with just the VCA vario transmission active..BUT !!! only when in the low range of the vario.. than it does the same even when driving on asphalt ( when turning outside a field or steep hill climb).. than the mods collide and the tractor is lost, and fly of the map at speeds over 200kmh.

so this occurs in the flowing settings: ( for me at least)
1-- in the low vario speed range when applying to near full throttle 
2-- with the difflocks on and off, when the wheels get stuck..and start to spin to fast
3-- with or without diff on or off, in a field, and make the wheels spin to much when still driving but with more than 80% slip.
4-- it started when i started to use the diffs of the VCA ( and on all maps modded or vanilla)

in all those cases, the tractor ( with RMT and without RMT) starts to go the opposite side of where it was heading for and tank is empty instant, and the rpm goes banana`s. 

The bad thing is.. no error or warning in the logs! in those cases.
and it can happen 6x in 20min of play time, and with watching for it , i can play for an 45min without it happening..but i have to be very careful, and make Shure i press the clutch pedal fast enough with the brake pedal , to stop the wheels from spinning to fast , to prevent it from happening.
i have VCA <version>9.1.8.5</version>
and REA <version>1.3.1.0</version>

i hope you can reproduce it and maybe find whats causing this.

Greetings Pascal

**Comment by templer013** [comment]
I had the same issue with initial version that was on modhub (when it still had the diff control). I also use REA. 
After i updated to the current version of VCA on modhub (the one without diff control) i have not had this issue anymore. I am now using the diff control of EV. 

I now have another issue though. Sometimes the front achsel wheel just seem to turn like 50% faster (they seem to have a different ratio in that case) then the rear resulting in high slip even on a road with nothing attached to the tracktor. A restart of the game fixes this. Unfortunately i havn't been able to reproduce this. It just happens sporadically.

**Comment by Williwillswisse** [comment]
I have the same issue Pascal describes without using REA. When the vehicle starts to sprint over the map I try to steer to a tree or building to stop it and reset it to the shop. After that the vehicle works like expected.

**Comment by Dinratte** [comment]
Hi,
we had the same problem.
We have delete the Rea mod and now it works.

Very strange ^^

**Comment by Mogli12** [comment]
Hi,

I think there is a problem in Giants engine. It seems that locked differentials make it more likely to happen. At one point in time the speed get really huge. Then the fuel tank is empty and the vehicle shoots over the map.

It can happen with and without REA or VCA.

Regards, Stefan

**Comment by mrPassion78** [comment]
Hi Stefan, 
I did a role-back on the vca mod, and installed version : <version>1.0.0.0</version> from the release version, and the problem of flying across the map is gone..
i have diff-lock engaged via TSX_EnhancedVehicle, and i spend 2 min of seeding with over 93% wheelslip at various speeds without a problem, and with still the same REA version installed.

For me that indicates that its not all a giants problem, but in my case, it looks like a mod clash of some sort.

i will try to find out when it goes wrong with adding all my mods in 1 by 1.. with the REA active and the latest version of VCA.
just give me some time for that, cause that will take up a few days..

**Comment by Mogli12** [comment]
If Giant engine returns an extremely high speed all of a sudden, then it is a bug. I am not discussing this further.

**Comment by mrPassion78** [comment]
thats one way to end it indeed
