### ISSUE TITLE
Settings not saved on dedicated Server / Einstellungen werden auf dedicated Server nicht gespeichert.

### ISSUE THREAD

**Issue by Confusedman74** [Mogli12/VehicleControlAddon#427]
Hi Mogli,

the settings aren't saved on a dedicated server. I see that the file VehicleControll.xml will be created in the savegamefolder when i change the global settings, but when the server saves next time, your file will be wiped from the folder and so no settings can be loaded.

Hi Mogli,

die Settings werden auf dem dedicated Server nicht gespeichert. Wenn ich in den globalen Einstellungen vom VCA was ändere, dann wird auch die Datei VehicleControlldingsbums.xml erstellt. Speichert aber der Server das nächste Mal, dann wird die Datei wieder gelöscht und so können ja keine Settings mehr geladen werden, alles wieder auf "Standard".

**Comment by Evilman2517** [comment]
Kann dies bestätigen. Habe mir aus einem alten Savegame-Backup vom Dedi einmal die Config.xml wieder ins aktuelle Savegame geschoben, die Settings wurden zwar einmal gelesen, allerdings wurde die Datei ebenfalls direkt wieder gelöscht.

**Comment by Mogli12** [comment]
Please check build 195
