### ISSUE TITLE
Getriebe selbst einbauen

### ISSUE THREAD

**Issue by ffwmaxi** [Mogli12/VehicleControlAddon#428]
Hallo,
Ich wollte in die Lua evtl. ein eigenes Getriebe einpflegen.
Ich wollte es erst Ingame irgendwie zusammenbauen. Aber ich bekomme es nicht hin.

Ich möchte ein ZF Getriebe nachbauen mit 24 Vorwärts und 12 Rückwärtsgängen. Unterteilt in 2 Gruppen mit 6 Gängen und die wiederum unterteilt in 2 Lastschaltstufen.
Ist das denn überhaupt möglich?

Habe schon gesehen wie andere schon ein Getriebe in die Lua. Implementiert haben.

**Comment by Mogli12** [comment]
Hallo,

VCA kann nur Gänge mit Gruppen ODER Lastschaltstufen.

Viele Grüße
