### ISSUE TITLE
Warning: mogliBase30Request received invalid NodeObject

### ISSUE THREAD

**Issue by xSteveUrkelx** [Mogli12/VehicleControlAddon#431]
Hi, kann mir jemand sagen ob ich mir bei dieser Warnung irgendwelche Bedenken machen muss ?

Kann diese Warning zu performance Problemen/Einbusen auf dem Dedi Server führen ?
Wie bekomme ich diesen Fehler weg ?

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5146723/log.txt)

**Comment by Mogli12** [comment]
Hi,

das passiert in der Regel, wenn in einem anderen Mod ein Problem im MultiPlayer-Modus ist. Dann verschieben sich alle weiteren Nachrichten um ein paar Bytes und nichts stimmt mehr,

Viele Grüße, Stefan

**Comment by xSteveUrkelx** [comment]
Ist diese Warning denn in irgendeiner Weise schlimm ? Kann diese Warning zu Performance Problemen oder Crashes führen ?

**Comment by Evilman2517** [comment]
Abend, ich habe diesen Fehler auch ab und an in der Log auf dem Dedi, mir ist aufgefallen, dass der Fehler immer dann kommt, wenn ein Spieler ein Fahrzeug mit aktivierter Rückfahreinrichtung nutzt (also den Sitz dreht).
