### ISSUE TITLE
Hud move

### ISSUE THREAD

**Issue by fenomen84** [Mogli12/VehicleControlAddon#432]
Hi Mogli12. I have little problem with Vehicle Control Addon mod,
how and where change line in mod to move white text left, and more up? 

![screen](https://user-images.githubusercontent.com/70572125/91830317-e9a32000-ec42-11ea-8272-ffd8234aafc2.png)

**Comment by Mogli12** [comment]
Please check the global settings

**Comment by fenomen84** [comment]
In VCA mod settings folder and next config file, I have only that:

VCAGlobals>
        g27Mode value="6"/>
        transmission value="5"/>
/VCAGlobals>

and I don't have any more lines to edit that text move... Any issue?

**Comment by fenomen84** [comment]
New version VCA fix that problem.
