### ISSUE TITLE
Enhancement suggestion: U-Turn

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#433]
Hi,
first thanks a lot for this great mod. I really love it and can't imagine playing without, as I'm a keyboard player.
Though, I have a suggestion: Would it be possible to add a function to make a U-Turn? Assigned to 2 keys for a left turn and a right turn? And, if the turn would be too narrow, the vehicle turns to the second row instead the next.

**Comment by Mogli12** [comment]
Hi,
das wäre zwar interessant und hilfreich. Aber der Teufel stickt im Detail, z.B. bei gezogenen Geräten.
Viele Grüße
