### ISSUE TITLE
Vordere/Hintere Geräte ausklappen

### ISSUE THREAD

**Issue by gh36** [Mogli12/VehicleControlAddon#436]
Guten Tag.

Leider habe ich bisher keine Tastenbelegung dafür gefunden, jedoch würde ich gerne per Tastendruck je das vordere und hintere Gerät ausklappen., vgl. mit der Tastenbelegung "X" für das jeweils ausgewählte Gerät.

Zum Verständnis, so sieht aktuell meine Belegung aus:
Keypad 5 - VCA: vordere Geräte heben/senken
Keypad 2 - VCA: hintere Geräte heben/senken
Keypad 6 - VCA: vordere Geräte (de-)aktivieren
Keypad 3 - VCA: hintere Geräte (de-)aktivieren

Hinzu kommen soll:
Keypad 4 - VCA: vordere Geräte ausklappen (*NEU*)
Keypad 1 - VCA: hintere Geräte ausklappen (*NEU*)

Gibt es die Funktion und ich habe sie nicht gefunden oder besteht die Möglichkeit dieses zu implementieren?

**Comment by Mogli12** [comment]
Hallo,

die Idee war, dass man mit den 4 Tasten die Funktionen steuern kann, die man auf dem Feld benötigt. Ich gehe momentan davon aus, dass man Ein- und Ausklappen nur einmal ganz am Anfang oder Ende benötigt. Da kann man die Geräte auch einmalig mit G durchschalten und dann X drücken.

LS19 hat ohnehin so seine Probleme mit Tastaturbelegungen. Da gibt es eine Reihe von Issues alleine hier bei VCA.

Viele Grüße
