### ISSUE TITLE
own configs in ein anderes SV uebernehmen

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#437]
Hi, x-mal wollte ich das schon anbringen...gibt es eigentlich eine Moeglichkeit, die diversen eigenen Getriebe-Configs in ein anderes sv zu uebernehmen? ich habe mittlerweile so um die 10-12 configs, und die jedesmal in ein anderes manuell zu uebernehmen ist schon ein bissl...........!

Schoene Gruesse,
Claudio

**Comment by JASNDE** [comment]
>  in ein anderes sv

In ein anders was? Savegame?
