### ISSUE TITLE
Update VCA auf ModHub

### ISSUE THREAD

**Issue by Sacred-Shadow** [Mogli12/VehicleControlAddon#438]
Hey zusammen,

auf ModHub ist noch die Version 1.0.0 oben.
Wäre doch langsam mal Zeit für ein Update oder? :)

**Comment by Mogli12** [comment]
Na ja, die aktuellste Version ist ohnehin immer hier auf GitHub. Und eine Bewertung von 3.8 im ModHub wirkt nicht gerade motivierend.

**Comment by bgo1973** [comment]
Zwischen der 1.0 und der aktuellen hier liegen aber Welten. Ich denke da wird sich einiges an der Bewertung ändern. Für mich ist VCA nicht wegzudenken

**Comment by Sacred-Shadow** [comment]
> Na ja, die aktuellste Version ist ohnehin immer hier auf GitHub. Und eine Bewertung von 3.8 im ModHub wirkt nicht gerade motivierend.

Da magst du Recht haben ... aber wenn man nur auf ModHub unterwegs ist, weiß man nichts von Github. 
Zudem möchte ich auch wetten, dass sich der ein oder andere seine Github Version ausversehen mit der ModHub Version updatet, wenn mal wieder eine Ingame Updateorgie ansteht. 

Es geht ja nicht zwangsläufig darum, die immer aktuellste Version dort zu haben.
Aber eine Stable die gut läuft, kann man hin und wieder doch mal dort reinladen. :)

**Comment by templer013** [comment]
Du würdest den vielen Fans deines Mods einen riesen Gefallen tun! Und ich würde wetten, dass die Bewertung auch besser wird. Pretty please! 🙏

**Comment by Sacred-Shadow** [comment]
@Mogli12 und eine Entscheidung getroffen?

**Comment by Mogli12** [comment]
Version 1.1 ist eingereicht.
