### ISSUE TITLE
Ownconfig zusatz separate Splitter Gruppe

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#439]
Wäre es möglich in dem ownConfig einstellungen noch eine 3 Gruppe einzufügen? Da manche Schlepper ja neben 6 Gänge, 3 Gruppen auch noch 4 Lastschaltstufen haben können.

 Vllt wäre es auch möglich zu sagen das man die Manuelle Kupplung für Gänge, Gruppen und zukünftig Splitter unabhängig von einandeer wählen könnte. Da es Schlepper gibt bei denen man die Kupplung treten muss um Gruppen zu wechseln aber die Gänge ohne Kupplung treten geschalten werde.

Mich würde es sehr freuen wenn man diese funktion noch bekommen würde, dann wäre aus meiner Sicht das VCA komplett und perfekt.

Danke für deine bisherige Mühe Stefan :)

MfG Chris

**Comment by Mogli12** [comment]
Hallo Chris,

Das Problem mit einer weiteren Gruppe sind die Tastaturzuweisungen. Da gibt es ohnehin schon Probleme im Spiel. Ich fürchte, dass dann nicht mehr alle Tasten sauber funktionieren.

Viele Grüße,
Stefan

**Comment by ChrisJD8400R** [comment]
Also beim Gearbox hatte man noch für die 3 Gruppe strg rechts und  ü/ä belegt.


Könnte man das vllt doch mal testen mit der 3 Gruppe :)

Die fehlt mir wirklich etwas. ^^
Da ich mit Seitenkonsole und G27 shifter spiele (wie einige andere Spieler auch) hat man da noch genug freie Tasten. 
LG Chris 😊


Gesendet von Yahoo Mail auf Android 
 
  Am Do., Sept. 17, 2020 at 17:59 schrieb Stefan Biedenstein<notifications@github.com>:   


Hallo Chris,

Das Problem mit einer weiteren Gruppe sind die Tastaturzuweisungen. Da gibt es ohnehin schon Probleme im Spiel. Ich fürchte, dass dann nicht mehr alle Tasten sauber funktionieren.

Viele Grüße,
Stefan
