### ISSUE TITLE
Fahrzeuge bremsen nicht ab und Leistungverlust

### ISSUE THREAD

**Issue by JohnDeere6920** [Mogli12/VehicleControlAddon#440]
Hallo @Mogli12 
Erstmal vielen dank für den Mod. Ohne geht einfach nicht mehr. Allerdings hab ich vor kurzem auf die neuste Version von Github geupdatet und hab festgestellt, die fahrzeuge mit Vario Getriebe nicht mehr abbremsen, wenn man vom Gas geht. In echt jedoch hat man immer einen gewissen "Motorbrems Effekt" auch bei stufenlosen Getrieben. Hab ich da was falsch eingestellt oder stehe ich auf dem schlauch?
Desweiteren ist mir aufgefallen, wenn man das getriebe auf off stellt, also das Standart LS getriebe verwendet, Steht das Fahrzeug direkt sobald man vom Gas geht. Das war vorher auch nicht.

Und dann noch Der leistungsverlust den man mit dem Vario oder dem IVT Getriebe hat. Klar das die Leistungsverlust haben aber das ist für meinen Geschmack schon etwas zu viel Leistungsverlust. Wäre es da möglich, das ich den irgendwie einstellen kann? z.B. Das Stufenlose AutoPowr Getriebe von John Deere hat weniger Leistungsverlust als zum Beispiel das Vario. Das AutoPowr hab ich mir schon in der Config hinzugefügt, aber das geht so gut wie garnicht wegen dem Leistungsverlust. Vielleicht kannst du mir ja helfen.

MfG
Eric
John Deere 6920

**Comment by bauerwilhelm** [comment]
Meinst du mit dem Leistungsverlust, dass du beim Pflügen z.B. nur noch 8 km/h anstatt 12 km/h fährst, wie es der Pflug eigentlich zulässt? Dann hätte ich schon mal einen Teil meiner Verwirrung geklärt :)

**Comment by Mogli12** [comment]
Hallo,

VCA ändert nichts an der eigentlichen Leistung. Was allerdings stimmt ist, dass die Beschleunigung (m/s^2) begrenzt wird. Das merkt man aber nur, wenn man ohne oder mit leerem Anhänger fährt.

Daher müsstest Du schon genauer beschreiben, was hier Leistungsverlust überhaupt bedeutet.

Viele Grüße

**Comment by JohnDeere6920** [comment]
Hallo,
Erstmal Danke für die Antwort.
Mit Leistungsverlust meine ich zum Beispiel: Ich habe 240 PS vor der Claas Presse aus dem Claas DLC. Klar das ich dann nicht mit 20 den Berg hoch komme beim Pressen, aber wenn ich VCA Getriebe aus habe, dann fahr ich sag ich mal mit 17-18 Km/h den berg hoch. Wenn ich VCA Getriebe an habe dann bin ich bei 11-12 Km/h an dem gleichen Berg. Deshalb hab ich gedacht das VCA was an dem Leistungsverlust ändert. Vielleicht hast du ja ne Lösung. Das mit dem Bremsen ohne VCA hab ich auch noch nicht gelöst. 

aber schonmal danke 

Viele Grüße

**Comment by Mogli12** [comment]
Hallo!
Welche Version verwendest du? Und kann man das an einem Hügel in Felsbrunn nachspielen? Verwendest Du auch REA?
Viele Grüße

**Comment by JohnDeere6920** [comment]
Hallo.
Entschuldignung das ich nicht geantwortet habe aber ich bin im moment etwas im stress.
Ich Verwende die Version 9.1.8.6 hier von GitHub.
Das mit dem hügel in Felsbrunn müsste ich probieren. Wir spielen auf einem Dedi Server auf der Stappenbach. Ich Verwende Kein REA. Das mit dem Screenshoot mach ich bei der nächsten gelegenheit. 
Gruß

**Comment by Mogli12** [comment]
Hallo,
ich habe einen kleinen Korrekturfaktor spendiert, so dass das Fahrzeug ohne VCA und mit VCA und Getriebe IVT ungefähr gleich schnell einen steilen Hügel erklimmt. Falls der Unterschied immer noch zu groß ist, dann mache diese Issue bitte wieder auf.
Viele Grüße
