### ISSUE TITLE
Grégoire-Besson SPSL 9 Autoerkennung Breite/Versatz

### ISSUE THREAD

**Issue by bauerwilhelm** [Mogli12/VehicleControlAddon#441]
Hallo Mogli,
zuerst einmal vielen Dank für Deine fortwährende Mühe, den virtuellen Landwirten das Leben leichter zu machen! 👍 
Ich habe soeben beim Testen herausgefunden, dass beim o.g. Pflug die Erkennung überhaupt nicht funktioniert. Bei **allen** anderen Pflügen (auch Mod-Pflügen) funktioniert das reibungslos. Leider habe ich auch noch nicht die optimale Einstellung herausbekommen, sodass eine automatische Erkennung des größten Vanilla-Pfluges doch eigentlich ganz praktisch wäre :)

Liebe Grüße
Torben
bauerwilhelm

**Comment by Mogli12** [comment]
Please check Build 197
