### ISSUE TITLE
Joystick-Steuerung (Vario)

### ISSUE THREAD

**Issue by steinelp** [Mogli12/VehicleControlAddon#442]
Hallo @Mogli12 !

Ich möchte mich zuerst für den großartigen Mod bedanken! Er ist ein klares Must-have!
Es geht nicht um ein Problem sondern einen Funktionsvorschlag. Ich fände es super wenn es die Möglichkeit gäbe über einen Joystick oder auch über zwei tasten die Getriebeübersetzung stufenlos zu wählen und gleichzeitig mit dem Gaspedal die Drehzahl zu kontrollieren. im Prinzip ist diese Funktion schon fast vorhanden: wenn man den "permanent keep speed" Modus und das Handgas aktiviert kann man die Drehzahl und die Getriebeübersetzung getrennt voneinander steuern nur eben das Gas auf dem Joystick/der Tastatur und die Übersetzung mit Gaspedal und Bremse... außerdem ist in diesem Modus sowohl die Bremskraft als auch die Beschleunigung ziemlich gering.
Deshalb meine Frage:
Wäre es Möglich einen "Joystick Modus" hinzuzufügen? entweder um damit die bestehenden stufenlose Getriebe "Manuell" zu steuern oder falls es einfacher ist ein neues Getriebe mit dieser Funktion hinzuzufügen. Das würde dann exakt einem realen Variogetriebe entsprechen (das Gaspedal verhält sich wie ein normales Gaspedal und der Joystick (Selbstzentriert) verringert das Übersetzungsverhältnis durch nach vorne drücken bzw. erhöht es durch zurückziehen).
Bei weiteren fragen auch bezüglich der Umsetzung kann ich gerne weiterhelfen. Ich habe nämlich bereits selbst versucht die Funktion zu integrieren und habe es im RMT auch fast geschafft bin aber beim versuch dasselbe im VCA einzufügen Gescheitert... beim RMT habe ich es nur mit einer ganzen (nicht zentrierten) Achse hinbekommen - somit war es dann ehr wie bei einem Hydrostaten was aber auch ein interessanter Nebeneffekt war und vielleicht eine Idee für später ist. 
Es würde mich sehr freuen wenn diese Idee wirklich funktioniert und dann auch noch in meinem absoluten Lieblingsmod integriert wäre :)

MfG
Paul

**Comment by Mogli12** [comment]
Hallo Pau,

ich habe mir folgendes Video angeschaut: [Hot to Drive Fendt 926 Favorit](https://youtu.be/wBqUjKAS2NI). Es gibt jetzt eine weitere Achse, mit der man manuell die Übersetzung einstellen kann. Dazu muss man das Getriebe von Automatik auf Manuell umstellen.

Gaspedal und Handgas funktionieren wie bisher, die Kupplung läuft erstmal für eine "Turbomatic".

Viele Grüße,
Stefan

**Comment by steinelp** [comment]
Hallo Stefan,
Ich habe soeben das neue feature getestet und bin begeistert! Es ist genau was ich mir vorgestellt habe.
Der einzige Punkt der mir noch auffiel ist dass die Einstellung nur mit Tasten geht bzw. wenn eine Achse belegt wird, wird diese nicht als Achse erkannt (nur binäre Eingabe möglich) und somit ist die Anpassung der Übersetzung nur recht grob möglich. Ich denke auch nicht dass es so geplant war... Ansonsten bedanke ich mich schonmal, dass das so schnell und so perfekt geklappt hat :)

**Comment by IzL902** [comment]
Halle @Mogli12

Danke für die schnelle Umsetzung von diesem Vorschlag. Ich gehe mit diesem Beitrag *sehr* ins Detail, aber vielleicht ist es eine kleine Inspiration für die Zukunft :)

Was mir im Moment fehlt, ist das automatische Anpassen der Übersetzung nach einem Bremsmanöver.

Bremst man einen Vario (ohne TMS) von 40km/h runter so wird er bei einem erneuten beschleunigen nicht wieder die volle Endgeschwindigkeit erreichen. Der Schlepper regelt schon während des Bremsens die Übersetzung so runter das der Motor wieder mit vollem Drehmoment weiter beschleunigt. Verändert der Fahrer nicht selber die Übersetzung beim Bremsen (minimales Verzögern) durch Antippen des Joysticks so brauch der Schlepper beim erneuten Beschleunigen 1-2 Sekunden um die passende Übersetzung anzusteuern.

Beispiel:

43,0km/h Endgeschwindigkeit
Bremsen auf ~20km/h -> Jetzt nur 22,5km/h möglich ohne selber die Übersetzung zu verändern.

Ebenso spielt auch die Einstellung der Beschleunigungstufe eine große Bedeutung. So lassen sich beim Vario vier Stufen wählen:

Stufe        Einmal am Joystick drücken          0-50Km/h
I                      +0,02-0,5km/h                    250-45,5sek
II                     +0,5km/h                                 45,5sek
III                    +1km/h                                    28.8sek
IV                    +2km/h                                    10sek

Quelle: Fendt 930 Vario Betriebsanleitung

Ein weiteres nützliches Feature wäre das Nutzen der MEMO Funktion. Im Vario Getriebe lassen sich so Geschwindigkeiten einstellen die der Schlepper selbstständig nach einem Richtungswechsel anfährt. (Deaktivierbar)

Beispiel im Acker- & Frontladereinsatz

9,5Kmh vorwärts MEMO
4,0Kmh rückwärts MEMO

So kann man ohne Betätigen des Joysticks die gewünschte Geschwindigkeit per Gaspedal erreichen.

Gerne stehe ich auch per Discord für fragen zu verfügung :)


Viele Grüße!

**Comment by Mogli12** [comment]
Hallo,

ich denke nicht, dass man alles so einfach umsetzen kann.

Aber es gibt ja jetzt schon eine Einstellung für die minimale und maximale Gangeschwindigkeit. Ich schaue mal, ob das für diesen Modus schon richtig umgesetzt ist.

Außerdem finde ich es gut, wenn beim Bremsen die Geschwindigkeit automatisch mit runter geht.

Wie ist es in der aktuellsten Version mit der Empfindlichkeit des Joysticks? Zu schnell, zu langsam oder gerade gut?

Viele Grüße

**Comment by Mogli12** [comment]
Hallo,

in Version 190 habe ich ein paar Kleinigkeiten angepasst. Man kann mit min und max Ganggeschwindigketi den Bereich der Steuerung einstellen. Beim Bremsen wird die Übersetzung automatisch verringert, aber nur bis zur Startgeschwindigkeit.

Ich spiele meistens mit der Tastatur. Daher macht das eigentlich nur zusammen mit Handgas Sinn. Auf der Straße ist das zu kompliziert. Auf dem Feld war das aber ganz interessant. Das ist viel feinfühliger als der Tempomat.

Viele Grüße,

**Comment by Mogli12** [comment]
English summary:

Transmissions IVT and Vario allow to switch into a manual mode. You can use action binding "vcaManRatio" ("VCA: Vario faster" and "VCA: Vario slower") to increase or decrease the gear ratio. This action binding is analog, if centered it will not change the gear ratio.

Important settings are the launch gear speed, minimum gear speed and maximum gear speed. The action binding variates between minimum and maximum gear speed. If you brake the vehicle will automatically reduce the gear speed but not lower than launch gear speed.

I think you need an analog throttle if you want to use the manual vario setting. Keyboard players might use the hand throttle together with manual gear ratio.

**Comment by klauskleber14** [comment]
Hallo Zusammen,

vorab erstmal vielen Dank an @Mogli12 für diese tolle Erweiterung des LS und den ständigen Erweiterungen.

Ich habe eine Frage zu dem IVT Getriebe. Mir werden dort zwei Geschwindigkeiten angezeigt die stetig mit Bewegung des Joysticks reguliert werden. Allerdings habe ich noch nicht heraus bekommen wie ich den unteren (geringeren) Geschwindigkeits Bereich geschaltet bekomme. Mit den normalen Schalttasten hat das bei mir nicht funktioniert.

Oder müssen in den VCA Einstellungen noch punkte eingestellt werden?

Ich wäre über eine Hilfestellung sehr dankbar. 

Viel Grüße

**Comment by Mogli12** [comment]
Hallo,

das IVT Getriebe hat nur eine Stufe. Die beiden angezeigten Geschwindigkeiten beziehen sich auf die aktuelle Übersetzung bei minimaler und maximaler Drehzahl.

10 km/h .. 22 km/h bedeutet z.B., dass das Fahrzeug 10 km/h bei 1000 U/min und 22 km/h bei 2200 U/min schnell fährt. Schneller geht es eigentlich nicht und falls man langsamer fährt, dann öffnet automatisch die Kupplung.

Viele Grüße

**Comment by steinelp** [comment]
Hallo @klauskleber14
Da kann ich sogar etwas weiterhelfen...
Die kleinere Zahl beschreibt nur die Geschwindigkeit die der Traktor bei Standgas (ohne Gas geben) fährt.
Umschalten zwischen zwei Bereichen ist nur beim vario getriebe möglich. Da steht dann low oder high vor den beiden Zahlen die den aktuellen Geschwindigkeitsbereich angeben.
Ich hoffe ich konnte die Frage soweit beantworten.
Gruß
Paul

**Comment by klauskleber14** [comment]
Ah ok dann hatte ich das falsch verstanden. 

Vielen Dank für die schnell Antwort :)
