### ISSUE TITLE
fps drops when shifting using G27

### ISSUE THREAD

**Issue by mikeboy203** [Mogli12/VehicleControlAddon#443]
when i press my clutch pedal it shows this in my log: 

2020-10-04 13:28 vcaMotorGetRotInertia:  2.00
2020-10-04 13:28 vcaMotorGetRotInertia:  0.50" 

and gives me a big FPS drop. the FPS drops makes it so i "let go the clutch" and grinds gears

**Comment by Didek96** [comment]
Yes, I have the same problem when shifting gears, but not only that, there are fps drops. It's so annoying

**Comment by Williwillswisse** [comment]
I think there are two forgotten print commands for testing in the vehicleControlAddon.lua
replace the "print(....." in line 6293 and line 6296 with "-- print(...."

**Comment by mikeboy203** [comment]
@Williwillswisse i gave this a try and it worked for me. thank you very much 👍

**Comment by Mogli12** [comment]
Did you try the latest version?
