### ISSUE TITLE
Schwache Beschleunigung

### ISSUE THREAD

**Issue by Kobes94** [Mogli12/VehicleControlAddon#444]
Hallo Mogli

In der Version 187 fühlt sich die Beschleunigung der Schaltgetriebe, in Kombination mit automatischem Kuppeln/Schalten, sehr langsam bzw. zäh an. Als wäre der leere Traktor mit einem sehr schweren Anhänger unterwegs.

Getestet habe ich auf der Felsbrunn ohne Mods, sowie auf einer Modmap mit Mods. Selbes Ergebnis, egal ob Standard- oder Modfahrzeug.

Bin dann zurück auf Version 185, da sind die Fahrzeuge wieder schneller.

Gruss
Kobes

**Comment by Mogli12** [comment]
Hallo Kobes,

das ist so gewollt. Ich finde die Fahrzeuge beschleunigen wie Formel 1 Fahrzeuge.

Viele Grüße
