### ISSUE TITLE
Schaltsounds 

### ISSUE THREAD

**Issue by Wolle00** [Mogli12/VehicleControlAddon#445]
Ist es irgendwie möglich, dass man die Schaltsounds ausschalten oder leiser stellen kann? Müsste doch irgendwie in der XML möglich sein. Danke schonmal im voraus.

**Comment by Williwillswisse** [comment]
Hallo Wolle, hast du schon mal in den Settings an den folgenden Parametern gedreht ?
![image](https://user-images.githubusercontent.com/47098121/95482404-5cb05c80-098e-11eb-8bee-9f64257e473e.png)

**Comment by Wolle00** [comment]
Ja aber das hat doch nichts mit den Schaltgeräuschen zu tun!

**Comment by Mogli12** [comment]
Hi,

Momentan ist mir die Dokumentation von [GDN SoundManager](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=31&class=314) zu dünn.

Viele Grüße

**Comment by Mogli12** [comment]
Hi,

Please try Build 193. You can change the values in config.xml. A sample modSettings folder is available here in Github.

Regards
