### ISSUE TITLE
Leistungsverlust

### ISSUE THREAD

**Issue by gowalso1** [Mogli12/VehicleControlAddon#446]
Hallo,

ich spiele die Map Ellerbach und fahre einen John Deere 6x20 (mod). Habe es aber auch mit original Fahrzeugen probiert.
Ich spiele mit VCA Getriebe 6x4 Autopowershift (auch andere Getriebe probiert).
Mein Problem:

Wenn ich mit dem Traktor in der Aussenansicht fahre und dann mit "C" in die Innenansicht wechsle dann geht die Drehzahl kurz
runter und habe Leistungseinbußen.
Habe mehrere Fahrzeuge probiert und auch alle Mods bis auf VCA entfernt. Das Problem tritt immer auf.

Wenn ich schnell mit C die Ansicht öfter hin und her wechsle geht dir Drehzahl fast ganz runter bis der Traktor aus geht.

Hat jemand noch dieses Problem?
Würde mich über eine Antwort freuen.

mfg
Andi

**Comment by Kobes94** [comment]
Tatsächlich, kann den Bug reproduzieren (Version 185). Ist mir nur nie wirklich aufgefallen, weil ich die Kamera nicht viel wechsle.
Scheint bis ca. 15 km/h ein Problem zu sein, wenn ich schneller unterwegs bin reduziert sich die Drehzahl nicht (oder so wenig, dass ich es nicht merke).

**Comment by gowalso1** [comment]
Hallo,

mir ist es aufgefallen, als ich bergauf mit Last gefahren bin und dann beim umschalten in die Innenansicht die Drehzahl rapide runtergegangen ist und den Traktor dann fast abgewürgt hat.


Ist es evtl. möglich diesen Bug in der nächsten Version zu fixen?
Das wäre wirklich super, da der VCA einfach perfekt und super ist.

Gruß
Andi

**Comment by Tensuko** [comment]
(Version: 9.1.8.5) FS19_VehicleControlAddon
Habe ich bisher noch nicht gehabt, mal die Tasten auf Doppelbelegung überprüft ?

**Comment by gowalso1** [comment]
Ich hab alle Mods rausgenommen und auch die Input Bindings gelöscht, so dass keine Doppelbelegung da sein dürfte.
Hab aber immer noch das Problem.

**Comment by Mogli12** [comment]
Hi,
ich denke, dass das Drücken einer anderen Taste den Zustand "Gaspedal ist gedrückt" kurzfristig unterbricht.
Viele Grüße,

**Comment by Mogli12** [comment]
Hi,

Ich habe das mit dem neusten Patch überprüft. Es ist so, dass bei Drücken der Taste C, das Gaspedal kurzfristig als nicht gedrückt ankommt. Konkret überschreibt VCA die Funktion `WheelsUtil.updateWheelsPhysics`. Bei gedrückter Taste W hat der Parameter `acceleration` den Wert 1. Wenn man nun zusätzlich die Taste C drückt, dann wechselt `acceleration` auf 0 und wieder zurück auf 1.

Ich sehe nicht, was VCA da einfach machen kann. VCA kann ja nicht von sich aus trotzdem Gas geben, oder?

Viele Grüße

***

I checked the lastest patch. Pressing key C interrupts the throttle. VCA overwrite function `WheelsUtil.updateWheelsPhysics`. If I just press key W, then the 3rd parameter with name `acceleration` has value 1. If I press key C together with W then `acceleration`  changes to 0 and back to 1.

But how should VCA overcome it? I think it cannot accelerated from its own.

**Comment by gowalso1** [comment]
Hallo, danke für die Antwort. Aber ganz versteh ich die Antwort nicht. Liegt es jetzt am VCA oder an was anderem? MfgVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Mogli12/VehicleControlAddon] Leistungsverlust (#446)Von: Stefan Biedenstein An: Mogli12/VehicleControlAddon Cc: gowalso1 ,Author 

Hi,

Ich habe das mit dem neusten Patch überprüft. Es ist so, dass bei Drücken der Taste C, das Gaspedal kurzfristig als nicht gedrückt ankommt. Konkret überschreibt VCA die Funktion WheelsUtil.updateWheelsPhysics. Bei gedrückter Taste W hat der Parameter acceleration den Wert 1. Wenn man nun zusätzlich die Taste C drückt, dann wechselt acceleration auf 0 und wieder zurück auf 1.

Ich sehe nicht, was VCA da einfach machen kann. VCA kann ja nicht von sich aus trotzdem Gas geben, oder?

Viele Grüße



I checked the lastest patch. Pressing key C interrupts the throttle. VCA overwrite function WheelsUtil.updateWheelsPhysics. If I just press key W, then the 3rd parameter with name acceleration has value 1. If I press key C together with W then acceleration  changes to 0 and back to 1.

But how should VCA overcome it? I think it cannot accelerated from its own.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Mogli12/VehicleControlAddon/issues/446#issuecomment-728166782",

"url": "https://github.com/Mogli12/VehicleControlAddon/issues/446#issuecomment-728166782",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Mogli12** [comment]
Hi,

es liegt im Spiel selber, dass das Wechseln der Kamera kurz das Gaspedal unterdrückt. Wahrscheinlich glättet das Vanilla Getriebe das Gaspedal so lange, bis das nicht mehr auffällt. Das führt aber auch zu einem verzögerten Ansprechen.

Viele Grüße

**Comment by gowalso1** [comment]
Alles klar und Danke für die Aufklärung. Das ist auch nicht schlimm mit der Unterbrechung vom Gas beim wechseln der Ansicht, da man ja das sowieso nicht oft macht. MfgAndiVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Mogli12/VehicleControlAddon] Leistungsverlust (#446)Von: Stefan Biedenstein An: Mogli12/VehicleControlAddon Cc: gowalso1 ,Author 

Hi,

es liegt im Spiel selber, dass das Wechseln der Kamera kurz das Gaspedal unterdrückt. Wahrscheinlich glättet das Vanilla Getriebe das Gaspedal so lange, bis das nicht mehr auffällt. Das führt aber auch zu einem verzögerten Ansprechen.

Viele Grüße



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Mogli12/VehicleControlAddon/issues/446#issuecomment-728186833",

"url": "https://github.com/Mogli12/VehicleControlAddon/issues/446#issuecomment-728186833",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
