### ISSUE TITLE
Parking Brake not working

### ISSUE THREAD

**Issue by ElfVierzehn** [Mogli12/VehicleControlAddon#448]
Hey there! I am using the latest version of your beautiful mod, and I have an issue with the parking brake. I have engine idle on and off (if that's the correct name in English) set to '#'. I have Stop and Go in FS19 activated and don't use the shuttle mode. I have not bound '#' for any other function. I use IVT gearbox, but it happens with others as well.

If I press '#' for the engine to idle I receive a red little ((P)). At the same time, the engine appears to raise the rpm by a little and starts moving a bit. If I don't press '#' for ((P)) I get an (A), which is probably the automatic parking brake. However, with both of those variants, the tractor moves very slowly. With the ((P)) it's like mentioned above, with the (A) it's like it does not have any brake active, at all. Do you have an idea here? I tried this on a vanilla map with just your mod in my folder, and the tractor just does not standstill.

Thanks for any advice! =)

**Comment by Mogli12** [comment]
Which version are you using. Please post the log.txt and a screen shot

**Comment by ElfVierzehn** [comment]
I use the latest build available here, which should be build 143.
It's a little difficult to capture the issue with a screen, though I tried anyway. What you can see there is the tractor rolling downhill backwards with the ((P)) active. I can brake until I stand still, if I stop braking, the tractor just starts rolling downhill again. 

Sry for not including the log right away. Please find it below as well as the screen.

Thanks for your reply!


![2020-10-23](https://user-images.githubusercontent.com/48221157/96999044-d6bb1680-1534-11eb-8f5f-6f2f4565e273.png)

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5429166/log.txt)

**Comment by Mogli12** [comment]
Latest build ist 188.

**Comment by ElfVierzehn** [comment]
I used the link for 'Latest version' to download it. Probably read the wrong line. 

modDesk says <version>9.1.8.8</version>

Thanks!

**Comment by Mogli12** [comment]
Hi,

It is fixed with build 191.

Thanks

**Comment by ElfVierzehn** [comment]
That's so amazing! =) Thank you very much for your beautiful work!
