### ISSUE TITLE
Spanish translation for version 9.1.8.8

### ISSUE THREAD

**Issue by KCHARRO** [Mogli12/VehicleControlAddon#449]
Hi Stefan ...

in the "modDesc_l10n_es.xml" there was a problem with long texts, I have fixed it and also added all the missing text fields of the new added functions that were not there.

Greetings to all

[modDesc_l10n_es.zip](https://github.com/Mogli12/VehicleControlAddon/files/5416946/modDesc_l10n_es.zip)

**Comment by KCHARRO** [comment]
Is there a way that the function of maintaining camera rotation and manual differential lock can also be controlled when the AI controls the vehicle as we could with FS17_GEARBOX?

I got realMud to work with the AI and Seasons, but VCA couldn't handle it ...

**Comment by Mogli12** [comment]
Hi,

The last setting in the diff.lock section controls the behavior under AI.

Regards
