### ISSUE TITLE
Snap Angle 

### ISSUE THREAD

**Issue by smartys1809** [Mogli12/VehicleControlAddon#452]
Dear Team,
I‘ve been wondering if it‘s intended but I’ve figured out that the snap angles are always divided by 10 from selected value in the settings menu. So 9 degrees instead of 90, 4.5 iso 45 etc... Is there any easy way to change this to be actually 90 degrees? 

Thank you in advance and keep up the good work!

**Comment by smartys1809** [comment]
In the meantime I fixed this temporarily by multiplying the angles in the Lua by 10 and this works without issues and as desired. However I didn’t found out, where the divider comes into place.

**Comment by Mogli12** [comment]
Hi,

The initial snap angle is a multiple of the selected snap angle. The adjustment with the arrow keys allows changes in 10% of the snap angle.

Regards,
Stefan
