### ISSUE TITLE
Keine manuelle Allrad/Diffsperre bei articulatedAxis Eintrag

### ISSUE THREAD

**Issue by Kobes94** [Mogli12/VehicleControlAddon#453]
Hallo Mogli

Bei dem Fahrzeug [hier (ModHub)](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=177377&title=fs2019), war der Eintrag manuelles Allrad/Diffsperre nicht verfügbar.

Ich wurde darauf hingewiesen, dass dies am Eintrag articulatedAxis liegt. Hab das auskommentiert und schon hats funktioniert.
Ist das gewollt oder planst du da ein Update?

Gruss
Kobes

**Comment by Mogli12** [comment]
Hallo Kobes,

Ich schaue es mir mal an. Aber ich vermute, dass ich hier kein eindeutiges Muster erkennen kann, wo welche Differentialsperre sitzen muss. Das Ding hat ja schließlich auch noch 3 Achsen.

Was macht hier eigentlich die Knicklenkung?

Viele Grüße

**Comment by Kobes94** [comment]
So wie ich dass feststellen konnte, funktioniert bei keinem Gerät mit der Knicklenkung die Steuerung der Diffsperren.

Bei dem Ural wird darüber das Lenkgestänge animiert (Nur sichtbar bei geöffneter Motorhaube).

Grüsse

**Comment by Mogli12** [comment]
Hallo,

das Fahrzeug ist leider zu komplex umd daraus die Position der Differentiale abzuleiten.

Viele Grüße
