### ISSUE TITLE
Ownconfig gearbox - different gears forward and reverse

### ISSUE THREAD

**Issue by Kalio91** [Mogli12/VehicleControlAddon#455]
Hi Mogli12,

Does it is available to configure own gearbox with different quantity of gears in forward and reverse direction (for instance. new holland powercommand with 19 gears forward and 6 gears)? 
![obraz](https://user-images.githubusercontent.com/70664852/97817423-b4479c80-1c9c-11eb-9922-b0687b5f9d16.png)
If it's not available now, are you planning to implement this option in the future?

**Comment by Mogli12** [comment]
Hi,

This is too complex for VCA. I am sorry.

Regards,
Stefan
