### ISSUE TITLE
Frontdifferenzial

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#456]
Hallo...ich weiss nicht, ob das nur an mir liegt, aber mit der neuesten Version bekomme ich die vordere Differenzialsperre nicht mehr aktiviert, und das bei jedem Traktor..hast du eine Idee?

![fsScreen_2020_11_02_19_58_42](https://user-images.githubusercontent.com/16596142/97907801-1a3c2e80-1d46-11eb-9c9b-96f765231033.png)
![fsScreen_2020_11_02_19_58_54](https://user-images.githubusercontent.com/16596142/97907805-1ad4c500-1d46-11eb-87b4-838d6178256d.png)

**Comment by Mogli12** [comment]
Hallo,

das kommt wahrscheinlich von der Tastaturbelegung von Courseplay. Leider ist Courseplay so codiert, dass Tasten, die darin verwendet werden, in allen anderen Mods nicht mehr funktoinieren.

Viele Grüße,
Stefan

**Comment by cabmac** [comment]
hmm...coursplay verwende ich schon ewig nicht mehr, das macht nur Probleme...nur autodrive..das ging aber mit autodrive auf jeden Fall...

**Comment by cabmac** [comment]
Moin, extrem seltsam...ich habe heute morgen mal kurz neu gestartet und auf einmal geht es wieder...k.A. warum das jetzt wieder....
nix fuer Ungut,

Schoene Gruesse,
Claudio
