### ISSUE TITLE
Italian translations for version 188 II

### ISSUE THREAD

**Issue by leonardo-scattola** [Mogli12/VehicleControlAddon#457]
Hi everyone, Stefan,
I have reviewed the Italian translations and checked a couple of small issues:
* I corrected some mixed cases in strings
* I rephrased some other strings to match the Italian syntax more closely

See [modDesc_l10n_it.zip](https://github.com/Mogli12/VehicleControlAddon/files/5480989/modDesc_l10n_it.zip)

Thank you,
Leonardo

**Comment by Mogli12** [comment]
Thanks Leonardo. I will add the file to the next version.

Best regards,
Stefan
