### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Blumi39** [Mogli12/VehicleControlAddon#458]
Hey....
Ich hab bei uns auf dem Server diesen Error in der game.log Error: mogliBase30Request received invalid NodeObject an was kann das liegen?komischerweise hab ich in der Spiellog diesen fehler nicht!

**Comment by Mogli12** [comment]
Hallo,
das passiert normalerweise, wenn das MultiPlayer-Coding in einem anderen Mod nicht korrekt ist. Dann werden auf einer Seite zu viele oder zu wenige Bytes aus der Nachricht genommen und bei nachfolgenden Mods kracht es dann.
Viele Grüße

**Comment by Mogli12** [comment]
Ich habe zu README.md einen kurzen Abschnitt hinzugefügt.
