### ISSUE TITLE
Suggestion: Hand throttle axis.

### ISSUE THREAD

**Issue by atledreier** [Mogli12/VehicleControlAddon#459]
I'd love to be able to use my slider axis for hand throttle.

I just discovered this mod, and it's amazing! Keep it up!

**Comment by Mogli12** [comment]
Isn't it an axis? I used it with the slider of my joystick but didn't test it for a longer time.

**Comment by atledreier** [comment]
There's three assignments that I can find for the hand throttle.

HT Mode, Raise HT and Lower HT.

They all seem to act like boolean inputs.

I may be misunderstanding the way they are supposed to be used of course.

**Comment by Mogli12** [comment]
Accelerate and brake or steer left/right are shown as separate inputs as well.
