### ISSUE TITLE
Adjust Camera Rotation Speed/Max Angle?

### ISSUE THREAD

**Issue by orkim** [Mogli12/VehicleControlAddon#462]
Hi Mogli!

Thanks for your work on the mod.  I just wanted to find out the ability to add camera rotation speed and maximum angle adjustments.  I'd like to slow the rotation down just a bit, and make it not rotate as far when the turn is held for a while.  I figured this might be something others might like to adjust as well, so it may be ideal to add to the configuration screen.

Let me know! Thanks!

**Comment by Mogli12** [comment]
Hi!

Did you already try to reduce the sensitivity? [screenshot](https://github.com/Mogli12/VehicleControlAddon/blob/master/Documents/fs19_screenshot_1_1__2.png)

Best regards,

**Comment by orkim** [comment]
Ah, this might be my issue.  I was under the assumption that this sensitivity was for the keyboard steering, not how quickly/far the head turn was.  I will try this and update the issue after.

Thanks

**Comment by orkim** [comment]
These controls either adjust the speed, or I've gotten use to the speed.  Either way we can close this issue.

Thanks!
