### ISSUE TITLE
Drehzahl beim Stufenlosem Getriebe.

### ISSUE THREAD

**Issue by hlwilly27** [Mogli12/VehicleControlAddon#463]
Hallo, könnte man beim stufenlosen Getriebe eine Drehzahlanstieg beim bremsen einfügen oder skripten. In Real steigt auch beim abbremsen mit der Motorbremse die Drehzahl. Im More Realistic mod vom LS17 war dies super gelöst.
Dadurch würde der Mod einen großen Schritt richtung realem Verhalten machen.

**Comment by Mogli12** [comment]
Hallo,

Probier bitte mal Build 192 aus.

Viele Grüße

***********************************************************************************
Build 192 increases the RPM if you brake above 3.6 kpm.

**Comment by tomy852** [comment]
richtig cool die neue Version, Danke Mogli12

**Comment by hlwilly27** [comment]
Hallo Mogli,

Danke für den schnellen Eintrag, fühlt sich schon besser an. Meiner Erfahrung nach sollte die Drehzahl aber höher steigen alls die 2000rpm. Würde sagen etwas zwischen 2200rpm und 2400rpm. Nett wäre der Eintrag vor allem auch noch bei der Wendeschaltung und beim verzögern mittels Tempomat. Dadurch würde die Motorbremse viel realistischer wirken. 

Danke für den tollen Mod und Beste Grüße

**Comment by Mogli12** [comment]
Hallo,

VCA berechnet die untere und obere Drehzahl mit fast Maximalleistung. Beim Bremsen wird nun die Drehzahl auf die Mitte dazwischen angehoben. Höher würde ich ungern gehen, da es sonst beim weiterfahren an Leistung fehlt.

Viele Grüße

VCA calculates the lower and upper max. power RPM. Braking increases the RPM to the middle between both values. I fear that a higher RPM will cause power loss.

**Comment by hlwilly27** [comment]
Hallo,

glaubst du nicht, dass es einen Versuch wert wäre die Drehzahl zu erhöhen? Bin der Meinung, dass ein größerer Drezahlbereich mehr akkustische Dynamik in die sonst recht monotone Soundkulisse bringen würde.

Beste Grüße

**Comment by hlwilly27** [comment]
Hallo,

was wurde in der neuesten version. Merke jetzt keine großen Unterschied.

Beste Grüße

**Comment by Mogli12** [comment]
Hallo,

ich habe die Drehzahl auf 80% der oberen Drehzahl für Maximalleistung erhöht. Der Unterschied zwischen der unteren und der oberen Drehzahl bei Maximalleistung ist aber meistens nicht sehr groß

Viele Grüße

**Comment by hlwilly27** [comment]
Hallo,

Hab jetzt mal testweise die self.vcaMaxPowerRpmL auf 1.4 gestellt, jetzt dreht der Vario mit IVT Getriebe bis 2100. Ok höhrt sich ganz gut an. Die Drehzahl sollte aber um einiges Schneller steigen, denn bis der Schlepper im Bremsvorgang auf Touren kommt steht er bereits.

Beste Grüße

**Comment by Mogli12** [comment]
vcaMaxPowerRpmL wird eigentlich für ganz andere Dinge benötigt. Ich würde das nicht machen. Und es hilft ja nicht, wenn es bei einem Traktor funktoiniert.

**Comment by hlwilly27** [comment]
Hallo,

ok ich nehme mir deinen rat zu herzen. Wäre es moglich die Drehzahl  aber schneller ansteigen zu lassen?

**Comment by Mogli12** [comment]
Nein

**Comment by hlwilly27** [comment]
OK, verstehe. Dann noch eine letzte bitte. Konntest du die drehzahlsteigung auch beim fahrtrichtungswechsel mittels Wendegetriebe einbauen?

**Comment by Mogli12** [comment]
Sowohl beim stufenlosen Getriebe, als auch bei (halb) geöffneter Kupplung, gibt VCA der Giants Engine einen Drehzahlbereich vor. Die Engine wählt daraus selber die Drehzahl aus. 

Wenn ich die untere Drehzahl nun anhebe, dann kann der Motor nicht niedriger drehen, auch wenn es im oberen Drehzahlbereich gar keine Leistung mehr gibt. Das Ergebnis ist, dass der Traktor gar nicht anfährt. Das geht auch nicht.
