### ISSUE TITLE
Gas und Bremse funktioniert nicht

### ISSUE THREAD

**Issue by nquix** [Mogli12/VehicleControlAddon#464]
Moin, 
ich habe mir die letzte Version des VCA heruntergeladen. Doch ich kann im Soiel manchmal kein Gas oder keine Bremse  betätigen. Hin und wieder funktioniert beides nicht. Dann starte ich mein Spiel neu und es funktioniert immer noch nicht. Ich habe Das VCA auch schon einmal aus dem Spiel entfernt. Ohne VCA ging es reibungslos. Ich glaube es hat etwas mit dem HuttleControl zutun.
LG Jonas

**Comment by Mogli12** [comment]
Ich kann es leider nicht nachvollziehen. Vielleicht ist es ein Mod-Konflikt?

**Comment by nquix** [comment]
Also, ich habe mal alle mods entfernt...leider geht es nicht. Nochmal eine genaue Erklärung:
Ich habe ein Spiel mit einigen Mods, einige von LS-Portal und der größere Teil von Modhub. Ich spiele nun schon sehr lange auf diesem Spielstand, mit dem VCA. Doch das Problem ist folgendes: Wenn ich das Spiel starte und mich in ein Fahrzeug setze, kann ich es machmal nicht bewegen. Wenn ich das Spiel dann neu starte, kann ich manchmal nicht bremsen (Der Traktor fährt aber hät nur durch ausrollen an) oder ich kann weder Gaas noch BRemse betätigen. Doch jetzt das Highlight...im Multiplayer kann ein Freund Problemlos fahren, nur ich habe das Problem mit Gas und Bremsen. Ich hoffe du kannnst dich in die Lage hineinversetzen.
LG

**Comment by Mogli12** [comment]
Hallo,

es steht doch hier in der Beschreibung, was ich für eine Problembeschreibung benötige, nämlich Screenshot und log.txt.

Danke

**Comment by nquix** [comment]
@Mogli12 Was genau soll ich denn aus der Log schicken

**Comment by Mogli12** [comment]
Halten wir fest: das Problem lässt sich nicht reproduzieren, Screenshot und log.txt sind nicht vorhanden. Daher habe ich keine Ahnung, wo das Problem überhaupt liegen könnte und kann daher auch nicht verbessern oder korrigieren.

**Comment by nquix** [comment]
Nichts halten wir fest...in der Liga stehen tausende Dinge und ich habe keine Ahnung was ich davon fotografieren soll...danke für die Hilfe hahaha du nicht vorhanden ist und danke das ich wegen deinem Mod nicht mehr vernünftig LS zocken kann

**Comment by MBTrac366** [comment]
Es wurde nie von nem Ausschnitt der Log gesprochen, die ganze Log wird benötigt, alles, vom Anfang bis zum Ende. Dazu sollst du ein Screenshot posten, wo man sieht, was bei dir passiert.
Ohne diese Informationen kann man einfach nicht helfen. 

Grüße
