### ISSUE TITLE
problem with internal view of vehicles

### ISSUE THREAD

**Issue by gimondino** [Mogli12/VehicleControlAddon#465]
hi Mogli12 I have a problem with the vehicle control addon since I updated the game to version 1.7.1 it no longer makes me use the internal view if I remove the mod everything works perfectly

**Comment by Mogli12** [comment]
I have no such problems. Did you reset your inputBinding.xml? Maybe it is a mod conflict?

**Comment by gimondino** [comment]
I removed all the mods and left only the vca and the same does not work

**Comment by Mogli12** [comment]
Please try die delete your inputBinding.xml If the problem persists I propose to attach a ascreen shot and the log.txt (Gist!).
