### ISSUE TITLE
Weird behaviour on dedi server

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#466]
Hallo Stefan,
ich habe die Build 193 auf unseren Dedi Server geladen und habe dort jetzt ein merkwürdiges Verhalten.
Im Spiel ruckelt es beim Fahren und der Traktor fährt über 40 km/h, obwohl er nur 35 km/h kann.
Dabei verliert er auch irgendwie die Bodenhaftung.
Bei VCA ist dabei alles ausgeschaltet.
In der Log sind keine Fehler zu finden. Ich bin dann zurück auf Build 190 und der Effekt ist weg.

Ich weiß, das ist keine perfekte Fehlerbeschreibung aber mehr bekomme ich nicht raus...

Vielen Dank für deine Arbeit
Willi

**Comment by Mogli12** [comment]
Hallo,

bitte Screen shot und log.txt von client und server (auf Gist!) anhängen.

Danke

**Comment by Williwillswisse** [comment]
Hallo Stefan,
ich war noch mal auf dem Dedi (leider nur alleine)
Das starke Ruckeln und Rutschen der Fahrzeuge trat alleine jetzt nicht auf.
Das Bild mit dem roten Traktor zeigt bei allen VCA Optionen ausgeschaltet eine Geschwindigkeit von 40 km/h. Normal fährt er nur 35 km/h (Ich hatte auch schon mal fast 50 km/h).
Die anderen beiden Bilder zeigen einen Traktor mit 32 km/h (VCA alles aus) und den selben Traktor mit Getriebe ein. Mit Getriebe fährt er dann die erwarteten 35 km/h. 

Ich hoffe die angehängten Dateien helfen.
Wenn ich noch was testen soll einfach Bescheid geben.

[ServerLog.txt](https://github.com/Mogli12/VehicleControlAddon/files/5577709/ServerLog.txt)
[ClientLog.txt](https://github.com/Mogli12/VehicleControlAddon/files/5577710/ClientLog.txt)
![fsScreen_2020_11_21_12_21_06](https://user-images.githubusercontent.com/47098121/99878716-a2a44580-2c07-11eb-9d8c-afdd7c737953.png)
![fsScreen_2020_11_21_12_29_39](https://user-images.githubusercontent.com/47098121/99878722-acc64400-2c07-11eb-86fb-cf746d3dc3a0.png)
![fsScreen_2020_11_21_12_31_28](https://user-images.githubusercontent.com/47098121/99878735-b780d900-2c07-11eb-87bb-72d823f3aa1e.png)

**Comment by Mogli12** [comment]
Hallo,

ich bin mir selber nicht 100% sicher, wann welche Änderung am Fahrzeug von VCA aktiviert wird. VCA hebt die Maximaldrehzahl an. Das sollte aber nur aktiv sein, wenn ein Getriebe aktiviert wurde. Es gibt oberhalb der Maximaldrehzahl noch ein paar 100 Umdrehungen mit 0 Leistung. Damit kann das Fahrzeug bergab schneller rollen. Ich fand die Begrenzung auf 2200 U/min über eine harte Geschwindigkeitsbegrenzung nicht so toll.

Vielleicht erklärt das das Verhalten?

Viele Grüße
