### ISSUE TITLE
shuttle control funktioniert mit gearbox nicht

### ISSUE THREAD

**Issue by Dagelkop** [Mogli12/VehicleControlAddon#468]
Hallo,
habe jetzt schon eine längere Zeit nicht mehr mit VCA gespielt und wollte nun den neuesten Patch verwenden.
Dabei fiel mir auf, dass wenn die Gearbox auf "off" ist die Shuttlesteuerung funktioniert, doch sobald man ein Getriebe auswählt, funktioniert die Fahrtrichtungsauswahl nicht mehr.

**Comment by Mogli12** [comment]
Ich habe keine Lust mehr auf Issues ohne Screenshot, log.txt oder detaillierte Beschreibung.
