### ISSUE TITLE
shuttle control funktioniert mit aktivierten Getriebe nicht (hoffentlich besser erklärt ;))

### ISSUE THREAD

**Issue by Dagelkop** [Mogli12/VehicleControlAddon#470]
Hallo nochmals,
Nachdem meine Beschreibung zuvor nicht ausreichte, habe ich mir die Mühe gemacht, das Problem so genau wie ich finde möglich zu beschreiben.

Zunächst habe ich den Mod ohne weitere Modifikationen auf einer Standard-Map gestartet.
![mods](https://user-images.githubusercontent.com/64906803/99991157-f738f380-2db4-11eb-9ad7-c91c8e23ea20.png)

Wenn man nun in ein Fahrzeug einsteigt, Shuttle Control eingeschaltet und Getriebe auf IVT, 4x4, … (alle außer "off") ist, lässt sich mit der Leertaste (Taster zur Steuerung der Fahrtrichtung) die Fahrtrichtung nicht ändern. Dies funktioniert nur, wenn bei dem Punkt Getriebe auf "off" gestellt ist.

Zur besseren Verdeutlichung habe ich ein Video gemacht, in dem ich das Problem zeige:
https://www.youtube.com/watch?v=JsoOiW-srDE

Hier ist die Log:
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5584478/log.txt)

**Comment by Mogli12** [comment]
Ich habe keine Ahnung, vielleicht ist bei Dir die inputBinding.xml kaputt. Bei mir und vielen anderen Usern funktioniert es. Glaubst Du ernsthaft, ich würde her eine Version hochladen, bei der Shuttle-Control grundsätzlich nicht für ausgewählte Getriebe funktionieren würde? Und keiner außer Dir hätte es gemerkt?

**Comment by Dagelkop** [comment]
Natürlich glaube ich das nicht, mich hat es nur gewundert, dass der Fehler erst jetzt kommt, da es ja früher (vor ca. 6 Monaten) noch funktioniert hat. Ich lösche mal die xml und melde mich dann wieder.
