### ISSUE TITLE
Can't connect to Dedi Server

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#471]
Hallo Stefan,
erst einmal ein großes Dankeschön dafür, dass du VCA noch weiter entwickelst.
Ich habe gerade die Build 194 auf meinen Dedi-Server hochgeladen.
Wenn ich mich mit dem Spiel verbinden möchte bleibt der Client bei 28% stehen und ich bekomme Fehler im Log.

[VCA-Client-log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5634900/VCA-Client-log.txt)
[VCA-Server-log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5634901/VCA-Server-log.txt)

**Comment by Mogli12** [comment]
Hi,

Build 195 should fix the client-server-communication.

Regards, Stefan
