### ISSUE TITLE
Danke. 

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#472]
Ich möchte hier auf diesen Weg nochmals Danke sagen und danke das du hier wieder aufgemacht hast. Ich war echt geschockt die letzten Tage als auf einmal hier nichts mehr ging und kann dich auch gut verstehen das es frustrierend gewesen sein muss aber ich hoffe das du weiter machst. 

Gibt es eigentlich die Möglichkeit etwas zu spenden für deine Arbeit? 

VG Thorsten

**Comment by Mogli12** [comment]
Hallo Thorsten,

Spenden benötige ich keine. Auch die "Einnahmen" aus ModHub lasse ich automatisch an eine gemeinnützige Organisation spenden. 

Viele Grüße.
Stefan
