### ISSUE TITLE
Allrad Problem

### ISSUE THREAD

**Issue by marcelr901** [Mogli12/VehicleControlAddon#473]
Hallo Mogli,

Ich habe seit der neusten Version folgendes Problem. Der Allrad lässt sich laut hud anzeige zwar ein- bzw ausschalten, ist allerdings beim fahren IMMER eingeschaltet. Egal ob allrad an oder aus. Man sieht in der außenperspektive das trotz deaktiviertem allrad die vorderräder mit antreiben. Habe schon viele einstellungen ausprobiert (voreilung ein/aus, getriebewechsel ect.) hatte zuvor build 185, da lief alles glatt. Nutze parallel noch den REA mod. 

Vielleicht kennt jemand eine lösung :)

**Comment by Mogli12** [comment]
Bitte lies doch die doch den Abschnitt "Developer version" der README.md. Sie ist hier sichtbar und kaum zu übersehen.

Welche Version nutzt Du? Screenshot? Wie viel Schlupf zeigt REA an? Welches Fahrzeug?

**Comment by marcelr901** [comment]
Entschuldigung für den Fehler meinerseits.

9.1.9.6 VehicleControlAddon
1.4.0.0 REA

REA zeigt auf dem Feld mit gezogenem Kalkstreuer zwischen 30 und 50% Schlupf an. Egal ob Allrad zugeschaltet oder aus. Die Fahrzeuge verhalten sich was den Allrad betrifft wie im original Game. Sprich Allrad dauerhaft aktiv

Habe es mit dem Fendt 700/800, Fendt Vario 800 S4 und dem Fendt 900 Vario Gen6 versucht.

Ich hänge die Log mal an. 
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5646191/log.txt)

Danke für deine Antwort und ein schönes Wochenende

Gruß

**Comment by Mogli12** [comment]
Screenshot?

**Comment by marcelr901** [comment]
Wovon hättest du denn gerne einen screenshot?
