### ISSUE TITLE
Arbeitsbreite wird nicht mehr gespeichert

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/VehicleControlAddon#475]
Wie der Titel schon sagt, habe auf die latest aktualisiert, nun wird die eingestellte Arbeitsbreite nicht mehr gespeichert, ist immer bei 0 nach jedem Neustart des Spiels. Ist das so beabsichtigt?

**Comment by Mogli12** [comment]
Es steht doch auf der [Startseite](https://github.com/Mogli12/VehicleControlAddon) welche Infos in ein Issue gehören:

- tell us the version number
- only use the vehicles necessary, not 10 other ones at a time
- which vehicles are involved, what is the intended action?
- Post! The! Log! to Gist or PasteBin

Und ein Bild sagt meistens mehr als 1000 Worte.

**Comment by iljarogoff** [comment]
Mich hätte nur interessiert, ob das so beabsichtigt ist. Wenn ja, dann ok. Wenn nicht, kann man ein echtes Issue draus machen. Und dann gebe ich auch die Infos mit rein.

**Comment by Mogli12** [comment]
Das ist nicht beabsichtigt. Aber wahrscheinlich verwendest Du die veraltete Version 195.
