### ISSUE TITLE
Raster links/rechts halten

### ISSUE THREAD

**Issue by Sacred-Shadow** [Mogli12/VehicleControlAddon#477]
Man kann das Raster ja per Tastendruck verschieben - entweder links o. rechts. 
Blöd ist nur, dass man immer wieder drücken muss.

Hier wärs cool wenn VCA da anders reagiert.
Wenn die Taste gehalten wird, dass er nach ein paar Sekunden anfängt weiter das Raster in die Richtung zu verschieben. 
Aktuell drückt man sich nen Wolf.

**Comment by Mogli12** [comment]
Gelöst mit Buidl 335

**Comment by Sacred-Shadow** [comment]
Super, danke dir.  :D Dann bin ich mal gespannt, wann das Update im Modhub kommt. :)
