### ISSUE TITLE
Erklärung zum Getriebe

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#478]
Hallo Mogli,
könntest du mal bitte kurz erklären welche Einstellungen "Automatik" bewirkt und was die Unterschiede bei "Automatischer Kupplung" sind. Zusätzlich gibt es ja bei dem eigenen Getriebe auch zwei Einstellungen einmal für die "Automatische Gänge" und einmal für die "Automatische Gruppen".  Ist es beabsichtigt das es die Strömungskupplung nicht mehr gibt? War ein cooles Feature wie ich finde ;-).

Und noch eine Frage dazu ist es möglich ein Getriebe zu bauen was manuell also mit betätigen der Kupplung die Gänge schaltet aber automatisch ohne die Kupplung zu treten die Gruppen schaltet kann?

Version vom VCA 9.1.9.7
Zusätzlich nutze ich ein Logitech G27 mit H-Shifter

VG Thorsten

![fsScreen_2020_12_09_21_11_20](https://user-images.githubusercontent.com/47506966/101682205-9d4a5600-3a63-11eb-815e-bb15e4c104f1.png)

![fsScreen_2020_12_09_21_11_14](https://user-images.githubusercontent.com/47506966/101682132-873c9580-3a63-11eb-8e23-b27c31821467.png)

**Comment by Mogli12** [comment]
Hallo,

Unter der Einstellung Automatik steuert man, ob das automatische Schalten grundsätzlich ein- oder ausgeschaltet ist. Beim eigenen Getriebe kann man dann auswählen, ob mit eingeschalteter Automatik die Gänge, Grüppen oder Beides geschaltet wird. Wenn dort aber zweimal "Aus" einstellt, dann ist die Einstellung für Automatik nutzlos.

Automatik kann man auch direkt über eine Teste ein- und ausschalten: Strg-Ü.

Viele Grüße

**Comment by Shreklich** [comment]
Danke schon mal dafür ich werde dann mal ein paar Einstellungen ausprobieren.
Wird es den die Strömungskupplung bei der manuellen Kupplung nochmal geben? 
Viele Grüße

**Comment by hemker500** [comment]
Hallo zusammen
Wollte jetzt kein extra issue auf machen da es nur eine Frage ist.
Und zwar zum Vario Getriebe ist das gewollt das beim runter bremsen die Drehzahl anfangs wieder hoch steigt.

Version:9.1.9.6

Grüße

**Comment by Mogli12** [comment]
Hallo,

Zum Anheben der Drehzahl beim Bremsen -> #463 

Die Strömungskupplung ist in VCA nur eine etwas andere Steuerung der Kupplungssimulation. Auch im Automatikmodus geht noch das Kupplungspedal. Was genau soll darüber hinaus die manuelle Strömungskupplung bringen?

Viele Grüße

**Comment by Shreklich** [comment]
Hallo
Mit der Strömungskupplung oder auch Turbokupplung ist es möglich auf null zu bremsen ohne zu kuppeln ist zb beim Case 1455 so. Bzw man kann den 1.Gang einlegen und auf der Bremse stehen und die Kupplung loslassen und wenn man dann die Bremse löst und Gas gibt fährt der Schlepper los. 
MfG Thorsten.

**Comment by Mogli12** [comment]
Hallo,
Ja, genau das geht doch mit der Turbo-Kupplung. Sie öffnet automatisch. Was fehlt noch? Das "Verbot" den Gang ohne getretene Kupplung zu wechseln?
Viele Grüße

**Comment by Shreklich** [comment]
Wenn man so ein Verbot noch zusätzlich zu den bestehenden Modis wählen könnte wäre das schon cool. Soll aber bitte nur umgesetzt werden wenn es dir nicht zu viel Arbeit macht. Ich selber verstehe leider nichts vom Skripten und bin echt erstaunt was du immer wieder dazu packst. 
Danke dafür.

**Comment by Shreklich** [comment]
Danke sehr funktioniert sehr schön. Man kann zwar den ersten Gang ohne Kupplung zu treten schalten aber das ist denk ich hab so wild, Nur zurückschalten also zB. vom 2ten in den 1ten Gang muss man dann wieder kuppeln.

**Comment by Mogli12** [comment]
Ich denke, dass Du beim Einlegen des ersten Gangs noch in Neutral bist.

**Comment by Shreklich** [comment]
Ja genauso ist es von Neutral in den 1ten Gang.
