### ISSUE TITLE
Teleskoplader kann den Arm nicht ausfahren

### ISSUE THREAD

**Issue by ChilliCw** [Mogli12/VehicleControlAddon#479]
Servus,

Wenn ich VCA benutze, hab ich keine Steuerungsmöglichkeit beim Teleskoplader um den Arm ein und aus zu fahren. Im Hilfefenster erscheint auch keine Anzeige für die Maus. Wenn ich die Tastenbelegung ändere, dann funktioniert es solange, bis ich ein Anbaugerät anschließe oder abhänge. Getestet wurde mit leerem Mod Ordner, LOG error frei.

Danke schonmal im Voraus

Gruß

**Comment by Mogli12** [comment]
Ich kann euch bei Problemen mit eurer Tastaturbelegung nicht helfen! Es steht doch hier auf der Startseite von VehicleControlAddon bereits:

> It seems that many players have problems with thier inpubBindings. Just look at issues #470, #468, # 464, ... I think this is a general problem in the handling of input bindings in FS19. Please try to delete your inputBinding.xml.
