### ISSUE TITLE
Vario Getriebe

### ISSUE THREAD

**Issue by Einfllslos** [Mogli12/VehicleControlAddon#480]
Moije,
ich hab heute die neue Funktion mit dem Vario Getriebe ausgetestet. 
Den Ansatz finde ich echt spitze und es macht schon wirklich Spaß damit etwas rumzuprobieren. 
In der Stufe "low" geht der Traktor im Standgas bei niedrigen Geschwindigkeiten allerdings aus bzw. droht zu stoppen, unterdreht und geht dann aus. Ich bin selbst noch keinen Vario gefahren, aber ich denke, vor allem bei solch niedrigen Übersetzungen, sollte er nicht aus gehen. 
Weiterhin muss ich sagen, dass mir jetzt im Handgas Modus eine Drehzahlanzeige fehlt. Eine kleine digitale Anzeige im HUD wäre super, aber selbst wenn es so wäre wie vorher wäre ich schon zufrieden.
In Kombination mit Vario und Handgas kann sich die Drehzahl irgendwie nicht richtig stabilisieren, sie springt immer hin und her.
Ohne Handgas Modus, aber im Zapfwellenbetrieb das gleiche.
Vielleicht könnte man auch noch eine Option im Menü oder eine Taste fürs An- und Ausschalten des TMS einfügen.
Auf jeden Fall weiter machen, deine Arbeit ist super!

**Comment by Mogli12** [comment]
Hallo,
Welche Kupplung hast Du eingestellt? Mach am besten mal einen Screenshot von den Einstellungen.
Danke

**Comment by Einfllslos** [comment]
Hallo, 
zuerst hatte ich es wie auf dem Bild zu sehen. 
![fsScreen_2020_12_16_16_44_39](https://user-images.githubusercontent.com/36106427/102371406-72f61c80-3fbe-11eb-9b16-0622d353c25f.png)

Jetzt habe ich es auch mal mit Turbokupplung(schnell) probiert. In Geschwindigkeiten unter 4km/h geht er nicht mehr aus, bleibt jedoch stehen wenn man kein Gas gibt. Bei höheren Geschwindigkeiten kann man hingegen im Standgas fahren.

**Comment by Mogli12** [comment]
Du kannst Geschwindigkeit Startgang noch reduzieren. Auch im manuellen Vario-Getriebe reduziert der Traktor die Übersetzung beim Bremsen, aber nicht niedriger als 20 km/h (bei Nenndrehzahl).

**Comment by Einfllslos** [comment]
In der build 203 geht er jetzt mit Turbo(schnell) auch aus, lediglich bei Turbo(langsam) bleibt er an. 
Immer wenn man die Geschwindigkeit auf unter 4km/h stellt.

**Comment by Einfllslos** [comment]
Der Fehler saß wie vielmals vor dem Bildschirm...
Ich hatte die niedrige Bremskraft zu hoch eingestellt. Jetzt bei 20% funktioniert alles so wie es soll. 
Die Drehzahl vom Handgas im F1 Hud finde ich auch gut.
