### ISSUE TITLE
Fehler in der Log

### ISSUE THREAD

**Issue by Falkewei** [Mogli12/VehicleControlAddon#482]
Hallo
Wir spielen auf dem dem Server mit dem neuen DLC. Seid dem erhalten wir folgenden Fehler 

Warning: mogliBase30Request received invalid NodeObject
 Warning: mogliBase30Event received invalid NodeObject
vehicleControlAddon; vcaIsEnteredMP; true
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
Error: Running LUA method 'packetReceived'.

Kann damit jemand etwas anfangen? Falls weiteres gewünscht, bitte auf dem DC vom LS Mapping Team oder per privat PN.

Wünsche allen eine schöne Weihnachtszeit.

[LSMT] Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

das habe ich doch schon auf der Startseite erwähnt. Vermutlich gibt es einen anderen Mod, dessen MP-Coding nicht korrekt ist. Das erzeugt dann solche Fehler.

Viele Grüße,
Stefan
