### ISSUE TITLE
RPM goes high when braking

### ISSUE THREAD

**Issue by 2Nems** [Mogli12/VehicleControlAddon#483]
The rpm is going up when you brake. I only tested with vario and ivt. The rpm is also high when you braked and the tractor Already Stands still. You Need to keep braking to get the rpm down. Even when the tractor already stands still

**Comment by 2Nems** [comment]
Ah auch deutsch sehe ich gerade:) ja wenn ich Bremse geht die Drehzahl nicht runter sondern geht erst noch hoch und bleibt solange oben, bis der Trecker steht. Bzw. man muss die Bremse noch länger drücken, selbst wenn der Trecker schon steht, um die Drehzahl runter zubekommen. Und das habe ich nicht, wenn ich das Getriebe auf off stelle. Also beim Vario und IVT ist es aufjedenfall. Da habe ich das getestet.

**Comment by Mogli12** [comment]
Hi,

Please check #463. The RPM is increased on purpose. 

Best regards,
Stefan

**Comment by 2Nems** [comment]
Achso. Also ausstellen kann man das nicht?

**Comment by Mogli12** [comment]
Leider nein, das ist nicht schaltbar.

**Comment by 2Nems** [comment]
Ok. Trotzdem danke
