### ISSUE TITLE
Tipp- / Kopierfehler in der vehicleControlAddonTransmissions.xml

### ISSUE THREAD

**Issue by MBTrac366** [Mogli12/VehicleControlAddon#484]
Hallo, 

ich habe mich heute mal mit der verschiedenen Transmissions befasst um eine eigene zu bauen, dabei sind mir in der vehicleControlAddonTransmissions.xml  der aktuellen VCA-Version ein paar Tippfehler aufgefallen. 
In den Zeilen: 832, 887, 895, 920 und 942 steht autoRanges´ statt autoRanges, dadurch wird der Parameter nicht richtig übergeben und die Getriebe schalten die Gruppen dennoch autmatisch, obwohl es auf "false" steht.
![Bild_2020-12-22_213540](https://user-images.githubusercontent.com/71411042/102930897-a2fd5e00-449d-11eb-8c9f-375b08c9bd69.png)

Grüße

**Comment by Mogli12** [comment]
Danke für den Hinweis. Irgendwie schleicht sich der Fehler immer wieder ein. Es sollte mit Beta 301 behoben sein.
