### ISSUE TITLE
Eigenes Getriebe funktioniert nicht mehr einzustellen

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#485]
Hallo Mogli,
zuallererst muss ich dir sagen die neue Kupplung ist richtig gut und gefällt mir sehr danke schonmal dafür. 

Mir ist aber leider heute ein Fehler aufgefallen und zwar wollte ich ein eigenes Getriebe einstellen. Doch sobald man da die Ganganzahl bzw die Gruppenanzahl ändern will stellt sich die Getriebeart automatisch zurück und man kann nicht mehr fahren. In der Log werden dann auch Errors angezeigt. Auf dem ersten Bilder sieht man was ich eingestellt habe, auf dem zweiten Bild wollte ich die Ganganzahl von 5 auf 4 ändern und die Gruppe von 3 auf 2 danach kam der Fehler. Ich habe jetzt nicht versucht das einzeln zu verstellen also entweder Gänge oder Gruppen. Kann es aber gerne nochmal testen wenn es gebraucht wird. Habe für den Test alle Mods bis auf die DLC´s aus dem Modordner genommen um Konflikte auszuschliessen.

Hier meine Log Datei: [log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5736598/log.txt)

![fsScreen_2020_12_23_19_21_44](https://user-images.githubusercontent.com/47506966/103026873-1a41f900-4555-11eb-86a6-197e2bdc7fae.png)
![fsScreen_2020_12_23_19_22_04](https://user-images.githubusercontent.com/47506966/103026874-1ada8f80-4555-11eb-8a40-116b1e5cb583.png)
![fsScreen_2020_12_23_19_22_32](https://user-images.githubusercontent.com/47506966/103026877-1b732600-4555-11eb-8941-2b9d4354842a.png)

**Comment by Shreklich** [comment]
Danke sehr sollte wieder funktionieren. Konnte es aber bis jetzt nur kurz testen.

Ich habe da noch eine Kleinigkeit, ich nutze deine Mod auf einem Server und da ist standartmäßig das Getriebe ausgeschaltet. Wenn das so eingestellt ist dann hat man den Drehzahlanzeiger fürs Standgas unten links im Bild. Denke mal das es so nicht gewollt ist. 

Nochmals Danke für deine Mühe, deine Zeit und diese geile Mod.
Lieben Gruß Thorsten 

![fsScreen_2020_12_23_21_43_54](https://user-images.githubusercontent.com/47506966/103035987-e7a1fb80-4568-11eb-9ce5-2188a689a1ee.png)
![fsScreen_2020_12_23_21_44_36](https://user-images.githubusercontent.com/47506966/103035989-e83a9200-4568-11eb-8240-0027439c0624.png)
![fsScreen_2020_12_23_21_44_53](https://user-images.githubusercontent.com/47506966/103035991-e8d32880-4568-11eb-9a9b-800e836d3651.png)

**Comment by Williwillswisse** [comment]
Der rote Pfeil taucht auch im SP an der Stelle auf.

**Comment by Mogli12** [comment]
Bei mir ist der rote Pfeil nicht da.

**Comment by Shreklich** [comment]
Ich prüfe das ganze nochmal. Evtl liegt es ja daran wenn man die globalen Einstellungen auf Getriebe OFF festlegt.

**Comment by Williwillswisse** [comment]
Der Pfeil erscheint, wenn man in den globalen Einstellungen das Getriebe auf 0 (keines) setzt. Schalte ich bei dem Fahrzeug einmal ein Getriebe ein geht der Pfeil weg und kommt auch nicht wieder wenn ich es dann wieder ausschalte.

**Comment by Shreklich** [comment]
Ja gerade getestet so wie es @Williwillswisse gemacht hat ist es auch. Hab die selbe Einstellung. Danke für den Hinweis.

**Comment by Shreklich** [comment]
Danke sehr für den Fix.
