### ISSUE TITLE
Winter LUA

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#489]
Hallo Stefan,
ich bekomme immer einen Fehler:

2020-12-24 13:03 Wishes: Dieser AIVE und VCA Benutzer wünscht dem Modder ein frohes Fest und einen guten Rutsch ins neue Jahr.

Kann ich da was machen ??
Vielen Dank für deine tollen Mods.

Gruß Willi

PS: Wenn du Lust hast streamen wir gerade einen 10 Tage Dauereinsatz von AIVE in Vollautomatisierung.
Wenn du Lust hast kannst du ja mal reinschauen:
https://www.twitch.tv/mariohirschfeld

**Comment by Shreklich** [comment]
Auch von mir ein frohes Weihnachtsfest und bleibt gesund. Schöne Idee hast du da gehabt Willi 😁
Viele Grüße Thorsten
