### ISSUE TITLE
Cooperation with ProSeed

### ISSUE THREAD

**Issue by nesingho** [Mogli12/VehicleControlAddon#490]
Quote from my inquiry at ProSeed:

https://github.com/stijnwop/proSeed/issues/22#issuecomment-750426114

> In auto mode, PS retrieves current track data from GS, unfortunately VCA does not save such data so that it can be loaded in this mode. You would need to do another counting function specifically for VCA (it is in semi-automatic mode, but uses data generated by PS), maybe if the author of the VCA added such data it could be used in automatic mode.

@Mogli12 : Is it possible?

Thanks

Nes

**Comment by Mogli12** [comment]
Hi Nes,

Please try build 303.

Regards,
Stefan

**Comment by nesingho** [comment]
Hi Stefan,

I have tested build 305 -> works great with ProSeed!

Thank you very much!

Nes
