### ISSUE TITLE
Gruppengetriebe

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Mogli12/VehicleControlAddon#491]
Hallo, hab mal ganze Zeit Gedanken gemacht und wollte euch Fragen. Wie wärs Gruppengetriebe als H-Schaltung sowie MB-Trac? Es gibt im Moment nur Gruppe Hoch und runter.. wie wärs mit Gruppe 1-4 wie normale Getriebe 8 Gänge mit R? Hab mitterlerweile 2 H-Stifter(6gang mit R und einmal 4 Gang für Gruppen)

Wäre super wenn gruppen auch als h-Schaltung nutzen können..

Gruß Chris W.

**Comment by Mogli12** [comment]
Hallo,

sorry, aber das ist nicht geplant. Eventuell gibt es so etwas in Real Manual Transmission. 

Viele Grüße
