### ISSUE TITLE
IVT

### ISSUE THREAD

**Issue by Mike-Juli** [Mogli12/VehicleControlAddon#492]
Servus . danke für deine tolle Arbeit.

ich hätte eine Frage, kann man die Drehzahlerhöhung beim Bremsen selber in der xml reduzieren (bzw. deaktivieren) ?

und, dei Drehzahlanzeige an sich war ja mega mit den Gaints Hud ... Schade, dass das nicht mehr ist.... oder sollte es noch sein?

PS.
Frohe Weihnachten!

**Comment by Mogli12** [comment]
Hallo

Es ist doch ohne Probleme möglich, das Getriebe auf off zu stellen und alle anderen Features von VCA zu verwenden.

Viele Grüße

**Comment by Mike-Juli** [comment]
Danke für dier schnelle Rückmeldung...

Stimmt habe ich vergessen dass, das auch geht.

Nochmals Danke
und
Schöne Feiertage

**Comment by Mogli12** [comment]
-> #493
