### ISSUE TITLE
VCA Bremssound

### ISSUE THREAD

**Issue by KlausKlausen66** [Mogli12/VehicleControlAddon#493]
Moin moin lieber Stefan,

der VCA-Mod ist wirklich eine super Sache, ich spielte sehr gern damit LS19
Seit dem du auf Wunsch den Gas-Sound so eingestellt hast, dass beim Bremsen dieser hoch dreht, macht es mir (und vielen anderen) keinen Spaß mehr, damit zu fahren.
Es gibt keinen Trecker in der Realität, wo das Gas so dermaßen beim Bremsen in die Höhe geht und so lange auf Vollgas bleibt, bis der Traktor steht.
Ich finde es toll von dir, dass du auf Wünsche diesbezüglich eingehst und das dann auch umsetzt, leider sind mit dieser Einstellung sehr viele nicht einverstanden.

Nun meine Frage:
Gibt es die Möglichkeit, einen VCA ohne diese Eigenschaft beim Bremsen parallel zur Verfügung zu stellen, oder kann man eventuell selber dieses in deinem aktuellen VCA rückgängig machen - wenn ja, wie?

Ich und viele andere Nutzer deines genialen VCA`s würden uns sehr freuen, wenn wir wieder bremsen und der Gassound auch mit herunter geht.

Über Antwort würde ich mich sehr freuen und wünsche dir noch eine ruhige, gesunde Rest-Weihnachtszeit.

LG

**Comment by Mogli12** [comment]
Hallo,

Es ist doch ohne Probleme möglich,  das Getriebe auf off zu stellen und alle anderen Features von VCA zu verwenden. 

Viele Grüße

**Comment by Mogli12** [comment]
https://www.landtreff.de/stufenlos-ohne-motorbremse-t78927.html

**Comment by KlausKlausen66** [comment]
Danke dir Stefan, für die Antworten und den Links.
Das Traktoren so etwas nicht haben, bezog sich auf den VCA, nicht, das es so etwas nicht in Real gibt. Im Video kann man es ja sehen/hören, dass es nicht so krass und störend rüberkommt als im Spiel. Er ist ja mit dem Fahrhebel unterwegs, nicht mit der Nutzung der Pedalen. Fährt er da mit Tempomat und/oder Handgas?

Vielleicht sollte diese Funktion der Bremse im VCA zuschaltbar sein (wenn es überhaupt möglich ist) oder ein Anbaugerät mit dieser Funktion...?

Der Tipp von dir, lieber Stefan, den VCA auf off zu stellen, würde mich/uns dazu zwingen, den REA-Mod zu deaktivieren oder in diesem den Rollwiderstand auf Null zu setzen, da im off der Trecker fast sofort stehen bleibt, wenn man im Pedalbetrieb vom Gas geht. Das wäre schade.

LG

**Comment by Mogli12** [comment]
Hallo,

man muss nicht VCA komplett ausstellen. Man kann einfach das Getriebe auf "off" stellen. Der Rest von VCA funktioniert dann immer noch.

Viele Grüße

**Comment by Mogli12** [comment]
Hallo,

Mit Build 303 wird beim normalen Bremsen die Drehzahl nicht angehoben. Aber beim Bremsen über den Tempomaten oder über KeepSpeed (=Fahrhebel) wird angehoben.

Viele Grüße
