### ISSUE TITLE
Option to Hide Keys in F1 Help Menu

### ISSUE THREAD

**Issue by SavageMkII** [Mogli12/VehicleControlAddon#494]
Hello Mogli, first I would like to thank you for this mod, and for continuing to improve it! I'm glad for you to have a new version on ModHub!

I have a suggestion for an improvement(Unless it is already there, and I just can't find it). Would you be able to create a config option to hide the keys in the F1 help menu?

Regards,

Adam

**Comment by Mogli12** [comment]
Hi Adam,

Most VCA keys have lowest priority and are only visible if there are no other keys. I would not like to add another option for this. There are already too many options.

Regards,
Stefan

**Comment by SavageMkII** [comment]
Ok, I understand. Many thanks for your response!
