### ISSUE TITLE
Problem mit dem Schaltschema 

### ISSUE THREAD

**Issue by alfsjan272** [Mogli12/VehicleControlAddon#495]
Hy,
erstmal danke für den super Mod.
ICh versuche das 6G, 1R, LH zu benutzen allerdings kann ich die Gruppen und Gänge nicht gezielt wählen. Gibt es eine Möglichkeit 2 Gruppen plus Rückwärtsgang gezielt zu schalten?

LG Jan

**Comment by Shreklich** [comment]
Also ich nutze diese Getriebeart schon lange in Verbindung mit einem H Shifter der 6 Gänge hat damit kannst du natürlich von Gang 1-6 schalten Plus den Rückwärtsgang. Damit ist es dann auch möglich zb in der erste Gruppe im 3Gang anzufahren falls es gewünscht ist. Die Gruppe kannst du dir dann über eine seperate Taste belegen. Du musst natürlich die Gänge in der Tastenbelegung zuweisen sonst funktioniert das nicht.
Hoffe ich konnte dir damit helfen.
VG Thorsten

**Comment by alfsjan272** [comment]
Ich hab es mit einer 2x6 Schaltung versucht und er wählt aus beiden Gruppen und wenn ich eine Gruppe auswähle und dann einen Gang einlege springt es zurück in den komischen Misch.

**Comment by Shreklich** [comment]
Das Problem hatte ich auch ich nutze dafür einfach den Splitter dann geht's. So kannst du zwischen der ersten und zweiten Gruppe wechseln. Keine Ahnung warum es beim 2x6 Getriebe so ist.

**Comment by alfsjan272** [comment]
Ich weiß nicht wieso aber wenn ich es über die seqeuntiellen einstellungen mache funktioniert es. wenn ich es über die H Schaltung nicht. Verhext

**Comment by Shreklich** [comment]
Schick mal bitte Screenshots von der Tastenbelegung also die wo VCA vorsteht und dann noch Screenshots von dem VCA Menü was du da eingestellt hast.

**Comment by alfsjan272** [comment]
https://imgur.com/cZIlSk5
https://imgur.com/aYkiZae
https://imgur.com/Xp0ttTW

**Comment by Shreklich** [comment]
Also ich habe es nochmal mit deinen Einstellung versucht es geht definitiv nur mit dem Gang Splitter der steht unter Gang 9. Ich würde dir aber trotzdem empfehlen das 2x6 Getriebe von VCA zu nehmen dann hast du die Gänge besser unterteilt oder musst dann eben die Geschwindigkeit bei den Gängen noch einstellen. 
Warum es beim 2x6 nur über den Splitter geht weiß ich nicht bei einem Getriebe 2x4 selbst konfiguriert  funktioniert es ohne Probleme mit Gruppe rauf und runter.

**Comment by Mogli12** [comment]
Hallo Jan,

für einen Shifter mit 6 Gängen gibt es 2 Getriebe: 

1. "2x6": Es gibt 12 Gänge. Mit einem Schalter wechselt man zwischen den oberen und unteren 6 Gängen. 
2. "6 Gears with Splitter": Hier gibt es auch 12 Gänge. Aber der Schalter wechselt zwischen den geraden und ungeraden Gängen

Ein Großteil der anderen Getriebe schaltet ungefähr wie das "6 Gears with Splitter".

Viele Grüße,
Stefan

**Comment by alfsjan272** [comment]
Ich habe mich wohl etwas falsch ausgedrückt. Das mit den Getrieben hab ich verstanden. Ich habe das Problem, dass in der 6G, 1R, LH Konfiguration ich keine Gruppen auswählen kann. Wenn ich Gänge einlege springt er aus der Gruppe die ich gewählt habe und baut sich einen Misch bei dem auf den Positionen 1-3 die erstern drei Gänge der kleinen Gruppe und bei den Positionen 4-6 die die letzten drei Gänge der großen Gruppe benutzt werden. Dies tritt aber nur auf, wenn ich die Schaltpostionen des G27 benutzte. Bei den "Sequentiellen" funktioniert es wie gewollt.

**Comment by alfsjan272** [comment]
https://imgur.com/AvgKe64

**Comment by Shreklich** [comment]
Ich habe dein Getriebe bei mir getestet so wie du es eingestellt hast und ja es springt durcheinander wenn man es einmal über die Gruppe schaltet. Wenn man aber die Taste für Gang Splitter nutzt sollte er in der jeweiligen Gruppe bleiben nutze es ja selbst auch mit dem G27. Wenn man die Tasten für die Gruppen drückt macht der komisches Zeug. Du darfst natürlich auch keine Tastendoppelbelegung haben also das heißt zB Gruppe runter und Gang Splitter auf die selbe Taste legen dann funktioniert es auch nicht mehr. Nach dem letzte Giants Update geht es leider nicht mehr das man dafür dann 2 Tasten belegen kann. Und noch eine Kleinigkeit da du das G27 nutzt ist eine Taste für das menü belegt diese Taste musst du in den Input bindings selber rauslöschen wenn du diese für was anderes nutzten willst, dass ging zumindest bei mir nicht übers ESC Menü ich mein das ist sogar die Taste 2 vom G27 die bei dir für Gruppe runter belegt ist.
Hoffe das hilft dir jetzt bei deinem Problem.

**Comment by knalltuete69** [comment]
Ich hab vermutlich die Lösung gefunden. Ich Dummkopf hab versucht ein Schaltschema für eine 8Gang Schaltung auf einer 6er zu benutzen wodurch wohl die Automatik es für mich umgerechnet hat.

**Comment by alfsjan272** [comment]
Hey ich wollte mal fragen ob es möglich ist Schaltpositionen für Gruppen hinzuzufügen?
