### ISSUE TITLE
Neue Tastenbelungen 

### ISSUE THREAD

**Issue by alfsjan272** [Mogli12/VehicleControlAddon#496]
Nach dem letzten etwas dummen Problem hätte ich hier noch eine Frage. Ich nutze ein PowrQuad Getriebe das die Gruppen über eine H Schaltung ansteuert. Gibt es eine Möglichkeit 6-8 direktwahltasten für Gruppen einzurichten?

**Comment by Mogli12** [comment]
Leider nein
