### ISSUE TITLE
Original Funktionen des Tempomats

### ISSUE THREAD

**Issue by Omat1998** [Mogli12/VehicleControlAddon#497]
Moin Moin,
ich würde mir gerne das Skript so umschreiben, dass der Tempomat wieder funktioniert wie im Originalen Spiel. Soll heißen, dass er sich auch wieder deaktiviert, wenn man Gas gibt.

Bin dies vom realen Fahren so gewöhnt und finde es persönlich etwas störend. Hat jemand einen Tipp, wo ich gucken muss? :D

Vielen Dank schon im voraus!
MfG Omat

**Comment by Shreklich** [comment]
Hallo darf man fragen bei welchen realen Fahrzeug das so ist? Ich kenne es nur beim Bremsen das sich der Tempomat abschaltet und nicht beim Gas geben. 
MfG Thorsten

**Comment by MBTrac366** [comment]
Kenne das aus diversen (realen) Fahrzeugen auch nur so, zusätzlich Gas geben lässt den Tempomaten aktiv, nur Bremsen deaktiviert ihn

**Comment by Mogli12** [comment]
Hallo,

man kann den Tempomaten sowohl mit der Taste 3 also auch mit der Bremse (Taste S) ausschalten. Das sollte doch genügen, oder?

Beim Ackern in LS19 schalte ich den Tempomaten meist auf 7 km/h. Das ist die Geschwindigkeit am Vorgewende. Sobald das Gerät abgesenkt ist, ist ja ohnehin der Begrenzer von LS19 aktiv. Dann gebe ich mit der Taste W Gas, so dass das Fahrzeug die maximal erlaubte Geschwindigkeit erreicht, z.B. 15 km/h.

Für Modifikationen gibt es leider keinen Support.

Viele Grüße

**Comment by Omat1998** [comment]
Moin Moin,

@Shreklich @MBTrac366 
Natürlich gibt es diverse Landwirtschaftliche Fahrzeuge bei denen es so ist, Siehe z.b. alle Fendt Vario und die neuen John Deere AutoPwr (ältere bin ich noch nicht gefahren). New Holland z.b. deaktiviert den Tempomaten nicht einmal beim Bremsen.

Vielen Dank für deine Antwort @Mogli12, es war nur meine persönliche Meinung und ich hatte nicht die Intention unhöflich zu wirken!
Schönen Abend noch
