### ISSUE TITLE
Hinzufügen eines Schaltschemas?

### ISSUE THREAD

**Issue by alfsjan272** [Mogli12/VehicleControlAddon#498]
Hy ich wieder. Gibt es die Möglichkeit sich selbst an den Schaltschemen auszutoben und wenn nicht erlaubt das Script ein einfaches 6Gang Schema. Hab die Gruppenwahl auf einem anderen Hebel und würde mein G27 shifter gerne für alle 6 Gänge nutzen.

**Comment by Mogli12** [comment]
Mit dem Schema "6G, R+/-, 1R" oder "6G, R+/-, Shuttle" kannst du doch jetzt schon 6 Gänge direkt schalten, die Gruppen mit 2 Tasten hoch und runter schalten und die Fahrtrichtung wechseln. Dazu sollte das Getriebe "4x6 HexaShift" passen.
