### ISSUE TITLE
Request for added precision

### ISSUE THREAD

**Issue by antler22** [Mogli12/VehicleControlAddon#499]
Hello,

I currently use this an love this mod, but the function of snap angle, or auto steer I am curious how I can make it more precise.  I have edited crop and ground textures to fit an exact 30 inch row spacing for plants, which aligns with the ingame headers.  I would like to have a track width of 9.144 meters or 12.192 meters to match these rows perfectly.  Right now the mod makes me round to 9.14 or 12.19.  After several passes in the field this small difference starts to show itself.  Is there a way I can get this to accept 3 digit decimals for the working width?

**Comment by Mogli12** [comment]
The rounding is just a display issue. The number is stored exactly as you typed it in.

**Comment by antler22** [comment]
Well, I feel dumb. Thank you for clarifying!  Once again great work with this mod!

**Comment by antler22** [comment]
I just tried this today. Input box only allows 2 decimals. What am I missing?
