### ISSUE TITLE
Eine Frage zum Getriebe

### ISSUE THREAD

**Issue by Shreklich** [Mogli12/VehicleControlAddon#500]
Hallo Mogli, 
ich habe mal eine Frage zu folgendem Schaltschema D/R , G+/-, R+/- ich habe dieses einmal ausgewählt für den G27 Shifter. Ich wollte damit so was ähnliches wie ein PowerShiftGetriebe simulieren nur wenn ich jetzt natürlich den erste oder zweiten Gang nicht eingelegt habe für die Fahrtrichtung fährt dieser ja nicht. Steht ja auch so in deiner Beschreibung. Aber ist es irgendwie möglich das man hier irgendwie ein Schaltschema baut wo ich die Fahrtrichtung vorwählen kann über die Wendeschaltung zB und das ich dafür nicht unbedingt in den Gängen 1 oder 2 sein muss. Hintergrund wenn man den Shifter nur zum Gänge hoch oder runterschalten nutzen will muss man ja immer wieder zu den Gängen 1 oder 2 zurück springen um zu fahren man kann also nicht permanent auf dem Gaspedal bleiben und hochschalen da er dann direkt in neutral geht. 
Hoffe ich habe es verständlich ausgedrückt. Vielleicht mache ich ja auch etwas bei der Einstellung falsch oder benutze das Schaltschema nicht richtig.
LG Thorsten

**Comment by Mogli12** [comment]
Hallo Thorsten,
ich glaube, dass dieser Modus fürs Vario-Getriebe gedacht ist. Leider geht das Getriebe automatisch in Neutral, wenn man nicht in D oder R ist.
Viele Grüße,
Stefan
