### ISSUE TITLE
Gruppen direkt auf Tastenlegen

### ISSUE THREAD

**Issue by Rammel123** [Mogli12/VehicleControlAddon#501]
Hallo Mogli
Wäre es möglich die Gruppen nicht nur hoch und runter zuschalten, sondern auch die gruppen direkt auf Tasten zu belegen.
Ich habe selbst 2 Shifter gebaut einer für Gänge 1-4 und einen für Gruppe 1/2 und Rückwärts.
Ich kann leider beim VCA nur Gang 1-4 angeben und die Gruppen nur mit 2 Tasten hoch und Runterschalten.
Vielen Dank

**Comment by Mogli12** [comment]
Nein, das ist nicht möglich
