### ISSUE TITLE
Linienfarbe ändern

### ISSUE THREAD

**Issue by chroboss** [Mogli12/VehicleControlAddon#502]
Hallo Mogli und Kollegen.
leider habe ich eine Farbschwäche und es fällt mir sehr schwer, die rote Linie bei inaktiver Spurführung zu erkennen.
Gibt es eine Möglichkeit, die Linienfarbe zu ändern? Ich traue mir zu, das selbst vorzunehmen, weiß aber nicht in welchem Script und an welcher Stelle.
Über eine Hilfestellung freue ich sehr.
Danke, Charlie

**Comment by Mogli12** [comment]
Hallo Charlie,

die Farben werden in den beiden setTextColor Aufrufen in den Zeilen 3742 und 3749 von vehicleControlAddon.lua gesetzt. Welche Farben sind den gut?

Viele Grüße

**Comment by chroboss** [comment]
Hallo Mogli. Danke für die schnelle Antwort und Deine Unterstützung. Ich mache mich noch heute an die Änderung! Gute Farben? Ich kann hier nur für mich sprechen. Ich werde weiss und ein mittleres grün verwenden. Ich denke, damit komme ich gut zurecht. Andere mit einer Grün-Schwäche werden hier wiedersprechen :) Danke nochmals und auch für Deine Bemühungen, uns Usern immer wieder neue, interessante Mods zur Verfügung zu stellen. Schicke mir doch bitte noch einen Link, ich würde dir gerne einen Kaffee oder ein Bier als Danke spendieren. Gruß Charlie

**Comment by Sacred-Shadow** [comment]
Ich empfehle mal diese Apps:
https://play.google.com/store/apps/details?id=asada0.android.cvsimulator&hl=de
oder
https://apps.apple.com/de/app/chromatic-vision-simulator/id389310222

Es geht ja darum, dass Menschen mit einer der Farbschwäche das evtl. nicht richtig sehen.
Also entweder schaust selbst per App welche Farbe man am besten erkennen kann oder bietest die Möglichkeit, in den Einstellungen ein paar Farben zu ändern.

Muss ja nicht direkt die Eingabe von einem Farbcode sein oder ein Colorpicker. 
Aber so eine kleine Auswahl von ein paar Farben die jeder gut erkennen kann, is ja nich verkehrt. :)

**Comment by Mogli12** [comment]
Das Problem ist, dass die Früchte grün bis gelb sind. Da bleiben am Ende nicht mehr viele Farben übrig. Rot geht nicht, weil man es nicht von Grün unterscheiden kann, Gelb wäre zu wenig Kontrast zum Hintergrund. Wie soll ich da 2 Farben finden? Leider habe ich hier noch keinen konstruktiven Vorschlag gesehen.

**Comment by Sacred-Shadow** [comment]
Lass es doch die Leute entscheiden ... zieh den Einstellungspunkt ins Menü. :)
Als Pulldown einfach ein paar Farben (Grün, Blau, Weiß, Rot, Gelb usw) zur Auswahl anbieten.

Wer Farbenblind is, für den sehen ja auch die Früchte anders aus. 
Wäre das eine Lösung? :)

**Comment by chroboss** [comment]
Da bin ich bei Sacred-Shadow, ich halte dies für eine gute Lösung. Farbschwache (nicht blind!) sehen Farben tatsächlich anders,  eine kleine Veränderung hilft oft schon viel. Und nicht jeder traut sich, in den Code der LUA einzugreifen, oder ist in der Lage, den richtigen Farbcode zu errechenen. Nee, eine einfache Farbwahl mit den Standartfarben wäre optimal, sofern sich das auch umsetzen lässt.

**Comment by Mogli12** [comment]
Ich kann keine einfach Farbpalette einbauen. Es gibt sie zwar im Shop, aber das LUA-Coding und vor allem die XML-Dateien dazu sind nach meinem Kenntnisstand nicht verfügbar. Ich habe auch schon eine ähnlich Anfrage an Giants gestellt, aber leider ist man dort nicht wirklich hilfsbereit. Ich habe leider auf meine Anfragen in den letzten Jahren nie brauchbare Antworten bekommen.

Da die Diskussion aber jetzt in die Farbpaletten-Ecke abgerutscht ist, mache ich sie jetzt zu.
