### ISSUE TITLE
Problem vehicle Control addon Warning

### ISSUE THREAD

**Issue by Aim400kgp** [Mogli12/VehicleControlAddon#503]
Hello 

1.Vehicle Control addon gearbox to FS 19- It is called a vehicle control addon modem, but the gearbox works without errors only such thing pops up and I do not know what it is and what it means, but the gearbox does not wake up with other mods only works without jealousy.

Warning: no l10n "input_vcaManRatio_1".
Warning: none l10n "input_vcaManRatio_2".

Greetings to

**Comment by Mogli12** [comment]
I do not get this warning.
