### ISSUE TITLE
keybind "Automatische Schaltung an/aus - STRG links, Ü" funktioniert nicht

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#504]
STRG links, Ä für Allrad an/aus funktioniert aber.

Andere Mods nutzen diese Tastenkombi nicht, jedenfalls nicht nach keybind settings und nicht dass ich wüsste.

**Comment by Aim400kgp** [comment]
I don't understand and you could write in English again. It would be best
to talk

wt., 5 sty 2021, 22:04 użytkownik Gordon-Dry <notifications@github.com>
napisał:

**Comment by Gordon-Dry** [comment]
The default keybind for automatic gearbox toggle is not working on german keyboard layout.
The keybind for 4WD toggle works, though.
   
I already changed those to CTRL+7 and CTRL+9 for my own pleasure.

**Comment by Mogli12** [comment]
Do you use courseplay?

**Comment by Aim400kgp** [comment]
Test idę courseplay

śr., 6 sty 2021, 08:59 użytkownik Stefan Biedenstein <
notifications@github.com> napisał:

**Comment by Aim400kgp** [comment]
Yes

śr., 6 sty 2021, 10:33 użytkownik Przemek Barczak <
przemekbarczak61@gmail.com> napisał:

**Comment by Mogli12** [comment]
Courseplay blocks some of the key bindings. I do not know why. I propose to open an issue in the Courseplay repository.
