### ISSUE TITLE
Question downgrade gears,

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/VehicleControlAddon#505]
Hallo Stephan **happy new year**🥳🎉 ! and I hope all is fine for you.

I would to know (again), is there a way (parameter) to increase faster downgrade gears in automatic mode you know? because I saw it seem when in load the gears make (the more time), long time to begin decrease one by one and detect the load it seem, and then it's too late to not lose the speed of the vehicle specially in the climbs.

Br

**Comment by oschuhm** [comment]
Hi Stephan,
da schließe ich mich an.
Das würde mich auch interessieren.
VG
Oliver

**Comment by Anonymous-any** [comment]
Hi Stephan,

Best of you faster reactive, seem be fixed in your last 307.
Also do you saw or is it normal that the "direct drive" does not support range in auto ?

I close thank Maestro !

**Comment by Mogli12** [comment]
Yes, it is normal to shift the ranges manually.

**Comment by Anonymous-any** [comment]
Ok thx

**Comment by Anonymous-any** [comment]
Hello Stephan,

I reopen it faster to know if you can do a fix for helpers like "AutoDrive" you know where I've not tested with like CP because I use it only for field "mean low speed" but it seem the fix you made for this ticket here don't take in account AD...it's not easy to say what is really about but I try for a fast explain.
When you just jump by TAB in vehicle and depend where is it in AD network (mean just before turns) like that or when a cross become, then VCA don't downgrade. But if you stay in the vehicle AutoDrived ^^ then it downgrade ok so it's weird to explain.
That mean too like me, if you use in combination VeExplorer and set it to save vehicle status (for fix train as example constraint), then after u reload your game and restart AD (depend where is it in his network) it stay with his highter gearbox as restarting AD. I hope this is comprehensible for you and you can find a fix again 🧐.

Best regard

**Comment by Mogli12** [comment]
What is your setting for VCA and hired worker?

**Comment by Anonymous-any** [comment]
Hello,
`<hiredWorker value="1"/>`

**Comment by Mogli12** [comment]
These are only the global defaults. It is part of the VCA settings dialog.

But `<hiredWorker value="1"/>`means that the transmission is disabled if auto drive is active and nobody entered the vehicle.

**Comment by Anonymous-any** [comment]
Hi so maybe I made a bad translation ?

Yes hiredWorker value is set only if auto-helper is on board like you see. Well I go set it on always ? but I was thinking it was sufficient. Maybe I have to correct the translation ? so what I must set to make the helper use always the gearbox even I switch to in or out **off** or **always** ?
Br

**Comment by Mogli12** [comment]
In this case the gearbox is only active if you enter the vehicle.

**Comment by Anonymous-any** [comment]
Ok well I made new test and set it as always mean even if entered ok.
But most of the time I always have no downgrade gearbox <u>if AD helped AND before turns</u>. After the turns it seem downgrade ok even I'm not entered...but it seem this is a bit difficult for VCA.
