### ISSUE TITLE
Brakeforce jumps immediately to 1.00

### ISSUE THREAD

**Issue by Jan238** [Mogli12/VehicleControlAddon#506]
Hey,
seit den letzten Versionen von VCA springt die brakeforce sofort auf 1.0 wenn man mit der Tastatur bremst. Man hat also schon bei einem kurzen antippen der Taste volle Bremskraft. Dadurch kann man kaum noch langsam runterbremsen. In älteren Versionen hatte ich dieses Verhalten nicht. 
Das gleiche tritt bei der Wendeschaltung auf. Wenn ich die Fahrrichtung ändere, wird sofort mit voller Kraft abgebremst. 

Ich hoffe du kannst da was machen. 

Hey, 
since the last versions of VCA the brakeforce jumps immediately to 1.0 while braking (with keyboard). That means full brakeforce even with a very short tap on the key. Because of that braking slowly/soft is very difficult or impossible. I think in older Versions this problem does not exists.
Another situation where this occures is when changing drive direction.
I have tested it with just VCA in my mod folder.

I hope you can fix this. 

Viele Grüße und ein frohes neues Jahr

**Comment by Mogli12** [comment]
Hi,

I removed the smoothing of acceleration and brake pedal. The smoothing of acceleration pedal causes problems when changing between cameras.

Regards, Stefan

**Comment by Mogli12** [comment]
Please check build 309
