### ISSUE TITLE
Shuttle control with less braking force ?

### ISSUE THREAD

**Issue by Lactic68** [Mogli12/VehicleControlAddon#507]
Hi,

Was the braking force of the shuttle somehow "nerfed" in latest 309 build ? When driving forward, if we use the shuttle to go backward, the tractor take more time to fully stop and then go backward.

**Comment by cabmac** [comment]
this is what 309 is about... to smooth changing fwd/bwd.... in my opinion perfect now

**Comment by Mogli12** [comment]
Hi,

This is a side effect of fix done for #506. I am not 100% sure if this is the best way for shuttle control. The idea of the fix for #506 is to help key board players with the brake pedal (KEY_s). 

Regards,
Stefan

**Comment by Mogli12** [comment]
Hi,

The brake force starts harder if you use shuttle control before stopping.

Regards,
Stefan

**Comment by Lactic68** [comment]
Thank you for this quick update @Mogli12 but now I have this error in the log with this build : 
Error: Can't load resource 'C:/Users/lacti/Documents/My Games/FarmingSimulator2019/mods_aTester/FS19_VehicleControlAddon/vehicleControlAddonTransmissionOwn2.lua'.

**Comment by Mogli12** [comment]
The error message should be fixed now.

**Comment by Lactic68** [comment]
Yes, everything is now OK. Thank you ! This was quick !
