### ISSUE TITLE
Fragen zur Eco-Getriebe Umsetzung

### ISSUE THREAD

**Issue by Stephan7530e** [Mogli12/VehicleControlAddon#508]
Hallo Mogli,
Ich habe das "John Deere PowrQuad by Shifty" modifiziert, sodass es dem PowerQuad ECO sehr nahe kommt. Dadurch habe ich im letzten Gang bei 40km/h eine Motordrehzahl von 1670 U/min. Dies konnte ich nur erreichen indem ich die Übersetzung im letzten Gang dementesprechend angepasst habe. Mein Problem ist, dass es beim letzten Gangwechsel einen gröberen Wechsel gibt, wenn ich kein Vollgas fahre. Das liegt bestimmt an den großen Differenz zwischen den Übersetzungen. Kann man den letzten Wechsel seperat schneller stellen, um dieses Problem zulösen? Oder haben Sie vielleicht eine andere Idee dazu? 

Hier mein Eintrag um es besser nach zuvollziehen:

{ class = vehicleControlAddonTransmissionBase,
			params = { name			= "JDPQ-ECO",
					isIVT			= false,
				noGears				= 4,
				timeGears			= 0,
				rangeGearOverlap	= {0,0,0,0},
				timeRanges			= 750,
				gearRatios			= { 0.0625, 0.0750, 0.0900, 0.1100,
										0.1325, 0.1600, 0.1925, 0.2350,
										0.2125, 0.2550, 0.3050, 0.3750,
										0.3925, 0.4725, 0.5650, 0.6925,
										0.5800, 0.7000, 0.8375, 1.3173 },
									--(km/h --> (A) 2.5, 3.0, 3.6, 4.4, (B) 5.3, 6.4, 7.7, 9.4, (C) 8.5, 10.2, 12.2, 15.0, (D) 15.7, 18.9, 22.6, 27.7, (E) 23.2, 28.0, 33.5, 40.0, ECO = 40km/h in VCA Menü eintragen)
				gearTexts			= {"1", "2", "3", "4"},
				rangeTexts			= { "A", "B", "C", "D", "E" } },
			text	= "PwrQuad-ECO"},

Mit freundlichen Grüßen 
Stephan

**Comment by Mogli12** [comment]
Hallo,

es ist gar nicht notwendig, eine Getriebe-Einstellung zu modifizieren. Man wählt einfach eine höhere Endgeschwindigkeit. Wenn der Traktor original 43 km/h schnell fährt und man 53 km/h einträgt, dann wird er trotzdem bei 43 km/h abgeregelt. Aber die Drehzahl ist nun 2200 * 43 / 53 = 1785.

Viele Grüße,
Stefan

**Comment by Stephan7530e** [comment]
Hallo und Danke für die schnelle Antwort.

Das hatte ich auch zuerst ausprobiert, doch dieser Ansatz funktioniert gut bei Stufenlosengetrieben und nicht bei "manuellen Getrieben". Das Problem ist, dass ich durch das Erhöhen auf z.b. 53km/h sich das ganze Gangspektrum verschiebt. D.h. in E3 (19 Gang) 53 km/h * 0,8375 = 44 km/h und nicht die vom Realen Getriebe 33,5 km/h. Daraus folgt in der Praxis das ich dann zwei Gänge E3 und E4 mit "40km/h" habe, aber mit unterschiedlicher Drehzahl. Deswegen habe ich das Getriebe modifiziert, um die Folge (A) 2.5, 3.0, 3.6, 4.4, (B) 5.3, 6.4, 7.7, 9.4, (C) 8.5, 10.2, 12.2, 15.0, (D) 15.7, 18.9, 22.6, 27.7, (E) 23.2, 28.0, 33.5, 40.0, beizubehalten.

Mit freundlichen Grüßen
Stephan

**Comment by Mogli12** [comment]
Hallo Stephan,

dann solltest Du es als Konfiguration in config.xml ablegen. Bei Modifikationen am Quellcode hast Du das Problem, dass Du andere Korrekturen und Erweiterungen verlierst.

Viele Grüße,
Stefan
