### ISSUE TITLE
Flying vehicles?

### ISSUE THREAD

**Issue by Nisfeer** [Mogli12/VehicleControlAddon#510]
Hello,

I'd like to report problem with flying vehicles you can see it here (I used phone sorry for the quality): https://drive.google.com/file/d/1K77PLvGx6L7fl3mt2y6jlwhsSbmFSFxw/view?usp=sharing

When it happens: if you work in field and your wheels gets stuck in the dirt (probably most of the time), never tried on even ground without being stuck.

What's causing this: I prefer driving with turning axles myself so I guess only in manual mode - when I'm stuck and I turn front axle then back axle myself and step on the gas this is what happens not all the time but happens a lot (probably with differential on also).

**Comment by Mogli12** [comment]
Hi,

I do not know if you use the latest version as log.txt is not attached. The problem was already reported several times, e.g. #488. It is a bug in gients engine. There happens something like an overflow. It is in the engine itself, not in LUA.

Regards,
Stefan
