### ISSUE TITLE
New feature request : hook/unhook front tool, hook/unhook rear tool

### ISSUE THREAD

**Issue by Lactic68** [Mogli12/VehicleControlAddon#512]
Hi Mogli,

Your VCA mod has inputbindings for lowering/lifting the rear/front tool. Do you think that it is possible to add inputbinding for hook and unhook front or back tool ? (to save the switching process between front and rear)

Regards,

Lactic

**Comment by Mogli12** [comment]
Hi Lactic,

I am more the fan of manual attaching. And there is a problem is two or more tools are attached to the back. Which one should be detached. Honestly, I do not want to implement it.

Regards,
Stefan
