### ISSUE TITLE
Adaptive Lenkung mit xBox Gamepad

### ISSUE THREAD

**Issue by Sacred-Shadow** [Mogli12/VehicleControlAddon#513]
Hiho,

hab da evtl. ein "Problem" gefunden?
Genutzt wird die aktuelle Version vom LS19 und die VCA Version aus dem ModHub. 

Einstellungen sind alle clean .. aktiviert wird nur die Adaptive Lenkung im Zusammenspiel mit einem xBox One Gamepad.
Nun dachte ich schon, ich hätte einen defekt am linken Analogstick. 

Manchmal haben die Fahrzeuge wild in eine Richtung gesteuert. 
Meistens, wenn man vorher kurz ein bisschen in diese Richtung gelenkt hatte.
Aufgefallen ist mir dann **im Stand**, ein komisches Verhalten am Fahrzeug. 

Beim lenken passiert es oft, dass die Lenkung nicht zurück auf Null geht. 
Mal bleibt sie bei Vollausschlag hängen, mal bei 50% mal bei 25%.
Mal wurde aus einer kleinen Lenkung ein Vollausschlag ohne Rückstellung.

Dann funktioniert die Rückstellung auch einfach mal ohne Probleme. 

Benutze ich die Funktion falsch oder läuft da irgendwas unrund?

**Comment by Mogli12** [comment]
Hallo,

beim analogen InputDevice sollte die adaptive Lenkung doch aus sein.

Viele Grüße,
Stefan

**Comment by Sacred-Shadow** [comment]
Hey Stefan,

meinst du aus, weil der User es aus lassen sollte?
Wenn du das meinst, sollte evtl. eine kleine Info mit in den Infotext. 

Oder sollte es technisch aufgrund einer Erkennung des Eingabegerätes aus sein?

Grüße

**Comment by Mogli12** [comment]
Hallo,

bei analogen Eingabegeräten gibt es keine automatische Rückstellung. Wenn es trotzdem gelegentlich funktioniert, dann liegt es vermutlich daran, dass die Sticks vom Controller in Mittelstellung sich auf nicht-analog umstellen. 

Viele Grüße
