### ISSUE TITLE
Wenn "Niedrige Bremskraft" auf 0%, dann Stillstand ohne Handbremse unmöglich

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#514]
Es ist so, als ob immer ein frecher Fuß die Kupplung kommen lassen will, so langsam und schleifend, um die Standgasddrehzahl zu nutzen, ein paar Meter zu fahren, bevor der Motor abwürgt.

**Comment by Mogli12** [comment]
Hallo,
es ist normal, dass das Fahrzeug wieder anfährt, wenn man den Fuß von der Bremse nimmt. Wenn man lange genug auf der Bremse steht, dann geht AutoHold an und das Fahrzeug bleibt stehen.
Viele Grüße

**Comment by Gordon-Dry** [comment]
Hmm.
"Normal" in Bezug auf dieses Mod?

Denn das jede Art von Getriebe, die in einem Lw-Fahrzeug verbaut sein kann, keinen Leerlauf kennt und immer einen Gang drin hat, will ich nicht so recht glauben.

**Comment by Mogli12** [comment]
Wenn man anhält, dann ist nur die automatische Kupplung geöffnet der Gang ist noch eingelegt. Wenn man dann auf Neutral geht, ist gleichzeitig die Handbremse angezogen.
