### ISSUE TITLE
Umsehen mit der Tastatur funktioniert teilweise

### ISSUE THREAD

**Issue by ChrisDerBauer** [Mogli12/VehicleControlAddon#515]
Hallo Mogli,

Nach dem Drücken der Tasten "Umschaltrechts+Pfeiltaste" kann ich mich mit den Pfeiltasten nicht mehr umsehen. Wenn ich das ESC Menü öffne und wieder schließe kann ich die Pfeiltasten wieder nutzen. 
Wenn ich die Tasten "Umschaltrechts+Pfeiltaste" wieder drücke, sind die Pfeiltasten wieder funktionslos. 
Ich habe das Problem auf der Untegrießbach mit Mods und auf der Ravenport ohne Mods. Die InputBuilding.xml habe ich mehrmals gelöscht.
Das Problem tritt bei der Modhub Version und bei der Github Version auf. 

SG ChrisDerBauer

**Comment by Mogli12** [comment]
Hallo,

ich vermute, dass Tasten doppelt belegt sind. Bei mir funktionieren die Tasten. Manchmal hilft es, die inputBinding.xml umzubenennen oder zu löschen.

Viele Grüße
