### ISSUE TITLE
"Wobbling" bei Knicklenkerfahrzeugen mit aktivierter Spurführung

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#516]
Der Kirovets K-700A zappelt deutlich, sobald die Spurführung aktiv ist.
Ohne Spurführung fährt der auch auf dem Acker tadellos.

**Comment by Mogli12** [comment]
Durchs Lenken bewegt sich der Bezugspunkt der Spurführung. Daher sind Knicklenker für die Spurführung und auch für AIVE eigentlich nicht geeignet.

**Comment by Gordon-Dry** [comment]
Verstehe.
Ich muss mich mit den Nachbarn auf der WildWest 16x Map eh besser stellen und endlich den sowjetischen Sc hlepper durch einen US-amerikanischen ersetzen ...
Nur dass der Kirovets bis zu 800 PS und unfassbar Drehmoment hat und für große US-Felder passt wie Arsch auf Eimer. ;)

**Comment by Gordon-Dry** [comment]
Ich stelle gerade fest, dass eigentlich alle sehr starken Schlepper Knicklenker sind.
Case IH
BigBud
NH T9

Hmm.

**Comment by Mogli12** [comment]
In VCA liegt der Fokus ganz klar darauf, eine einfaches Tools zum Halten der Spur zur Verfügung zu stellen.
Für kompliziertere Fälle, und Knicklenker sind kompliziert, versuch doch bitte [Guidance Steering](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=140328&title=fs2019).
Dasselbe gilt im Grunde fürs Getriebe: Das Getriebe für die komplizierten Fälle ist hier: https://github.com/modelleicher/FS19_realManualTransmission.
