### ISSUE TITLE
LUA Error with Build 316

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#517]
Hallo Stefan,
beim aktuellen Build bekomme ich diesen Fehler und das Spiel startet nicht:

2021-01-23 18:23 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-01-23 18:23 E:/Spiele/FS19-Modordner/GDP_SchwarzePumpe1988/FS19_VehicleControlAddon/vehicleControlAddon.lua:6842: attempt to compare number with nil

Wenn du mehr Info brauchst einfach melden.

Gruß

**Comment by Mogli12** [comment]
Hallo,

Sorry, aber der Umbau mit den Drehmomentkurven war doch etwas umfangreicher. Ich hatten einen tollen Traktor gefunden, aber dann festgestellt, dass er über 200PS anstatt der realen 160 PS hatte.

Mit Build 317 klappt es hoffentlich besser.

Viele Grüße

**Comment by Williwillswisse** [comment]
Danke für die schnelle Rückmeldung Stefan.
Funktioniert wieder ... kann dann hier zu.
