### ISSUE TITLE
Gaspedalbegrenzer mit umgekehrter Logik ("75% / 100%" statt "100% / 75%") lässt sich nicht auf Tempomat anwenden

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#519]
Wenn der Tempomat aktiv ist und ich die Taste für den Gaspedalbegrenzer drücke, wird dort standardmäßig um 25% reduziert, also von z.B. 20 km/h auf 15 km/h.
Da ich Sprit sparen möchte und nicht immer Vollgas geben möchte, habe ich die Einstellung für den Gaspedalbegrenzer von "100% / 75%" zu "75% / 100%" geändert und auch die Tastenbelegung auf eine Zusatz-Maustaste gelegt für einfaches Handling, falls ich doch mal Vollgas brauche.
Auf dem Acker nun ziehe ich einen Grubber und es wird mit 75% Leistung gefahren, drücke ich aber die Taste, wird nicht mit 100% Leitung gefahren, sondern die Tempomateinstellung um 25% reduziert.

**Comment by Gordon-Dry** [comment]
Ich stelle gerade fest, dass auch bei "normalrum", also "100% / 75%" bei fahrt mit Tempomat um 25% reduziert wird, wenn ich die Taste drücke - also wird das Standardverhalten in jedem Fall genutzt.

Bei einem Test mit "100% / 50%" und "50% / 100%" wird in beiden Fällen bei Fahrt mit Tempomat um 50% reduziert, also in meinem Beispiel von 20 km/h auf 10 km/h.

**Comment by Mogli12** [comment]
Hallo,

wenn der Tempomat an ist, dann wird automatisch Vollgas gegeben und das Fahrzeug dann in der Physik-Engine eingebremst.

Viele Grüße

**Comment by Gordon-Dry** [comment]
Okay.
Also das Drücken der Taste für den "Begrenzer" (hier dann ja "Erhöher") verringert die im Tempomat eingegebene Geschwindigkeit um genau den Prozentsatz, der bei VCA als Differenz zwischen "Vollgas" und "reduziert" vorliegt.

**Comment by Gordon-Dry** [comment]
Einstellung 75% ohne Taste, 100% mit Taste.

Ohne Taste zeigt der Tempomat 20 km/h an, das ist der von mir eingestellte und korrekte Wert:
![fsScreen_2021_01_24_16_12_44](https://user-images.githubusercontent.com/29145213/105634659-7901d780-5e5f-11eb-81ab-2316c0fa189c.jpg)

Mit Taste  zeigt der Tempomat 15 km/h an, das ist 25% weniger und entspricht der Differenz vom Gaspedalbegrenzer:
![fsScreen_2021_01_24_16_12_45](https://user-images.githubusercontent.com/29145213/105634666-815a1280-5e5f-11eb-8558-39618f607d72.jpg)

**Comment by Mogli12** [comment]
Ich verstehe das Problem immer noch nicht. Wenn Du die Taste drückst wird um 25% reduziert, und zwar sowohl bei 100/75, als auch bei 75/1ßß. Das ist von mir so gewollt.
