### ISSUE TITLE
New differtials 4WD and gearbox setttings

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#520]
Hallo Stefan,
ich schon wieder ;-)

Mit den neues Settings ist mir Folgendes aufgefallen:
Neues Fahrzeug gekauft (hier Lizard Pickup 1978)
Allrad und Differentiale eingeschaltet. Nennleistung zeit 189 PS in den Settings.
Fahrverhalten wie erwartet.
Jetzt habe ich ein Getriebe ausgewählt.
Fahrverhalten: Fahrzeug ist sehr träge und beschleunigt kaum. Erreicht auch keine höheren Geschwindigkeiten.
Gebe ich jetzt von Hand bei der Nennleistung "9999999999" ein ist das Fahrverhalten wieder einigermaßen normal.
Ist mir bis jetzt nur bei PKW aufgefallen.

Grüße

**Comment by Mogli12** [comment]
Ein paar Screenshots wären schon hilfreich.

**Comment by Williwillswisse** [comment]
Klar, hier ein paar Screenshots:
Globale Einstellungen:
![image](https://user-images.githubusercontent.com/47098121/105640550-ff79e180-5e7e-11eb-9bf2-99071444580d.png)
Getriebe:
![image](https://user-images.githubusercontent.com/47098121/105640562-18829280-5e7f-11eb-8d8c-5ae74c4257c7.png)
Allrad:
![image](https://user-images.githubusercontent.com/47098121/105640604-39e37e80-5e7f-11eb-9a48-d2a6fbc79671.png)

Mit diesen Einstellung fährt der Pickup "normal".

Wenn ich jetzt ein Getriebe einstelle (hier z.B. 2x6) :
![image](https://user-images.githubusercontent.com/47098121/105640751-e45ba180-5e7f-11eb-8129-a1700241f00a.png)
Der Pickup fährt sehr langsam und ruckelig an und erreicht nur ganz langsam hohe Geschwindigkeiten.
Stelle ich jetzt die "Nennleistung in PS" auf "9999999999" geht es wieder einigermaßen mit Getriebe:
![image](https://user-images.githubusercontent.com/47098121/105640829-75cb1380-5e80-11eb-8086-f272f3c80c18.png)
Log ist sauber.

Grüße

**Comment by Mogli12** [comment]
Der alte Pickpup hat nur rund 400 Nm Drehmoment. Mit der Einstellung von 189 PS und Default-Drehmomentkurve ändert VCA auch nichts an den Leistungsdaten. Eine andere Kurve zu verwenden klappt auch nicht, da beim Pickup das Verhältnis zwischen Leerlaufdrehzahl (1000) und Nenndrehzahl (knapp 6000) ganz anders als bei einem Traktor ist. 

Was allerdings ganz gut hilft ist, die Kupplung auf Turbo (langsam) zu stellen. Das ist ja auch realistisch, weil die alten amerikanischen Autos ja meistens 3-Gang-Automatik mit weichem Drehmomentwandler hatten. Damit wird die Drehmomentschwäche untenherum gut überwunden.

**Comment by Mogli12** [comment]
Ich konnte das Problem mit der aktuellen Version auf GitHub nicht nachvollziehen.
