### ISSUE TITLE
Drehzahl geht beim Beschleunigen auf 0

### ISSUE THREAD

**Issue by xBrinkix** [Mogli12/VehicleControlAddon#521]
Habe jetzt schon bei einigen Fahrzeugen erlebt, sobald man das Getriebe umschaltet, 
geht das Fahrzeug beim Beschleunigen so in die Knie, dass der Sound fast weg ist und man nicht von der Stelle kommt. 
Manchmal kommt auch eine Meldung, dass die Drehzahl zu gering ist. 
Wenn ich mit dem Handgas eine höhere Drehzahl einstelle, geht er ab der Beschleunigung auch in den Keller. 
Leider lassen sich so einige Fahrzeuge gar nicht mehr fahren. 
Wenn das Getriebe auf "off" oder auch "IVT" steht funktioniert es noch. 
Zur Info, alle anderen Einstellungen sind auf Standard. 

LG Brinki

**Comment by Mogli12** [comment]
Hallo Brinki,

Welche Version verwendest Du? Welches Fahrzeug und welches Getriebe verwendest Du? Wie ist die Kupplung eingestellt?

Es gibt einen Grund, warum in [README.md](https://github.com/Mogli12/VehicleControlAddon/blob/master/README.md) steht, dass man gewissen Angaben einem Problem hinzufügen sollte. 

Viele Grüße

**Comment by xBrinkix** [comment]
Moin Stefan, 
Version: 1.1.0.0 
Fahrzeug: z.B. im Modhub der Fiat 1300DT Rebuild von Modelleicher. Habe ich jetzt aber auch schon bei anderen gemerkt, aber bei dem Fiat am schlimmsten, da dieser sich dann gar nicht mehr bewegen möchte. Man muss ihn zurücksetzen. 
Getriebe: z.B. 4x4, 2x6, 6 mit Shifter, 6 Hexa. Eigentlich fast alle. Selbst wenn man es danach wieder auf off oder IVT stellt, fährt er nicht mehr und muss ihn zurücksetzen. 
Die Kupplung ist Standard auf Automatik. 
Sorry :(

**Comment by Mogli12** [comment]
Moin Brinki,

kannst Du noch einen Screenshot (Taste "Druck" im Spiel, dann im Verzeichnis ...\Dokumente\My Games\FarmingSimulator2019\screenshots) hinzufügen. 

Hast Du es mit der neuesten Version hier auf Github probiert?

Viele Grüße

**Comment by xBrinkix** [comment]
Ich mache gleich mal einen Youtube Clip und lade den mal hoch. 
Screenshot sollst du auch bekommen. Mache ich heute alles fertig. 

Vorher teste ich das aber mal mit der aktuellsten Version, das habe ich übersehen. 

Vielen Dank Stefan und vielen Dank für diese Mega geile Mod. Diese Mod ist einer der Gründe, warum ich überhaupt noch beim LS bin ;) Vielen Dank. Bis später.

**Comment by MBTrac366** [comment]
Kann das Problem mit exakt diesem Traktor bestätigen, glaube aber, dass es eher an der "eigenwilligen" Motorkonfig dieses Traktors liegt. Da wurde im unteren Drehzahl erreicht eine Torque von 0 eingetragen

**Comment by Mogli12** [comment]
Die Drehmomentkurve sieht doch gut aus. Bei 0 RPM hat ein Dieselmotor auch 0 Nm Drehmoment.

**Comment by xBrinkix** [comment]
Moin Jungs, 

habe gestern Abend das ganze noch mal mit der Version 1.1.1.0 getestet und mir ist der Traktor kein einziges mal abgesoffen. 
Also bis jetzt sieht es gut aus. 

Ich werde das heute Abend noch mal mit einem Case Puma testen, bei dem das Problem oft vor kam und euch dann morgen erneut berichten. 

Danke schon mal soweit =)

**Comment by MBTrac366** [comment]
Laut der MotorConfig hat er aber 0 Torque bei 450 RPM, das verwundert mich etwas.

Habe den Traktor ebenfalls gestern Abend nochmal getestet, aktuelle VCA, nur der Traktor hat funktioniert, sobald ich aber nen Anhänger dran hatte ist er direkt abgesoffem.
Wie gesagt, vermute es liegt an der Konfig des Fahrzeugs 
![torque](https://user-images.githubusercontent.com/71411042/106129567-a6e96380-6160-11eb-9e73-137a89644339.png)

**Comment by Mogli12** [comment]
Ah, stimmt, da habe ich nicht genau genug hingeschaut. 

Am besten nimmt man in der neuesten Version von VCA die Drehmomentkurve "klassisch (20% Anstieg)". In Moddeleichers Version sind es sogar nur 10% Anstieg, aber das ist unten herum auch ziemlich mau.

**Comment by MBTrac366** [comment]
Danke für den Tipp, schaue ich mir heute Abend mal an

**Comment by xBrinkix** [comment]
Moin, 

hab auch noch mal getestet heute und der Fehler bleibt doch bestehen. 
Hier die Bilder von den Einstellungen zur Zeit. Kann weder vor noch zurück fahren. 

![Unbenannt1](https://user-images.githubusercontent.com/78072035/106197016-729e9300-61b2-11eb-893e-6e46d6a0467e.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/78072035/106197027-74685680-61b2-11eb-8a86-fde6f6c56abd.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/78072035/106197030-76cab080-61b2-11eb-851b-579df2a4b527.PNG)

**Comment by Mogli12** [comment]
Hallo,

es liegt an der Drehmomentkurve im Fiat 1300 DT. Der Traktor ist ohnehin für Modelleichers Real Manual Transmission gedacht.

Viele Grüße
