### ISSUE TITLE
Beim Beschleunigen schießt die  Drehzahl hoch und Fahrzeug beschleunigt nicht

### ISSUE THREAD

**Issue by Ernst1512** [Mogli12/VehicleControlAddon#522]
Moin, 
wenn ich mit einem Fahrzeug mit beliebigem Getriebe beschleunigen möchte, geht die Drehzahl rasant nach oben un der Beschleunigungsvorgang stoppt bei ca. 5 km/h. Aus einem Discord-Server habe ich eine Problemlösung gefunden. Man muss im Allradreiter die Nennleistung auf 9999999999 stellen und die Kupplung auf Turbo stellen. So kann man das Problem umgehen. 
So funktioniert es dann aber der Nennleistungswert ist dann leider unrealistisch.
Liebe Grüße

**Comment by Mogli12** [comment]
Hallo,

die Nennleistung sollte man bitte nicht umstellen, um diese Problem zu lösen. Bitte machen doch einen Screen Shot von den VCA Settings und vom fahrenden Fahrzeug.

Danke

**Comment by Ernst1512** [comment]
Moin,
sorry das es etwas länger gedauert hat, aber ich hatte Nachtschicht. Hier sind die Screenshots aus den Settings. Allerdings kam bei mir jetzt noch das Problem dazu, dass ich mit W und S nicht mehr beschleunigen bzw. bremsen kann. Das Problem mit der hohen Drehzahl konnte ich beheben, da ich die Geschwindigkeiten der Gänge im eigenen Getriebe aus versehen verändert habe
Liebe Grüße
![Bild_2021-01-28_104051](https://user-images.githubusercontent.com/78075994/106119279-4acd1200-6155-11eb-806b-23f1bd765218.png)
![Bild_2021-01-28_104102](https://user-images.githubusercontent.com/78075994/106119298-515b8980-6155-11eb-8047-7bee043df72f.png)
![Bild_2021-01-28_104225](https://user-images.githubusercontent.com/78075994/106119447-836ceb80-6155-11eb-815e-019e2af3e356.png)
![Bild_2021-01-28_104251](https://user-images.githubusercontent.com/78075994/106119499-92ec3480-6155-11eb-9819-d11e41e85b6b.png)

**Comment by Mogli12** [comment]
Bitte probiere doch mal die aktuelle Version hier auf Github. Leider fehlt der Screenshot vom 3. Tab und ein Screenshot vom Fahrzeug wenn das Problem auftritt. Ich vermute mal, dass das Fahrzeug einfach nicht hoch schaltet.

**Comment by Mogli12** [comment]
Hallo Ernst,

bitte probiere es mit dieser Version: [FS19_VehicleControlAddon.zip](https://github.com/Mogli12/VehicleControlAddon/blob/master/FS19_VehicleControlAddon.zip?raw=true).

Viele Grüße
