### ISSUE TITLE
2x6 Komplikationen mit G-Shiftern 

### ISSUE THREAD

**Issue by Dave467** [Mogli12/VehicleControlAddon#523]
Guten Morgen mogli,

**(habe den Text ausm Giants Forum nur hierher kopiert. Die benötigten Logs und Screens kommen heute Abend.)**

bin mit meinen MP Kollegen wahre Fans deines Mods. Tolle Arbeit die du da leistest. Vielen Dank.

Eine Frage hätte ich allerdings, da ich hier nichts im Netz oder Discord gefunden habe:

Wenn man das 2x6 Getriebe nutzen möchte, dann verstehe ich das so, dass man zwei Mal das "normale" Sechsganggetriebe hat, jeweils untersetzt und "normal".
Wenn ich dies dann jedoch mit einem Shifter der G2x Reihe schalten möchte (probiert mit einem G25, G27 & G29 Shifter) springt die Gruppe von vor eingestelltem LOW und 1. Gang in den HIGH 2. Gang und verbleibt im HIGH Bereich, was ab und zu dazu führt, dass dann die Kiste absäuft, gerade im Feld wo ja dann die LOW Gänge geschaltet werden sollte.

Gibt es eine versteckte, oder für uns nicht bekannte Funktion wo man mit der 6-Gangschaltung im jeweiligen Gangbereich bleibt und erst durch einen gewollten Knopfdruck die Gruppe wechselt?

Gerne können wir ein yt-vid beifügen indem die Schaltvorgänge dargestellt werden, wenn du das möchtest.

Viele Dank schonmal für deine Mod und eventuell Hilfe bei obenstehendem Problem.

Viele Grüße
Dave

**Comment by Mogli12** [comment]
Hallo Dave,

kannst Du eventuell Screen Shots von den VCA Settings (Getriebe) machen? Zum Umschalten zwischen Low und High gibt es eine eigene Taste, nämlich vcaShifterLH ("VCA: G27/G29 Gang Splitter"). Aber automatisch sollte das nicht Schalten.

Viele Grüße,
Stefan

**Comment by Dave467** [comment]
Hi mogli, 

mittlerweile habe ich die Video soweit aufgenommen. 
Du hast Recht: Mittlerweile schaltet es wirklich nichtmehr hin und her. Das muss eine ZwischenVersion hier vom GitHub gewesen sein (mein Beitrag im Giantsforum ist ja auch schon paar Updates her).

Was wir aber jetzt herausgefunden haben, ist, dass die Rangebereiche (LOW oder HIGH) miteinander auf einer Belegung sind:

Sprich (ich will im LOW Bereich starten):

L1 = GANG 1
L2 = GANG 3
L3 = GANG 5

H1 = Gang 2
H2 = Gang 4
H3 = Gang 6

Dann nutze ich den VCA: G27/G29 Gang Splitter zum wechseln der Getriebegruppe in HIGH:

L4 = Gang 1 (wieder)
L5 = Gang 3
L6 = Gang 4

H4 = Gang 2
H5 = Gang 4
H6 = Gang 6

Hier die LOG des Testes (nur die offi. DLCs und deine Version ausm GitHub im Mod-Ordner)

[logDL.txt](https://github.com/Mogli12/VehicleControlAddon/files/5880553/logDL.txt)
![20210127104618_1](https://user-images.githubusercontent.com/78076662/105999316-d25f4600-60ad-11eb-9bfa-d5b16de17fe5.jpg)
![20210127110940_1](https://user-images.githubusercontent.com/78076662/105999326-d4c1a000-60ad-11eb-82cb-b4146c12ad4f.jpg)

Die Videos werde ich dir heute Abend hier einfügen. Da habe ich dir auch die Einstellungen im VCA 

Viele Grüße
Dave

**Comment by Mogli12** [comment]
HI Dave,

das Problem könnte sein, dass du auch die Tasten für Gang rauf/runter und Gruppe rauf/runter belegt hast. Man kann eigentlich nur die G27 Tasten oder die anderen für Gang- und Gruppenwechsel. Wenn man eine G27-Taste betätigt, dann schaltet sich VCA für Gang- und Gruppenwechsel in den G27-Modus. Wenn man nun aber die normalen Tasten für Gang- und Gruppenwechsel verwendet, dann wird der G27-Modus ausgeschaltet.

Viele Grüße

**Comment by Dave467** [comment]
Hi mogli,
meinst du wirklich? Ich kann die Tastenkombinationen heute mal testen, wenn ich diese lösche. 
Dann sollte es gehen? 

Ich berichte. 

Viele Grüße

**Comment by Mogli12** [comment]
Hi Dave,

ich hoffe, dass es dann geht. Du kannst vom 2x6 mit der Taste vcaShifterLH ("VCA: G27/G29 Gang Splitter") den Bereich wechseln. Ich habe zwar keinen LKW Führerschein, aber ich denke, dass in Echt am Ganghebel ein kleiner Kipphebel ist, um zw. 1..6 und 7..12 zu wechseln.

Viele Grüße

**Comment by Dave467** [comment]
Hallo Mogli, 

ich kenn es nur vom Unimog, und mein MP-Kumpel als Landwirt von den vielen Youngtimer-Traktoren: 

Es gibt dort halt eine Art kl. Kipphebel, mit welchen man dann in die Kriechganggruppe (bei dir in VCA wäre das dann der Bereich LOW) schalten würde, der Hebel bleibt gesetzt. Dann hat man die sechs bzw. acht Kriechgänge (beim Unimog z.B.) zur Verfügung und schaltet hier ganz normal zwischen den Gängen. Möchte man nun in die "normale" Gruppe wechseln legt man den den Gruppenhebel (ich nenne den kl. Kipphebel jetzt mal so) zurück auf das Symbol "Hase" (was, bei dir der HIGH Bereich wäre für die schnelleren Gänge und ). Dann kann man eben die schnellen Gänge z.B. auf der Straße benutzen. Und deshalb war für mich bei der Belegung der Tasten ganz klar, dass du diesen Schaltablauf dir überlegt hattest. Ehrlich gesagt, auf die Idee, dass der Gangsplitter dafür benutzt werden sollte, wäre ich niemals gekommen. 

Deshalb war ja auch meine Frage im Vid, ob das nicht eventuell wechselbar wäre...

Viele Grüße

**Comment by Mogli12** [comment]
Hall Dave,

ich habe den Fehler gefunden und mit Build 326 behoben.

Viele Grüße

**Comment by Dave467** [comment]
Hallo mogli,

wunderbar. Vielen Dank, werde ich gleich mal testen!

Viele Grüße
Dave

**Comment by Dave467** [comment]
V
