### ISSUE TITLE
Gänge schalten geht nicht mit Anhänger

### ISSUE THREAD

**Issue by MrKoka25** [Mogli12/VehicleControlAddon#528]
Hallo,
als erstes mal ein lob an den Mod es macht mega spass damit.
Leider habe ich das Problem das wenn ich einen Anhänger anhänge das ich die Gänge nicht mehr schalten kann die Gruppen hingegen schon. Vllt weis ja jemand woran das liegen kann.
Allen noch einen schönen abend

**Comment by Mogli12** [comment]
Hallo,
das könnte eine Doppelbelegung sein. Ist der Anhänger oder der Traktor ausgewählt? Das passiert z.B. auch bei der Abschleppstange.
Viele Grüße

**Comment by MrKoka25** [comment]
Habe mal nachgeschaut und ja war eine doppelbelegung. Danke für die schnelle Antwort und danke für deine Super Arbeit.
