### ISSUE TITLE
"hard launch"

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#529]
Hi Stefan, mit 323 hattest du den harten launch ja etwas verbessert, aber ich denke, dass geht immer noch zu "brutal ab". Auch die Wendeschaltung ist in vorherigen Versionen sanfter von statten gegangen. Kann man das noch eine Tick sanfter gestalten?

Schoene Gruesse

Claudio

**Comment by cabmac** [comment]
moin...ich glaube, dass kann man so  lassen mit 329...(mMn)

Schoene Gruesse

**Comment by Mogli12** [comment]
Ist halt immer ein Kompromiss...

**Comment by cabmac** [comment]
von mir aus wuerde ich es mir sogar noch ein bisschen sanfter wuenschen, aber dann gibts ja wieder andere, die wollen es dann nicht so "sanft"...aber wie gesagt, ich denke, so gehts ganz gut...

**Comment by Mogli12** [comment]
Das Problem ist, dass man ansonsten die Drehzahl beim Anfahren nicht hoch genug bekommt und der Traktor absäuft. Daher muss VCA auch ziemlich mit der Trägheit herumspielen.
