### ISSUE TITLE
Gas und Bremse funktionier nicht 

### ISSUE THREAD

**Issue by nquixv2** [Mogli12/VehicleControlAddon#532]
Moin,
ich habe ein Problem mit dem Gas und der Bremse. Manchmal kann ich Nicht Bremsen und kein Gas geben. Im Multiplayer habe nur ich als Host dieses Problem. Ist das vielleicht ein Problem in den Einstellungen oder ist es ein Mod Konflikt? 

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5932114/log.txt)

**Comment by Mogli12** [comment]
Hallo,

wahrscheinlich bist Du irgendwie in Neutral gelandet. 

Viele Grüße

**Comment by nquixv2** [comment]
Okay, ich probiere mal ein bisschen rum, wenn das Problem weiterhin besteht schreibe ich noch mal.

**Comment by Mogli12** [comment]
Bitte mache auch einen Screenshot.

**Comment by leo32128fs** [comment]
I had this problem a lot using the REA mod I took it out and the problem was fixed

**Comment by leo32128fs** [comment]
I had this problem a lot using the REA mod I took it out and the problem was fixed

**Comment by Mogli12** [comment]
How much wheel slip did you have? I use REA mod as well.

**Comment by leo32128fs** [comment]
it got me into trouble in the corners even without a high level of sliding, when the vehicle did a certain speed, just shot on the map or stayed in the same place skating until the fuel ran out

**Comment by leo32128fs** [comment]
so I took it out and the problem was never repeated

**Comment by leo32128fs** [comment]
and even without the VCA it still makes the same mistake I think the problem and the mod rea

**Comment by nquixv2** [comment]
Moin, leider konnte ich das Problem mit dem entfernen des REA Mods nicht beheben. Ich habe leider keine Ahnung was ich in den Einstellungen des VCAs ändern soll damit dieses Problem behoben werden kann. Zudem bin ich ach nicht im Neutralgang. 

LG

**Comment by nquixv2** [comment]
Bei welchen Mods gibt es denn mit dem VCA Konflikte

**Comment by Mogli12** [comment]
Hallo,

ich habe keine Ahnung, was bei Dir passiert. Ich kann Dir versichern, dass bei mir Gas und Bremse funktionieren. Da hier weiterhin keine Details zum Problem kommen, schließe ich das Issue. Bitte nur mit log.txt und Screenshot wieder auf machen.

Viele Grüße,
