### ISSUE TITLE
are the guidelines in the following photo from this mod

### ISSUE THREAD

**Issue by matthewjessee16** [Mogli12/VehicleControlAddon#533]
[
![Farming Simulator 19 Screenshot 2020 12 21 - 18 31 28 57](https://user-images.githubusercontent.com/58116173/107080578-7ee0ac80-67bf-11eb-91ce-e26fd7af10ed.png)
](url)

**Comment by Mogli12** [comment]
Yes

**Comment by Mogli12** [comment]
Just press LCrtl+W to activate it. You can bring up the settings menu of VCA with LCrtl+C.

**Comment by matthewjessee16** [comment]
I found a YouTube video that stated that

**Comment by Mogli12** [comment]
I think this can be closed? Or are there still open question? If yes, please re-open this issue.
