### ISSUE TITLE
Feature request: "own setup" als preset speichern

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#534]

**Comment by Gordon-Dry** [comment]
Ich habe mir gerade die Werte des TW 902.2 Getriebes des Deutz-Fahr AgroStar 4.78 von hier geholt
https://de.wikibooks.org/wiki/Traktorenlexikon:_Deutz-Fahr_AgroStar_4.78
und danach bestmöglich in VCA eingepflegt.

Wenn ich dieses Setup als Vorlage speichern könnte, wäre das eine große bereicherung.

**Comment by Mogli12** [comment]
Hi,

I wanted to add this feature for a long time, but failed to add context sensitive buttons to the tabbed menu. 

After this was clarified, I can now present build 331.

Regards,
Stefan

**Comment by Gordon-Dry** [comment]
Sieht schon ganz gut aus. 
Allerdings ist die Syntax der Presets anders als die aus der
Documents\My Games\FarmingSimulator2019\modsSettings\FS19_VehicleControlAddon\transmissions.xml
und erschließt sich mir noch nicht ganz.

**Comment by Mogli12** [comment]
Es steht ja hier schon auf der Startseite:
> If you are looking for a realistic manual transmisison please visit FS19_realManualTransmission
Die gibst einfach die Geschwindigkeit bei Nenndrehzahl im 1. und im höchsten Gang ein, und VCA berechnet alle Gänge dazwischen. Bei Gruppen ist es ähnlich. Man kann zum einen die Endgeschwindigkeit im höchsten Gang der vorletzten Gruppe, und dann noch die Geschwindigkeit im 1. Gang der untersten Gruppe eingeben. 

Manuelles Editieren der XML Dateien ist dagegen nicht vorgesehen.

**Comment by Gordon-Dry** [comment]
Manche Getriebe haben ja andere Übersetzungen und Endgeschwindigkeiten für die Rückwärtsgänge.
Manche haben sogar weniger Rückwärtsgänge (in nur einer Gruppe) als in den Vorwärtsgruppen.

Ist RMT 100% manuell oder hat es auch Automatik?

**Comment by Mogli12** [comment]
Man kann doch mit Komma getrennt die Liste der Rückwärtsgänge und -gruppen eingeben. Dazu kann man noch einen Faktor für die Rückwärtsgänge eingeben.

`1,` 3, `5

wählt dann von 5 (oder mehr) Gängen nur die Gänge 1, 3 und 5 für Rückwärts aus.

**Comment by Gordon-Dry** [comment]
Ich hatte mir ja für die Schlüter-Modelle die verschiedenen Einträge in die Documents\My Games\FarmingSimulator2019\modsSettings\FS19_VehicleControlAddon\transmissions.xml eingepflegt und das funktioniert auch soweit ganz gut.
Aber wie definiere ich dort Rückwärtsgänge und -gruppen?
Die beiden bereits enthaltenen Test-Presets haben ja keine Angaben dazu.

**Comment by Mogli12** [comment]
Das geht dort nicht. Die transmission.xml ist ein Auslaufmodell.

**Comment by Gordon-Dry** [comment]
Nun gut, dann werde ich die configs noch mal neu ingame basteln und dann als preset exportieren, um "zukunftsfähig" zu sein.
Müssen die Presets immer einen Dateinamen haben, der mit "ownTransmission" beginnt?
