### ISSUE TITLE
Gänge der Rückwärtsgruppe werden nicht automatisch geschaltet bei "own configuration"

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#536]
Es wird der Gang ausgewählt, der dem 1. Gang der aktuellen Vorwärtsgruppe am ehesten entspricht und bei dem bleibt es.

Manuelles Durchschalten geht, bringt die Automatik aber nicht dazu, es danach auch zu tun.

**Comment by Mogli12** [comment]
Sorry, aber die Problembeschreibung ist einfach zu kurz.
