### ISSUE TITLE
The VCA configuration screen does not open in multiplayer mode

### ISSUE THREAD

**Issue by leo32128fs** [Mogli12/VehicleControlAddon#540]
the VCA configuration screen does not open in multiplayer mode. I will attach a video showing

https://drive.google.com/file/d/1-4pmej7K8ojD27nQb3SQETB1sP2U2tK1/view?usp=sharing

**Comment by Mogli12** [comment]
Please attach the log file of server and client.

**Comment by leo32128fs** [comment]
I don't know how to save this file, but I have this
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5937548/log.txt)

**Comment by leo32128fs** [comment]
I'm still a layman in this matter

**Comment by Mogli12** [comment]
Hi,
Thanks for the log.txt. That was perfect.
Best regards

**Comment by Dave467** [comment]
Same by me... 
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5937606/log.txt)

**Comment by leo32128fs** [comment]
please i am here to help you with whatever is needed with the mod, thanks for the excellent work

**Comment by Mogli12** [comment]
Please try build 332

**Comment by leo32128fs** [comment]
ok i will test now

**Comment by leo32128fs** [comment]
now it seems to be perfect, the problem is not repeated

**Comment by Mogli12** [comment]
Good
