### ISSUE TITLE
Gas und Bremse funktioniert nicht

### ISSUE THREAD

**Issue by nquixv2** [Mogli12/VehicleControlAddon#541]
Es funktioniert nur ohne Getriebe. mit einen Getriebe kann ich nicht Bremsen oder kein Gas gen. Und was soll ich für ein Screenshot schicken, wenn man nicht drauf erkennt wo das Problem ist, oder kannst du in durch die Einstellung hindurchsehen?? Irgendwann platzt mir der Kragen, wenn einem (selbst nicht vom Modder) geholfen werden kann :/

**Comment by nquixv2** [comment]
Es ist jetzt das Dritte mal, das ich hier anfrage, und mir kann nicht geholfen werden, sondern die Issue wir immer nur aus keinem Grund geschlossen. Wo kann man hier bewerten?

**Comment by nquixv2** [comment]
![Uploading VCA.png…]()

**Comment by nquixv2** [comment]
Hier ein Bild...aber keine Ahnung wozu

**Comment by Mogli12** [comment]
Lies bitte die README.md:

> If you're still ok with this, please remember to post possible issues that you find in the developer version. That's the only way we can find sources of error and fix them. Be as specific as possible:
>
> * tell us the version number
> * only use the vehicles necessary, not 10 other ones at a time
> * which vehicles are involved, what is the intended action?
> * Post! The! Log! to Gist or PasteBin
>
> From today on I will close all new issues without the above information!

**Comment by Mogli12** [comment]
Also, hier nochmal ein paar Informationen:
Ich spiele auf der neusten LS Version und auf der neusten VCA Version.
Ich habe einen Server gemietet und spiele ihn mit 2 weiteren Freunden.
Nur ich habe dieses Problem mit dem Gas und der Bremse. Meine Mitspieler können Problemlos den VCA nutzen. Wichtig: Ich kann nur dann nicht fahren, wenn irgendein getriebe aktiviert ist! Wenn ich Getriebe auf off stelle ist alles normal und ich kann fahren.
Gibt es vielleicht irgendein Mod der sich nicht mit dem VC verträgt?
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5953220/log.txt)
![VCA](https://user-images.githubusercontent.com/8790374/107405911-1fa8d200-6b08-11eb-91ff-b7c571ffea68.png)

**Comment by Mogli12** [comment]
Hallo,

ich habe den Verdacht, dass es ein Problem mit Deiner inputBinding.xml gibt. Die Datei im normalerweise in ...\My Games\FarmingSimulator2019.

Ich würde die Datei mal umbenennen. Beim nächsten Start wird dann eine neue Datei angelegt. Solle das nicht das Problem sein, dann hast Du ja immer noch die alte, umbenannte Datei. 

LG Stefan

**Comment by Mogli12** [comment]
Nur nochmal zum Verständnis. Du startest auf Deinem Rechner ein MultiPlayer Spiel. Das läuft auf Deinem Rechner, nicht auf einem Dedi-Server, richtig? Dann kommen Deine beiden Freunde dazu. Nachdem einer von beiden im Fahrzeug war, kannst Du es nicht mehr fahren.

Läuft es ungefähr so?

**Comment by nquixv2** [comment]
Ja so ist es richtig, außer das der Server Momentan auf einem Dedi läuft. Vorher ging es im normalen Multiplayer aber auch nicht.

**Comment by nquixv2** [comment]
So, ich habe das mit der inputBindin.xml mal ausprobiert. Auf den ersten Blick sieht es gut aus. Ich spiele mal eine Weile und schreibe dann nochmal. :)

**Comment by nquixv2** [comment]
Moin, es hat sich alles geklärt! Tatsächlich war es die inputBindin.xm, die den Fehler ausgelöst hat. 
Danke, dass du mir doch noch helfen konntest. Kuss an dich Mogli und noch viel Erfolg. Freue mich schon auf die kommenden Updates! Ich werde die Issue dann schließen! <3 
LG Jonas
