### ISSUE TITLE
Setting up a custom tranmission - gear speed configuration

### ISSUE THREAD

**Issue by tdiniz93** [Mogli12/VehicleControlAddon#542]
I've been a long time user of your mod, and I am now getting into the transmissions.xml file, where I'm trying to setup a John Deere Quad-Range transmission, among others, but I don't understand what information I need to fill in the "speed" part of this area:
`	<gear speed="50"  text="1"   forwardOnly="false"/>`

I was able to figure out the range ratios, but I don't understand what gear speed is.

This is what I have so far:
```
	<transmission label="Quad-Range" numberOfGears="4" gearShiftTimeMs="0" rangeShiftTimeMs="750" autoShiftGears="false" autoShiftRanges="false">

		<gears shiftTimeMs="750" baseSpeed="180">
			<gear speed="50"  text="1"   forwardOnly="false"/>
			<gear speed="70"  text="2"  forwardOnly="true"/>
			<gear speed="95"  text="3" forwardOnly="true"/>
			<gear speed="130" text="4"  forwardOnly="true"/>
		</gears>
		<ranges shiftTimeMs="750">
			<range ratio="0.235" text="A" />
			<range ratio="0.555"   text="B"/>
			<range ratio="0.647" text="C" />
			<range ratio="1.0"   text="D" forwardOnly="true"/>
		</ranges>
	</transmission>	
```

Thanks.

**Comment by Mogli12** [comment]
Hi,

The idea is the specify the maximum vehicle speed in baseSpeed, e.g. 43 km/h. If the vehicle reaches this speed in highest gear at rated RPM, then the speed of 4th gear would be 43 again. 

VCA calculates `ratio = speed / baseSpeed`.

Best regards,
Stefan
