### ISSUE TITLE
Stationary vehicles

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/VehicleControlAddon#543]
Hello. There are many cars on the HofBergmann map that do not have wheels. They are stationary. For example feed mixers. I am getting an error when using them. 

Error in updateWheelsPhysics :E:/FARMING_SIMULATOR/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua:5736: bad argument #2 to 'min' (number expected, got nil)

Previously, it was not there, it appeared recently, but from which version I did not notice.

Can any exception be made for them? If you need more information about these machines, please contact us. Thank.

**Comment by Mogli12** [comment]
Please post the complete log. I cannot help with a single line.

**Comment by Gonimy-Vetrom** [comment]
Here. 
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/5976018/log.txt)

Tested on two versions that I still have: build 319 and 335.
The error occurs when I start the engine. The first mixing process goes well. But the second may not start. I need to restart the game.

**Comment by Mogli12** [comment]
Please try the latest build. If it still does not work, please reply with a new log.txt.
Thanks

**Comment by Gonimy-Vetrom** [comment]
Seems to work without error. I'll play a little. If something changes, then I'll let you know. Thanks.

**Comment by Gonimy-Vetrom** [comment]
In order not to create a topic, can I ask another question? When using the equipment as in the picture, sometimes when unloading a bale from the first chamber to the second, the mower turns off. :) It seems that the tractor lacks power. Is there such a function in your mod, or is the problem in something else?
![fsScreen_2021_02_14_15_22_02](https://user-images.githubusercontent.com/8200153/107878062-e93ccf80-6ed8-11eb-925f-507a2edd3e9a.png)

**Comment by Mogli12** [comment]
Maybe there is a function that turns off equipment if there is too little power. But it is not part of VCA.

**Comment by Gordon-Dry** [comment]
Perhaps the pto power needed when pushing out a bale is higher than the "normal" pto usage. Which baler is it?

**Comment by Mogli12** [comment]
The brown indicator above the speedometer shows some damage. This reduces the available torque. The maximum damage torque reduction is 30%. Based on your picture I would estimate an actual reduction by 20%.

Both equipment together need 230 HP according to shop menu. The peak power of the tractor is 258 HP, reduced by 20% => 207 HP.

**Comment by Gonimy-Vetrom** [comment]
> Which baler is it?
Vicon FastBale (DLC)+Vicon Extra 732FT (DLC)
Now I'm trying to repeat this on a vanilla map and almost without mods.

**Comment by Mogli12** [comment]
I think the vanilla game does it.

**Comment by Gonimy-Vetrom** [comment]
After unloading a stationary car, I received this error. After that, it is not possible to drive the car: a new production process cannot be started.
Later I will conduct an experiment without mods, then I will add the entire log.

2021-02-19 21:28 Warning (script): 'setMotorProperties': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-02-19 21:28   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-02-19 21:28 LUA call stack:
2021-02-19 21:28   dataS/scripts/vehicles/specializations/Motorized.lua (1609) : setMotorProperties
2021-02-19 21:28   =E:/FARMING_SIMULATOR/mods/FS19_VehicleControlAddon/vehicleControlAddon.lua (7116) : superFunc
2021-02-19 21:28   dataS/scripts/vehicles/specializations/Motorized.lua (356) : updateMotorProperties
2021-02-19 21:28   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2021-02-19 21:28   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
2021-02-19 21:28   dataS/scripts/network/NetworkNode.lua (98) : update
2021-02-19 21:28   dataS/scripts/network/Server.lua (58) : updateActiveObjects
2021-02-19 21:28   dataS/scripts/BaseMission.lua (1500) : update
2021-02-19 21:28   dataS/scripts/FSBaseMission.lua (1979) : update
2021-02-19 21:28   dataS/scripts/missions/mission00.lua (469) : update
2021-02-19 21:28   dataS/scripts/main.lua (1944) : update

**Comment by Mogli12** [comment]
Hi,

laut https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=32&class=374#updateMotorProperties4983 ist argument 1 spec.motorizedNode. Da manipuliert VCA nichts. Ohnehin macht VCA nicht so viel in updateMotorProperties. Ich kann mir daher nur schwer vorstellen, warm VCA dafür verantwortlich sein soll, dass motorizedNode plötzlich leer ist.

Viele Grüße

**Comment by Gonimy-Vetrom** [comment]
Got it. I was also alarmed that there are so many different errors at once.

**Comment by Mogli12** [comment]
Hi,

Sorry for switching to German. Based on the error message I think that self.spec_motorized.motorizedNode is empty (nil). I have no idea how this happened. VCA just changes minRpm and maxRpm and then calls the original implementation. That is why I do not believe that VCA caused the bug.

Best regards
