### ISSUE TITLE
Sim-Dashboard

### ISSUE THREAD

**Issue by Mike-Juli** [Mogli12/VehicleControlAddon#544]
Servus,

Schnelle Frage, Schnelle Antwort...

Ist es möglich trotz VCA-Mod, die Motorumdrehungen in der Applikation  anzeigen zu lassen?

Denn bei mir sieht man nur die Idle und Max PTO (wenn aktiv) Drehzahl.

LG.
Mike

**Comment by Mogli12** [comment]
Hallo Mike,

Ja, das geht. Allerdings muss man dazu 
```lua
local motor = self:getMotor()
local rpm = motor:getEqualizedMotorRpm()
```
verwenden.

Viele Grüße

**Comment by oschuhm** [comment]
> Hallo Mike,
> 
> Ja, das geht. Allerdings muss man dazu
> 
> ```lua
> local motor = self:getMotor()
> local rpm = motor:getEqualizedMotorRpm()
> ```
> 
> verwenden.
> 
> Viele Grüße

Hi,
das müsste ich aber dann auf Sim Dashboard Seite ändern?
VG
Oliver

**Comment by Mogli12** [comment]
Hi,
wie mach Sim Dashboard das denn bislang? Da motor.equalizedMotorRpm in [VehicleMotor:update](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=41&class=450#update6463) gesetzt wird, lässt sich das schwer mit dem korrekten Wert überschreiben.

Daher sollte man - wie Giants auch - besser die Funktion getEqualizedMotorRpm() verwenden.

Viele Grüße

**Comment by oschuhm** [comment]
Hi Stefan,
leider wurde der Sim Dashboard Lua Code unkenntlich gemacht.
Da kann man nicht wirklich etwas draus lesen.
Deswegen kann man aktuell zumindest nicht selbst Änderungen und Anpassungen vornehmen.
VG
Oliver
