### ISSUE TITLE
Frage zu own Config Getriebe. 

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#545]
Wie verwendet man korrekt die Rückswärsgruppe und Gänge? Nachdem ich mir die Anzahl der Gruppen und Gänge erstellt habe lassen sich diese leider nicht schalten. Es ist immer der größte Rückwärtsgang eingelegt. Vllt hast du für mich einen Anwendungs Tipp

MfG Chris

**Comment by Gordon-Dry** [comment]
@ChrisJD8400R 
hier mal ein Beispiel:
```
<ownTransmission>
    <name string="Deutz-Fahr AgroStar 6.81 (H 6165 VDT)"/>
    <maxSpeed float="11.138889"/>
    <gearFactor float="0.246883"/>
    <rangeFactor float="0.264339"/>
    <range1st1st float="0.012469"/>
    <gears int="9"/>
    <ranges int="3"/>
    <gearTime int="125"/>
    <rangeTime int="375"/>
    <autoGears bool="true"/>
    <autoRange bool="false"/>
    <splitG27 bool="true"/>
    <revRatio float="1.089776"/>
    <g27Mode int="10"/>
    <regGears>
        <regGear int="1"/>
        <regGear int="2"/>
        <regGear int="3"/>
        <regGear int="4"/>
        <regGear int="5"/>
        <regGear int="6"/>
        <regGear int="7"/>
        <regGear int="8"/>
    </regGears>
    <revRanges>
        <revRange int="1"/>
        <revRange int="2"/>
        <revRange int="3"/>
    </revRanges>
</ownTransmission>
```

**Comment by Mogli12** [comment]
Hi Chris,

In "Lister der ..." trägt man die jeweiligen Nummern mit Komma getrennt ein und drückt dann Enter.

Im Beispiel oben ist der 9. Gang nur Vorwärts möglich. Im UI sieht man dann:
`1, 2, 3, 4, 5, 6, 7, 8`

Die Einstellungen werden unter dem Namen ownTransmission<Zahl>.xml im FS19_VehicleControlAddon Unterverzeichnis von modsSettings gespeichert. Dabei ist <Zahl> eine ein- oder zweistellige Ziffer. Da dürfen auch Lücken drin sein. Man kann die Dateien hoffentlich untereinander tauschen.

Erstellen sollte man die Dateien aber immer direkt im Spiel über die VCA Einstellungen.

Hier ist mal ein Fendt 615 LSA:
[ownTransmission2.zip](https://github.com/Mogli12/VehicleControlAddon/files/5989820/ownTransmission2.zip)

Pack die Datei doch einfach mal in den entsprechenden Order und lade sie in VCA.

Viele Grüße

**Comment by ChrisJD8400R** [comment]
Danke für die Antwort. Ich meine in dem von dir vorgesehenen own Config, ingame. Da tippt man ja nur alles ein. Weil dort kann ich die Rückwärtsgänge nicht schalten 🙂

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Feb. 16, 2021 at 16:54 schrieb Stefan Biedenstein<notifications@github.com>:   


Hi Chris,

In "Lister der ..." trägt man die jeweiligen Nummern mit Komma getrennt ein und drückt dann Enter.

Im Beispiel oben ist der 9. Gang nur Vorwärts möglich. Im UI sieht man dann:
1, 2, 3, 4, 5, 6, 7, 8

Die Einstellungen werden unter dem Namen ownTransmission.xml im FS19_VehicleControlAddon Unterverzeichnis von modsSettings gespeichert. Dabei ist eine ein- oder zweistellige Ziffer. Da dürfen auch Lücken drin sein. Man kann die Dateien hoffentlich untereinander tauschen.

Erstellen sollte man die Dateien aber immer direkt im Spiel über die VCA Einstellungen.

Hier ist mal ein Fendt 615 LSA:
ownTransmission2.zip

Pack die Datei doch einfach mal in den entsprechenden Order und lade sie in VCA.

Viele Grüße

**Comment by Mogli12** [comment]
Die beiden Beispiele sind aus dem Own Config Bereich.

Ich schlage vor, dass Du - wie es auch schon hier auf der Startseite steht - das Problem mal um log.txt und Screenshot ergänzt. Nur so kann man sehen welche Mods in  welcher Version im Spiel verwendet werden.

**Comment by ChrisJD8400R** [comment]
Vielen Dank Stefan, ich werde mich darum kümmern. Ich könnte zur Not auch einen kleines Video aufnehmen und dazu sprechen. Ist vllt noch einfacher und schicke dir eine Link 🙂

MfG Chris

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Feb. 16, 2021 at 19:55 schrieb Stefan Biedenstein<notifications@github.com>:   


Die beiden Beispiele sind aus dem Own Config Bereich.

Ich schlage vor, dass Du - wie es auch schon hier auf der Startseite steht - das Problem mal um log.txt und Screenshot ergänzt. Nur so kann man sehen welche Mods in welcher Version im Spiel verwendet werden.
