### ISSUE TITLE
Snap angle question

### ISSUE THREAD

**Issue by kylemeyer13** [Mogli12/VehicleControlAddon#547]

**Comment by kylemeyer13** [comment]
Sorry for screwing up when posting. This is less of a issue than a question about the snap angle. We recently updated VCA on our dedi and we have noticed that the snap angle no longer rotates 90 degrees like it used to. We personally loved this function in the older version version. Now it seams that even if we set the width to zero it still snaps back to that original line. Is this a new function or is there a way to make it act like it used to without reverting to the old version.

**Comment by Mogli12** [comment]
Hi,

I removed that feature so that the snap angle works every 180°. I added an option (2nd last in 1st column of 1st tab) to switch back to 90°.

Best regards.
