### ISSUE TITLE
Variable zum Tausch von Gang- und Gruppentastenbelegung

### ISSUE THREAD

**Issue by D9005** [Mogli12/VehicleControlAddon#548]
Hallo Stefan,
mittlerweile gibt es im Netz ja schon einige vorgefertigte Getriebe für dein VCA. Bei einigen sind jedoch die Gänge als Gruppe und andersrum die Gruppen als Gänge eingetragen. 
Man kann jetzt natürlich jedesmal die Tastenbelegung ändern, damit es funktioniert wie gewünscht, was jedoch irgendwann nervig wird 😅
Meine Frage/ Idee wäre jetzt, ob man in den VCA Variablen eine Abfrage implementieren könnte, die einen Wechsel der Tastenbelegung für Gang und Gruppen bewirkt. 
Ich hab aber keine Ahnung wie aufwendig das wäre, daher betitel ich das mal als "Luxusproblem" 😂

Vielen Dank im Voraus. 

Mfg D9005

**Comment by Sirucool** [comment]
wäre es möglich die gruppen über die H Schaltung darzustellen wie es im Fend 500 c ist

**Comment by Mogli12** [comment]
Nein, die G27/G29 Gänge beziehen sich immer auf Gänge. Aber man kann sich die Gänge und Gruppen in "Own Configuration" doch so einstellen, dass es passt.

**Comment by Mogli12** [comment]
Hi D9005,

Mit Version 338 oder höher kannst Du im 3. Tab die Tasten für Gänge und Gruppen tauschen. Das wirkt sich allerdings nicht auf die G27/G29 Schaltung aus.

Viele Grüße

**Comment by D9005** [comment]
Hi Stefan,
Ausprobiert und definitiv für Gut befunden. 
Vielen Dank für die schnelle Umsetzung 🙂

MfG
