### ISSUE TITLE
Arbeitsgeschwindigkeit wird (bei den meisten Kombinationen) nicht erreicht

### ISSUE THREAD

**Issue by Gordon-Dry** [Mogli12/VehicleControlAddon#549]
Vorab:
Ich benutze auch REA, aber in diesem Fall habe ich genug Traktion auf dem Acker, keinen Schlupf und der Schlepper hat keine Probleme mit der Leistung, die Motorlast pendelt so bei 20-25% auf der Ebene und leicht bergauf so max. 30% dank Vario-Getriebe.
Zudem kann ich nicht mit Gewissheit sagen, dass es an VCA liegt.
Irgendwo muss ich jedenfalls anfangen zu suchen.

Es handelt sich um einen Fendt Vario 1050 E87 (soll wohl eine Chip-getunte und anderweitig aufgemotzte Version sein, der hat jedenfalls 625 PS statt 517).
Das Vario-Getriebe habe ich ausgewählt, alles ist korrekt eingestellt.

Gezogen wird eine Einzelkornsämaschine John Deere DB90 36-Row 30".

Arbeitsgeschwindigkeit soll 15 km/h sein, es wird max. 12 km/h gefahren.

Ich hatte das schon bei anderen Schleppern mit anderen Getrieben, dass die nie die Arbeitsgeschwindigkeit erreichen, egal ob leicht bergauf oder leicht bergab, egal ob feuchter oder trockener Boden.
Egal ob Schlupf oder super Traktion.

Mir kommt es so vor, als ob pauschal ca. 20% langsamer gefahren wird als die Arbeitsgeschwindigkeit.

Ausser, wenn alles passt. Aber das sind Ausnahmen.

**Comment by D9005** [comment]
Wie ist denn der Verschleißzustand der Sähaschine? Je weiter die Maschine abnutzt, umso geringer wird die Aebeitsgeschwindifkeit. Dadurch wird der Verschleiß simuliert.

Mfg

**Comment by Gordon-Dry** [comment]
Ah, gut zu wissen, darauf muss ich mal achten.

**Comment by Gordon-Dry** [comment]
Das war es. Ich hatte einen gemietete (und per Mod als "gebraucht" markierte) Sämaschine mit 73% Wartungsbedarf.
