### ISSUE TITLE
strange log 

### ISSUE THREAD

**Issue by denut** [Mogli12/VehicleControlAddon#551]
hello

i have sometimes problem by synchronising in multiplayer the loading stuck at 29%

but the strange things is that by opening console i see all vca action from other players

actuel vca version 333 but was sometimes append with other version

you can see it in the log file attached 

thank"s for you mod !!! have a good day

**Comment by denut** [comment]
[logvca.txt](https://github.com/Mogli12/VehicleControlAddon/files/6062535/logvca.txt)

**Comment by denut** [comment]
version 339 same problem

**Comment by Mogli12** [comment]
Please read the README.md.

**Comment by Lactic68** [comment]
@Mogli12 
Hi,
Is there a tool that will help to investigate what mod causes incorrect client-server communication please ?

**Comment by Mogli12** [comment]
I do not know any.

**Comment by denut** [comment]
hello

we have made some test and  we detected that if nowbody is in vehicle the 3 lines 
"Warning: mogliBase30Request received invalid NodeObject
Warning: mogliBase30Event received invalid NodeObject
vehicleControlAddon; vcaIsEnteredMP; true" are not present in the log 
but if somebody is in vehicle we get the 3 lines for eatch persones in vehicle

not sure it's a good info ??

**Comment by Mogli12** [comment]
Can you please attach all logs? The logs of all connected clients and the log.txt of the server?

**Comment by denut** [comment]
hello 
there is the 2 logs server and client
thank's
[log client.txt](https://github.com/Mogli12/VehicleControlAddon/files/6144035/log.client.txt)
[log server.txt](https://github.com/Mogli12/VehicleControlAddon/files/6144036/log.server.txt)

**Comment by Mogli12** [comment]
Please try build 344. But there are several other error messages in the log. As written in the README.md. The error message are typically caused but another mod with invalid MP code.

**Comment by denut** [comment]
344 is in test
