### ISSUE TITLE
Verbesserungsvorschlag: Hydraulik nur wenn Motor gestartet

### ISSUE THREAD

**Issue by MBTrac366** [Mogli12/VehicleControlAddon#552]
Hallo Mogli,

ich weiß nicht ob und wie es technisch umsetzbar wäre, allerdings glaube ich, dass die Funktion ganz gut zu VCA passen würde ;-)
Als Idee / Anregung, könnten man die Steuerung der Front- und Heckhydraulik und des Frontladers abhängig vom Motorstart machen?  

Grüße

**Comment by Dave467** [comment]
Coole Idee,  wäre definitiv eine Eigenschaft, die gut zu vca passen würde..

**Comment by niro2206** [comment]
Gute Idee! 

Für mich wäre auch interessant mehrere Gruppen schalten zu können mit eigenen Tasten: zb Gruppe L Shift+1 Gruppe M Shift +2 usw dadurch das ich vca und rmt nicht vermischen möchte und mir auch das Gesamtpaket bei vca einfach besser gefällt. 

Liebe Grüsse Daniel

**Comment by Mogli12** [comment]
Hallo,

meiner Meinung nach lässt sich das nicht einfach so umsetzen. Eventuell passt es zum WorkRPM Mod. Und mehrere Gruppen wird es in VCA nicht geben.

Viele Grüße
