### ISSUE TITLE
Stop-and -Go bei Drescher und Kompaktlader/Telelader etc.

### ISSUE THREAD

**Issue by NiklasWGC** [Mogli12/VehicleControlAddon#554]
Hallo Mogli,
hätte eine Frage.Und zwar spiele ich mit einem Joystick wo ich beim Drescher den Fahrhebel simuliere,bzw. wenn ich mit einem kompaktlader oder Telelader fahre mit Bremse und Gas ohne Shuttle control.Mir persönlich dauert der Wechsel von vorwärts hierbei allerdings zu lange,weil die Maschine für meinen Geschmakc zu lange stehen bleibt,vor allem da ich das aus real life anders kenne.Gibt es vielleicht eine Möglichkeit,wie ich mir das anpassen könnte?Habe schon in den luas geschaut,bin allerdings nciht fündig geworden.

LG
Niklas

**Comment by Mogli12** [comment]
Hallo Niklas,

Ist Stop-and-Go-Bremsung im Hauptmenu aktiviert?

LG Stefan

**Comment by NiklasWGC** [comment]
Ja,Stop-and-Go-Bremsung ist aktiviert.Wenn es hilft kann ich auch eine Aufnahme davon machen und genauer erklären worum es mir geht.Als Zusatzinfo wenn es hilft,wenn ich das Getriebe auf Off stelle,also Standard,dann wechselt er die Fahrtrichtung ohne stehen zu bleiben und dreht teilweise reifen durch.Für mich wäre es dann gut das er maximal 0,5s stehen bleibt damit die reifen stehen und dann direkt in rückwärtsgang übergeht und man nciht paar sekunden wartet,damit es flüssiger übergeht.
LG

**Comment by Mogli12** [comment]
Hast Du Stop-and-Go mal ausgeschaltet?

**Comment by NiklasWGC** [comment]
Ja habe ich gerade probier,dann dauert es noch länger und ich muss eeinmal pedal loslassen

**Comment by NiklasWGC** [comment]
Habe es probiert,ist schon deutlich besser.Welche Zeile muss ich denn wo ändern um mir das nochmal feiner anzupassen?

**Comment by Mogli12** [comment]
Wenn du das Coding selber änderst, dann kann ich keinen Support leisten.

**Comment by NiklasWGC** [comment]
Das ist logisch,habe ja in der build gesehen welche zahl du geändert hast.Die Änderung davon sollte ja ausreichen richtig?

**Comment by NiklasWGC** [comment]
Auf jeden Fall vielen Dank für deine Hilfe!
