### ISSUE TITLE
please add swap ranges and gears to shifter

### ISSUE THREAD

**Issue by panczeslaw** [Mogli12/VehicleControlAddon#555]
please add swap ranges and gears to shifter

**Comment by Mogli12** [comment]
Why? What is the transmission you are using? If it is an own configuration, why do you still need to swap it?

**Comment by panczeslaw** [comment]
i want this to change gears no using clutch but ranges changing on shifter

sry for english i come from poland

**Comment by Mogli12** [comment]
Which transmission?

**Comment by panczeslaw** [comment]
own, 4x4 powershift, full power shift, 6x4 autopowershift, 4x6 hexashift , direct drive, 16x5 full power shift

**Comment by Mogli12** [comment]
It is not possible to swap gears and ranges for 4x4 PS, full power shift, 6x4 APS, ...

**Comment by panczeslaw** [comment]
and it would not be possible to make a button to swap own transmission ?

**Comment by panczeslaw** [comment]
or to change it in controls ?

**Comment by Mogli12** [comment]
What should happend to own transmission? Why should there be a swap?

**Comment by panczeslaw** [comment]
so that I could change ranges with a shifter and gears without clutch like half-gears with buttons

Translator

**Comment by panczeslaw** [comment]
would you do it please
I have been using this mod for a year and recently I have a steering wheel

**Comment by Mogli12** [comment]
Just configure it. I do not understand why there needs to be a swap something. You can configure our gears for the shifter and you add ranges with 0ms shifting time.

**Comment by panczeslaw** [comment]
ehh 
I would like to change gears as in powershift
ranges with clutch and shifter
and gears without a clutch with a button, like in tractors

**Comment by panczeslaw** [comment]
if I do as you say, the half-gears will change my speed from 5 km / h to 30 km / h

**Comment by panczeslaw** [comment]
i try it

**Comment by panczeslaw** [comment]
thanks <3
