### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by panczeslaw** [Mogli12/VehicleControlAddon#556]
anyway thanks, but there is a problem with that, you have a video here, (look at the speed, there is a difference, with faster tractors it is a big problem, because there are speeds in one gear from 18 km / h to 45 km / h, and on the powershift there is no such thing )
https://www.youtube.com/watch?v=DAcJ-cBFt4g&ab_channel=panczeslaw

**Comment by Mogli12** [comment]
I really do not understand what you are trying to achieve.

**Comment by panczeslaw** [comment]
I like it a lot and I miss it, but no its no, thats end
