### ISSUE TITLE
Gänge Gruppen und lastschaltung

### ISSUE THREAD

**Issue by niro2206** [Mogli12/VehicleControlAddon#557]
Guten Morgen! 

Mir ist aufgefallen das man keine weiteren Gruppen erstellen kann bzw. wenn ich 3 Gruppen mit je 6 Gänge erstelle gibts keine Möglichkeit mehr eine lastschaltung zu erstellen. Dieses Getriebe gibts ja doch bei einigen Herstellern. Desweiteren wäre es für meinen Geschmack angenehmer die Gruppen per Tasten zu schalten anstatt diese sequentiell. Vlt könnte man ja da was umsetzen würde mich freuen! 

Lg Daniel

**Comment by Mogli12** [comment]
Hallo Daniel,

Weitere Gruppen lassen sich leider nicht einfach so hinzufügen.

Viele Grüße
