### ISSUE TITLE
Gears in the HUD

### ISSUE THREAD

**Issue by MichalKucavik** [Mogli12/VehicleControlAddon#562]
Hi, I use a steering wheel with a gear lever and in the VCA setting I use transmission "**2x6**" or "**6 Gear with Splitter**" and G27 / G29 shifter mode "**6G, 1R, LH**".

The gears are displayed in the HUD:
**1+ (H1) ... km / h** _(transmission 2x6)_
**2+ (H2)**
or
**1- (L1)
1- (L1)**

and

**1- (1-) ... km / h** _(transmission 6 Gear with Splitter)_
**1+ (1+)
2- (2-)**

It would not be possible to change this to?:
**H1 ... km / h** or **L1 ... km / h**  _(transmission 2x6)_

and
**1- ... km / h** or **1+ ... km / h** _(transmission 6 Gear with Splitter)_

Such a display of the transmission could be displayed after the start of the engine, because at the moment it is different after the start (capital letters) and will change after the gear is engaged. That could be unified. 

Thanks
Michal

**Comment by Mogli12** [comment]
Hi,

The HUD shows that real name of the gear, e.g. H1 and the position of the G27 shifter 1+ or 1-. In general, those do not match.

Regards,
Stefan
