### ISSUE TITLE
Idee - Sound bei Lastschaltstufen 

### ISSUE THREAD

**Issue by D9005** [Mogli12/VehicleControlAddon#566]
Hallo Stefan,
Ich hätte da mal eine Idee / Anregung.

Für Gänge, die als Lastschaltung arbeiten, greifst du ja auf den Blinkersound zurück. Oftmals "überschlagen" sich dann diese Sounds aber, wenn man blinkt und zusätzlich die Gänge schaltet. Für mich habe ich schon seit einigen Versionen den Code so umgeschrieben, dass eine zusätzliche Sounddatei für eben diesen Schaltvorgang geladen wird.
Falls Interesse besteht könnte ich dir meine kleinen Änderungen auch zu kommen lassen.

Vielen Dank für deine Arbeit 👍

Mfg D9005

**Comment by Viper21025** [comment]
Hallo D9005,
kannst du mir evtl. sagen wo du das eingetragen hast?

MFG Viper21025

**Comment by D9005** [comment]
Hallo zusammen,
wenn es für Stefan in Ordnung geht, würde ich die Änderungen hier einmal posten.

Mfg D9005

**Comment by Mogli12** [comment]
Hallo,

Wenn du es kannst, dann mach doch gleich einen Pull Request. Ansonsten hänge die Soundkarten einfach hier als Anhang dran.

Vielen Dank

**Comment by D9005** [comment]
Moin,
ich versuche mich morgen Vormittag mal an einem Pull Request. 

Mfg

**Comment by D9005** [comment]
Hallo,
ich habe meine Änderungen mal als Pull Request hochgeladen.
Ich hoffe das geht so in Ordnung.

MfG D9005

**Comment by Viper21025** [comment]
Moin D9005,
ich habe leider immer noch den Blinksound beim Gangwechsel drin.  Selbst wenn ich eine Vanilla Map mit deine Version lade.

MFG Dennis

**Comment by D9005** [comment]
Moin,
beim Update auf die neue Version hatte ich eine Änderung vergessen zu übernehmen.
Probiere mal bitte die neue Version.

MfG

**Comment by Viper21025** [comment]
Moin,
super funktioniert. Danke
