### ISSUE TITLE
geringe Leistung bei Handgas 

### ISSUE THREAD

**Issue by templer013** [Mogli12/VehicleControlAddon#567]
Hallo Mogli, 

ich habe eine Frage zum "Handgas". Hiermit stellt man bei modernen Maschinen ja nicht wirklich die "Gaspedal" Stellung ein, sondern gibt eine Drehzahl vor, die die Maschine, auch unter Last, halten soll. 

Hierbei ist bisher bei allen Versionen deines wirklich großartigen Mods, vielen Dank dafür, die Leistungsabgabe der Maschinen unter Last viel geringer, als wenn man mit manuellem Gas oder Tempomat fährt. 

Z.B. kann ich bei manuellem Gas oder mit Tempomat im Gang X mit1600U/min einen Berg hochfahren. Stelle ich jedoch die Drehzahl mit dem "Handgas" auf 1600U/min ein und fahre die gleiche Situation (gleicher Gang, gleiche Strecke etc.) dann schafft es der Traktor nicht, die 1600U/min zu halten. 

Ist das so beabsichtigt? Oder verstehe ich hier etwas falsch. 

Wenn es sich bei dem Feature hingegen um ein klassisches Handgas handelt, bei dem quasi eine Gaspedalstellung gewählt wird, dann sollte doch bei 100% Handgasstellung unter Last die gleiche (volle) Leistung anliegen, wie bei manuellem "Vollgas" (oder mit Tempomat bis die gewählte Geschwindigkeit erreicht ist). Dies ist mit deinem Mod aber auch nicht der Fall. Für mich macht das irgendwie keinen Sinn. 

Vielen Dank für deine Arbeit an dem Mod! 

Und Danke für eine Antwort im voraus! 

VG

**Comment by Mogli12** [comment]
Hallo,

- kein Screenshot
- keine log.txt (-> Versionen, andere Mods, ,,,)
- welches Getriebe wurde verwendet?
- welcher Traktor und Anhänger wurde gefahren? Womit war der Anhänger gefüllt
- Karte und Position auf der Karte? Oft wird das aber aus dem Screenshot bereits deutlich

Viele Grüße

**Comment by Mogli12** [comment]
Vollgas wird bei 1600 U/min Handgas ungefähr bei 1450 U/min gegeben.

**Comment by templer013** [comment]
![Handgas Screenshot](https://user-images.githubusercontent.com/68430565/112505479-1bb9d200-8d8d-11eb-9eee-518cc1feca36.png)
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/6206193/log.txt)

Beispielsweise vanilla Ravenport nur mit VCA im Mod Ordner mit 4x4 PS Getriebe. Wenn ich in der Situation (siehe Screenshot) kein Gas gebe, dann wird der Schlepper immer langsamer trotz der Einstellung auf 1600U/min im Handgas. Wenn ich Gas gebe, dann schafft es der Traktor locker in dem Gang den Berg hoch. Ist bei anderen Schaltgetrieben das gleiche Verhalten. 

Wenn ich deine Antwort richtig deute, dann sollte der Traktor selbstständig Vollgas geben. Danke!

**Comment by Mogli12** [comment]
Bei mir (Version 345 anstatt 377) gibt der Traktor Vollgas und hält die Drehzahl

**Comment by templer013** [comment]
> Bei mir (Version 345 anstatt 377) gibt der Traktor Vollgas und hält die Drehzahl
Sorry, ich hab erst die Log hochgeladen und dann die Version 345 runtergeladen und ausprobiert, deshalb steht im Log die v337. Ich habe das Problem mit 345 auch.  Könnte das mit dem Eingabegerät zusammenhängen? Das ist der einzige Unterschied, den ich mir noch so vorstellen könnte?

**Comment by templer013** [comment]
> Bei mir (Version 345 anstatt 377) gibt der Traktor Vollgas und hält die Drehzahl

Sorry, ich hab erst die Log hochgeladen und dann die Version 345 runtergeladen und ausprobiert, deshalb steht im Log die v337. Ich habe das Problem mit 345 auch.  Könnte das mit dem Eingabegerät zusammenhängen? Das ist der einzige Unterschied, den ich mir noch so vorstellen könnte?

**Comment by templer013** [comment]
Ich habe testweise die input binding gelöscht und die Saitek Controller alle abgesteckt, hat aber auch nichts gebracht.

**Comment by Mogli12** [comment]
Ich kann es leider nicht reproduzieren.
