### ISSUE TITLE
multiplayer

### ISSUE THREAD

**Issue by panczeslaw** [Mogli12/VehicleControlAddon#569]
is it possible to turn off rated power for multiplayer

**Comment by Mogli12** [comment]
Why?

**Comment by panczeslaw** [comment]
because i don't trust the person on the server

**Comment by panczeslaw** [comment]
and it would be nice if only administrators could change it and the speed of the axis

**Comment by Mogli12** [comment]
Sorry, but it would be too difficult to separate the settings into settings, everybody can change and administrator settings only.

**Comment by Mogli12** [comment]
Please try build 347

**Comment by panczeslaw** [comment]
thanks, it's working
