### ISSUE TITLE
Textzeilen funktionieren nicht mehr

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#571]
Hi Stefan, man kann in die Textzeilen wie zum Beispiel Nennleistung die Zahlen und Buchstaben nicht mehr eingeben

**Comment by Mogli12** [comment]
Multiplayer?

**Comment by ChrisJD8400R** [comment]
ja, Server, auch wenn man als Admin eingeloggt ist. Du kannst die Zeile anklicken und der "Strich" blinkt aber die Tasten nimmt er nicht an

**Comment by Mogli12** [comment]
Hi Chris, probiere mal die neueste Version. LG

**Comment by ChrisJD8400R** [comment]
Hi Stefan, super, funktioniert alles wieder 👌

Gesendet von Yahoo Mail auf Android 
 
  Am Sa., Apr. 3, 2021 at 10:57 schrieb Stefan ***@***.***>:   


Hi Chris, probiere mal die neueste Version. LG
