### ISSUE TITLE
Texteinträge werden nicht übernommen bei anderem Spielern 

### ISSUE THREAD

**Issue by Viper21025** [Mogli12/VehicleControlAddon#572]
Hallo Stefan,
Ist das richtig, wenn ein Admin im MP die Nennleistung bzw. Drehmoment Kurve in einen Fahrzeug ändert, diese Einstellungen für einen anderen Mitspieler der nicht Admin ist nicht mit übernommen werden?

MFG Dennis

**Comment by Mogli12** [comment]
Hallo Dennis,

klappt es mit Build 350 wieder?

LG

**Comment by Viper21025** [comment]
Hallo Stefan,
werde ich nachher mal probieren, kann doch dann auch die Version 351 benutzen oder?

Echt super für deine schnelle Bemühungen! Dankeschön

LG

**Comment by Viper21025** [comment]
Hallo Stefan, 
die ersten Tests waren sehr zufriedenstellend. Ich werde diese so schnell wie möglich auf unseren Root Server testen. Gebe dir dann noch eine Info.

Kann man eigentlich Im Menü den Rahmen wo die Infotexte stehen mit einer Bildlaufleiste versehen, um z.b. weitere Getriebevarianten in der Moddesk nachzutragen und dann zum nachlesen entsprechend scrollen kann?

MFG Dennis

**Comment by Mogli12** [comment]
Hallo Dennis,

sämtliche Controls stammen von Giants. Keine Ahnung, ob die eine Scrollbar unterstützen.

Viele Grüße, Stefan

**Comment by Viper21025** [comment]
Hallo Stefan,
Kein Problem 😉, ich probiere mal und wenn es klappt melde ich mich noch einmal bei dir.
Danke dir für deine rasche Antwort. 

Mfg dennis

**Comment by loenne-michel** [comment]
Hallo Stefan,

zunächst möchten wir uns für deine hervorragende Arbeit bedanken. VCA ist wirklich ein must have!
Nun zum Problem: Mit 353 auf unserem Dedi Server besteht weiterhin das Problem, daß die Einträge des Admin nicht übernommen werden. Ich hänge die Server Log an. MFG Micha
[Server Log.txt](https://github.com/Mogli12/VehicleControlAddon/files/6275955/Server.Log.txt)

**Comment by Mogli12** [comment]
Hallo,

was genau heißt "daß die Einträge des Admin nicht übernommen werden"? Welche Einträge? 

Viele Grüße

**Comment by loenne-michel** [comment]
Die Einträge für Nennleistung und Drehmomentkurve. Nachdem die Einstellungen vorgenommen wurden, sind sie aktiv. Beim nächsten Betreten des Servers aber wieder auf default.

**Comment by Mogli12** [comment]
Sorry, aber ich verstehe die Problembeschreibung nicht. Vielleicht machst Du mal ein paar Screenshots.

**Comment by loenne-michel** [comment]
Ok, ich versuche es einmal anders:

Auf unserem Server besteht das Problem aus dem ersten Beitrag dieses Themas fort. 

Zitat Viper21025: 
Hallo Stefan,
Ist das richtig, wenn ein Admin im MP die Nennleistung bzw. Drehmoment Kurve in einen Fahrzeug ändert, diese Einstellungen für einen anderen Mitspieler der nicht Admin ist nicht mit übernommen werden?

Dann gab es einen Tag später folgende Rückmeldung von Viper21025:
Hallo Stefan,
die ersten Tests waren sehr zufriedenstellend. Ich werde diese so schnell wie möglich auf unseren Root Server testen. Gebe dir dann noch eine Info.

Leider ist das Problem auf unserem Server mit der Version 353 nicht behoben.

**Comment by Mogli12** [comment]
Ich gebe es auf. Was ändert wer und was heißt "Beim nächsten Betreten des Servers aber wieder auf default"?
