### ISSUE TITLE
CVT/CVX/AutoCommand

### ISSUE THREAD

**Issue by BLACKOUT-Z0ck3R** [Mogli12/VehicleControlAddon#575]
Hallo :) 
ich habe mir eine Getriebe Config für die CNH Stufenlosen geschrieben: 

{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "AC",
				isIVT				= true,
				 noGears			= 4,
				 rangeGearOverlap	= {},
				 autoGears			= true,
				 timeGears			= 0,
				 speedMatching		= true,
				 gearRatios			= { 0.214, 0.357, 0.642, 1 },
					reverseGears		= { 1, 2 },
					reverseRatio		= 1.000,
				gearTexts			= {"1", "2", "3", "4"} },
			text   = "CVX/CVT/AutoCommand lang"},	

nun ist es leider so, dass sich die Gänge trotz "autoGears= true," nicht selber schalten und der erste Gang ziemlich ruckelig fährt....
was kann man da tun? 
LG

**Comment by Mogli12** [comment]
Hallo,

das geht leider nicht. Und Modifikationen am LUA-Code unterstütze ich grundsätzlich nicht.

Viele Grüße
