### ISSUE TITLE
Eigene Tasten zum klappen 

### ISSUE THREAD

**Issue by niro2206** [Mogli12/VehicleControlAddon#577]
Guten Tag! 

Kleiner Verbesserungsvorschlag ;)

die Taste x also klappen der Geräte wäre auch super wen dies über eigene Tasten möglich wäre bei mähen zb kann man hubwerk vorn und hinten ja extra betätigen ebenso pto aber zum klappen müsste man immer gerät wechseln. Darum frage ich ob es möglich wäre auch dies über eigene Befehle zu lösen 

danke Liebe Grüsse

**Comment by Mogli12** [comment]
Hallo,

Heben, Senken, Ein- und Ausschalten benötigt man meiner Ansicht nach bei der Feldarbeit. Das Aus- und Einklappen macht man einmalig vorher. Daher ist es nicht implementiert.

Viele Grüße

**Comment by Mogli12** [comment]
Was ist aber mit 2 Geräten (z.B. Kreiselegge mit Drille) im Heck angebaut sind. Das ist nicht so einfach.
