### ISSUE TITLE
Dedicate Keys for front/rear fold/unfold

### ISSUE THREAD

**Issue by ornellino** [Mogli12/VehicleControlAddon#578]
Hi Stefan,
   is it possible to add dedicated keys to fold / unfold the front and rear implements separately?

thanks in advance

Andrea

**Comment by Mogli12** [comment]
Hi Andrea,

I am sorry, but I do not want to code it. The idea of separate keys for front and rear implements is to support work in the field. I think the (un-)fold action happens only once before and after field work.

Additionally, it is difficult to code in case of multiple implements in the rear.

Regards, Stefan

**Comment by ornellino** [comment]
ok, I just ask because I made a custom controller with 40 buttons and 8 joystick and It's more realistic have separate keys for.

Tanks anyway

**Comment by Kobes94** [comment]
Well, this mod should help you https://www.modhoster.de/mods/vereinfachte-steuerung

**Comment by ornellino** [comment]
@Kobes94 Tanks! Very helpful!
