### ISSUE TITLE
Motor wird abgewürgt

### ISSUE THREAD

**Issue by xerion8300** [Mogli12/VehicleControlAddon#580]
Hallo was mache ich falsch, bei mir wird der Motor immer abgewürgt wenn ich stehen bleibe. Getriebe ist das Hexashift ausgewählt. 
Beim Vario geht es.
Muss ich da noch was einstellen.
Habe mal ein Video mit angehängt.

https://www.youtube.com/watch?v=TcQchYQUTZg

**Comment by Tellto4** [comment]
Hello xerion8300,
I think this is because your throttle is in manual mode. Try with the automatic one, that's will resolve your problem.

**Comment by Kobes94** [comment]
Beim HexaShift musst du die Gruppen A-D selbst schalten. die Gänge 1-6 können automatisch geschaltet werden, sofern die Automatik aktiv ist. Gruppe D ist zu hoch um mit schwerem Gerät auf dem Acker anzufahren.

**Comment by Mogli12** [comment]
Hallo,

@Kobes94 besser kann ich es auch nicht erklären

Ein Class Xerion hat ohnehin ein stufenloses Getriebe. Dass dabei intern 4 verschiedene feste Fahrstufen verwendet werden, kann VCA nicht simulieren. Daher ist das Getriebe IVT (oder off) das beste für den Xerion.

Viele Grüße,
Stefan

P.S.: Gute Problembeschreibung mit Video

**Comment by xerion8300** [comment]
Habe jetzt die Lösung gefunden bei der Hexashift Schaltung. Muss länger auf die Bremse drücken, dann würgt er den Traktor nicht mehr ab.

@Mogli12   Danke so sollte auch eine Fehlermeldung oder Problem gepostet werden.
