### ISSUE TITLE
Undesired gear switching with overlapping gears

### ISSUE THREAD

**Issue by Bevardisz** [Mogli12/VehicleControlAddon#582]
Not sure if this is my mistake or a misunderstanding, but I created a couple of custom gearboxes for my tractors in the .xml file and in one of them I have 9 gears and 2 ranges. Basically, some the gears overlap in a way, where  6 low < 5 High < 6 High and so on. I have the 
autoShiftGears="false" autoShiftRanges="false"
part  included, yet, when I try to change the range, It also down- or upshifts the gear to switch to the closest ratio to the last one. 
It really annoys me, because I spent quite a bit of time perfecting the gearbox and it's ratios to make it exactly as in real life.
Here's my gearbox: 

![Screenshot_23](https://user-images.githubusercontent.com/83036356/115775976-3f882c00-a3bc-11eb-805f-335922014d4c.png)

**Comment by Mogli12** [comment]
Can you please upload the XML entries in Gist? Thanks

**Comment by Bevardisz** [comment]
I'm new to github, but I hope I understood what you meant.  Here's the whole .xml file
https://gist.github.com/Bevardisz/925a31450afffd836e67c1742fbf55a1
Also, I wanted to add that the unneeded gear switch only happens when the tractor is moving. If I'm fully stopped, changing the range works as intended (only changes the range, leaving the gear as is). Tested on both the modhub version and the latest version here on github

**Comment by Mogli12** [comment]
Thanks, gist ist perfect.

**Comment by Mogli12** [comment]
Hi,

Please use the lastest version (build 355) and change the settings in the following way:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<transmissions>
	<transmission label="MTZ 80 9/2 split" reverseRatio="1.0">
		<ranges shiftTimeMs="250" autoShift="false">
			<range ratio="1.0" text="Letas" />
			<range ratio="1.35"   text="Greitas"/>
		</ranges>
		
		<gears shiftTimeMs="251" autoShift="false">
			<gear speed="1.9"  text="1"   forwardOnly="true"/>
			<gear speed="3.4"  text="2"  forwardOnly="true"/>
			<gear speed="5.8"  text="3" forwardOnly="true"/>
			<gear speed="7.2" text="4"  forwardOnly="false"/>
			<gear speed="8.4" text="5"   forwardOnly="true"/>
			<gear speed="10" text="6"  forwardOnly="true"/>
			<gear speed="12.1" text="7"  forwardOnly="true"/>
			<gear speed="14.4" text="8"  forwardOnly="true"/>
			<gear speed="26.6" text="9"  forwardOnly="true"/>
		</gears>
		
	</transmission>	
</transmissions>	
```

If you use the `gears` and `ranges` tags, then the settings belong to those tags. The baseSpeed is defaulted to the maximum speed value. It is better no to specify it.

Best regards
