### ISSUE TITLE
Keep speed not working

### ISSUE THREAD

**Issue by MateusKronbauer** [Mogli12/VehicleControlAddon#583]
Maybe it's just with me or a mod conflict but it's been a while since i can't use the Keep Speed function anymore. I've been using in a joystick i have to simulate the hydro from combines but now the values appears on the screen but the machine don't move...
![fsScreen_2021_04_25_21_33_18](https://user-images.githubusercontent.com/83147718/116014935-f5968480-a60d-11eb-8a74-7389b7f06680.png)

**Comment by MateusKronbauer** [comment]
I've opened a savegame without any mod, just the base map and VCA and the Keep Speed has worked, but what annoys me is that nothing is shown on the log that can be related to that

**Comment by Mogli12** [comment]
Is courseplay active? What transmission is active? "Off"?

**Comment by MateusKronbauer** [comment]
> 
> 
> Is courseplay active? What transmission is active? "Off"?

Courseplay is active and transmission is in off, but its't that. I've reopened the savegame and disabled a lot of mods i've not using and it worked again. I've gonna be slowly reactivating some mods to understand what's happening...

**Comment by MateusKronbauer** [comment]
Just to show that it's working now ![Uploading fsScreen_2021_04_26_23_16_49.png…]()

**Comment by MateusKronbauer** [comment]
Just to show that it's working now ![fsScreen_2021_04_26_23_16_49](https://user-images.githubusercontent.com/83147718/116327005-299fb000-a79c-11eb-8798-4b463bb3951b.png)

**Comment by MateusKronbauer** [comment]
But now that you mentioned Gear type i've remembered of another bug that it's happening to me, depending of the vehicle/transmission that i choose, that shows on the HUD and the vehicle doesn't move, and nothing is shown on the log, at least not immediately ![fsScreen_2021_04_27_14_44_55](https://user-images.githubusercontent.com/83147718/116327042-40460700-a79c-11eb-9163-94eaab55d60e.png)

**Comment by Mogli12** [comment]
Hi,
You turned on the manual mode. There is an extra axis to set the gear ratio of the IVT.
Best regards

**Comment by MateusKronbauer** [comment]
> 
> 
> Hi,
> You turned on the manual mode. There is an extra axis to set the gear ratio of the IVT.
> Best regards

This happens on the ''Harvester'' gearbox too? That's the one i selected there

**Comment by Mogli12** [comment]
The ranges of the Vario or Harvester transmissions are not operated automatically. Turning off automatic of IVT, Vario or Harvester will switch to this manual gear ratio mode. It operates like the first Fendt Vario tractors w/o TMS. The joystick controls the gear ratio and the throttle controls the RPM.

**Comment by MateusKronbauer** [comment]
> 
> 
> The ranges of the Vario or Harvester transmissions are not operated automatically. Turning off automatic of IVT, Vario or Harvester will switch to this manual gear ratio mode. It operates like the first Fendt Vario tractors w/o TMS. The joystick controls the gear ratio and the throttle controls the RPM.
> 
> Just keep automatic in ON if you do not want to control the gear ratio.

Thanks! It has worked now, i really didn't know that! Now i gonna try to find which mod is conflicting with the Keep Speed fuction...
