### ISSUE TITLE
Can't open settings. 

### ISSUE THREAD

**Issue by Jasiek22** [Mogli12/VehicleControlAddon#585]
Hello, i can't open vca settings.
I tried to rebind it, didn't work.
I deleted all mods, nope.
And weird thing is that no config is created at modsSettings.
(Idk if this is relevant but i have modoverride ticked)
Pls help

**Comment by Mogli12** [comment]
Hi,
I guess you have a problem with your input bindings. Just rename inputBinding.xml.
Elsewise, please post the log.
BR
