### ISSUE TITLE
Numeric RPM in the HUD

### ISSUE THREAD

**Issue by leo32128fs** [Mogli12/VehicleControlAddon#589]
Hello good night, I love your mod, and I would like to make a suggestion, one more request actually, I would like to see a numerical RPM in the game's hud it would be interesting to see what rpm your engine is working on and be able to control it

**Comment by Mogli12** [comment]
The last two digits are changing quickly and hard to read. That is why VCA visualizes the RPM in the speedometer. Just to remember: the blue curve shows the speed in the vanilla game. :-)

**Comment by leo32128fs** [comment]
can close the question!
