### ISSUE TITLE
Arbeitsbreite einstellen via Hotkey

### ISSUE THREAD

**Issue by BizzWareX** [Mogli12/VehicleControlAddon#591]
Hey ich Feier deine Mod sehr!

Sie gibt mir ein großen Hauch von Realismus mehr in diesen Game und das GPS finde ich um längen besser wie das andere.

Mir persönlich fehlt nur die Möglichkeit, die Arbeitsbreite via Hotkey automatisch anzupassen, anstatt immer  erst das Menü zu öffnen und anschließend auf "Automatische Arbeitsbreite" zu klicken bzw. bei der 1.1.1.0 Version eine "0" einzutragen :(

Vielleicht kann man dies ja noch einbauen 👍  :-)

**Comment by Mogli12** [comment]
Hi,

Das ist eine gute Idee. Probiere mal Version 356. Die Tastenkombination ist "KEY_lctrl KEY_lalt KEY_w".

Viele Grüße

**Comment by BizzWareX** [comment]
Funktioniert super! Danke! :)
