### ISSUE TITLE
Cruise in MP

### ISSUE THREAD

**Issue by iEBPO** [Mogli12/VehicleControlAddon#592]
Good afternoon!
The mod is great, but there is one drawback in it, which greatly interferes with playing in multiplayer mode. When you go on cruise control, if you write to the general chat, the equipment stops, and when you close the window with the text, it starts driving again. Is it possible to fix it somehow, maybe make some changes in the settings?

**Comment by Mogli12** [comment]
Does cruise control continue without VCA? It would be really helpful if you could test it.

**Comment by iEBPO** [comment]
> Does cruise control continue without VCA? It would be really helpful if you could test it.

Without VSA, the cruise works and does not stop when you start typing in the chat. I'll record the video today.

**Comment by Mogli12** [comment]
That's starnge. VCA does not stop cruise control.

**Comment by iEBPO** [comment]
https://youtu.be/WLv5qT8g0rg

**Comment by Mogli12** [comment]
Is build 357 better?

**Comment by iEBPO** [comment]
> Is build 357 better?

Yes

**Comment by iEBPO** [comment]
https://youtu.be/nry2SoAj__U

**Comment by Mogli12** [comment]
Hi,

Please try build 358.

Thanks

**Comment by iEBPO** [comment]
> Hi,
> 
> Please try build 358.
> 
> Thanks

Same as before

**Comment by iEBPO** [comment]
Maybe some additional steps can be taken. Or collect any additional information about the problem?

**Comment by iEBPO** [comment]
Have a nice day, everyone. I noticed that this appeared between version 190 -191

**Comment by iEBPO** [comment]
If you remove this setting, when you open the chat, the cruise will not turn off
![2021-12-04_23-53-12](https://user-images.githubusercontent.com/60730333/144719540-a3f48ee1-f7ab-43b8-af81-7e12454af8bc.png)

**Comment by iEBPO** [comment]
https://youtu.be/bEHUElwJmX8

**Comment by Mogli12** [comment]
Sorry, but I stopped working on FS19.
