### ISSUE TITLE
Is there a way to store shuttle control preferences for each player ?

### ISSUE THREAD

**Issue by Lactic68** [Mogli12/VehicleControlAddon#594]
Hi,
We have noticed that most of driving preferences are stored by vehicles and by players when playing on MP dedi server. That is a very good feature.
However, the shuttle control preference is not stored by player. Is there a way to also store this preference by player ?

**Comment by Mogli12** [comment]
Hi,
Sorry, but this is not possible

**Comment by Lactic68** [comment]
Hi, ok thank you for your answer.

**Comment by newbie-near-cologne** [comment]
Hello together, as first I want say thanks for the great mod and your work. This yet not available feature would be very nice and additional it would be nice if each player can store their own "global" settings. 
It is possible to store settings in the savegame for each player. For example the mod "Autodrive" does this and separate it on the uniqeID which each player has. Other way would be that you store the settings for each player local in the game folder. This should also work on a dedicated server or not? In SP it's great that you set your global configuration and each new bought vehicle has these settings then. 
On a dedicated server with known players and no fear that someone do stupid things it's a little bit annoying that the settings not stored. Every time after the login each player must set it again to the own preferences. Also new bought vehicles didn't have the settings of the global settings which was set by an admin on the server. Is this a bug?

It would be nice if you rethink about it and it would be very great if you can realize that the settings were stored for each player. If you can also realize own global settings for each player would be awesome. 

I hope it's ok to reopen this issue again. Thanks in advance. English isn't my natural language so sorry if anything isn't clear.
