### ISSUE TITLE
Load custom transmissions.xml on a dedicated server

### ISSUE THREAD

**Issue by tdiniz93** [Mogli12/VehicleControlAddon#596]
I've setup a few transmissions using the transmissions.xml, however I cannot get the file to be recognized by the mod on a multiplayer server, is this possible, or can I only make ingame configurations on a multiplayer server?

**Comment by Kobes94** [comment]
Sorry, but RTFM https://github.com/Mogli12/VehicleControlAddon#multi-player

**Comment by Mogli12** [comment]
Please use own transmissions instead.
