### ISSUE TITLE
No shuttle on JD 8R

### ISSUE THREAD

**Issue by yumi-modding** [Mogli12/VehicleControlAddon#597]
Hello,

Thanks for the mod, it really adds a lot of realism and simulation to the game.
I have one question regarding JD 8R. I've configured it to use IVT transmission but for unknown reason I'm not able to activate shuttle. I tried to set it in the panel and also edit the vehicles.xml manually, but it doesn't work. I can only go backward by using brakes.
I don't have this behavior for other vehicles with IVT (like JD 6R or Fendt 800) and I could not find anything in the code that could justify this.
Have you already encountered this kind of issue?

Thanks
Yumi

**Comment by Mogli12** [comment]
Hi,
I have no idea. Did you rename your inputBinding.xml (temporarily)? Maybe it is an input conflict?
Regards, Stefan

**Comment by yumi-modding** [comment]
Hello,
Same issue with new inputBinding.xml but issue is gone on a new game with only VCA Mod so I guess I have to look for mod conflicts.
Thanks
Yumi
