### ISSUE TITLE
Launch speed overwriten

### ISSUE THREAD

**Issue by DrewCZ** [Mogli12/VehicleControlAddon#605]
Hi Mogli, 
here si Ticho again. I found maybe a small issue. No matter if MP or SP game. Value 
_launchSpeed=_
is still overwritten and not hold by value from game save, or menu record. Example: 
In vehicles.xml is recorded: launchSpeed="7.0" (written manually by me) 
In-game, the first start is correct. But when the vehicle stops and then start again, in the VCA menu I can see the value like 
_launchSpeed="3"_
Strange. The issue is, when the value is changed to high value, i.e. 18+. Then the loaded vehicle can't start to move and a few seconds is a battle between clutch and gearbox. After save, this new value 
_launchSpeed="2.514888"_
is written into the vehicles.xml file. 
I don't know if this is coupled issue, but when you hold the gas pedal in max position, the auto gearbox never changes gear down. You must release the gas pedal (ca less than 50%) and push it again, then gearbox set (one or more) gear down. If I remember, this is the opposite of IRL. 
Anyway, all of these reported issues is only polishing, mod as-is works, and I'm happy to see you make Farming more Simulator 🥇 Thank you.

**Comment by Mogli12** [comment]
Hi,
Changing gears in neutral (or auto stop) changes the launch speed. 
Best regards

**Comment by DrewCZ** [comment]
Clear. Thank you.
