### ISSUE TITLE
Transmission not shiftig automatically (last Update from Modhub ingame) 

### ISSUE THREAD

**Issue by SSlz** [Mogli12/VehicleControlAddon#606]
Transmissions with gears and groups are not automatically shifted as set. 

I'm using the Steam version of Farm Simulator 19. 

Is there a reason for this? What can I do?. 

Please help me. 

Thank you very much.

**Comment by Mogli12** [comment]
Hi.
Which transmission? Can you add some screen shots?

**Comment by SSlz** [comment]
Everyone is affected by the existing gearboxes.
As soon as a gearbox consists of groups and gears. 
Only the gears are shifted at a time. 
The groups are not changed automatically. 

Why is that?

**Comment by Mogli12** [comment]
Hi,

When you work on a field, it is easier if the gears shift automatically but not the groups.

Maybe you try to configure your own transmission?

**Comment by SSlz** [comment]
I mean on the street. That was possible. I liked to make it work like this again without having to build a gearbox myself

**Comment by Mogli12** [comment]
Which transmission did you select?

**Comment by SSlz** [comment]
For example, "Direct drive"

**Comment by Mogli12** [comment]
No, any gearbox is not true. The 4x4 powershift shifts geras and groups.

**Comment by SSlz** [comment]
With the "DirectDrive" transmission, he has always shifted the groups. At 4x4 without Powershift, he always shifted group by group and gear by gear. 

That was actually the case with all gearboxes. 

The one with powershift he has always shifted which gear is the best. Aisles were also omitted. That's normal with powershift.

**Comment by Mogli12** [comment]
The current implementation is the correct one. For most transmissions groups are shifted manually only.
