### ISSUE TITLE
FS19 Crash

### ISSUE THREAD

**Issue by itsJustme1111** [Mogli12/VehicleControlAddon#608]
Hi, Love this addon, couldn't be without it.
however, I couldn't be without my Fendt Trisix.

VCA Version 1.1 from ModHub
No info is produced in the log.txt file

When I enter the Trisix, the engine will startup, then FS19 will stop responding, then crash.

If you need any more info, please let me know. (Trisix V1)

**Comment by Mogli12** [comment]
I do not think that this is related to VCA.
