### ISSUE TITLE
Manual Shifting doesn't work

### ISSUE THREAD

**Issue by jeffersondarsy** [Mogli12/VehicleControlAddon#617]
If you have "manual shifting by using a clutch" activated in the options menu, this didn't work, if VCA is activated. 

The shifting of groups works, but not the gears.

Tested by using a Fendt Favorit 515c on Haut-Bayleron. 

By deactivating VCA, the manual shifting works as expected (groups and gears).

**Comment by jeffersondarsy** [comment]
BTW: Thanks a lot for the amazing mod and all your effort to make it work in LS22!!!

**Comment by Mogli12** [comment]
Does this really only happen if VCA is active?

**Comment by Mogli12** [comment]
Ah ok. I removed several keybindings in 9.0.0.2.

**Comment by waghD** [comment]
@Mogli12 actually the problem is still there in 9.0.0.2

in modDesc.xml line 106, this is the problem
```
<actionBinding action="vcaINCHING">	
    <binding device="KB_MOUSE_DEFAULT" input="KEY_lshift"/>
</actionBinding>	
```

lshift is already taken by manual clutch. That is why you can not press the clutch when VCA is installed and because of that can't shift gears at all

**Comment by Leon8490** [comment]
Hello @Mogli12  So manual shifting with VCA still doesn't work for me I can't shift a gear because he says the clutch is not actuated although I press it how can I fix this error because I would still like to play with VCA I play with the steering wheel there manual shifting with clutch does not work

**Comment by Mogli12** [comment]
The error message comes out of the standard game. VCA does not have a gearbox in FS22.

**Comment by Leon8490** [comment]
> The error message comes out of the standard game. VCA does not have a gearbox in FS22.

In the standard game, the gearshift with clutch works, but as soon as VCA is active, it no longer works, I can only shift powershift levels and the normal gears can no longer be used

**Comment by Mogli12** [comment]
Check your input bindings
