### ISSUE TITLE
Richtungswechsel (Automatisch)

### ISSUE THREAD

**Issue by xJ0i** [Mogli12/VehicleControlAddon#621]
Hallo,

falls in den "Allgemeinen Einstellungen" (Reiter "Steuerung") des LS 22 bei "Richtungswecksel" "Automatisch" eingestellt ist, ist der Mod aktuell leider unbrauchbar, da beim Richtungswechsel nicht abgebremst wird und der Traktor dann kilometer weit ausrollt bis er die Richtung wechselt. Ich hatte mich schon sehr auf den mod gefreut und hoffe deshalb, dass dies bald funktioniert.

Mfg
xJoi

**Comment by Th301** [comment]
Ich glaube da gibt es eine Einstellung im VCA Menü, bei der man die Bremskraft auf 100% stellen muss. So hab ich es vorhin mal in einer Mod-Vorstellung gesehen. Testen konnte ich es selbst noch nicht. Aber probier du es doch mal eben aus! :)
Das Video war von Mario Hirschfeld, der hatte auf das (oder ein ähnliches) Problem hingewiesen.

**Comment by Mogli12** [comment]
Hallo,

Das Getriebe ist NICHT von VCA. Anscheinend bremst das Spiel nicht beim Richtungswechsel.

Viele Grüße
