### ISSUE TITLE
Dedicated  Error:    Error: Running LUA method packetReceived

### ISSUE THREAD

**Issue by Momo13092022** [Mogli12/VehicleControlAddon#624]
PIC:  https://ibb.co/FHBXp6R

**Comment by Mogli12** [comment]
Build 4?

**Comment by Momo13092022** [comment]
Ne war die 3er, die 4er lässt sich gerade gar nicht auf den Server laden, kommt immer Mod ist beschädigt.

**Comment by Mogli12** [comment]
Ich schließe jetzt alle MP Issues außer #620.
