### ISSUE TITLE
No auto rotate back (FS22)

### ISSUE THREAD

**Issue by AgroMeester** [Mogli12/VehicleControlAddon#625]
Hi Stefan,

I noticed some different behaviour on the "no auto rotate back" function as compared to the FS19 version;
1. When I release the key (set with keybinding) the wheels almost instantly 'snap' back to straight forward. I would like to see the wheels rotating back with the speed set in the game preferences (for instance 40%).
2. When I press the key and the wheel are straight forward the "no auto rotate back" function works as aspected. However when I press the key shortly after steering to the left or right the wheels 'snap' to their maximum steering position, so for instance fully to the left or fully to the right. I would like to just enable the "no auto rotate back" function while steering without the "snapping".

Maybe you can have a look at it.

Thanks for your work!

**Comment by AgroMeester** [comment]
Hi Stefan,

This issue can be closed.
I discovered that the behaviour I described only occurs when "Adaptive Steering" is OFF. When it is switched ON everything works as expected. It probably already worked right from the beginning but I tested it with several tractors and had some of them  with the Adaptive Steering on and some of them off. 

Sorry for the mix up and keep up the good work!

**Comment by Mogli12** [comment]
Anyway, thanks for notifying what went wrong.
