### ISSUE TITLE
GPS hält den Kurs nicht DediServer

### ISSUE THREAD

**Issue by DJT0BE** [Mogli12/VehicleControlAddon#626]
GPS hält im SP den Kurs aber auf dem DediServer nicht. Es zeigt zwar an das es aktiv ist, aber nur optisch. Es greift nicht in die Lenkung ein und hält den Kurs

**Comment by alexanderweide** [comment]
gleicher Bug wie: https://github.com/Mogli12/VehicleControlAddon/issues/620
