### ISSUE TITLE
Geräte-Offset verschiebt beim Richtungswechsel die gesamte Bahn

### ISSUE THREAD

**Issue by mlewelt** [Mogli12/VehicleControlAddon#627]
Wenn ich einen Offset eingestellt habe und den Offset manuell umschalte oder duch Richtungswechsel der VCA automatisch schaltet wird der Offset zwar relativ zur GPS-Bahn gewechselt, allerdings verschiebt sich auch die gesamte Bahn.

![BahnAltKorrekt](https://user-images.githubusercontent.com/3612152/144148412-97f195a7-407a-4570-8b10-0c5729280a12.jpg)
![BahnNeuNachOffsetSwitch](https://user-images.githubusercontent.com/3612152/144148417-842a1d2f-e695-4d5c-a591-45814fd34d4d.jpg)

**Comment by Mogli12** [comment]
Die Mittellinie sollte bleiben. Der Offset ist nur für die Optik und verschiebt die äußeren Linien.

**Comment by Mogli12** [comment]
Bitte probier Build 18. Sollte das Problem immer noch auftreten, dann öffne bitte **dieses** Issue wieder.
