### ISSUE TITLE
Build 5: Speichern nicht möglich

### ISSUE THREAD

**Issue by KrawuDE** [Mogli12/VehicleControlAddon#628]
Hallo Mogli, habe durch Mario erfahren, dass deine Mod nun auch für LS22 verfügbar ist und wollte die auch direkt mal ausprobieren.

Der aktuelle Build 5 funktioniert ingame tadellos, aber sobald man speichern möchte, bleibt er im Speicherbildschirm hängen.
Dadurch wurde leider auch kein Eintrag in der log.txt generiert, da eben nichts gespeichert werden konnte.

Gibt es da zufälligerweise ein kleines Workaround?

LG Krawu

**Comment by Mogli12** [comment]
Hallo Krawu,

wo ist die log.txt? 

LG Stefan

**Comment by Mogli12** [comment]
Wird fortgesetzt in #630
