### ISSUE TITLE
Build 6: Wieder Errors + keine Benutzung von Fahrzeugen möglich (MP)

### ISSUE THREAD

**Issue by keksi1991** [Mogli12/VehicleControlAddon#629]
Moin Stefan,
ich habe den Build 6 direkt mal getestet, ich konnte weder mit E noch mit Tab ein Fahrzeug nutzen.
Die LUA Errors sind in diesem Build bei mir auch wieder da.
Im SP klappt weiterhin alles ohne Probleme. 

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7631501/log.txt)
 Grüße und danke für den Mod, im SP ist er schon verdammt gut!

**Comment by b3nutzmich** [comment]
Servus,

erstmal.. Ich liebe diesen Mod! Vielen Dank dafür!
Die Probleme von keksi kann ich bestätigen. Im MP kann ich auch in kein Fahrzeug mehr einsteigen.

Danke für deine tolle arbeit!

**Comment by alexanderweide** [comment]
vielleicht sollten wir alle Multiplayer themen in den Multiplayer Post packen. jeder macht hier ständig seinen eigenen neuen Multiplayer thread auf. Kann ich nicht verstehen...

**Comment by Mogli12** [comment]
Ich schließe jetzt alle MP Issues außer #620.
