### ISSUE TITLE
Speichern nicht möglich (SP)

### ISSUE THREAD

**Issue by flattergaul** [Mogli12/VehicleControlAddon#630]
Hallo Stefan,

ich kann mit Build 6 nicht speichern. Das Spiel bleibt hängen und kann nur mehr mittels Taskmanager beendet werden.

Anbei das Log:
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7632256/log.txt)

Hab es mit einem neuen Spielstand und nur VCA als aktiviertem Mod versucht.

lg
Michael

**Comment by Mogli12** [comment]
Probiere bitte mal Version 7

**Comment by newbie-near-cologne** [comment]
It works again with build 7. Thanks a lot for such a fast bug fixing. Great job.

**Comment by KrawuDE** [comment]
Okay, sorry das ich erst verspätet antworte. Aber hier meine log.txt

https://pastebin.com/rQv3tBQS

Habe aber schon im anderen Beitrag gelesen das es gefixed ist?

**Comment by Mogli12** [comment]
Please try the lastest build.
