### ISSUE TITLE
The red line only showing up in one vehicle?

### ISSUE THREAD

**Issue by SyphiliticWeasel** [Mogli12/VehicleControlAddon#631]
Hello,

I was using the auto steer function while mowing grass for a contract and the lines worked just fine. Once I switched a different tractor the lines would not show up anymore. But I could still use the auto steer. 

I tried three more tractors and still nothing. But when I went back to the mower the lines were there again?

**Comment by Mogli12** [comment]
Single player / multi player? Version? log.txt?

**Comment by SyphiliticWeasel** [comment]
It was single player, verison: FS 22 Build 9.

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7636139/log.txt)

**Comment by Mogli12** [comment]
Die log.txt ist noch von Build 6.

**Comment by SyphiliticWeasel** [comment]
I did just update it after you said that with the same issue. here are some screenshots of what I am saying is happening. 
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7636434/log.txt)
![20211201133959_1](https://user-images.githubusercontent.com/79814946/144294276-4ca9d152-fef3-4aee-895c-c95618507b45.jpg)
![20211201133930_1](https://user-images.githubusercontent.com/79814946/144294286-3782b89e-e41b-4ceb-831a-544d01f1685e.jpg)

**Comment by SyphiliticWeasel** [comment]
I have updated the mod again with the latest one on here and still the same issue... I am not sure what it is but hopefully one day it will get figured out... I enjoy the mod but I can't use it... I have to constantly reset the offset if I want it to even continue in the same direction...

**Comment by SyphiliticWeasel** [comment]
I thought I sent them up for each vehicle. So what I did was when I went into the other vehicle I I would hit ALT + W and then CTRL + W. And it would make the noise as it connected and the degrees above the speed would turn green but no lines. Is there a different way I am supposed to be setting it up for each vehicle?

**Comment by Mogli12** [comment]
What is your lines setting? You can change them per vehicle.

**Comment by SyphiliticWeasel** [comment]
So this is how it is set up... The first screenshot is the harvester where the lines show up perfectly every time. The second is the tractor I am in with a baler behind it currently. The tractor again has no lines. The third screenshot shows you that there is no lines and the degrees is white and the fourth shows no lines with degrees in green.
![20211203140240_1](https://user-images.githubusercontent.com/79814946/144658538-e2bb60b6-87cc-40fb-9399-a231657fb1ec.jpg)

![20211203140005_1](https://user-images.githubusercontent.com/79814946/144658346-0f64777a-5277-4ff1-8c86-2248e211c186.jpg)
![20211203140118_1](https://user-images.githubusercontent.com/79814946/144658364-6cf27607-6002-49a7-80b5-f3470e568b7a.jpg)
![20211203140248_1](https://user-images.githubusercontent.com/79814946/144658542-c2a3c483-2580-4b9b-ac15-e74305dd5186.jpg)

**Comment by Mogli12** [comment]
The working width is 0.
