### ISSUE TITLE
Build 7: Weiterhin der lua-Fehler im MP

### ISSUE THREAD

**Issue by renezerm** [Mogli12/VehicleControlAddon#633]
Hallo Mogli,
vielen Dank für Deine Arbeit und den mod, den wir auch im LS19 genutzt haben.

Ich habe gerade Build7 im MP getestet. Und es erscheint beim Einsteigen in ein Fahrzeug, bzw. dem Versuch, weiterhin der lua-Fehler:

Games/FarmingSimulator2022/mods/FS22_VehicleControlAddon/vehicleControlAddonEvent.lua:23: attempt to index local 'prop' (a nil value)

**Comment by alexanderweide** [comment]
Bitte Post schließen und Inhalt in https://github.com/Mogli12/VehicleControlAddon/issues/620 posten.

**Comment by renezerm** [comment]
@alexanderweide Alles klar, danke für die Info.
