### ISSUE TITLE
[Featurerequest] Teilbreiten

### ISSUE THREAD

**Issue by DonBolli** [Mogli12/VehicleControlAddon#635]
Erstmal herzlichen Dank für diesen Mod.

Was schön wäre, wenn der Mod automatisch Teilbreiten nutzen würde, wenn es diesse Funktion schon im LS gibt. Aber wenn nicht geht die Welt auch nicht unter, ist aus der Kategorie "Nice to  have"

**Comment by Mogli12** [comment]
Ich weiß nicht wirklich, was VCA mit den Teilbreiten machen soll. Wenn man selber eine andere Breite bei der Spurführung verwenden will, dann kann man den Wert ja einfach selber eintippen.

**Comment by DonBolli** [comment]
@Mogli12  Ich dachte, das VCA die letzte Spur auf dem Feld so wählt das man die Teilbreite nutzen kann und diese automatisch durch VCA eingestellt wird. Nur als Idee.

**Comment by Mogli12** [comment]
VCA kennt keine Felder.

**Comment by DonBolli** [comment]
Ah okay, keine Ursache
