### ISSUE TITLE
Spiel hängt mitBuild 8

### ISSUE THREAD

**Issue by timmi4026** [Mogli12/VehicleControlAddon#636]
Moin, kurze Info zum Server. Das Spiel friert ab und zu ein wenn: Kamera Innenansicht Rückblicken, Sobald ich mit Sämaschine GPS starte,ich in ein Fahrzeug einsteigen möchte und es werden die Settings nicht gespeichert sobald ich den Server betrete.
Leider gibt es keine log Fehler weil das Spiel einfriert.
[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7633935/log.txt)

**Comment by Mogli12** [comment]
Hmm, ich denke ich, dass das an VCA liegt.

**Comment by timmi4026** [comment]
Hmm ich hab jetzt mal alle anderen Scripte deaktiviert am Server, und Spiel hängt wieder.

**Comment by Mogli12** [comment]
Ich denke, dass es am Spiel selber liegt.
