### ISSUE TITLE
Calculation of snap offset (Build 9 MP does (kind of) work)

### ISSUE THREAD

**Issue by Helmi** [Mogli12/VehicleControlAddon#637]
Disclaimer: This is the first time I'm using this mod. So far I only saw it on YT and read the previous issues. While Build 8 didn't do it for me on MP, Build 9 seems to work - kind of.

Guide lines are drawn, auto steer works, but when turning at the end of the field the guides are offset. At least that is what it looks to me. I need to Alt+W reset the guides and Strg+W set new guides to get it working. I only tried with a stone picker that has an offset so maybe this is due to the offset?

**Comment by Mogli12** [comment]
Yes, calculation of the offset is still buggy. It was initially developed (in FS19) for plows. Please use the same offset for both values.

**Comment by Helmi** [comment]
good, thx. But is it meant to only show one path when turning? I might have gotten this wrong but I was thinking it is supposed to show multiple guide lines to show me options which one to take - especially on fields where you couldn't see the separation based on textures.

**Comment by Mogli12** [comment]
Please try build 18. If the problem persits then please re-open **this** issue.
