### ISSUE TITLE
Controller Steuerung ändert Einstellung beim Öffnen der Einstellungen

### ISSUE THREAD

**Issue by derMiepz** [Mogli12/VehicleControlAddon#638]
Heya!
Ich habe mir das Öffnen der VCA Einstellungen auf RB+LB+Y gelegt, aber leider verstellt sich jedes mal beim Öffnen der Einstellung die Einstellung, die zuletzt ausgewählt war. VCA nimmt quasi LB als Input beim Beenden der Tastenkombination/Öffnen der Einstellungen.

Ich weiß nicht genau wie ich es erklären soll, darum hier ein Video :D https://s.imparium.de/niho0/sugoPIHO60.mp4

Ich weiß auch nicht ob es an VCA oder dem Spiel an sich liegt, aber ich hoffe dass man das irgendwie gelöst bekommt ^^

PS: Build 9 funktioniert soweit im MP, danke für deine Arbeit!

**Comment by Sacred-Shadow** [comment]
Ich bin noch mit Build 3 oder 4 unterwegs ... da konnte ich das nicht nachstellen.

**Comment by Mogli12** [comment]
Ich denke, dass hier Tasten doppelt belegt sind.

**Comment by derMiepz** [comment]
Tatsächlich ist der der Fall, es geht hier aber eher darum dass man mit LB und RB die Werte im Menü einstellen kann. Das geht im normalen FS Menü nicht, da man dort die Kategorien an der linken Seite wechselt. Interessant ist auch, dass das bei meinem Kollegen nicht passiert. Könnte es am Controller liegen? Ich hab einen Xbox 360 (Kabel) und er einen Xbox One (Kabel)?

**Comment by Mogli12** [comment]
Das UI verwendet die UI-Profile aus dem Standard-Game. Da kann ich wenig machen.
