### ISSUE TITLE
I10n_da

### ISSUE THREAD

**Issue by Michaelbjerg21978** [Mogli12/VehicleControlAddon#639]
Hello Mogli. LOVE YOUR MOD!!. thats why i made a updated da translation, hope you will use i
[modDesc_l10n_da.zip](https://github.com/Mogli12/VehicleControlAddon/files/7635750/modDesc_l10n_da.zip)
t'
Best regards Michaelbjerg21978 (And keep up the good work)

**Comment by Mogli12** [comment]
Thanks. I will update in the ZIP-file with version 11.

**Comment by Michaelbjerg21978** [comment]
Thank you. i will update the da. xml. if you dont mind?

**Comment by Michaelbjerg21978** [comment]
BIG thanks from me.
