### ISSUE TITLE
Steuerung auf XBOX Controller wird nicht angenommen

### ISSUE THREAD

**Issue by HurrycaneBE** [Mogli12/VehicleControlAddon#640]
Hey Mogli , tiptop Build 9 scheint im MP ganz gut zu laufen.
Mir ist aufgefallen das der keybind für VCA: in Fahrtrichtung am Raster ausrichten auf Tastatur funktioniert , jedoch bei Binding ans pad nicht will. Ich nutze RB + LB + Y dafür , VCA reagiert aber nicht dadrauf. Fehler habe ich keine im Log.
Thx 4 your Work :>

**Comment by Sacred-Shadow** [comment]
Hast evtl. die Meldung, dass die Kombi schon belegt ist und du die doppelt vergibst? 
Auch extra auf Speichern geklickt?

**Comment by HurrycaneBE** [comment]
mähh schei?# doppelbelegung ... danke Closed
