### ISSUE TITLE
Probleme mit Build9 im MP Modus

### ISSUE THREAD

**Issue by xxdacrusherxx** [Mogli12/VehicleControlAddon#642]
Aktuell hat sich bei uns das Problem herausgestellt, dass im Multiplayer mit aktuell 7 Spielern, das Problem auftritt das nicht bei jedem Spieler der Fall ist, dass die Anzeige für die Ausrichtung in Form der Gradzahl nicht über dem Tacho angezeigt wird. Dies variiert, zumindest wie wir es festellen konnten, derzeit unterscheidet es sich von Spieler zu Spieler in den Varianten Steamspieler und Giants direct Download Spieler.

Möglicherweise gibt es hierfür ja schon eine Lösung, dies jedoch nur der Info.
Ansonsten konnten wir mit dem Build9 keine weiten Multiplayer Problem derzeit festellen auf einem Dediserver über Nitrado.

**Comment by Antoz1103** [comment]
Ich hab einen Dawn Server und einen Nitrado. und bei beiden Anbietern ist manchmal das HUD da und manchmal nicht. Mal geht das gut mal das. Abwarten und tee trinken. Der Modder macht einen Bomben Job, und ich hoffe dass er bald eine Finale Version rasuhauen kann weil mir gefällt der Mod mega gut

**Comment by Mogli12** [comment]
MP Probleme => #620

**Comment by xxdacrusherxx** [comment]
> MP Probleme => #620

Leider finde ich hier den Hinweis nicht, der das Problem von uns Beschreibt. Die Anzeige ist weder über dem Tacho, noch unterhalb der Minimap. Es ist einfach KEINE Anzeige vorhanden bezüglich der Gradzahl.
Ich befürchte das eine Log da aber nicht weiterhilft, da es unterschiedlich ist was die User angeht.

Wenn wir irgendwie behilflich sein können, oder der Wunsch da ist selbst auf dem Multiplay mit zu kommen um sich dies anzuschauen, sollte das kein Problem darstellen.
