### ISSUE TITLE
Is HandRPM coming back?

### ISSUE THREAD

**Issue by Dldrth** [Mogli12/VehicleControlAddon#643]
I did not want to make a new issue about this but after waiting few days I just could not resist. 
Is HandRPM coming back anytime soon, I realize you got your hands full with MP issues. 
I saw the keybinds for HandRPM in first builds (was not working) then they just disappeared. 
Also thank you for your contribution to the community. Your mod was a gamechanger for me in 19 with ability to set the RPM and shifting manually without using the throttle.
A simple Yes or No will suffice, I will be waiting happily.

**Comment by Mogli12** [comment]
HandRpm was implemented in VCA's gearbox. Since FS22 already has a gearbox, I removed the gearbox from VCA.

But it could be possible to implement HandRpm via PowerConsumer / PTO. And therefore the answer is:

Maybe

**Comment by tdiniz93** [comment]
FS22 supports using a slider axis for a brand throttle, however there is no way to put CVT transmissions in neutral. This should probably be posted as a separate issue, but it's also related to this one.

**Comment by Mogli12** [comment]
Please address transmission questions directly to Giants. VCA can do small tweaks like reduced lowBrakeForceScale, automatic braking during direction change, idle enrichment. But putting a CVT into neutral is not possible.

**Comment by Mogli12** [comment]
Hand RPM is available in build 12. You can change it with the according key bindings. It will not be saved.

**Comment by tdiniz93** [comment]
> Please address transmission questions directly to Giants. VCA can do small tweaks like reduced lowBrakeForceScale, automatic braking during direction change, idle enrichment. But putting a CVT into neutral is not possible.

Would a parking brake be possible? My main concern is for running stationary implements like augers, forage blowers, and bale shredders, etc.

**Comment by Mogli12** [comment]
I will not create a parking break. Sorry
