### ISSUE TITLE
Error: Running LUA Method 'update' Build 11 Dedi Server

### ISSUE THREAD

**Issue by M4rciii** [Mogli12/VehicleControlAddon#644]
Hi,

Meine Console ist immer mit dem gleichen fehler voll.

Error: Running LUA Method 'update' 
attempt to compare two table values

Ich kann nicht genau sagen wann der Fehler genau auftritt aber ich werde es beobachten.

Grüße und vielen dank für den Mod :)

**Comment by M4rciii** [comment]
Der Fehler kommt immer wenn ich Paletten aufeinander Stapel.

**Comment by Mogli12** [comment]
Ohne komplette log.txt kann man dazu nichts sagen. Probiere mal Version 13.
