### ISSUE TITLE
Camera der Schäffer Hoflader 

### ISSUE THREAD

**Issue by FarmerMike87** [Mogli12/VehicleControlAddon#646]
Moin Mogli, mir ist aufgefallen das die Camera nicht in die ansicht nach hinten mit gedreht wird wenn ich auf den Rückwärtsgang wechsle. Aufgefallen is mir das bei den Hofladern alla Weidemann, beim Gabelstapler und bei den Schleppern funktioniert es.

LG Mike

**Comment by Mogli12** [comment]
Hallo Mike,

in FS22 sind zunächst alle Funktionen ausgeschaltet. Hast Du sie mit Strg+C auch eingeschaltet?

LG Stefan

**Comment by FarmerMike87** [comment]
Ja ich hab im Menü das zurückblicken an, bei allen anderen Fahrzeugen ist alles super nur bei den Hofladern nicht. :)

**Comment by whizzle21** [comment]
Moin, 

ich habe das Problem, dass die Kamera nur nach hinten wechselt, wenn die manuelle Schaltung angeschaltet ist. Sobald die Automatik an ist, blickt die Kamera im Rückwärtsgang nicht mehr nach hinten.

**Comment by whizzle21** [comment]
Edit: Wenn der automatische Fahrtrichtungswechsel aktiviert ist geht es nicht. Bei manuellem Richtungswechsel geht es.

**Comment by FarmerMike87** [comment]
Ich schalte die richtung Manuell und es geht nicht.

**Comment by whizzle21** [comment]
Update: Seit Build 18 funktioniert es jetzt bei mir im automatischen Richtungswechsel. Vielen Dank!

Bester Mann!

**Comment by FarmerMike87** [comment]
Im Manuellen leider immer noch nicht, ich wechsle die Fahrtrichtung mit nem Knopf am Joystick. Da funktioniert es bei den Weidemann ladern immer noch ned. Was prinzipiel kein Drama ist, den die nutze ich eh nur Sporadisch. Aber der Vollständgkeitshalber wollte ich es erwähnt haben.

**Comment by Mogli12** [comment]
Die Blickrichtung wird erst dann gewechselt, wenn das Fahrzeug auch stand und die Richtung wirklich gewechselt hat. Abgesehen davon kann ich keinen Weidemann Hoflader im Spiel finden.

**Comment by FarmerMike87** [comment]
Ja is egal dann, dann nutze ich die alternative und schau mich mit der Maus um.

**Comment by Mogli12** [comment]
Ok, jetzt konnte ich es reproduzieren

**Comment by Mogli12** [comment]
Das Problem ist in der neuesten Version korrigiert
