### ISSUE TITLE
[Build11] Massive Lag im Rübenernter

### ISSUE THREAD

**Issue by HurrycaneBE** [Mogli12/VehicleControlAddon#648]
Moin , 
habe heute morgen Build11 auf den Dedi geschmissen. Alles läuft fein , nur im Rübenernter Ropa Panther (vom Spiel , nicht modded)
bekomme ich massiven lag. Server Pingzeit steigt jenseits von 250ms. Andere Fz keine Probleme bemerkt , nur bei diesem. Fehler leider keine Im log. Da es aber gestern mit Build9 alles einwandfrei funktionierte , vermute ich das Build11 hier irgendwo einen Bug hat.

**Comment by iljarogoff** [comment]
Bestehen die lags auch, wenn du VCA rausnimmst?

**Comment by Mogli12** [comment]
Seit Build 11 verfügbar ist hat heute geregnet. Mit Build 9 war das Wetter besser...

**Comment by HurrycaneBE** [comment]
Nein ohne VCA hat der ernter keinen Lag , gerade eben getestet
