### ISSUE TITLE
Allrad wird nicht angezeigt

### ISSUE THREAD

**Issue by Nicokdge** [Mogli12/VehicleControlAddon#650]
Bei mir wird das Symbol für die Alrad steuerung nicht angezeigt

**Comment by Mogli12** [comment]
Wurde Allrad in den Settings eingeschaltet? Ist das HUD eingeschaltet?

Abgesehen davon: Version, log.txt und Screeshot fehlen.

**Comment by Nicokdge** [comment]
Wo schalte ich das HUD an?

**Comment by Mogli12** [comment]
Tasten LCtrl + C

**Comment by Nicokdge** [comment]
Ja das weis ich schon so komme ich in die Einstellungen aber da ist bei mir keine Möglichkeit das HUD zu aktivieren?!
