### ISSUE TITLE
Bremsgeschwindigkeit bei "Geschwindigkeit permanent halten"

### ISSUE THREAD

**Issue by jenseits94** [Mogli12/VehicleControlAddon#652]
Hi Mogli,

mir ist aufgefallen, dass die Geschwindigkeitsreduktion mit "Geschwindigkeit permanent halten" deutlich geringer ist als die tatsächliche Geschwindigkeit des Traktors.

Bsp.: Ich bremse von 40 km/h auf 20 km/h  mit aktiviertem "Geschwindigkeit halten" ab. Während der Traktor schon auf 20 km/h ist geht die eingestellte Geschwindigkeit (über dem HUD) immer noch runter.

Das ganze ist also etwas verzögert, weil die Geschwindigkeitsreduktion kleiner ist als die tatsächliche Bremsgeschwindigkeit. Besonders kritisch/ störend ist das wenn der Traktor bereits steht, die eingestellte Geschwindigkeit aber noch bei 10km/h ist und der Traktor somit beim loslassen der Bremse von alleine wieder auf die 10 km/ beschleunigt.

Für mich sieht das so aus, dass aus irgendeinem Grund die "Geschwindigkeit halten" Geschwindigkeit und die tatsächliche Geschwindigkeit beim Bremsen nicht gekoppelt sind. Beim LS19 hat das einwandfrei funktioniert.
 
Ich hoffe ich konnte das Problem einigermaßen beschreiben.

Grüße

**Comment by Mogli12** [comment]
Dieses Problem sollte mit Build 19 behoben sein.
