### ISSUE TITLE
 Rückwärtsfahren

### ISSUE THREAD

**Issue by DonBolli** [Mogli12/VehicleControlAddon#653]
Hallo

Ich habe festgestellt das man, wenn man vergisst ihn zu deaktivern. Nach etwa 2-3 Meter schlägt er stark ein, wenn man ein gezogenes 
Atbeitsgerät dahinter hat, ist das Chaos vorprogrammiert, Da es nur auftritt wenn man es aktiv hat ist es nicht weiter tragisch, ich wollte es dir einfach mitteilen.

**EDIT:**
Ich verwende Build 13, das "Problem" trat jedoch auch in früheren Versionen auf

**Comment by Sacred-Shadow** [comment]
Kann ich bestätigen .. war im LS19 ja glaube nicht so? Da konnte man schön auf der Spur zurück fahren.
Dachte das wurde mit Absicht geändert. :D

**Comment by Mogli12** [comment]
Bitte probiert Build 18. Sollte das Problem immer noch auftreten, dann öffnet bitte **dieses** Issue wieder.
