### ISSUE TITLE
No drive with HandRPM

### ISSUE THREAD

**Issue by Dldrth** [Mogli12/VehicleControlAddon#654]
Sorry to open the issue about this again. 
Thanks for the quick action you took about the subject.
In 19, HandRPM was connected to vehicle drive through the gears as well. I tried the last version of the VCA. Yes, I can set the RPM and tractor holds that RPM, but it does not drive the tractor unfortunately. It just holds the rpm, maybe it holds the rpm just for pto as gearbox removed from VCA as you mentioned before.
Would it be possible to also drive the vehicle by matching the RPM according to the gear you are currently in. 
A quick video I just took to show as it was acting in 19. 
I use the mouse wheel to set RPM and let the tractor drive according to the gear it is in. 
Only a tap to the throttle used to take the vehicle out from park used in the video.
Thank in advance for all the troubles.

https://www.youtube.com/watch?v=BwmpIL-dFvA&ab

**Comment by Mogli12** [comment]
Hi,

Just tapping the throttle won'T be enough. The hand throttle in FS22 has limitations. But build 14 will try to accelerate to the requested RPM if the clutch is closed. 

Best regards

**Comment by Dldrth** [comment]
Yeah, the throttle feels bit different. But it works like charm. Thanks for the update. 
Now I can start playing 22 thanks to you.
