### ISSUE TITLE
Einstellungen speichern ?

### ISSUE THREAD

**Issue by Tommyloo13** [Mogli12/VehicleControlAddon#655]
Guten Morgen, mir ist aufgefallen, dass er die Einstellungen über STRG+C nicht speichert, wenn man den Server verlässt.

Ich muss immer wieder alles neu einstellen, gibt es eine Möglichkeit, dass man nicht immer wieder jedes Fahrzeug einstellen muss ( Lenkgeschwindigkeit, freie Lenkung, Kamera etc.) ?

Mit freundlichen Grüßen 

Thomas

**Comment by Mogli12** [comment]
Nein
