### ISSUE TITLE
Standart settings for first use

### ISSUE THREAD

**Issue by Crykor90** [Mogli12/VehicleControlAddon#656]
Die Grundeinstellungen sind leider sehr nervig 

Folgender Vorschlag:
-Freie Fahrt auf aus stellen 
-90° Standart bei gps 
-Lenkung alles auf aus um standart steuerung zu haben
-Geschwindigkeit von 50% auf 100% erhöhen

leider muss man sonst bei allen Fahrzeugen diese Einstellungen korrigieren und das ist sehr nervig

**Comment by Mogli12** [comment]
Auch das ist nur ein MP Fehler => #620
