### ISSUE TITLE
Ankuppeln von Geräten

### ISSUE THREAD

**Issue by AgraSrolch** [Mogli12/VehicleControlAddon#657]
Hi ich nutze Build 14 auf Server und offline in beiden fällen ist ein ankuppeln von Geräten nicht möglich . kein Zeichen von Ankuppeln

2021-12-02 14:50 Error in vehicleControlAddonConfigEvent: Event has wrong end marker. 

[log.txt](https://github.com/Mogli12/VehicleControlAddon/files/7642666/log.txt)

**Comment by Mogli12** [comment]
Bitte #620 durchlesen
