### ISSUE TITLE
Dediserver

### ISSUE THREAD

**Issue by LzzDieter** [Mogli12/VehicleControlAddon#658]
Weiß jemand ob der Mod mittlerweile sauber auf dem Dedi läuft. Dienstag ist das Spiel im MP abgestürzt. Danke

**Comment by xxdacrusherxx** [comment]
Ja wir nutzen den Build14 aktuell und es läuft, bereits der Build9 lief ohne Abstürze auf unserem Dedi Server

**Comment by Mogli12** [comment]
Und schon wieder ein neues MP Issue. -> #620 #641
