### ISSUE TITLE
Spurführung - Wendefahrt - Bei stehendem Fahrzeug durchgehend rechts-links

### ISSUE THREAD

**Issue by Jaylem176** [Mogli12/VehicleControlAddon#659]
Beim Panther 2 von Ropa wird bei stehendem Fahrzeug und eingeschalteter Spurführung durchgehend rechts-links gesteuert, wenn als Lenkmodus "Wendefahrt" ausgewählt ist. Beim Rückwärtsfahren passiert das gleiche.
Sobald man geradeaus fährt ist es okay.

Genutzte Version ist die 14. Ich bin leider noch nicht dazu gekommen andere Fahrzeuge mit Wendefahrt zu testen.

**Comment by Mogli12** [comment]
Bitte probier Build 18. Sollte das Problem immer noch auftreten, dann öffne bitte **dieses** Issue wieder.
