### ISSUE TITLE
Only small typo

### ISSUE THREAD

**Issue by Torolino** [Mogli12/VehicleControlAddon#662]
Hello Mogli,

I think there is a small typo in the "modDesc_l10n_de.xml". In line 190 is written `Sie werden in der Datei modsSettings/FS19_VehicleControlAddon/config.xml gespeichert]]></longText>`. I think this should be `...FS22_...`

Thank you for your really great and fast work. 

Oli

**Comment by Mogli12** [comment]
Hi Oli,

Thanks for the hint. The help texts are not shown yet. There is a help section in the ingame menu. I will try to place them there.

BR, Stefan
