### ISSUE TITLE
Featurereques: Tasten für Arbeitsweite

### ISSUE THREAD

**Issue by Farantis81** [Mogli12/VehicleControlAddon#663]
Moin - ich liebe deine Mods - wir haben sie schon im 19er eingesetzt. Was ich mir echt noch wünschen würde, wäre eine Möglichkeit die Arbeitsbreite und offset per Tastendruck zu manipulieren. Wenn man z.b. nach einem Schwader mit dem Ladewagen nachfahren möchte, oder z.b. beim Ballensammeln. Vor allem mit Sidepanel und/oder SimDashboard würde das echt zur Immersion beitragen. 

Grüße ausm Ösiland

**Comment by Mogli12** [comment]
Es gibt nur eine Tastenkombination zum automatischen Ermitteln der Arbeitsbreite.
