### ISSUE TITLE
inching

### ISSUE THREAD

**Issue by cabmac** [Mogli12/VehicleControlAddon#665]
Hi Stefan, klasse, dass du das so schnell rausbringst...jetzt kann ich dann auch mal anfangen :D .

Das "inching" funktioniert bei mir nur, wenn der traktor ausgewaehlt ist. wenn ich Anhaenger oder anbaugeraete dran habe, und diese ausgewaehtl sin, gehts leider nicht.

Schoene Gruesse

Claudio

**Comment by Mogli12** [comment]
Hallo Claudio,
das ist eine Doppelbelegung der Taste. Leider liegt die Kupplung auf LShift. Und LCtrl+W und LAlt+W sind schon belegt.
Viele Grüße, Stefan

**Comment by Leon8490** [comment]
Bei mir funktioniert das Schalten mit VCA irgendwie gar nimmer Lastschaltstufen kann ich noch Schalten aber die normalen Gänge nicht mehr muss ich da im VCA irgendwas löschen weil ich kann so mometan nicht mehr Schalten wenn ich Komplett Manuell fahren will mit meinem G29 mit Shifter und Kupplung weil Doppelt belegt is im LS bei mir eigentlich nichts

**Comment by cabmac** [comment]
> Hallo Claudio,
> das ist eine Doppelbelegung der Taste. Leider liegt die Kupplung auf LShift. Und LCtrl+W und LAlt+W sind schon belegt.
> Viele Grüße, Stefan

Ahh, ok, dann versuch ich mal die Kupplungsbelegung zu löschen... brauche ich mit Tastatur sowieso nicht..Ixh hatte das inching naemlich wieder auf LShift gelegt, sowie wie ichs (wir 😆 l ja gewohnt waren.

**Comment by Leon8490** [comment]
> > Hallo Claudio,
> > das ist eine Doppelbelegung der Taste. Leider liegt die Kupplung auf LShift. Und LCtrl+W und LAlt+W sind schon belegt.
> > Viele Grüße, Stefan
> 
> Ahh, ok, dann versuch ich mal die Kupplungsbelegung zu löschen... brauche ich mit Tastatur sowieso nicht..Ixh hatte das inching naemlich wieder auf LShift gelegt, sowie wie ichs (wir 😆 l ja gewohnt waren.

Wenn du weißt was man löschen muss würd mich das auch interessieren

**Comment by cabmac** [comment]
Hallo, ich habe die inching Taste auf LShift gelegt und die Kupplung LShift geloescht....funktioniert....close...
