### ISSUE TITLE
Offset alignment appears to be miscalculating when turning around (Revision 18)

### ISSUE THREAD

**Issue by doyouevencarebro** [Mogli12/VehicleControlAddon#666]
I just tested the offset functionality with a few mowers on the latest version and it looks like the shift is off a bit when completing a turn. I provided some screenshots.

First screenshot is my starting position, no issues there.

Second screenshot is my return pass which is when things start to misalign. Seems to be aligning the end of the first pass with the tractor rather than the mower leaving grass between the tractor and the mower on the return pass.

Third screenshot shows the 3rd pass from the original side where the misalignment continues.

Fourth screenshot is the 2nd return pass similar to the second screenshot.

This alignment issue continues after each subsequent pass. This occurs on the two offset mowers from the default shop (no modded equipment / dlc). I verified the auto width for each mower as well to be sure.

![01](https://user-images.githubusercontent.com/38877430/144696669-d08b465d-3774-40f2-915c-a75329c72635.jpg)
![02](https://user-images.githubusercontent.com/38877430/144696673-a09aa119-33e9-468e-b065-f63140754163.jpg)
![03](https://user-images.githubusercontent.com/38877430/144696676-dfc1545e-3eab-4071-8aa3-e0299c56c2ca.jpg)
![04](https://user-images.githubusercontent.com/38877430/144696679-faa66874-e0ad-4278-8758-1799ca3134be.jpg)

**Comment by Mogli12** [comment]
Please try build 19. If the problem is not yet fixed, then please reopen **this** issue.
