### ISSUE TITLE
Rüfa

### ISSUE THREAD

**Issue by DerEwok** [Mogli12/VehicleControlAddon#668]
Hallo und DANKE für deine  super Arbeit !
Habe das Problem das die Rüfas nicht mehr funktionieren, in allen Maschinen wird der Befehl in F1 nicht mehr Angezeigt.

Vielleicht kannst du noch die Möglichkeit schaffen das man Voder/Hinter Def zusammen schalten kann. Mit Tastenbelegung geht es leider nicht. Es wird dann immer das erste ausgeführt, auch wenn man die gleiche Belegung macht.

THX Ewok

**Comment by cater901645** [comment]
Rückfahreinrichtungen  funktionieren allgemein noch nicht, sin buggy.
Man kann allgemein keine 2 Funktionen auf eine Taste legen.

**Comment by Mogli12** [comment]
Da kann VCA leider nichts machen.
