### ISSUE TITLE
GPS Linien

### ISSUE THREAD

**Issue by timmi4026** [Mogli12/VehicleControlAddon#669]
Hallo Mogli, erst mal ein großes Danke das du in der kurzen Zeit eine Stabile Version auch für den Mp her gezaubert hast. Läuft alles super bisher. 
Meine Frage: Wäre es noch machbar die Linien was heller bzw sichtbarer zu machen, was ich meine wenn man wendet und so in den 90 grad Winkel zu den Linien kommt verschwinden sie irgendwie und sind sehr dünn gehalten. Ist das machbar das man sie im komplett sieht wenn man 360 grad rund herum schaut?

LG TImmi

**Comment by Mogli12** [comment]
Hallo Timmi,
das ist nicht so einfach. 
LG Stefan

**Comment by timmi4026** [comment]
Ich glaub an Dich ^^

**Comment by BigBlackBahamut** [comment]
Also, super Arbeit. 
Aber ich muss leider zustimmten. War gerade auf einem Weizenfeld. Leider wurden die GPS-Linien komplett vom Rasen links und vom Weizen komplett bedeckt. Man hat die GPS-Linien leider gar nicht mehr gesehen. Vielleicht ist es Möglich eine weitere Linie über die Originale Linie mit einer Tastenzuweisung zu setzen.

**Comment by Mogli12** [comment]
Man kann die Linen doch in den Einstellungen auf hoch setzen.

**Comment by BigBlackBahamut** [comment]
Ah, sorry. In Klammern stehend. Nicht gesehen. Dann habe ich nichts gesagt :-)
Nochmals, Klasse Arbeit

**Comment by Mogli12** [comment]
Bitte probiert die neueste Version (FS22 1.0 rc2).
