### ISSUE TITLE
Handgas - Traktoren erreichen nicht die Höchstgeschwindigkeit

### ISSUE THREAD

**Issue by templer013** [Mogli12/VehicleControlAddon#670]
Build 19

Handgas auf maximaler Einstellung, jedoch wird die Höchstgeschwindigkeit nicht erreicht. 

z.B. MF 3670 auf Elmcreek ohne Anhänger, Handgas auf 2200 RPM erreicht in Gang 4 Gruppe D ca. 35km/h 

Mit durchgetretenem Pedal erreicht man im gleichen Gang die Höchstgeschwindigkeit von 39km/h

VCA Einstellung: 
Leerlaufanreicherung: an 
(sonst funktioniert Handgas überhaupt, man kann zwar die Drehzahl einstellen, aber die Geschwindigkeit wird davon nicht beeinflusst, als würde die Kupplung nicht schließen, wenn man vom Pedal geht, um initial in Bewegung zu kommen.)

[log-copy.txt](https://github.com/Mogli12/VehicleControlAddon/files/7654508/log-copy.txt)

Vielen Dank für deine Arbeit an dem Mod!

**Comment by Mogli12** [comment]
Hallo,

In FS22 ändert VCA das Getriebe nicht. Handgas teilt sich in 2 Bereiche auf. Zunächst wird über die Zapfwellenfunktion die Drehzahl angefordert. Darauf reagiert das Standardgetriebe nunmehr wie beobachtet. 

Zusammen mit der Leerlaufanreicherung gibt das Fahrzeug dann auch selbstständig Gas. Aber warum trotzdem nicht die volle Geschwindigkeit erreicht wird? Da habe ich keine Ahnung. Das passiert irgendwo in den Tiefen des Standardgetriebes.

LG Stefan

**Comment by templer013** [comment]
Hi Stefan, 

danke für die schnelle Antwort... das Standardgetriebe... ja... das ist ein ganz tolles neues Feature.  :(

VG

**Comment by Fendtfan84** [comment]
Hey Stefan,

erstmal vielen Dank für deine super Arbeit bezüglich VCA. Das Getriebe hat Giants ja nicht richtig dargestellt. Das fängt ja schon dabei an,dass der Traktor abgewürgt wird wenn man die Kupplung kommen lässt. Ich würde es sehr begrüßen wenn du dich bezüglich VCA auch dem Getriebe annehmen würdest. Wenn nicht verstehe ich das auch absolut.

Viele Grüße vom Realismus Spieler aus Südhessen
Wünscht dir Christopher

**Comment by Mogli12** [comment]
Hallo Christopher,

Eventuell gehe ich das Thema Getriebe später mal an. Wenn, dann aber nur als realistischere Version des Getriebes, welches im Traktor bereits eingestellt ist.

Bis dahin mache ich dieses Issue erstmal zu.

Viele Grüße
Stefan
