### ISSUE TITLE
snapLeft / snapRight

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#671]
Hi Stefan, wäre es möglich die angehängten Geräte (Pflug, Grubber, ...) während der Wende anzuheben?

Hi Stefan, would it be possible to lift the attached equipment (plow, cultivator, ...) during the turn?

**Comment by Mogli12** [comment]
Hallo, nein, das möchte ich nicht anbieten. Eventuell wird es ja das Vorgewendemanagement wieder als Mod geben.

**Comment by Williwillswisse** [comment]
Alles klar, vielen Dank für die schnelle Antwort.
Und natürlich für VCA überhaupt 😉

Mit freundlichem Gruß

Christoph Willen
Heerdamm 2
49692 Cappeln-Warnstedt
Tel.: 01522 7417285

Von: Stefan ***@***.***>
Gesendet: Sonntag, 5. Dezember 2021 10:16
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [Mogli12/VehicleControlAddon] snapLeft / snapRight (Issue #671)


Hallo, nein, das möchte ich nicht anbieten. Eventuell wird es ja das Vorgewendemanagement wieder als Mod geben.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMogli12%2FVehicleControlAddon%2Fissues%2F671%23issuecomment-986193792&data=04%7C01%7C%7Cf067688efb1147c311f208d9b7cff2fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637742926023746362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7vXvg5y46DJsIBDsqDgdbBz0ixhql7UgLfpCY5zQx38%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALHKSCIBDTUBFZT7D4S23FLUPMUXRANCNFSM5JME4CNQ&data=04%7C01%7C%7Cf067688efb1147c311f208d9b7cff2fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637742926023746362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=okNs87YpVR8EKvCgbo5xOV4VOFLfVsYM8iy1CQpHxfo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf067688efb1147c311f208d9b7cff2fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637742926023756356%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bk6EtO0JqQnXdu6Tni7KFi8zpEFF5nMGin4xA5iHdf0%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf067688efb1147c311f208d9b7cff2fe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637742926023766347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=slpLWmGDwQuvJ9%2Bs1r8TvVai7MuKuXwFgskvGFOQarM%3D&reserved=0>.
