### ISSUE TITLE
"Geschwindigkeit halten" - Beschleunigungsproblem

### ISSUE THREAD

**Issue by jenseits94** [Mogli12/VehicleControlAddon#672]
Hi Mogli,

vielen Dank erstmal für die schnelle Lösung mit dem Bremsproblem bei "Geschwindigkeit halten".

Ich habe noch ein Problem mit "Geschwindigkeit halten" gefunden. Diesmal bei der Beschleunigung. Die Geschwindigkeit von "Geschwindigkeit halten" lässt sich bei abgesenktem Anbaugerät bis auf die max. zulässige Geschwindigkeit einstellen, obwohl der Traktor diese Geschwindigkeit nicht erreichen kann.

Bsp.: An einem Traktor mit abgesenktem Pflug wird mit "Geschwindigkeit halten" die Geschwindigkeit erhöht. Der Traktor beschleunigt bis zur Leistungsgrenze (6 km/h), aber die eingestellte Geschwindigkeit lässt sich weiter bis zur zulässigen Geschwindigkeit des Pflug erhöhen (10,5 km/h). Wenn man jetzt den Pflug anhebt, beschleunigt der Traktor selbstständig auf die eingestellten 10.5 km/h.

Wenn man ohne HUD spielt, sieht man ja leider nicht welche Geschwindigkeit eingestellt ist und wird von der plötzlichen Beschleunigung des Traktors überrascht.

Ist es möglich die eingestellte Geschwindigkeit bei "Geschwindigkeit halten" an die tatsächliche Geschwindigkeit beim Beschleunigen zu koppeln?

Build 19 wurde verwendet

Grüße

**Comment by Mogli12** [comment]
Bei Geschwindigkeit halten ist die Geschwindigkeit über Gaspedal und Bremse an die tatsächliche Geschwindigkeit gekoppelt. Es darf aber 1 m/s mehr oder weniger sein. Das sind 3,6 km/h.
