### ISSUE TITLE
Motor Leistung.

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#673]
Hi Stefan, schön das du den Weg in den LS22 gefunden hast.^^

Meine Frage ist, wird man die Motorleistung wieder Ingame anpassen können falls diese unrealistisch ist und ob man in Zukunft auch die Getriebe per own config für die Schlepper selbst bauen könnte und dazu ein 2 Gruppenset zu erstellen ( Gänge Gruppen Lastschaltstufen)

Viele Grüße Chris 

 Modding Team RedCat3D

**Comment by Mogli12** [comment]
Hallo Chris,

bislang habe ich nicht vor, am Motor oder Getriebe selber etwas zu verändern. 

Viele Grüße, Stefan
