### ISSUE TITLE
Der 19er Bug ist wieder da

### ISSUE THREAD

**Issue by SuperSeba** [Mogli12/VehicleControlAddon#674]
Hatte heute den Bug den es schon im 19er gab. Bin mit dem John Deere 9470RX mit Allrad und beiden Sperren auf ein zu verdichtendes Fahrsilo hochgefahren. Just in diesem Moment rauscht der Traktor in unheimlicher Geschwindigkeit rückwärts über die Karte und der Tank leer sich im Bruchteil einer Sekunde. Das Phänomen ist relativ reproduzierbar.

**Comment by Mogli12** [comment]
Das war schon in LS19 ein Bug in der Giants-Engine. Bei Raupenfahrzeugen sollte man Allrad ohnehin besser aus lassen.
