### ISSUE TITLE
Wrong settings for Kverneland PW 100 - 12

### ISSUE THREAD

**Issue by crane-denny** [Mogli12/VehicleControlAddon#675]
The calculated settings are 5.7m as working witdth and 0.9m as offset.
But it should be something like 6m and -0.3m offset depending on which site the plough is setup to.
My experience is that VCA is always using the inverted offset which is wrong.

There might be an layer 8 issue here but I haven't figured anything on my side at this moment. :)

**Comment by Mogli12** [comment]
VCA calculates the width and offset using the AI marker. But you can always enter it manully.

**Comment by crane-denny** [comment]
So the ingame numbers are wrong? 🤔 
if so I would open the bug report on Giants side ^^
