### ISSUE TITLE
Auf Nitrado Server macht der Mod Lua Fehler

### ISSUE THREAD

**Issue by Brombee42** [Mogli12/VehicleControlAddon#677]
Kann man den VCA Mod jetzt Multiplayer spielen? Gestern am 5.12.21 um19 Uhr  haben wir den VCA Mod ausprobiert aber ging nicht da 
LUA Fehler kamen und das Spiel abstürzte .Welcher Code funktioniert vom VCA auf Nitrado Server?

**Comment by Mogli12** [comment]
Hallo,

wenn Du einen Fehler melden möchtest, dann bitte mit Log-Dateien von Server und Client und Beschreibung des Fehlers. 

Falls Du nur wissen möchtest, welche Version stabil auf einem Dedi-Server läuft, dann warte bitte bis zur Veröffentlichung im ModHub.

Danke.

**Comment by Brombee42** [comment]
Ok 👌 --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 06.12.21, 07:01 schrieb Stefan Biedenstein ***@***.***>:

   
  Hallo, 
  wenn Du einen Fehler melden möchtest, dann bitte mit Log-Dateien von Server und Client und Beschreibung des Fehlers. 
  Falls Du nur wissen möchtest, welche Version stabil auf einem Dedi-Server läuft, dann warte bitte bis zur Veröffentlichung im ModHub. 
  Danke.
