### ISSUE TITLE
Non Stop Cruise : Is it possible to keep vehicle going?

### ISSUE THREAD

**Issue by zetdota** [Mogli12/VehicleControlAddon#678]
Is it possible to keep the vehicle going, once you've set the cruise control and lane? 

I'd like to leave vehicle at this point, and do something else. 

In FS19 I had a mod to keep the vehicle going, but I'm not sure how to in FS22

**Comment by Mogli12** [comment]
Giants has already implemented someting to keep the vehicle going. I do not want to mess up with it.
