### ISSUE TITLE
Feature Request: Global Settings

### ISSUE THREAD

**Issue by tslindsay** [Mogli12/VehicleControlAddon#679]
I can see that there’s an XML for VCA in the modSettings folder, but it’s empty.

I don’t know if it’s planned or already possible, but it’s be nice to be able to set some global settings for the mod, so that you don’t have to change the settings every time you get a new vehicle.

i.e. I’d like Adaptive Steering and Manual Trans/Diff to be enabled by default for my vehicles.

**Comment by Mogli12** [comment]
You can maintain the global settings in the game (LAlt+LCtrl+C).
