### ISSUE TITLE
Feature Request: Horizontal Turn Lines

### ISSUE THREAD

**Issue by zetdota** [Mogli12/VehicleControlAddon#684]
Could you consider 2 lines, that one could set, that are always perpendicular to the usually displayed assist drive lines.

Their function would be to press ALT+A or ALT+D, when tractor passes through them, for starters. With currently set settings.

You'd need input bindings for moving the lanes around, and setting whether each lane should turn left or right.

**Comment by zetdota** [comment]
Later on, it could also press V, whenever passing a lane with certain, set offsets.

**Comment by Mogli12** [comment]
Hi,

Sorry, but I am not planning to implement this. 

Best regards
