### ISSUE TITLE
Reverse Drive Control blocked

### ISSUE THREAD

**Issue by bjt3833** [Mogli12/VehicleControlAddon#688]
I noticed that I couldn't swap to reverse drive control on one of my FS22 saves so I swapped to a fresh game, enabled nothing but the government subsidy mod and checked to make sure I could use reverse drive control in vanilla and I could. Next I enabled only government subsidy and VCA on the fresh save and I could no longer swap to reverse drive control on the Fendt or the Valtra. I made sure to test to make sure it wasn't just a problem with the Valtra.

It's on the Haut map on a fresh save and no other mods enabled except VCA. I didn't think log was needed since it is easily reproducible.

I also have the latest version of VCA from the github, build 21, that was posted 6 hours prior to my post. I didn't see this mentioned when I looked through the issues already but if it was already posted not in english then I would have missed it. Thanks

**Comment by Mogli12** [comment]
Vehicle? Screenshot?

**Comment by Mogli12** [comment]
Hi,
These are just duplicate input bindings. Please adjust them to your needs.
Best regards,

**Comment by bjt3833** [comment]
> Hi, These are just duplicate input bindings. Please adjust them to your needs. Best regards,

Oh, I'm sorry.
Key bindings were my first guess but I missed it when I looked through them the first time. 

Thank you.
