### ISSUE TITLE
Linien Auswahl

### ISSUE THREAD

**Issue by FalconDS9** [Mogli12/VehicleControlAddon#689]
Hi, folgendes problem:
Ich erstelle das Raster am Feldrand, lasse die erste linie etwas überlappen damit es auch passt. Lässt sich soweit mit der 1° Einstellung und rechts/links schieben perfekt platzieren.
Dann fahre ich die erste Linie im Feld an, will das System aktivieren und er fährt direkt wieder zum Feldrand...
Selbes wenn ich dann eben selber die erste Linie gefahren bin und ihn auf die nächste Position stelle..
Wie kann ich ihm beibringen das er bitte die Linie nehmen soll auf die ich ihn geparkt habe? Er soll nicht selber denken sondern einfach da fahren wo ich ihn einschalte. Und ich will auch nicht jedesmal die Linien mit Tasten durchschalten müssen, da fehlt ein hervorheben der gewählten Linie, vll in Orange.
Weiterhin wäre es schön wenn man ihn so einstellen kann das sein Raster immer 0.5m überlappt, falls ich eben doch manuell die Linie abfahren muss.
War nu leider ein frustrierender erster Test des Systems mit einem Kampf um die Kontrolle gegen selbiges xD
Wäre sehr dankbar für etwas mehr Einfluss =)

**Comment by FalconDS9** [comment]
Nachtrag: war vll nicht schlau als erstes Gerät gleich eines mit 42m Arbeitsbreite zu nehmen... aber genau dafür kann ich dieses System eben brauchen..
Bei kleinen Geräten ist es machbar eine Linie weiter zur Seite zum einstellen des Feldrandes zu nehmen.. wäre trotzdem schön wenn er genau die Linie auf die man ihn stellt als Fahrspur akzeptiert, auch wenn es eigentlich eine Seitenlinie ist.. flexibilität halt.

**Comment by Mogli12** [comment]
Hallo Falcon,

Ich weiß nicht, war Du am Feldrand machst. Du musst dein Fahrzeug so positionieren, dass es nahezu perfekt auf der ersten Bahn steht. In Deinem Beispiel müsste die Mitte des Fahrzeugs ca. 20,5m vom Rand entfernt stehen. Die Arbeitsbreite sollte auf 41m von Hand korrigiert werden.

Aber VCA wird das nicht automatisch für Dich erledigen.

Viele Grüße, Stefan

**Comment by FalconDS9** [comment]
ich fange am rand an weil man dort die linie besser auf den rand packen kann.. bei 42m ist das aufgrund des winkels doch recht schwer zu sehen, vor allem an feldern die keine 90° kante auf der seite haben.. sonst muss ich ja um die position der ersten bahn zu finden material verschwenden oder antesten...
raster platzieren, bahn anfahren und arbeit starten war für mich die logische reihenfolge...

aber ich hab mittlerweile einen workaround für mich gefunden.. ich mach das so am rand wie bisher..allerdings stell ich ihn dann manuell auf die erste bahn im feld, lösche das raster und setze es dort neu.... geht wohl nicht anderst.

wegen der arbeitsbreite wäre ein -0.5m modifikator denkbar aber auch nicht so wichtig wenn das system macht was es soll dürften ja niemals lücken entstehen, war nur ein gedanke falls ich das automatische spurhalten nicht nutzen kann.
