### ISSUE TITLE
Feature request: Freie Kamera

### ISSUE THREAD

**Issue by FalconDS9** [Mogli12/VehicleControlAddon#690]
Hi,
dein Mod hat einfluss auf die Kamera, wäre es vll auch möglich die Kamera komplett frei vom Fahrzeug zu bekommen? Also das ich sie immer selber mit der Maus drehe und nie das Spiel an der Ausrichtung dreht? 
Grade beim wenden fahren ist es ein ständiger Kampf mit dem Spiel die Kamera auf mein Ziel gerichtet zu halten.
Was auch ein sehr großes Problem ist: Die Knicklenker, Radlader zb.. ich kann die nicht fahren, da wird mir schlecht weil bei jeder kleinen Lenkbewegung die Kamera mit zuckt. Da hilft deine Lenkkamera leider auch nicht, bei Knicklenkern steuert die in die falsche Richtung..

Danke fürs lesen =)

**Comment by Mogli12** [comment]
Das geht doch schon längst mit Taste KEY_insert (Einfg).

**Comment by Mogli12** [comment]
In der neuesten Version sollte es klappen. Die Einstellung wird allerdings nicht gespeichert.
