### ISSUE TITLE
Spurführung funktioniert nicht richtig

### ISSUE THREAD

**Issue by Todd674** [Mogli12/VehicleControlAddon#691]
Ich habe soeben herausfinden müssen, dass die Spurführung mit dem Knicklenker New Holland T9 Tracked nicht funktioniert.
Weitere Tests haben ergeben, dass das Problem bei allen knickgelenkten Grosstraktoren besteht.

Sobald man die Spurführung aktiviert, rasten die Knicklenker komplett aus. Sie lenken bei Fahrt nach vorne wild nach links und rechts.
Beim Rückwärtsfahren jedoch halten sie dann schön die spur.

**Comment by Mogli12** [comment]
Ich werde die Funktion bei knickgelenkten Fahrzeugen deaktivieren. Das Problem ist, dass sich beim Lenken der Referenzpunkt selber nach rechts oder links verschiebt.

**Comment by Mogli12** [comment]
Bitte teste die aktuellste Version.

**Comment by Todd674** [comment]
Werd ich so gleich tun.

**Comment by Todd674** [comment]
> Bitte teste die aktuellste Version.

Also, die Knicklenker verhalten sich jetzt in der Vorwärtsfahrt so wie sie sollten. Das wilde links-rechts lenken ist jetzt beim rückwärts fahren, denke aber nicht, dass das grossartig stört.
Das war ausgezeichnete Arbeit. Danke dir von gamzem Herzen :D

**Comment by Mogli12** [comment]
Für das automatische Lenken benötigt man im I3D-Modell des Fahrzeugs einen Referenzknoten. Ich habe jetzt gesehen, dass Giants für das neue Helfersystem eine neue Funktion getAIRootNode gebaut hat. Damit geht es jetzt forwärts.

Beim Knicklenker ist eben das Problem, dass die Mitte des Fahrzeugs durch das Lenken in die entgegen gesetzte Richtung verschiebt.
