### ISSUE TITLE
Rückwärts ohne Kamerabewegung / Kamera zentrieren

### ISSUE THREAD

**Issue by BigBlackBahamut** [Mogli12/VehicleControlAddon#692]
Hi, habe da einfach mal ´ne kleine Frage. Ist es vielleicht möglich das man die Kamerabewegung Rückwärtsfahren deaktivieren kann?
Wenn ja dann wäre das schon mal cool.

Die andere Sache ist ob es vielleicht auch möglich ist mit Tastenzuweisung die Kamera zu zentrieren?

Lieben Gruß

**Comment by Mogli12** [comment]
RShift + hoch stellt die Kamera gerade nach vorne und hinten. Die Rotation der Kamera kann nicht für die Fahrtrichtung getrennt einstellen.
