### ISSUE TITLE
enhancement Rasterbahnen Richtung

### ISSUE THREAD

**Issue by alexanderweide** [Mogli12/VehicleControlAddon#694]
Hi Mogli,

vielen Dank für deine mega Arbeit. Ich habe auch das neue Feature Rasterbahnen versatz/wechsel oder wie es genau heißt ausprobiert..
Ansich ist die Funktion mega, dass man die Rasterbahn via Knopfdruck wechsels kann. Noch besser wäre es wenn man am Ende des Feldes im Vorgewende eine Umkehr der Fahrtrichtung hätte. 
Aktuell lenkt VCA korrekt ein und wechselt die Rasterbahn, leider immer in die Richtung die zuvor gefahren wurde.

Daher ist mein Vorschlag/Idee eine zusätzliche Tasten Kombi einzuführen um bei Bedarf, oder Automatisch die Rasterfahrt Richtung genau entgegen gesetzt zu fahren. Zusätzlich wäre es sinnvoll eine Art Pfeil einzublenden der die exakte Fahrtrichtung zeigt.

Das Bild soll zeigen wie ich mir das mit dem Pfeil vorstelle. 

![Bildschirmfoto vom 2021-12-08 14-58-00](https://user-images.githubusercontent.com/7734241/145221801-7822665a-7eb4-462d-b0ed-e068fd20af0e.png)

Solltest Du Fragen haben, immer gerne her damit ;-) 

Alex

**Comment by Mogli12** [comment]
So einfach ist das ist. Schau dir bitte die neueste Version an. Mehr kann ich aktuell nicht machen.

**Comment by alexanderweide** [comment]
SUPER absolut ausreichend vielen Dank
