### ISSUE TITLE
Help Text

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/VehicleControlAddon#696]
Help Text when you press F1 shows "global settings".

Shouldn't it rather say "Vehicle Control Global Settings" or VCA Global Settings? Or something more identifying?

Thanks!

**Comment by Jayshua83** [comment]
Also the In Vehicle Help text is "settings".

Maybe "Vehicle Control Vehicle Settings"? Or something more identifying?

Thanks!

**Comment by Mogli12** [comment]
I removed the VCA prefix because the input bindings are now sorted by mod. But I added it with rc2.
