### ISSUE TITLE
Anschalten des Mähdreschers funktioniert nicht

### ISSUE THREAD

**Issue by Thestorm1234** [Mogli12/VehicleControlAddon#697]
moin Mogli, cooler mod wollte anmerken ob noch jemand das problem hat mit dem anschalltendes mähdreschers hat, bei anderen maschine z.b sähmaschine
mähwerk geht es aber beim mähdrescher wird nichtmal die taste "B" oben links angezeigt wenn ich denn vca mod aktiv habe.

wäre um hilfe dankbar.

**Comment by Mogli12** [comment]
Du hast vermutlich Tasten doppelt belegt.
