### ISSUE TITLE
GPS Raster wird nicht angezeigt

### ISSUE THREAD

**Issue by Nendel** [Mogli12/VehicleControlAddon#704]
Das Raster wird nicht angezeigt, hab mir heute die neue Version geladen und seit dem wird mir das nicht mehr gezeigt

**Comment by Mogli12** [comment]
Bei mir wird das Raster angezeigt. Für mich ist das Problem also nicht reproduzierbar. Abgesehen davon steht - zwar auf Englisch - hier auf der Startseite, welche Infos ich in einem Issue benötige.

Viele Grüße

**Comment by Mogli12** [comment]
Ist überhaupt eine Arbeitsbreite in den Einstellungen eingegeben?

**Comment by Nendel** [comment]
Ja daran hat es gelegen, er nimmt nicht die arbeitsbereite vom Ladewagen nicht, aber ist kein Problem wen man es weiß. Vielen Dank, für die schnelle Hilfe.

**Comment by Mogli12** [comment]
Die Arbeitsbreite kann VCA nur bei Geräten, die auch vom normalen Helfer unterstützt werden, ermittelt werden. Die Schwaden liegen ja auch meist viel weiter auseinander.

**Comment by Nendel** [comment]
Das leuchtet mir ein, bin wohl auf neu erkennen gekommen, und hatte das Mähwerk nicht mehr vorne dran.

**Comment by Nendel** [comment]
Aber wäre es nicht machbar das, wenn nichts dran ist es auf ein Meter zu stellen das man das Raster sieht.
