### ISSUE TITLE
[Anregung] Anhalten am Feldrand

### ISSUE THREAD

**Issue by Sacred-Shadow** [Mogli12/VehicleControlAddon#706]
Wär es möglich, bei der Spurführung irgendwie den Feldrand mit zu berücksichtigen?
Cool wären eigentlich diese 3 Usecases, mit denen mal da echt viel abdecken würde. 

Ich als Fahrer,
möchte automatisch am Feldrand anhalten,
damit ich nicht irgendwohin fahre wenn ich mal nicht hinschaue.

Ich als Fahrer, 
möchte einen Abstand zum Feldrand einstellen können,
damit die Maschine automatisch auf/vor meinem Vorgewende anhält. 

Ich als Fahrer, 
möchte auch mit aktivierter Feldranderkennung aufs Feld fahren können,
damit ich erst am Ende der Spur automatisch anhalte.

**Comment by Mogli12** [comment]
VCA kennt leider keine Felder. Eventuell bieten [GPS](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228522&title=fs2022) oder [VorgewendeManagement](https://github.com/jason0611/FS22_HeadlandManagement) so etwas.

**Comment by Sacred-Shadow** [comment]
Sry fürs nochmal aufmachen .. aber weniger Mods sind mehr. 😀😉
Es muss ja nicht so kompliziert gemacht sein ... cool wäre halt einfach nur, dass man am Ende nicht rausballert. 

Spurführung aktiv ... "AutoStop" aktiv = am Ende des Feld stoppen. 
Wenn ich im GDN schaue, gibt es mit WheelsUtil.getGroundType ja die Möglichkeit abzufragen, ob sich die Maschine auf dem Feld befindet. 

Wenn "AutoStop" aktiv ist und die Spurführung aktiviert wird, müssten wir nur schauen, ob die Maschine nicht mehr auf dem Feld ist. 
Ist er nicht mehr auf dem Feld dann stopp. 

Ist "AutoStop" aktiv und die Spurführung wird aktiviert und die Maschine steht bereits nicht im Feld wirds ignoriert.
Ändert sich dann ja, wenn die Maschine ins Feld fährt und dann müsste das Verhalten einfach wie oben sein.

**Comment by Mogli12** [comment]
VCA kennt keine Felder. Daher kann VCA auch nicht am Ende von etwas anhalten, was es gar nicht kennt.

**Comment by Sacred-Shadow** [comment]
Aber die Abfrage ob das Gerät auf nen Feld steht kommt doch vom LS? 
Da muss doch VCA das Feld selbst garnicht kennen, muss doch nur den LS fragen ob es auf nem Feld steht oder nicht.

**Comment by Mogli12** [comment]
VCA fragt auch nicht ab, ob das Fahrzeug auf dem Feld steht. Es gibt den Begriff Feld gar nicht in VCA, ok?
