### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by blckphnx** [Mogli12/VehicleControlAddon#707]
Long time user of your mods. Would it be possible to get the neutral button back from the 2019 version of VCA. It would be immensely useful for parking vehicles in multiplayer.

**Comment by Mogli12** [comment]
With the standard gear up/down buttons you can swtich to gear N. Isn't this what you are looking for?

**Comment by clanfreak1988** [comment]
I think he mean go directly in the N gear. When you have the Truck transmission, you need a lood of gear down

**Comment by Mogli12** [comment]
In FS22 VCA does not handle gear shifting.
