### ISSUE TITLE
Fehler bei Rückfahreinrichtung

### ISSUE THREAD

**Issue by Sandman92** [Mogli12/VehicleControlAddon#708]
Hi super mod danke immer wieder dafür. 
Haben das problem bei Fahrzeugen mit Fahrtrichtungs wechsel wie der ponsse buffalo.
Wenn man das umschaltet wird nur noch auf 1 kmh beschleunugt, haben das logitech lenkrand mit console am laufen. Es lässt sich dan nur per tempomat beschleunigen in dem man diesen aktiviert.

**Comment by Mogli12** [comment]
Wie viele Issues sollen dazu noch geöffnet werden? Ich habe es selber mit dem Valtra getestet und das Problem tritt auch ohne VCA auf.

**Comment by Mogli12** [comment]
Ah, der Ponsse ist anders als der Valtra. Probiere mal die neueste Version FS22 1.0 rc4.

**Comment by Sandman92** [comment]
passt mit der rc4 klappt es danke dir
