### ISSUE TITLE
VCA blockiert andere Tasten

### ISSUE THREAD

**Issue by Achimobil** [Mogli12/VehicleControlAddon#711]
Hi,

sobald ich mit VCA und strg + Pfeiltasten das raster verschiebe, kann ich die Pfeiltasten dannach nicht mehr benutzen um die Ansicht zu drehen oder sonstiges. Anscheinend wird das Binding da überschrieben und nicht wiederhergestellt oder so was. 

Version: FS22 1.0 rc4

Falls mehr info gebraucht wird, einfach melden ;)

**Comment by Mogli12** [comment]
Hallo,

VCA meldet lediglich die ActionBindings an. Es gibt da kein Freigeben.

Ich verwende die Standardtastenbelegung und habe diese Problem nicht. Vielleicht hilft es ja, wenn Du deine inputBinding.xml löscht.

Viele Grüße

**Comment by Achimobil** [comment]
Binding mal gelöscht, so dass dieses neu erstellt wurde. Bleibt das gleich, sobald ich mit STRG +w die Fahrspur aktiviere kann ich mit den Pfeiltasten noch die Ansicht bewegen. Wenn ich dann mit STRG und Pfeiltasten die spur verschiebe kann ich die Pfeiltasten danach nicht mehr benutzen.
In einem Testspielstand mit fast keinen mods noch mal geprüft, wenn VCA drin ist und ich mache das mit VCA werden die Pfeiltasten blockiert und wenn ich das ohne VCA im spiel STRG +Pfeiltasten drücke bewegt er nur die Ansicht, es liegt also an VCA.

Kleiner Hinweis noch: Das löschen oder zurücksetzen der Bindings ist generell keine Lösung, den da hängt jedes mal eine halbe stunde neu konfigurieren des LS Lenkrads hinten dran. Ich höre das oft bei Fehlermeldungen und das löst es auch oft, aber als Lösung ist das nicht wirklich tragbar. 

Ich hoffe nach dem Text wird das Ticket auch wieder geöffnet, den es ist ein Problem durch VCA und ja nicht gelöst, auch wenn es als geschlossen markiert wurde.

**Comment by Achimobil** [comment]
Ok, gesehen dass es nicht wieder geöffnet wird. Wie öffne ich das Ticket wieder?

**Comment by Mogli12** [comment]
VCA kann daran nichts ändern. Die Tasten werden vom Spiel selber gemanagt. Ich werde dieses oder neue Issues ohnehin wieder zumachen.

**Comment by Achimobil** [comment]
Du meinst also das ist ein Problem der Giants Engine. Schade, dann kann man da wohl nicht machen.

**Comment by Mogli12** [comment]
Genau, in der modDesc.xml steht der Name der Aktion und die Default-Tastenbelegung. In der LUA Datei gibt es die Funktion onRegisterActionEvents. Dort teilt man dem Spiel mit, welche der Aktionen eingeschaltet sein sollen, und welche Callback-Funktion gerufen werden soll.

Wenn das Spiel nun denkt, dass eine Tastenkombination gedrückt wurde, dann wird der Callback gerufen.

Das Spiel entscheidet aber selber, wie es mit Doppelbelegungen umgehen soll.

**Comment by Achimobil** [comment]
Stimmt, hab ich beim autoloader übers script direkt gemacht, aber so geht es auch und sollte auch dann kein problem machen. Doppelbelegungen hab ich nicht in der binding, bigt nur die mit und die ohne strg. Sehr merkwürdig. Hofentlich dann mit einem patch behoben, weil das ist echt nervig und auch bei meinen Freunden ist das so.
