### ISSUE TITLE
Log l10n Warnings

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/VehicleControlAddon#713]
These warnings are showing up in the log for VCA FS22 1.0 RC4

Warning: Missing l10n 'input_vcaDIRECTION' in mod 'FS22_VehicleControlAddon'
Warning: Missing l10n 'input_vcaFORWARD' in mod 'FS22_VehicleControlAddon'
Warning: Missing l10n 'input_vcaREVERSE' in mod 'FS22_VehicleControlAddon'

Thanks!

**Comment by Mogli12** [comment]
It will be fixed one of the next versions.
