### ISSUE TITLE
Zurückblicken (innen)

### ISSUE THREAD

**Issue by foreverls19** [Mogli12/VehicleControlAddon#714]
Hallo,
erstmal vielen herzlichen Dank, dass du wieder den VCA für den LS22 bereit stellst.

mir ist aufgefallen wenn ich das "Zurückblicken (innen)" an habe und zurückfahre, dass ich verschiedene Ansichten je nach Traktor habe, vermutlich dem ReverseDriving geschuldet.
Hier die screenshot:
Valtra 8750 mit Rüchfahreinrichtung
![fsScreen_2021_12_14_13_38_11](https://user-images.githubusercontent.com/42800237/146007967-b1795e78-5e2d-4437-855b-8b94152465e1.png)

Fendt Favorit 515 ohne Rückfahreinrichtung
![fsScreen_2021_12_14_13_38_23](https://user-images.githubusercontent.com/42800237/146007997-9c6cf90b-b5d2-4907-a502-b5d2b25ecca7.png)
sind beide Standardtraktoren und ich benutze ein HeadTracking-System.

Mit freundlichen Grüßen

 Arnie

**Comment by Mogli12** [comment]
Ich denke nicht, dass Headtracking und die Kamerabewegungen von VCA zusammen funktionieren können.

**Comment by foreverls19** [comment]
ok Schade, 
ich dachte das es evtl ein Fehler ist, weil bei manchen Traktoren es ja geht.

**Comment by Mogli12** [comment]
VCA **rotiert** die Kamera. Headtracking **verschiebt** die Kamera.
