### ISSUE TITLE
Absturz nach Installation von VCA 

### ISSUE THREAD

**Issue by ErwinPet** [Mogli12/VehicleControlAddon#715]
Hallo, ich Spiele auf Steam, im Spiel ist alles gut und funktioniert alles. Nach Speichern und verlassen des Spiels stürzt das Spiel ab. Ich komme nicht zum Startbildschirm zurück. Ich habe alle anderen Mods schon gelöscht, es passiert nur bei VCA

**Comment by Shreklich** [comment]
Hallo dieses Verhalten zeigt der LS 22 bei jedem Skriptmod und wird von seitens Giants mit dem nächsten Patch gefixt werden. Dieser Absturz ist aber nicht spielrelevant und kann soweit ignoriert werden. Hoffe ich konnte dir helfen.

**Comment by Mogli12** [comment]
kein Kommentar
