### ISSUE TITLE
l10n_br   ( Update )

### ISSUE THREAD

**Issue by leo32128fs** [Mogli12/VehicleControlAddon#716]
Hello good night, I did more update on the Brazilian Portuguese translation, and once again thank you for your effort to keep the VCA mode up to date, it makes the game much more realistic
[modDesc_l10n_br.zip](https://github.com/Mogli12/VehicleControlAddon/files/7715204/modDesc_l10n_br.zip)

**Comment by Mogli12** [comment]
Thanks
