### ISSUE TITLE
keep speed funktion setzt sich beim wenden zurück [FS 22]

### ISSUE THREAD

**Issue by VivienHardgas** [Mogli12/VehicleControlAddon#718]
aloha aloha erstmal vielen vielen dank für die schnelle VCA verfügbarkeit. 

mir ist aufgefallen das wenn ich die "keep speed" funktion nutze das sich die geschwindigkeit die ich halten will beim fahrtrichtungs wechsel zurücksetzt auf 0 und ich dann wieder beschleunigen muss.  die version von VCA ist die von gestern vormittag. 

MFG Vivien

**Comment by Mogli12** [comment]
Hallo Vivien,

ja, ich finde das so besser. 

Viele Grüße,
Stefan

**Comment by VivienHardgas** [comment]
und das als option deaktivieren währe keine möglichkeit? ich fand die funktion so wie sie im 19 war sehr praktisch da ich gerne bei feldarbeit oder beim dreschen einen joystick nutze und die geschwindikeit eigenlich nur reduziere zum wenden und dann via tempomat wieder beschleunige

**Comment by Mogli12** [comment]
Das sollte mit Build 39 oder höher wieder funktionieren.
