### ISSUE TITLE
Bei FS22 1.0 rc6 funktioniert CTRL-W nicht mehr, mit 9.0.2.5 keine Probleme

### ISSUE THREAD

**Issue by Clouseau219** [Mogli12/VehicleControlAddon#720]
Hi,
habe gerade über die 9.0.2.5 die FS22 1.0 rc6 kopiert und plötzlich gehen die Tasten für den VCA nicht mehr.
Kein CTRL-W usw. Auch wenn ich z.B. meinen XBox Controller neu belege geht VCA nicht. Habe auch die komplette Tastenbelegung zurückgesetzt. Hat nicht geholfen.
KEY_lctrl KEY_w ist auch nur einmal gebunden. So wie es soll mit : 
`    <actionBinding action="vcaSNAP">
        <binding device="KB_MOUSE_DEFAULT" input="KEY_lctrl KEY_w" axisComponent="+" neutralInput="0" index="1"/>`
Aber wenn ich lctrl-w drücke fährt er nach vorne.
LCTRL-C geht aber z,B.
Wenn ich wieder die 9.0.2.5 verwende passt wieder alles. Ohne dass ich was an der Tastenbelegung ändern muss.
An was kann das liegen?
Grüße,
Clou

**Comment by Clouseau219** [comment]
Habe den Übeltäter gefunden. Wenn ich Guidance Steering raus schmeiße, dann geht die 1.0RC6.

**Comment by Mogli12** [comment]
Man muss nach dem Update auf 1.2.0.0 die Tastenbelegung zurücksetzen.

**Comment by Clouseau219** [comment]
Hi Mogli12,
wie ich schon erwähnt habe, habe ich die Tastenbelegung schon zurück gesetzt.
Trotzdem geht der VCA 1.0 rc6 nicht, wenn ich auch den Guidance Steering Mod und im Fahrzeug ein GPS (beim Kauf)  aktiviert habe.
Wenn ich beim Fahrzeug in der Werkstatt das GPS wieder deaktiviere, geht der VCA 1.0 rc6 wieder.
Wenn ich dann in der Werkstatt bei den Konfigurationen das GPS wieder einbaue, funktioniert der VCA 1.0 rc6 wieder nicht.

Grüße,
Clou

**Comment by Clouseau219** [comment]
Ich habe auch testweise mal vcasnap mit einer anderen Taste z.B. # festgelegt. Um sicher zugehen dass es nicht an einer lCTRL+ Kombination liegt.
Aber genau das gleiche Phänomen.
Mit Guidance Steering Mod aktiv und wenn das Fahrzeug ein GPS verbaut hat geht VCA 1.0 rc6 nicht.
Nehme ich den GPS Einbau in der Werkstatt wieder raus, geht der VCA 1.0 rc6 wieder.
Was macht denn die rc6 anders als die 9.0.2.5 ?

**Comment by Mogli12** [comment]
Ich habe schon mehrfach erklärt, dass in einem Mod die Aktionen in der modDesc.xml definiert werden. Dort haben sich auch einen Standardbelegung. Im Spiel kann man die Tastenbelegung ändern. 
Im LUA-Skirpt meldet man nun an, dass die Aktion aktiv sein soll, und welche Funktion beim Drücken der Tastenkombination aufgerufen werden soll. Den Rest erledigt das Spiel selber.
=> Wenn irgendwelche Tastenkombinationen nicht funktionieren, dann liegt es am Spiel oder an doppelt belegten Tasten. Im Mod kann man da nichts machen.
Mich nervt es allerdings ungemein, dann ständig diese Issues aufgemacht werden.

**Comment by Clouseau219** [comment]
Sorry wenn dich das nervt. Aber an der Tastaturbelegung kann es doch nicht liegen, wenn es mit dem VCA 9.0.2.5 geht und mit dem VCA 9.0.2.7 nicht mehr.  Oder verstehe ich da was falsch?

**Comment by Mogli12** [comment]
Du hast doch den GPS Mod im Spiel. Ich verstehe nicht warum Du trotzdem die Spurführung von VCA einschalten willst.

**Comment by Mogli12** [comment]
Damit beide Mods sich nicht gegenseitig stören, ist die Spurführung von VCA aus, sobald das Fahrzeug GPS an Bord hat.

**Comment by Clouseau219** [comment]
Dann war wohl dieses "Feature" beim 9.0.2.5 wohl noch nicht dabei, dass erklärt es aber dann auch warum es mit dem 9.0.2.7. läuft wenn das GPS ausgebaut ist. 
Finde es dann nur schade dass man dann nicht das eine oder andere nutzen kann ohne immer GPS aus und wieder einzubauen.
Warum ich beide habe? Mit gefällt dein VCA von der Bedienung besser als das GPS von Wopster, wollte mir aber halt beide Optionen offen halten.

**Comment by Mogli12** [comment]
Ja, es waren dann doch nicht die Tastenbelegungen, das war ein Missverständnis von meiner Seite. 

Um auf der sicheren Seite zu sein habe ich die Spurführung und deren Tasten deaktiviert, sobald GPS im Fahrzeug verfügbar ist.

**Comment by Clouseau219** [comment]
> Ja, es waren dann doch nicht die Tastenbelegungen, das war ein Missverständnis von meiner Seite.

Kein Problem 👍 

> Um auf der sicheren Seite zu sein habe ich die Spurführung und deren Tasten deaktiviert, sobald GPS im Fahrzeug verfügbar ist.

Ok, aber vielleicht wäre es ja irgendwann mal möglich dieses als Option zu machen. Falls du mal da sitzen solltest und dich langweilst und krampfhaft überlegen musst was du jetzt machen könntest :) Aber ich weiss, solche Momente gibt es eigentlich nicht mehr :)
