### ISSUE TITLE
LS22 seit rc5 "deaktiviert" CabView

### ISSUE THREAD

**Issue by Peppie23** [Mogli12/VehicleControlAddon#724]
Hi Mogli12,

seit rc5 habe ich das Problem das die 180 Grad Drehung durch CapView nicht mehr funktioniert. Ich kann durch VCA rc5 dann den Kopf komplett umdrehen.

Ist das so vorgesehen? Falls ja, könnte man eventuell eine Config einbauen, damit man das abschalten kann? - Damit die 180 Grad View wieder funktioniert

---
- LS22: v1.2.0.0 (war auch vor dem update schon so)
- CapView v1.0.0.0 (vom Modhub https://www.farming-simulator.com/mod.php?mod_id=225764)
- VCA seit rc5

Aktueller Workaround: rc4 benutzen

Danke schon mal.

**Comment by Mogli12** [comment]
Hallo,

Vielleicht kannst Du mal bei Cabview nachfragen.

Viele Grüße

**Comment by Peppie23** [comment]
hmm ich weiß nicht wo ich dem loki_79 von Cabview schreiben kann und wenn dann wird vermutlich antworten, dass ich VCA entfernen soll.

Nun gut, trotzdem danke.
