### ISSUE TITLE
Änderung des Blickzeitpunktes?

### ISSUE THREAD

**Issue by Bomberman82** [Mogli12/VehicleControlAddon#725]
Hi @Mogli12, 

kleine Bitte, wenn möglich. Bei Manuelschaltung funktioniert das wechseln der Kameraperspektive schon sehr gut, wenn man Richtungswechsel macht, nur bei Stufenlosen Getriebe funktioniert es nicht so ganz optimal, da man erst ein paar Km/h fahren muss. 

Kann man das beim Rückwärtsfahren so einstellen das die Kamera schon bei weniger als 1kmh switchen tut? Wenn ich Rückwärtsgang bei Stufenlosemgetriebe fahre schaltet die Kamera sich erst bei 5kmh ein. 

Vielen Dank und gut Grün.

**Comment by Mogli12** [comment]
Hallo @Bomberman82,

ich lese hier auch nur die Variablen des Spiels aus. Oberhalb von 5 km/h verwendet VCA die aktuelle Fahrtrichtung (self.movingDirection). Darunter wird die Fahrrichtung des Getriebes verwendet (motor.currentDirection).

https://github.com/Mogli12/VehicleControlAddon/blob/0ea42f45ee50842560a76dc1436b08c3e2b32d47/FS22_VehicleControlAddon/vehicleControlAddon.lua#L1769

Viele Grüße

**Comment by Mogli12** [comment]
Ist es in der aktuellen Version ok? Wenn nicht bitte wieder öffnen.
