### ISSUE TITLE
Hand brake

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/VehicleControlAddon#764]
There is probably an error in the game that ignores the activated foot brake (G27) and the machine starts moving when the menu is opened. I detected this error when using manual gearbox with clutch. (reported to Giants).
Should the parking brake function be added to prevent the machine from moving?

https://youtu.be/n83rO9Jdf80

Thanks
Kynuska

**Comment by Mogli12** [comment]
Hi Kynuska,

Please try build 35.

Best regards

**Comment by Kynuska** [comment]
Thanks.
The parking brake operates until I press ESC. Then the vehicle rushes down the hill uncontrollably.
I will have to learn to use "pause".
Note:
when the gear is engaged and the parking brake is active, the engine does not report an overload when the clutch is not pressed.

Kynuska

**Comment by Mogli12** [comment]
Hi Kynuska,

This is a little problematic. I re-activted the isBlocked indicator if a GUI is open. But this may cause problems with the ChatDialog. You can check #407 and #592.

Please try build 36. The vehicle should now stop if a dialog is open.

Best regards

**Comment by Kynuska** [comment]
Hi.
MP should take precedence over my requirements.
Build 35 worked better. Although hard to say. The game probably has a hidden handbrake that sometimes activates and sometimes does not. The machine then (does not) move regardless of the parking brake on or off.
If it should cause any problems. I would remove the parking brake function.
At the end of the test, the machine moved even when switching to the menu.
What comes to my mind is to activate isBlocked when the parking brake function is on. If the machine then moves in the menu while driving and not during the handbrake.
Log is clear.

Kynuska

**Comment by Kynuska** [comment]
Hi.
I bow to your skill.
The parking brake now works even when the engine is switched off.
When activating the menu (esc):
1. with the tractor stopped - does not move
2. If in motion:
a: with the clutch pedal active, tractor stops
b: with the clutch pedal inactive, tractor stops, reports an overload and shuts off the engine.
c: does not stop when cruise control is active.
I don't know if this stopping will cause problems in MP.

Kynuska

**Comment by MateusKronbauer** [comment]
A question a bit of this topic but still in the use of Logitech steering: Anyone noticed that Force Feedback isn't working? I use a G29 and nothing happens, but there's a friend that have a G27 and it works fine...

**Comment by Mogli12** [comment]
@MateusKronbauer Please open a new discussion under discussions.
