### ISSUE TITLE
hand throttle and manual gears odd behaviour

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/VehicleControlAddon#765]
Hello,

Ive been enjoying this mod alot since you started working on it for FS 22.  I have however recently noted odd behaviour with manual tractors since perhaps RC3 (Im not sure exactly).  Basically if I'm using a manual tractor like the MF3670 with a cultivator,  I would select perhaps 1400 or 1600 rpm, or 1800 rpm, with hand throttle, then change speed going up/down the gears in the range like IRL.  This was working quite well although at lower rpms it would sometimes 'auto-declutch', rather than pulling down the revs.  Although for the most part this seemed to work.  However with the most recent RC when going up a hill for example, engine revs stay the same, but tractor speed decreases.  dropping a couple gears may increase speed a bit to what is limited by the gear ratio.

It seems that there is a sort of automatic torque converter/slip clutch on manual tractors.  I notice the new setting for automatic engine speed control and switching this off I *think* might help/resolve this.  But the tractor wont stay in clutch engaged when you push W to move off and let go like it did previously.  it just starts and then rolls to a stop, the minute you release 'W'.  

Just driving (with keyboard) by holding W for full throttle does seem to work correctly from the testing I have done.

FYI this has been on keyboard with 'manual' gears selected in game settings.  manual with clutch using the key also didn't yield the result I was expecting.

Otherwise great progress and enjoying it and I look forward to each release!

thanks

Matt

**Comment by Mogli12** [comment]
Hi Matt,

VCA does not change the vanilla gearbox. It just does some tweaks here and there. VCA does not touch the clutch.

Best regards

**Comment by miracleman51** [comment]
Hi Stefan,

OK I did wonder.  Although something does seem different between say RC3 and the latest RC38 when driving manual tractors. but perhaps its just me.

Ill keep testing.

Thanks

Matt

**Comment by Mogli12** [comment]
Hi Matt,

Please try build 43.

Best regards, 
Stefan

**Comment by miracleman51** [comment]
Stefan,

Brilliant!  Works perfectly as I would expect now!  

Thanks very much!
Matt
