### ISSUE TITLE
Modus für Menschen mit Rot-Grün-Schwäche

### ISSUE THREAD

**Issue by LSMT-elMatador** [Mogli12/VehicleControlAddon#766]
zu erst mal Danke!  Einfach nur Danke für diesen Spitzenklasse Mod!
Da ich in  meinem Team mehrere Menschen habe, die an rot-grün Schwäche (Farbenblindeit) leiden. 
Weshalb diese dann die Linien (Türkis/rot) sehr schwer zu erkennen sind!
Wäre es möglich, die Farben der Linien wählbar zu machen?

**Comment by Mogli12** [comment]
Hallo, 
bitte schaue ins Dikussionsforum: #733 
Viele Grüße
