### ISSUE TITLE
Handbremse funktioniert nicht mit manueller Schaltung

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#768]
Hallo Stefan. Die Handbremse lässt die Fahrzeuge mit Schaltgetriebe trotzdem wegrollen bei manueller Schaltung. 

Liebe Grüße 

Chris

**Comment by Mogli12** [comment]
Warum machst Du dazu ein neues Issue auf? Kann man das nicht in #764 schreiben?

**Comment by ChrisJD8400R** [comment]
Sorry Stefan. Habe ich wohl überlesen :D

**Comment by Mogli12** [comment]
Ok. hast Du mal Version 38 probiert?
