### ISSUE TITLE
Kamera Zoom

### ISSUE THREAD

**Issue by timmi4026** [Mogli12/VehicleControlAddon#771]
Moin Mogli,

seit dem Build 38 kann ich mit dem Mausrad die Kamera nur noch in eine Richtung zoomen. Entweder Zurück, dann geht nicht mehr vor oder anders herum. Kannst Du da nochmal schauen bitte.

**Comment by Mogli12** [comment]
Das Mausrad ist doppelt belegt. Bitte überprüfe einfach deine Tastenbelegung.

**Comment by c0nnex** [comment]
Hatten das gleiche Problem mit Build 38. (Dedi server)
Tastatur-belegung für zoom funktionierte auch nicht mehr.
Nach downgrade auf Build 28 ging wieder alles normal.
Build 44 hat das Problem nicht mehr.

Da ich nichts an meiner Tastatur/Maus-belegung geändert habe sondern nur jeweils das VCA mod ausgetauscht, kann ich die Rückmeldung "Mausrad ist doppelt belegt" nicht so ganz nachvollziehen.

**Comment by Mogli12** [comment]
Das Problem ist, dass man selber das Mausrad in den Einstellungen keiner Aktion zuordnen kann. Daher ist das Mausrad immer noch doppelt belegt.
