### ISSUE TITLE
Kollisionssymbole mit FS22_HeadlandManagement

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/VehicleControlAddon#773]
Hallo.
Build 39

![fsScreen_2022_01_07_17_48_07](https://user-images.githubusercontent.com/15960970/148579197-3a4c034a-e6aa-4bec-8088-3371c40a5fc4.png)

Kynuska

**Comment by Mogli12** [comment]
Should be fixed with build 40

**Comment by jason0611** [comment]
Danke! :-)
