### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by manuelgbel** [Mogli12/VehicleControlAddon#787]
Könnte man das Overlay verschiebbar machen? Es kreuzt sich nämlich mit anderen Overlays von anderen Mods. Wie z.B. dem Mod: EdvancedVehicle. Oder könnte man eine Funktion in den Einstellungen einfügen die man einschaltet, damit es sich an die Overlays von Enhanced Vehicle anpasst?(Also z.B. die km/h-Bereichsanzeige beim Schaltgetriebe links neber der Gewichtsanzeige(Enhanced Vehicle) anzeigen)

**Comment by Mogli12** [comment]
Schau mal hier rein: https://github.com/Mogli12/VehicleControlAddon/discussions/762

Nachdem ich mir https://github.com/ZhooL/FS22_EnhancedVehicle/issues/61 durchgelesen habe, bin ich der Ansicht, dass man entweder VCA oder EnhancedVehicle verwendet. Aber beides gleichzeitig geht nicht.

**Comment by manuelgbel** [comment]
Ich benutze beides und benutze aus der Ihrer Mod die GPS-Funktion und die Anzeige der Geschwindigkeitsbereiche. Den Rest benutzte ich aus der anderen Mod. Die Anzeigen überlappen sich halt. Könnte man kein Ein-Aus-Schalter in den Einstellungen einbauen der die Anzeige an die andere Mod anpasst? Finde die GPS-Funktion von Ihnen besser. Wäre cool wenn sowas geht

**Comment by Mogli12** [comment]
EV hat auch eine GPS-Funktion. Und die Anzeige zur Ganggeschwindigkeit kann @Zhool gerne nachbauen. Die Berechnung steht in vehicleControlAddon:onPostUpdate.

**Comment by manuelgbel** [comment]
Ich finde die GPS-Funktionen von Ihnen besser. Deswegen würde ich gerne diese Mod mitverwenden. Außerdem hat diese Mod auch automatisches nach hinten schauen beim Rückwärtsfahren, das hat EnhancedVehicle nicht. Würde das nicht funktionieren?
