### ISSUE TITLE
Anfahren im Standgas

### ISSUE THREAD

**Issue by ChrisJD8400R** [Mogli12/VehicleControlAddon#802]
Ich habe bemerkt, dass beim anfahren im Standgas (kleiner Gang) der schlepper nicht eigenstädig losfährt. Man muss immer die Drehzahler des Motors erhöhen damit der Schlepper losfährt.

MfG Chris

**Comment by Mogli12** [comment]
Ja, das ist korrekt so. Unterhalb von 3,6 km/h greift die automatische Bremse vom Spiel. Daran ändert VCA nichts.
