### ISSUE TITLE
Escape Button Not Working

### ISSUE THREAD

**Issue by WickkedWolf** [Mogli12/VehicleControlAddon#812]
Hi,  Installed the VCA mod tonight (FS22) and after activating the mod I can do everything the VCA needs to do however it has disabled my Escape Button from working even out of the VCA menu and another menu like Placeables.  Pretty sure it could be a Mod Conflict but  nothing showing in my game log.

**Comment by Mogli12** [comment]
I think your inputBinding.xml is damaged. VCA does not have a key binding for ESC. This is the standard key binding.
