### ISSUE TITLE
Vehicles are randomly stuck in park

### ISSUE THREAD

**Issue by Atriusftw** [Mogli12/VehicleControlAddon#815]
Hi there. I absolutely love this mod, and prefer it over other GPS mods. Thank you for making it.
However, recently we've experienced random issues with vehicles being stuck in park, making it impossible to drive them.

I figured out that this was caused by VCA by disabling mods one by one until we could drive again.
This has happened on game versions 1.2.0.0 and 1.2.0.2.

I'd be happy to provide logs and savegame files if that would help track down this bug.

Thanks!

**Comment by Mogli12** [comment]
Sorry, but where is the log.txt? Where is the screen shot? Did you press vcaHandbrake (key semicolon, 'ö' on German keyboard)?

**Comment by Atriusftw** [comment]
> Sorry, but where is the log.txt? Where is the screen shot? Did you press vcaHandbrake (key semicolon, 'ö' on German keyboard)?

Wow. I honestly wasn't aware that the mod had a handbrake. We have probably hit the keybind by mistake then.. this is embarassing. I'm very sorry! Thank you for making us aware.

**Comment by Mogli12** [comment]
No problem
