### ISSUE TITLE
Eratic steering during Reverse on Articulated Steering Vehicles

### ISSUE THREAD

**Issue by Invr4get** [Mogli12/VehicleControlAddon#817]
Hello, I've been having trouble trying to properly reverse tractors with Articulated Steering, such as the Holland T9, Case IH QuadTrac AFS, as well as vehicles with "Turn Steering", like any of the Sugar Beet Harvesters. What VCA  will do is overcompensate and will end up a "wave pattern" as it's trying to reverse, never really self correcting. But the moment I go forward it corrects itself immediately.

It's easy to replicate, just buy any of the 2-axle large tractors that turn by turning half their body, or any of the beet harvesters, and try to reverse while VCA is initiated. 

Thank you.

**Comment by Mogli12** [comment]
This problem is that these vehicles have an invalid node for reverse driving. I think the russian tractor works.

**Comment by Mogli12** [comment]
It does not appear in the most recent FS22 version, right?
