### ISSUE TITLE
Can't enable diff control setting on 2wd vehicles.

### ISSUE THREAD

**Issue by talianagisan** [Mogli12/VehicleControlAddon#819]
So I'm not sure if this is intentional or not but I can't enable the setting to control diffs on 2wd vehicles. If this is intentional, why? We still need rear diff control or front diff. But if its not intentional... well now you're aware.

**Comment by talianagisan** [comment]
The option for difflock is greyed out on any 2wd. Enhanced vehicle control does it without issues. Good examples are these the 2wd ones. 
https://tired-iron-modding.itch.io/john-deere-large-frames
https://tired-iron-modding.itch.io/john-deere-30-and-40-series-hi-crop and his others. 

My guess is if it doesnt detect a front differential it freaks out. I've not had a single 2wd vehicle work but the moment i used enhanced vehicle's diff lock it worked flawlessly. If you want me to try anything specific ingame do tell me and i can report on it.

**Comment by Mogli12** [comment]
Hi, sorry for the late response. But the diffs in the mod look strange:
```xml
            <differentialConfiguration>
                <differentials>
                    <differential torqueRatio="0.5" maxSpeedRatio="1.8" wheelIndex1="1" wheelIndex2="2"/>
                    <!-- front left-right-->
                    <differential torqueRatio="0.5" maxSpeedRatio="0.0" wheelIndex1="3" wheelIndex2="4"/>
                    <!-- back left-right -->
                    <differential torqueRatio="0.5" maxSpeedRatio="1.8" differentialIndex1="1" differentialIndex2="2"/>
                    <!-- front-back -->
                </differentials>
            </differentialConfiguration>

```
I 2WD vehicle should have one diff only. It should rather look like this:
```xml
        <differentialConfigurations>
            <differentialConfiguration>
                <differentials>
                    <differential torqueRatio="0.5" maxSpeedRatio="1.9" wheelIndex1="3" wheelIndex2="4" /> <!-- back left-right -->
                </differentials>
            </differentialConfiguration>
        </differentialConfigurations>
```
