### ISSUE TITLE
Spelling Issue in modDesc_l10n_de.xml

### ISSUE THREAD

**Issue by SimonBalu** [Mogli12/VehicleControlAddon#828]
There is an issue in modDesc_l10n_de.xml in line 94 (or nearly)

`<text name="vca_tip_DEBUG"        text="Er werden zusätzliche Meldungen ins Log geschrieben"/>`
**but it should be**
`<text name="vca_tip_DEBUG"        text="Es werden zusätzliche Meldungen ins Log geschrieben"/>`

But yeah, I know it's a small problem 😉

**Comment by Mogli12** [comment]
Thanks for finding this typo.

Danke für den HInweis auf den Tippfehler.
