### ISSUE TITLE
Inching toggle

### ISSUE THREAD

**Issue by cwhandersen** [Mogli12/VehicleControlAddon#832]
So this is not a bug/issue. It's simply a suggestion/wish. I would like to have a toggle option for the inching key. 
An example for the reason why, is when i drive around in a small barn with a telehandler with bales on. I like to use inching so my accelarations aren't as rapid, so i don't drop my bales or hit something.

**Comment by Mogli12** [comment]
Did you try to use an XX % / 100 % setting for "Throttle Limiter"?

**Comment by cwhandersen** [comment]
Yes i did try that. But i would rather not have to change it every time i'm done with using the telehandler inside of the barn. 
But yes that has been my solution the last couple of times.
