### ISSUE TITLE
Anfahren über Kupplung ohne Gas würgt den Motor ab

### ISSUE THREAD

**Issue by Helgomant** [Mogli12/VehicleControlAddon#836]
Hallo Stefan,

erstmal vielen Dank, dass du deinen VCA Mod auch im LS22 zur Verfügung stellst! Ohne VCA wäre das Spielerlebnis für mich nicht ansatzweise so gut.

Ich spiele mit Lenkrad, H-Schaltung und Joystick zur Steuerung der Fahrzeuge und es ist alles so konfiguriert, dass Trecker mit stufenlosen Getrieben, sowie auch Schaltgetrieben gut bedienbar sind. 
Eine Sache ist mir aber noch aufgefallen. Anfahren mit Kupplung ohne Gas würgt zwangsläufig den Motor ab. Auch wenn ich mit Handgas fahre wird der Motor beim Anfahren abgewürgt. Man braucht immer einen minimalen Impuls vom Gaspedal (Eingabe über die konfigurierte Achse) damit der Trecker anfährt. Zudem gibt es dann immer einen kurzen Drehzahlüberschwinger. Ich hatte den Versuch unternommen, meine Pedale (Gas und Bremse) in den Controllereinstellungen über getrennte Achsen zu konfigurieren. Und siehe da, es hat kurzfristig funktioniert, allerdings nur für einige Male. Danach wieder das Abwürgen. Ich werde da nicht richtig schlau draus.

Ich spiele mit folgenden Einstellungen: 
1. VCA: Motormodifikationen = an
2. VCA: niedrige Bremskraft = 0 bis 20% (zum Testen, aber selbst 0% bringt keine Verbesserung hinsichtlich abwürgen)
3. FS22: Stop and Go Bremsung = an (wenn der Punkt auf "aus" ist, bleibt das Fahrzeug nach Fahrtrichtungswechsel stehen)

Dann sind mir noch zwei Kleinigkeiten aufgefallen. 
1. Die gleichmäßige Drehzahl bei Treckern mit Schaltgetrieben ist bei Teillast sehr unruhig. Obwohl ich meinen Fuß absolut ruhig halte toggelt die Drehzahl mit einer verhältnismäßig hohen Frequenz. Das hört sich so an, als wenn der Motor nicht richtig läuft (Drehzahlsägen). Vielleicht kann man die konstante Drehzahl noch irgendwie glätten. 
**Edit:** Das Phänomen tritt nur bei Geschwindigkeiten bis ca. 10 km/h bei Drehzahlen ab 1400 min-1 auf und das mit verhältnismäßig wenig Last.

2. Bei Treckern mit stufenlosen Getrieben habe ich mir die Beschleunigungsfunktion in Verbindung mit Keep Speed auf eine Achse des Joysticks gelegt. Persönlich finde ich es ziemlich schwierig die Geschwindigkeit darüber zu regeln, da sich das Signal bei Betätigung sehr schnell verändert. Ich würde mir wünschen, das es etwas feinfühliger zu bedienen wäre.
**Edit:** Es wäre schön, wenn auch bei Treckern mit Automatikgetrieben (stufenlos) die Kupplung funktionieren würde.

Ich gehe davon aus, dass das Abwürgen und Drehzahlsägen wahrscheinlich eher Punkte sind, die mit der Vanilla Version des Spiels zusammenhängen. Wie die richtige Umsetzung eines Antriebsstrangs funktioniert, hast du ja im 17er und 19er gezeigt. Ich hätte mir für den LS22 gewünscht, das Giants sich etwas mehr von dir abgeschaut hätte. 

Vielleicht findest du die Zeit und Muße, dir die Punkte mal anzuschauen.

Viele Grüße
Helge

**Comment by Mogli12** [comment]
Hallo Helge,

ich nutze leider selber die manuelle Kupplung nicht. Wie funktioniert es mit Version 112?

Viele Grüße,
Stefan
