### ISSUE TITLE
VCA erkennt Shifter nicht

### ISSUE THREAD

**Issue by Y41nnick** [Mogli12/VehicleControlAddon#837]
Hallo, 
ich habe das Problem dass LS19 meinen Shifter nicht erkennt. Ich nutze das Logitech G923 mit dem Shifter von Logitech. Vorher hatte ich ein G29, bei dem hat alles super geklappt, aber seit ich das G923 nutze erkennt der LS den Shifter nicht mehr beziehungweise ich kann die Gänge nicht mehr belegen. 
Falls mir jemand helfen kann bedanke ich mich schonmal im Vorraus.

**Comment by Mogli12** [comment]
Hallo,
VCA macht selber nichts mit den Eingabegeräten. 
Viele Grüße

**Comment by Y41nnick** [comment]
Hallo,
erstmal vielen Danl für die Info!
Hast du noch eine Idee an was es liegen könnte dass LS19 meinen Shifter nicht erkennt?
MfG

**Comment by Hmmvee** [comment]
Ist ein bekanntes Problem im LS19. Erst LS22 erkennt den Shifter am G923.
