### ISSUE TITLE
4WD und Difflock funktionieren nicht bei Xerions

### ISSUE THREAD

**Issue by Mahohny** [Mogli12/VehicleControlAddon#839]
Bei den Ingame Claas Xerion's (SattleTrac, 4000er, 5000er) lässt sich der 4WD und die hinteren Difflocks nicht aktivieren.
Im Einstellungsmenü sind "Voreilung der Vorderachse" und "Tausch der Differentiale" ausgegraut. 
Hängt das eventuell mit den Allrad-Lenkern zusammen und lässt sich da was machen?

**Comment by Mogli12** [comment]
Die Xerions haben doch 4 gleich große Räder. Kann man da in Echt überhaupt den Allradantrieb ausschalten? Und Voreilung der Vorderachse gibt es dort bestimmt nicht.

**Comment by Luciel-Fox** [comment]
Beim Xerion, ist der Allrad immer an, das kann man nicht ändern, jedoch kann man manuell die Differentiale sperren.

**Comment by Mahohny** [comment]
Guter Punkt, stimmt natürlich, bei den Xerions ist Allrad immer an. Mich irritiert nur die Anzeige im HUD einwenig. Allrad und das hintere Differential ist komplett dunkel ausgegraut. Nur das vordere Differenztial lässt sich aktivieren. Die Frage wäre jetzt, wenn VCA aktiviert ist, funkioniert der Allradmodus oder ist es deaktiviert?

**Comment by Hmmvee** [comment]
Xerion hat schaltbaren Allrad und Längs- sowie Querdiffs.:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjim7-ehLX3AhXhSvEDHR3cDbkQFnoECAcQAQ&url=https%3A%2F%2Flandtechnik-mueller.ch%2FDokumente%2FClaas%2FClaas_Xerion_5000-4000.pdf&usg=AOvVaw25r0cNZqp_8NshAtVqlXu8

**Comment by Mogli12** [comment]
Man kann am Xerion Raupen konfigurieren, das mag VCA aber leider nicht.
