### ISSUE TITLE
Suggestion:Hand throttle to axis

### ISSUE THREAD

**Issue by atledreier** [Mogli12/VehicleControlAddon#852]
Hi.

I love this mod, and it's the only way to drive non-CVT tractors in my mind.

One thing that would enhance it further is to allow an axis hand throttle. right now the increase/decrease buttons work fine, I have a rotary encoder for it, but an axis would feel even more authentic.

**Comment by Mogli12** [comment]
Hi,
This is already an axis. As soon as analog input is detected VCA will take the position of the axis as value.
BR Stefan
