### ISSUE TITLE
GearShiftSound

### ISSUE THREAD

**Issue by atte624** [Mogli12/VehicleControlAddon#853]
Hy. If it is possible, can you add to FS22 version VentilBloffOff sound like in FS19? Thanks for answer.

**Comment by Mogli12** [comment]
That is tricky in FS22. In FS19 VCA redefined the whole VehicleMotor. In FS22 it keeps the original transmission in VehicleMotor and just adds some minor tweaks here and there.

**Comment by Mogli12** [comment]
Giants already added the blow off valve sound.

**Comment by atte624** [comment]
How can I add Ventil blow off sound or can you suggest anything in connection with ,,turbo’’ sound while shift like MB Trac. Thanks your answer. 🙌🏽

**Comment by Mogli12** [comment]
Hi,
that should be done in the mod. 
BR

**Comment by atte624** [comment]
Hi, 
It should be done, but it is not done 😅
Whick mod included blow off valve sound or how is it treated in fs22? 
I can make blow off sound,but i can not control it well. Sould not be blow off sound when shift down but there is.
Thanks for answer have a nice day.
