### ISSUE TITLE
Request: Turn on/off AWD / Differentials automaticly

### ISSUE THREAD

**Issue by headhunter84** [Mogli12/VehicleControlAddon#855]
Hy Stefan.

Is it possible when slip is to high when AI Helper / AutoDrive drives a vehicle VCA turn on/off AWD (f. E. at 30% Slip) and Differentials (f. E. 60% Slip) automaticly? Whould be great especially for REA Wheels User.

Greetings.

**Comment by Mogli12** [comment]
Hi,

Per default VCA does not operate the differentials if the helper is engaged. In this case, the vanilla vehicles are used. This is like a permanent AWD with limited slip differential.

Best regards
