### ISSUE TITLE
Issue: Handthrottle RPM low limit

### ISSUE THREAD

**Issue by headhunter84** [Mogli12/VehicleControlAddon#856]
On a AgraPlays Video he showed a issue with handtrottle. Its limited to ~1500RPM. There is somwhere at VCA a issue. He tried a other mod with handthrottle there is no limited RPM for handthrottle.

**Comment by Mogli12** [comment]
I have no idea. It is difficult to fix something if you don't know how to reproduce it. Maybe there is something wrong in the mod?
