### ISSUE TITLE
Swap axles

### ISSUE THREAD

**Issue by kandk1** [Mogli12/VehicleControlAddon#858]
Hi. Would it be possible to activate the swap axles-function like it was in fs19? All harvesters in fs22 seems to be RWD, wich is not very realistic xD

**Comment by Mogli12** [comment]
VCA separates the wheels and differentials into steering and non-steering wheels. Nevertheless, the swap setting is still in the configuration UI.

**Comment by kandk1** [comment]
Thanks for your reply. I should have provided a little more information about my issue. I use VCA in combination with EV, wich works very nice. But with combine harvesters, 4WD have to be turned on at all times. If i turn it off, it seems like only rear wheels are turning, further resulting in the vehicle stalling. It would be very nice being able to swap axle, so that the front wheels would do the pulling. As you say, the settings are in the GUI, but i can't change them, as they are grayed out.
![fsScreen_2022_10_17_00_08_13](https://user-images.githubusercontent.com/62986719/196061032-f8b23c43-0c69-4a4e-aa45-d9ae5714f590.png)
