### ISSUE TITLE
No clutch when installing VCA 

### ISSUE THREAD

**Issue by Mpompotska** [Mogli12/VehicleControlAddon#864]
Hello everyone!! Right after I installed the VCA mod my g29 clutch is not giving any input to the game... I disable it on the savegame, nothing. I have to uninstall it to get clutch function back... Otherwise use manual without clutch. Any help??

**Comment by Mogli12** [comment]
VCA does not change the clutch. I guess that you have duplicate input bindings.

**Comment by Mpompotska** [comment]
So could a key binding reset help??

**Comment by Mogli12** [comment]
I do not know. I do not own a wheel with clutch pedal. And the clutch pedal is operated by the vanilla game.
