### ISSUE TITLE
Issue VCA in dedicated server

### ISSUE THREAD

**Issue by Squallqt** [Mogli12/VehicleControlAddon#866]
Hello,
I want to inform you of a warning in my server logs with the latest version deployed on the official modhub.

### Warning:` Missing l10n 'input_vcaLimitSpeed' in mod 'FS22_VehicleControlAddon'

Does this need a fix?

**Comment by Mogli12** [comment]
Warnings do not need a fix

**Comment by Squallqt** [comment]
ok nvm I'll wait for a next version to put it back on the server.
ty for your answer (:

**Comment by Mogli12** [comment]
Sorry, but I do not get this. You can simply ignore the warning. Why wait for the next version?

**Comment by Squallqt** [comment]
because on a dedicated server the slightest warning impacts server performance as well as client synchronization.
just having removed the mods in warning with missing ai attachment made the server more stable.
it's not a problem I'll wait for a next patch, in the meantime I keep enhanced vehicle
gl mate and nice mod :)

**Comment by Mogli12** [comment]
Sorry, but this is just not true. A warning during load has NO impact on the game at all.
