### ISSUE TITLE
Keep speed broken on multiplayer after build 120

### ISSUE THREAD

**Issue by Tubezki** [Mogli12/VehicleControlAddon#882]
Keep speed is broken for anyone else playing in the multiplayer with me and we have tried all mods disabled expect VCA. Keep speed dosent accelrate anymore with Keep Speed enabled and basically no1 else joining the multiplayer cant use Keep Speed feature. We all have to use previous versions suchs as build 115 if I remember correctly.

**Comment by Jan238** [comment]
I have the same problem in multiplayer, but haven't tried it without all my other mods yet.

**Comment by antler22** [comment]
Also the same here, I did with no mods and KeepSpeed didn't function.  I put more detail in the Discussion section where it looks like this is a known issue.

**Comment by Mogli12** [comment]
Does it work again with build 126?
