### ISSUE TITLE
Typo in modDesc_l10n_de.xml and modDesc_l10n_en.xml

### ISSUE THREAD

**Issue by Williwillswisse** [Mogli12/VehicleControlAddon#892]
Hi Modli, there are two typos in the l10n's
modDesc_l10n_de.xml
line 163
		<text name="input_vcaGearSplitDwn" text="VCA: Getriebeuntersetzung -"/>
missing "o" in Down
		<text name="input_vcaGearSplitDown" text="VCA: Getriebeuntersetzung -"/>

modDesc_l10n_en.xml
line 147
		<text name="input_vcaGearSplitDwn" text="VCA: Gear splitter -"/>
missing "o" in Down
		<text name="input_vcaGearSplitDown" text="VCA: Gear splitter -"/>

**Comment by Mogli12** [comment]
Fixed with build 130.
Thanks
